library item_list;

final List<String> itemList = [
  'accordian',
  'airplane',
  'anaconda',
  'ant',
  'anteater',
  'apple',
  'apricot',
  'archery',
  'astronaut',
  'avocado',
  'badminton',
  'banana',
  'baseball',
  'basketball',
  'bassoon',
  'bat',
  'beach',
  'bear',
  'bicycle',
  'blackboard',
  'blowfish',
  'blueberries',
  'boar',
  'book',
  'boots',
  'bowling',
  'boxing',
  'broccoli',
  'bumper car',
  'bus',
  'cabbage',
  'camel',
  'canteen',
  'carp',
  'carpenter',
  'carrot',
  'castanets',
  'cat',
  'cello',
  'chameleon',
  'cheetah',
  'cherry',
  'chick',
  'chicken',
  'clarinet',
  'classroom',
  'cloud',
  'cobra',
  'coconut',
  'computer',
  'conductor',
  'contrabass',
  'cook',
  'corn',
  'cow',
  'crab',
  'crane',
  'crocodile',
  'crow',
  'cucumber',
  'curling',
  'cymbals',
  'deer',
  'dentist',
  'desert',
  'doctor',
  'dog',
  'dolphin',
  'drum',
  'duck',
  'eagle',
  'earthquake',
  'elephant',
  'exam',
  'farmer',
  'fencing',
  'ferris wheel',
  'fig',
  'firefighter',
  'fisherman',
  'flower',
  'flute',
  'fog',
  'forest',
  'fox',
  'friend',
  'frog',
  'garlic',
  'ginger',
  'ginseng',
  'giraffe',
  'gloves',
  'goat',
  'golf',
  'goose',
  'gorilla',
  'grape',
  'grapefruit',
  'guitar',
  'hairdressor',
  'hallway',
  'harmonica',
  'harp',
  'hat',
  'hawk',
  'helicopter',
  'hippo',
  'hippocampus',
  'hockey',
  'horse',
  'hyena',
  'iceberg',
  'iguana',
  'jellyfish',
  'judge',
  'judo',
  'jujube',
  'jungle',
  'kangaroo',
  'kiwi',
  'koala',
  'lake',
  'lemon',
  'leopard',
  'lettuce',
  'lightning',
  'lion',
  'lizard',
  'lobster',
  'magpie',
  'mango',
  'marathon',
  'meerkat',
  'melon',
  'Merry go round',
  'mole',
  'monkey',
  'moon',
  'mountain',
  'mouse',
  'mushroom',
  'notebook',
  'ocarina',
  'ocean',
  'octopus',
  'onion',
  'orange',
  'orangutan',
  'orchestra',
  'ostrich',
  'owl',
  'painter',
  'pants',
  'parrot',
  'parsley',
  'peach',
  'peacock',
  'pelican',
  'pencil',
  'penguin',
  'pepper',
  'pharmacist',
  'piano',
  'pickle',
  'pig',
  'pigeon',
  'pilot',
  'pineapple',
  'platypus',
  'playground',
  'policeman',
  'pomegranate',
  'potato',
  'principal',
  'professor',
  'pumpkin',
  'rabbit',
  'raccoon',
  'rain',
  'restroom',
  'rhino',
  'river',
  'rock',
  'saxophone',
  'scientist',
  'seagull',
  'seal',
  'sesame',
  'shark',
  'sheep',
  'shirt',
  'singer',
  'ski',
  'skunk',
  'sky',
  'snail',
  'snake',
  'snow',
  'snowboard',
  'soccer',
  'socks',
  'soil',
  'soldier',
  'space',
  'sparrow',
  'spinach',
  'starfish',
  'stewardess',
  'stingray',
  'strawberry',
  'sun',
  'subway',
  'swallow',
  'sweater',
  'swimming',
  'swing',
  'table',
  'tambourine',
  'teacher',
  'tiger',
  'timpani',
  'toad',
  'trampoline',
  'tree',
  'triangle',
  'truck',
  'trumpet',
  'turtle',
  'typhoon',
  'unicorn',
  'violin',
  'viking ship',
  'volcano',
  'volleyball',
  'vuvuzela',
  'waterfall',
  'watermelon',
  'wave',
  'whale',
  'wind',
  'window',
  'wolf',
  'woodpecker',
  'xylophone',
  'yacht',
  'zebra',
];

final Map<String, String> korItemList = {
  'accordian': '아코디언',
  'airplane': '비행기',
  'anaconda': '아나콘다',
  'ant': '개미',
  'anteater': '개미핥기',
  'apple': '사과',
  'apricot': '살구',
  'archery': '양궁',
  'astronaut': '우주비행사',
  'avocado': '아보카도',
  'badminton': '배드민턴',
  'banana': '바나나',
  'baseball': '야구',
  'basketball': '농구',
  'bassoon': '바순',
  'bat': '박쥐',
  'beach': '해변',
  'bear': '곰',
  'bicycle': '자전거',
  'blackboard': '칠판',
  'blowfish': '복어',
  'blueberries': '블루베리',
  'boar': '멧돼지',
  'book': '책',
  'boots': '부츠',
  'bowling': '볼링',
  'boxing': '권투',
  'broccoli': '브로콜리',
  'bumper car': '범퍼카',
  'bus': '버스',
  'cabbage': '양배추',
  'camel': '낙타',
  'canteen': '구내식당',
  'carp': '잉어',
  'carpenter': '목수',
  'carrot': '당근',
  'castanets': '캐스터네츠',
  'cat': '고양이',
  'cello': '첼로',
  'chameleon': '카멜레온',
  'cheetah': '치타',
  'cherry': '체리',
  'chick': '병아리',
  'chicken': '닭',
  'clarinet': '클라리넷',
  'classroom': '교실',
  'cloud': '구름',
  'cobra': '코브라',
  'coconut': '코코넛',
  'computer': '컴퓨터',
  'conductor': '지휘자',
  'contrabass': '콘트라베이스',
  'cook': '요리사',
  'corn': '옥수수',
  'cow': '소',
  'crab': '게',
  'crane': '두루미',
  'crocodile': '악어',
  'crow': '까마귀',
  'cucumber': '오이',
  'curling': '컬링',
  'cymbals': '심벌즈',
  'deer': '사슴',
  'dentist': '치과의사',
  'desert': '사막',
  'doctor': '의사',
  'dog': '개',
  'dolphin': '돌고래',
  'drum': '드럼',
  'duck': '오리',
  'eagle': '독수리',
  'earthquake': '지진',
  'elephant': '코끼리',
  'exam': '시험',
  'farmer': '농부',
  'fencing': '펜싱',
  'ferris wheel': '관람차',
  'fig': '무화과',
  'firefighter': '소방관',
  'fisherman': '어부',
  'flower': '꽃',
  'flute': '플루트',
  'fog': '안개',
  'forest': '숲',
  'fox': '여우',
  'friend': '친구',
  'frog': '개구리',
  'garlic': '마늘',
  'ginger': '생강',
  'ginseng': '인삼',
  'giraffe': '기린',
  'gloves': '장갑',
  'goat': '염소',
  'golf': '골프',
  'goose': '거위',
  'gorilla': '고릴라',
  'grape': '포도',
  'grapefruit': '자몽',
  'guitar': '기타',
  'hairdressor': '미용사',
  'hallway': '복도',
  'harmonica': '하모니카',
  'harp': '하프',
  'hat': '모자',
  'hawk': '매',
  'helicopter': '헬리콥터',
  'hippo': '하마',
  'hippocampus': '해마',
  'hockey': '하키',
  'horse': '말',
  'hyena': '하이에나',
  'iceberg': '빙산',
  'iguana': '이구아나',
  'jellyfish': '해파리',
  'judge': '판사',
  'judo': '유도',
  'jujube': '대추',
  'jungle': '정글',
  'kangaroo': '캥거루',
  'kiwi': '키위',
  'koala': '코알라',
  'lake': '호수',
  'lemon': '레몬',
  'leopard': '표범',
  'lettuce': '상추',
  'lightning': '번개',
  'lion': '사자',
  'lizard': '도마뱀',
  'lobster': '바닷가재',
  'magpie': '까치',
  'mango': '망고',
  'marathon': '마라톤',
  'meerkat': '미어캣',
  'melon': '멜론',
  'Merry go round': '회전목마',
  'mole': '두더지',
  'monkey': '원숭이',
  'moon': '달',
  'mountain': '산',
  'mouse': '쥐',
  'mushroom': '버섯',
  'notebook': '노트북',
  'ocarina': '오카리나',
  'ocean': '바다',
  'octopus': '문어',
  'onion': '양파',
  'orange': '오렌지',
  'orangutan': '오랑우탄',
  'orchestra': '오케스트라',
  'ostrich': '타조',
  'owl': '부엉이',
  'painter': '화가',
  'pants': '바지',
  'parrot': '앵무새',
  'parsley': '파슬리',
  'peach': '복숭아',
  'peacock': '공작새',
  'pelican': '펠리컨',
  'pencil': '연필',
  'penguin': '펭귄',
  'pepper': '후추',
  'pharmacist': '약사',
  'piano': '피아노',
  'pickle': '피클',
  'pig': '돼지',
  'pigeon': '비둘기',
  'pilot': '조종사',
  'pineapple': '파인애플',
  'platypus': '오리너구리',
  'playground': '놀이터',
  'policeman': '경찰관',
  'pomegranate': '석류',
  'potato': '감자',
  'principal': '교장',
  'professor': '교수',
  'pumpkin': '호박',
  'rabbit': '토끼',
  'raccoon': '너구리',
  'rain': '비',
  'restroom': '화장실',
  'rhino': '코뿔소',
  'river': '강',
  'rock': '바위',
  'saxophone': '색소폰',
  'scientist': '과학자',
  'seagull': '갈매기',
  'seal': '물개',
  'sesame': '참깨',
  'shark': '상어',
  'sheep': '양',
  'shirt': '셔츠',
  'singer': '가수',
  'ski': '스키',
  'skunk': '스컹크',
  'sky': '하늘',
  'snail': '달팽이',
  'snake': '뱀',
  'snow': '눈',
  'snowboard': '스노보드',
  'soccer': '축구',
  'socks': '양말',
  'soil': '흙',
  'soldier': '군인',
  'space': '우주',
  'sparrow': '참새',
  'spinach': '시금치',
  'starfish': '불가사리',
  'stewardess': '승무원',
  'stingray': '가오리',
  'strawberry': '딸기',
  'sun': '태양',
  'subway': '지하철',
  'swallow': '제비',
  'sweater': '스웨터',
  'swimming': '수영',
  'swing': '그네',
  'table': '테이블',
  'tambourine': '탬버린',
  'teacher': '선생님',
  'tiger': '호랑이',
  'timpani': '팀파니',
  'toad': '두꺼비',
  'trampoline': '트램펄린',
  'tree': '나무',
  'triangle': '삼각형',
  'truck': '트럭',
  'trumpet': '트럼펫',
  'turtle': '거북이',
  'typhoon': '태풍',
  'unicorn': '유니콘',
  'violin': '바이올린',
  'viking ship': '바이킹선',
  'volcano': '화산',
  'volleyball': '배구',
  'vuvuzela': '부부젤라',
  'waterfall': '폭포',
  'watermelon': '수박',
  'wave': '파도',
  'whale': '고래',
  'wind': '바람',
  'window': '창문',
  'wolf': '늑대',
  'woodpecker': '딱따구리',
  'xylophone': '실로폰',
  'yacht': '요트',
  'zebra': '얼룩말',
};

final Map<String, String> spaItemList = {
  'accordian': 'acordeón',
  'airplane': 'avión',
  'anaconda': 'anaconda',
  'ant': 'hormiga',
  'anteater': 'oso hormiguero',
  'apple': 'manzana',
  'apricot': 'albaricoque',
  'archery': 'tiro con arco',
  'astronaut': 'astronauta',
  'avocado': 'aguacate',
  'badminton': 'bádminton',
  'banana': 'plátano',
  'baseball': 'béisbol',
  'basketball': 'baloncesto',
  'bassoon': 'fagot',
  'bat': 'murciélago',
  'beach': 'playa',
  'bear': 'oso',
  'bicycle': 'bicicleta',
  'blackboard': 'pizarra',
  'blowfish': 'pez globo',
  'blueberries': 'arándanos',
  'boar': 'jabalí',
  'book': 'libro',
  'boots': 'botas',
  'bowling': 'bolos',
  'boxing': 'boxeo',
  'broccoli': 'brócoli',
  'bumper car': 'coche de choque',
  'bus': 'autobús',
  'cabbage': 'repollo',
  'camel': 'camello',
  'canteen': 'cantina',
  'carp': 'carpa',
  'carpenter': 'carpintero',
  'carrot': 'zanahoria',
  'castanets': 'castañuelas',
  'cat': 'gato',
  'cello': 'violonchelo',
  'chameleon': 'camaleón',
  'cheetah': 'guepardo',
  'cherry': 'cereza',
  'chick': 'pollito',
  'chicken': 'pollo',
  'clarinet': 'clarinete',
  'classroom': 'aula',
  'cloud': 'nube',
  'cobra': 'cobra',
  'coconut': 'coco',
  'computer': 'computadora',
  'conductor': 'director de orquesta',
  'contrabass': 'contrabajo',
  'cook': 'cocinero',
  'corn': 'maíz',
  'cow': 'vaca',
  'crab': 'cangrejo',
  'crane': 'grúa',
  'crocodile': 'cocodrilo',
  'crow': 'cuervo',
  'cucumber': 'pepino',
  'curling': 'curling',
  'cymbals': 'platillos',
  'deer': 'ciervo',
  'dentist': 'dentista',
  'desert': 'desierto',
  'doctor': 'médico',
  'dog': 'perro',
  'dolphin': 'delfín',
  'drum': 'tambor',
  'duck': 'pato',
  'eagle': 'águila',
  'earthquake': 'terremoto',
  'elephant': 'elefante',
  'exam': 'examen',
  'farmer': 'granjero',
  'fencing': 'esgrima',
  'ferris wheel': 'noria',
  'fig': 'higo',
  'firefighter': 'bombero',
  'fisherman': 'pescador',
  'flower': 'flor',
  'flute': 'flauta',
  'fog': 'niebla',
  'forest': 'bosque',
  'fox': 'zorro',
  'friend': 'amigo',
  'frog': 'rana',
  'garlic': 'ajo',
  'ginger': 'jengibre',
  'ginseng': 'ginseng',
  'giraffe': 'jirafa',
  'gloves': 'guantes',
  'goat': 'cabra',
  'golf': 'golf',
  'goose': 'ganso',
  'gorilla': 'gorila',
  'grape': 'uva',
  'grapefruit': 'pomelo',
  'guitar': 'guitarra',
  'hairdressor': 'peluquero',
  'hallway': 'pasillo',
  'harmonica': 'armónica',
  'harp': 'arpa',
  'hat': 'sombrero',
  'hawk': 'halcón',
  'helicopter': 'helicóptero',
  'hippo': 'hipopótamo',
  'hippocampus': 'hipocampo',
  'hockey': 'hockey',
  'horse': 'caballo',
  'hyena': 'hiena',
  'iceberg': 'iceberg',
  'iguana': 'iguana',
  'jellyfish': 'medusa',
  'judge': 'juez',
  'judo': 'judo',
  'jujube': 'azufaifo',
  'jungle': 'jungla',
  'kangaroo': 'canguro',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'lago',
  'lemon': 'limón',
  'leopard': 'leopardo',
  'lettuce': 'lechuga',
  'lightning': 'relámpago',
  'lion': 'león',
  'lizard': 'lagarto',
  'lobster': 'langosta',
  'magpie': 'urraca',
  'mango': 'mango',
  'marathon': 'maratón',
  'meerkat': 'suricata',
  'melon': 'melón',
  'Merry go round': 'carrusel',
  'mole': 'topo',
  'monkey': 'mono',
  'moon': 'luna',
  'mountain': 'montaña',
  'mouse': 'ratón',
  'mushroom': 'hongo',
  'notebook': 'cuaderno',
  'ocarina': 'ocarina',
  'ocean': 'océano',
  'octopus': 'pulpo',
  'onion': 'cebolla',
  'orange': 'naranja',
  'orangutan': 'orangután',
  'orchestra': 'orquesta',
  'ostrich': 'avestruz',
  'owl': 'búho',
  'painter': 'pintor',
  'pants': 'pantalones',
  'parrot': 'loro',
  'parsley': 'perejil',
  'peach': 'durazno',
  'peacock': 'pavo real',
  'pelican': 'pelícano',
  'pencil': 'lápiz',
  'penguin': 'pingüino',
  'pepper': 'pimienta',
  'pharmacist': 'farmacéutico',
  'piano': 'piano',
  'pickle': 'pepinillo',
  'pig': 'cerdo',
  'pigeon': 'paloma',
  'pilot': 'piloto',
  'pineapple': 'piña',
  'platypus': 'ornitorrinco',
  'playground': 'parque infantil',
  'policeman': 'policía',
  'pomegranate': 'granada',
  'potato': 'patata',
  'principal': 'director',
  'professor': 'profesor',
  'pumpkin': 'calabaza',
  'rabbit': 'conejo',
  'raccoon': 'mapache',
  'rain': 'lluvia',
  'restroom': 'baño',
  'rhino': 'rinoceronte',
  'river': 'río',
  'rock': 'roca',
  'saxophone': 'saxofón',
  'scientist': 'científico',
  'seagull': 'gaviota',
  'seal': 'foca',
  'sesame': 'sésamo',
  'shark': 'tiburón',
  'sheep': 'oveja',
  'shirt': 'camisa',
  'singer': 'cantante',
  'ski': 'esquí',
  'skunk': 'mofeta',
  'sky': 'cielo',
  'snail': 'caracol',
  'snake': 'serpiente',
  'snow': 'nieve',
  'snowboard': 'snowboard',
  'soccer': 'fútbol',
  'socks': 'calcetines',
  'soil': 'suelo',
  'soldier': 'soldado',
  'space': 'espacio',
  'sparrow': 'gorrión',
  'spinach': 'espinaca',
  'starfish': 'estrella de mar',
  'stewardess': 'azafata',
  'stingray': 'mantarraya',
  'strawberry': 'fresa',
  'sun': 'sol',
  'subway': 'metro',
  'swallow': 'golondrina',
  'sweater': 'suéter',
  'swimming': 'natación',
  'swing': 'columpio',
  'table': 'mesa',
  'tambourine': 'pandereta',
  'teacher': 'maestro',
  'tiger': 'tigre',
  'timpani': 'timbales',
  'toad': 'sapo',
  'trampoline': 'trampolín',
  'tree': 'árbol',
  'triangle': 'triángulo',
  'truck': 'camión',
  'trumpet': 'trompeta',
  'turtle': 'tortuga',
  'typhoon': 'tifón',
  'unicorn': 'unicornio',
  'violin': 'violín',
  'viking ship': 'barco vikingo',
  'volcano': 'volcán',
  'volleyball': 'voleibol',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'cascada',
  'watermelon': 'sandía',
  'wave': 'ola',
  'whale': 'ballena',
  'wind': 'viento',
  'window': 'ventana',
  'wolf': 'lobo',
  'woodpecker': 'pájaro carpintero',
  'xylophone': 'xilófono',
  'yacht': 'yate',
  'zebra': 'cebra',
};

final Map<String, String> fraItemList = {
  'accordian': 'accordéon',
  'airplane': 'avion',
  'anaconda': 'anaconda',
  'ant': 'fourmi',
  'anteater': 'fourmilier',
  'apple': 'pomme',
  'apricot': 'abricot',
  'archery': 'tir à l\'arc',
  'astronaut': 'astronaute',
  'avocado': 'avocat',
  'badminton': 'badminton',
  'banana': 'banane',
  'baseball': 'base-ball',
  'basketball': 'basket-ball',
  'bassoon': 'basson',
  'bat': 'chauve-souris',
  'beach': 'plage',
  'bear': 'ours',
  'bicycle': 'vélo',
  'blackboard': 'tableau noir',
  'blowfish': 'poisson-globe',
  'blueberries': 'myrtilles',
  'boar': 'sanglier',
  'book': 'livre',
  'boots': 'bottes',
  'bowling': 'bowling',
  'boxing': 'boxe',
  'broccoli': 'brocoli',
  'bumper car': 'auto tamponneuse',
  'bus': 'bus',
  'cabbage': 'chou',
  'camel': 'chameau',
  'canteen': 'cantine',
  'carp': 'carpe',
  'carpenter': 'charpentier',
  'carrot': 'carotte',
  'castanets': 'castagnettes',
  'cat': 'chat',
  'cello': 'violoncelle',
  'chameleon': 'caméléon',
  'cheetah': 'guépard',
  'cherry': 'cerise',
  'chick': 'poussin',
  'chicken': 'poulet',
  'clarinet': 'clarinette',
  'classroom': 'salle de classe',
  'cloud': 'nuage',
  'cobra': 'cobra',
  'coconut': 'noix de coco',
  'computer': 'ordinateur',
  'conductor': 'chef d\'orchestre',
  'contrabass': 'contrebasse',
  'cook': 'cuisinier',
  'corn': 'maïs',
  'cow': 'vache',
  'crab': 'crabe',
  'crane': 'grue',
  'crocodile': 'crocodile',
  'crow': 'corbeau',
  'cucumber': 'concombre',
  'curling': 'curling',
  'cymbals': 'cymbales',
  'deer': 'cerf',
  'dentist': 'dentiste',
  'desert': 'désert',
  'doctor': 'médecin',
  'dog': 'chien',
  'dolphin': 'dauphin',
  'drum': 'tambour',
  'duck': 'canard',
  'eagle': 'aigle',
  'earthquake': 'tremblement de terre',
  'elephant': 'éléphant',
  'exam': 'examen',
  'farmer': 'fermier',
  'fencing': 'escrime',
  'ferris wheel': 'grande roue',
  'fig': 'figue',
  'firefighter': 'pompier',
  'fisherman': 'pêcheur',
  'flower': 'fleur',
  'flute': 'flûte',
  'fog': 'brouillard',
  'forest': 'forêt',
  'fox': 'renard',
  'friend': 'ami',
  'frog': 'grenouille',
  'garlic': 'ail',
  'ginger': 'gingembre',
  'ginseng': 'ginseng',
  'giraffe': 'girafe',
  'gloves': 'gants',
  'goat': 'chèvre',
  'golf': 'golf',
  'goose': 'oie',
  'gorilla': 'gorille',
  'grape': 'raisin',
  'grapefruit': 'pamplemousse',
  'guitar': 'guitare',
  'hairdressor': 'coiffeur',
  'hallway': 'couloir',
  'harmonica': 'harmonica',
  'harp': 'harpe',
  'hat': 'chapeau',
  'hawk': 'faucon',
  'helicopter': 'hélicoptère',
  'hippo': 'hippopotame',
  'hippocampus': 'hippocampe',
  'hockey': 'hockey',
  'horse': 'cheval',
  'hyena': 'hyène',
  'iceberg': 'iceberg',
  'iguana': 'iguane',
  'jellyfish': 'méduse',
  'judge': 'juge',
  'judo': 'judo',
  'jujube': 'jujube',
  'jungle': 'jungle',
  'kangaroo': 'kangourou',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'lac',
  'lemon': 'citron',
  'leopard': 'léopard',
  'lettuce': 'laitue',
  'lightning': 'éclair',
  'lion': 'lion',
  'lizard': 'lézard',
  'lobster': 'homard',
  'magpie': 'pie',
  'mango': 'mangue',
  'marathon': 'marathon',
  'meerkat': 'suricate',
  'melon': 'melon',
  'Merry go round': 'manège',
  'mole': 'taupe',
  'monkey': 'singe',
  'moon': 'lune',
  'mountain': 'montagne',
  'mouse': 'souris',
  'mushroom': 'champignon',
  'notebook': 'cahier',
  'ocarina': 'ocarina',
  'ocean': 'océan',
  'octopus': 'poulpe',
  'onion': 'oignon',
  'orange': 'orange',
  'orangutan': 'orang-outan',
  'orchestra': 'orchestre',
  'ostrich': 'autruche',
  'owl': 'hibou',
  'painter': 'peintre',
  'pants': 'pantalon',
  'parrot': 'perroquet',
  'parsley': 'persil',
  'peach': 'pêche',
  'peacock': 'paon',
  'pelican': 'pélican',
  'pencil': 'crayon',
  'penguin': 'pingouin',
  'pepper': 'poivre',
  'pharmacist': 'pharmacien',
  'piano': 'piano',
  'pickle': 'cornichon',
  'pig': 'cochon',
  'pigeon': 'pigeon',
  'pilot': 'pilote',
  'pineapple': 'ananas',
  'platypus': 'ornithorynque',
  'playground': 'aire de jeux',
  'policeman': 'policier',
  'pomegranate': 'grenade',
  'potato': 'pomme de terre',
  'principal': 'directeur',
  'professor': 'professeur',
  'pumpkin': 'citrouille',
  'rabbit': 'lapin',
  'raccoon': 'raton laveur',
  'rain': 'pluie',
  'restroom': 'toilettes',
  'rhino': 'rhinocéros',
  'river': 'rivière',
  'rock': 'rocher',
  'saxophone': 'saxophone',
  'scientist': 'scientifique',
  'seagull': 'mouette',
  'seal': 'phoque',
  'sesame': 'sésame',
  'shark': 'squalo',
  'sheep': 'pecora',
  'shirt': 'chemise',
  'singer': 'chanteur',
  'ski': 'ski',
  'skunk': 'moufette',
  'sky': 'ciel',
  'snail': 'escargot',
  'snake': 'serpent',
  'snow': 'neige',
  'snowboard': 'snowboard',
  'soccer': 'football',
  'socks': 'chaussettes',
  'soil': 'sol',
  'soldier': 'soldat',
  'space': 'espace',
  'sparrow': 'moineau',
  'spinach': 'épinard',
  'starfish': 'étoile de mer',
  'stewardess': 'hôtesse de l\'air',
  'stingray': 'razza',
  'strawberry': 'fragola',
  'sun': 'soleil',
  'subway': 'métro',
  'swallow': 'hirondelle',
  'sweater': 'pull',
  'swimming': 'natation',
  'swing': 'balançoire',
  'table': 'table',
  'tambourine': 'tambourin',
  'teacher': 'enseignant',
  'tiger': 'tigre',
  'timpani': 'timbales',
  'toad': 'crapaud',
  'trampoline': 'trampoline',
  'tree': 'arbre',
  'triangle': 'triangle',
  'truck': 'camion',
  'trumpet': 'trompette',
  'turtle': 'tortue',
  'typhoon': 'typhon',
  'unicorn': 'licorne',
  'violin': 'violon',
  'viking ship': 'drakkar',
  'volcano': 'volcan',
  'volleyball': 'volley-ball',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'cascade',
  'watermelon': 'pastèque',
  'wave': 'vague',
  'whale': 'baleine',
  'wind': 'vent',
  'window': 'fenêtre',
  'wolf': 'loup',
  'woodpecker': 'pic',
  'xylophone': 'xylophone',
  'yacht': 'yacht',
  'zebra': 'zèbre',
};

final Map<String, String> deuItemList = {
  'accordian': 'Akkordeon',
  'airplane': 'Flugzeug',
  'anaconda': 'Anakonda',
  'ant': 'Ameise',
  'anteater': 'Ameisenbär',
  'apple': 'Apfel',
  'apricot': 'Aprikose',
  'archery': 'Bogenschießen',
  'astronaut': 'Astronaut',
  'avocado': 'Avocado',
  'badminton': 'Badminton',
  'banana': 'Banane',
  'baseball': 'Baseball',
  'basketball': 'Basketball',
  'bassoon': 'Fagott',
  'bat': 'Fledermaus',
  'beach': 'Strand',
  'bear': 'Bär',
  'bicycle': 'Fahrrad',
  'blackboard': 'Tafel',
  'blowfish': 'Kugelfisch',
  'blueberries': 'Blaubeeren',
  'boar': 'Wildschwein',
  'book': 'Buch',
  'boots': 'Stiefel',
  'bowling': 'Bowling',
  'boxing': 'Boxen',
  'broccoli': 'Brokkoli',
  'bumper car': 'Autoscooter',
  'bus': 'Bus',
  'cabbage': 'Kohl',
  'camel': 'Kamel',
  'canteen': 'Kantine',
  'carp': 'Karpfen',
  'carpenter': 'Zimmermann',
  'carrot': 'Karotte',
  'castanets': 'Kastagnetten',
  'cat': 'Katze',
  'cello': 'Cello',
  'chameleon': 'Chamäleon',
  'cheetah': 'Gepard',
  'cherry': 'Kirsche',
  'chick': 'Küken',
  'chicken': 'Huhn',
  'clarinet': 'Klarinette',
  'classroom': 'Klassenzimmer',
  'cloud': 'Wolke',
  'cobra': 'Kobra',
  'coconut': 'Kokosnuss',
  'computer': 'Computer',
  'conductor': 'Dirigent',
  'contrabass': 'Kontrabass',
  'cook': 'Koch',
  'corn': 'Mais',
  'cow': 'Kuh',
  'crab': 'Krabbe',
  'crane': 'Kran',
  'crocodile': 'Krokodil',
  'crow': 'Krähe',
  'cucumber': 'Gurke',
  'curling': 'Curling',
  'cymbals': 'Becken',
  'deer': 'Hirsch',
  'dentist': 'Zahnarzt',
  'desert': 'Wüste',
  'doctor': 'Arzt',
  'dog': 'Hund',
  'dolphin': 'Delfin',
  'drum': 'Trommel',
  'duck': 'Ente',
  'eagle': 'Adler',
  'earthquake': 'Erdbeben',
  'elephant': 'Elefant',
  'exam': 'Prüfung',
  'farmer': 'Bauer',
  'fencing': 'Fechten',
  'ferris wheel': 'Riesenrad',
  'fig': 'Feige',
  'firefighter': 'Feuerwehrmann',
  'fisherman': 'Fischer',
  'flower': 'Blume',
  'flute': 'Flöte',
  'fog': 'Nebel',
  'forest': 'Wald',
  'fox': 'Fuchs',
  'friend': 'Freund',
  'frog': 'Frosch',
  'garlic': 'Knoblauch',
  'ginger': 'Ingwer',
  'ginseng': 'Ginseng',
  'giraffe': 'Giraffe',
  'gloves': 'Handschuhe',
  'goat': 'Ziege',
  'golf': 'Golf',
  'goose': 'Gans',
  'gorilla': 'Gorilla',
  'grape': 'Traube',
  'grapefruit': 'Grapefruit',
  'guitar': 'Gitarre',
  'hairdressor': 'Friseur',
  'hallway': 'Flur',
  'harmonica': 'Mundharmonika',
  'harp': 'Harfe',
  'hat': 'Hut',
  'hawk': 'Falke',
  'helicopter': 'Hubschrauber',
  'hippo': 'Nilpferd',
  'hippocampus': 'Seepferdchen',
  'hockey': 'Hockey',
  'horse': 'Pferd',
  'hyena': 'Hyäne',
  'iceberg': 'Eisberg',
  'iguana': 'Leguan',
  'jellyfish': 'Qualle',
  'judge': 'Richter',
  'judo': 'Judo',
  'jujube': 'Jujube',
  'jungle': 'Dschungel',
  'kangaroo': 'Känguru',
  'kiwi': 'Kiwi',
  'koala': 'Koala',
  'lake': 'See',
  'lemon': 'Zitrone',
  'leopard': 'Leopard',
  'lettuce': 'Salat',
  'lightning': 'Blitz',
  'lion': 'Löwe',
  'lizard': 'Eidechse',
  'lobster': 'Hummer',
  'magpie': 'Elster',
  'mango': 'Mango',
  'marathon': 'Marathon',
  'meerkat': 'Erdmännchen',
  'melon': 'Melone',
  'Merry go round': 'Karussell',
  'mole': 'Maulwurf',
  'monkey': 'Affe',
  'moon': 'Mond',
  'mountain': 'Berg',
  'mouse': 'Maus',
  'mushroom': 'Pilz',
  'notebook': 'Notizbuch',
  'ocarina': 'Okarina',
  'ocean': 'Ozean',
  'octopus': 'Oktopus',
  'onion': 'Zwiebel',
  'orange': 'Orange',
  'orangutan': 'Orang-Utan',
  'orchestra': 'Orchester',
  'ostrich': 'Strauß',
  'owl': 'Eule',
  'painter': 'Maler',
  'pants': 'Hose',
  'parrot': 'Papagei',
  'parsley': 'Petersilie',
  'peach': 'Pfirsich',
  'peacock': 'Pfau',
  'pelican': 'Pelikan',
  'pencil': 'Bleistift',
  'penguin': 'Pinguin',
  'pepper': 'Pfeffer',
  'pharmacist': 'Apotheker',
  'piano': 'Klavier',
  'pickle': 'Essiggurke',
  'pig': 'Schwein',
  'pigeon': 'Taube',
  'pilot': 'Pilot',
  'pineapple': 'Ananas',
  'platypus': 'Schnabeltier',
  'playground': 'Spielplatz',
  'policeman': 'Polizist',
  'pomegranate': 'Granatapfel',
  'potato': 'Kartoffel',
  'principal': 'Direktor',
  'professor': 'Professor',
  'pumpkin': 'Kürbis',
  'rabbit': 'Kaninchen',
  'raccoon': 'Waschbär',
  'rain': 'Regen',
  'restroom': 'Toilette',
  'rhino': 'Nashorn',
  'river': 'Fluss',
  'rock': 'Felsen',
  'saxophone': 'Saxophon',
  'scientist': 'Wissenschaftler',
  'seagull': 'Möwe',
  'seal': 'Robbe',
  'sesame': 'Sesam',
  'shark': 'Hai',
  'sheep': 'Schaf',
  'shirt': 'Hemd',
  'singer': 'Sänger',
  'ski': 'Ski',
  'skunk': 'Stinktier',
  'sky': 'Himmel',
  'snail': 'Schnecke',
  'snake': 'Schlange',
  'snow': 'Schnee',
  'snowboard': 'Snowboard',
  'soccer': 'Fußball',
  'socks': 'Socken',
  'soil': 'Boden',
  'soldier': 'Soldat',
  'space': 'Weltraum',
  'sparrow': 'Spatz',
  'spinach': 'Spinat',
  'starfish': 'Seestern',
  'stewardess': 'Stewardess',
  'stingray': 'Stachelrochen',
  'strawberry': 'Erdbeere',
  'sun': 'Sonne',
  'subway': 'U-Bahn',
  'swallow': 'Schwalbe',
  'sweater': 'Pullover',
  'swimming': 'Schwimmen',
  'swing': 'Schaukel',
  'table': 'Tisch',
  'tambourine': 'Tamburin',
  'teacher': 'Lehrer',
  'tiger': 'Tiger',
  'timpani': 'Pauken',
  'toad': 'Kröte',
  'trampoline': 'Trampolin',
  'tree': 'Baum',
  'triangle': 'Dreieck',
  'truck': 'LKW',
  'trumpet': 'Trompete',
  'turtle': 'Schildkröte',
  'typhoon': 'Taifun',
  'unicorn': 'Einhorn',
  'violin': 'Geige',
  'viking ship': 'Wikingerschiff',
  'volcano': 'Vulkan',
  'volleyball': 'Volleyball',
  'vuvuzela': 'Vuvuzela',
  'waterfall': 'Wasserfall',
  'watermelon': 'Wassermelone',
  'wave': 'Welle',
  'whale': 'Wal',
  'wind': 'Wind',
  'window': 'Fenster',
  'wolf': 'Wolf',
  'woodpecker': 'Specht',
  'xylophone': 'Xylophon',
  'yacht': 'Yacht',
  'zebra': 'Zebra',
};

final Map<String, String> jpnItemList = {
  'accordian': 'アコーディオン',
  'airplane': '飛行機',
  'anaconda': 'アナコンダ',
  'ant': 'アリ',
  'anteater': 'アリクイ',
  'apple': 'リンゴ',
  'apricot': 'アンズ',
  'archery': 'アーチェリー',
  'astronaut': '宇宙飛行士',
  'avocado': 'アボカド',
  'badminton': 'バドミントン',
  'banana': 'バナナ',
  'baseball': '野球',
  'basketball': 'バスケットボール',
  'bassoon': 'ファゴット',
  'bat': 'コウモリ',
  'beach': 'ビーチ',
  'bear': 'クマ',
  'bicycle': '自転車',
  'blackboard': '黒板',
  'blowfish': 'フグ',
  'blueberries': 'ブルーベリー',
  'boar': 'イノシシ',
  'book': '本',
  'boots': 'ブーツ',
  'bowling': 'ボウリング',
  'boxing': 'ボクシング',
  'broccoli': 'ブロッコリー',
  'bumper car': 'バンパーカー',
  'bus': 'バス',
  'cabbage': 'キャベツ',
  'camel': 'ラクダ',
  'canteen': '食堂',
  'carp': 'コイ',
  'carpenter': '大工',
  'carrot': 'ニンジン',
  'castanets': 'カスタネット',
  'cat': '猫',
  'cello': 'チェロ',
  'chameleon': 'カメレオン',
  'cheetah': 'チーター',
  'cherry': 'サクランボ',
  'chick': 'ひよこ',
  'chicken': '鶏',
  'clarinet': 'クラリネット',
  'classroom': '教室',
  'cloud': '雲',
  'cobra': 'コブラ',
  'coconut': 'ココナッツ',
  'computer': 'コンピュータ',
  'conductor': '指揮者',
  'contrabass': 'コントラバス',
  'cook': '料理人',
  'corn': 'トウモロコシ',
  'cow': '牛',
  'crab': 'カニ',
  'crane': 'クレーン',
  'crocodile': 'ワニ',
  'crow': 'カラス',
  'cucumber': 'キュウリ',
  'curling': 'カーリング',
  'cymbals': 'シンバル',
  'deer': '鹿',
  'dentist': '歯医者',
  'desert': '砂漠',
  'doctor': '医者',
  'dog': '犬',
  'dolphin': 'イルカ',
  'drum': 'ドラム',
  'duck': 'アヒル',
  'eagle': 'ワシ',
  'earthquake': '地震',
  'elephant': '象',
  'exam': '試験',
  'farmer': '農家',
  'fencing': 'フェンシング',
  'ferris wheel': '観覧車',
  'fig': 'イチジク',
  'firefighter': '消防士',
  'fisherman': '漁師',
  'flower': '花',
  'flute': 'フルート',
  'fog': '霧',
  'forest': '森',
  'fox': 'キツネ',
  'friend': '友達',
  'frog': 'カエル',
  'garlic': 'ニンニク',
  'ginger': 'ショウガ',
  'ginseng': '高麗人参',
  'giraffe': 'キリン',
  'gloves': '手袋',
  'goat': 'ヤギ',
  'golf': 'ゴルフ',
  'goose': 'ガチョウ',
  'gorilla': 'ゴリラ',
  'grape': 'ブドウ',
  'grapefruit': 'グレープフルーツ',
  'guitar': 'ギター',
  'hairdressor': '美容師',
  'hallway': '廊下',
  'harmonica': 'ハーモニカ',
  'harp': 'ハープ',
  'hat': '帽子',
  'hawk': 'タカ',
  'helicopter': 'ヘリコプター',
  'hippo': 'カバ',
  'hippocampus': 'タツノオトシゴ',
  'hockey': 'ホッケー',
  'horse': '馬',
  'hyena': 'ハイエナ',
  'iceberg': '氷山',
  'iguana': 'イグアナ',
  'jellyfish': 'クラゲ',
  'judge': '裁判官',
  'judo': '柔道',
  'jujube': 'ナツメ',
  'jungle': 'ジャングル',
  'kangaroo': 'カンガルー',
  'kiwi': 'キウイ',
  'koala': 'コアラ',
  'lake': '湖',
  'lemon': 'レモン',
  'leopard': 'ヒョウ',
  'lettuce': 'レタス',
  'lightning': '稲妻',
  'lion': 'ライオン',
  'lizard': 'トカゲ',
  'lobster': 'ロブスター',
  'magpie': 'カササギ',
  'mango': 'マンゴー',
  'marathon': 'マラソン',
  'meerkat': 'ミーアキャット',
  'melon': 'メロン',
  'Merry go round': 'メリーゴーランド',
  'mole': 'モグラ',
  'monkey': 'サル',
  'moon': '月',
  'mountain': '山',
  'mouse': 'ネズミ',
  'mushroom': 'キノコ',
  'notebook': 'ノート',
  'ocarina': 'オカリナ',
  'ocean': '海',
  'octopus': 'タコ',
  'onion': 'タマネギ',
  'orange': 'オレンジ',
  'orangutan': 'オランウータン',
  'orchestra': 'オーケストラ',
  'ostrich': 'ダチョウ',
  'owl': 'フクロウ',
  'painter': '画家',
  'pants': 'ズボン',
  'parrot': 'オウム',
  'parsley': 'パセリ',
  'peach': 'モモ',
  'peacock': 'クジャク',
  'pelican': 'ペリカン',
  'pencil': '鉛筆',
  'penguin': 'ペンギン',
  'pepper': 'コショウ',
  'pharmacist': '薬剤師',
  'piano': 'ピアノ',
  'pickle': 'ピクルス',
  'pig': 'ブタ',
  'pigeon': 'ハト',
  'pilot': 'パイロット',
  'pineapple': 'パイナップル',
  'platypus': 'カモノハシ',
  'playground': '遊び場',
  'policeman': '警察官',
  'pomegranate': 'ザクロ',
  'potato': 'ジャガイモ',
  'principal': '校長',
  'professor': '教授',
  'pumpkin': 'カボチャ',
  'rabbit': 'ウサギ',
  'raccoon': 'アライグマ',
  'rain': '雨',
  'restroom': 'トイレ',
  'rhino': 'サイ',
  'river': '川',
  'rock': '岩',
  'saxophone': 'サクソフォン',
  'scientist': '科学者',
  'seagull': 'カモメ',
  'seal': 'アザラシ',
  'sesame': 'ゴマ',
  'shark': 'サメ',
  'sheep': '羊',
  'shirt': 'シャツ',
  'singer': '歌手',
  'ski': 'スキー',
  'skunk': 'スカンク',
  'sky': '空',
  'snail': 'カタツムリ',
  'snake': 'ヘビ',
  'snow': '雪',
  'snowboard': 'スノーボード',
  'soccer': 'サッカー',
  'socks': '靴下',
  'soil': '土',
  'soldier': '兵士',
  'space': '宇宙',
  'sparrow': 'スズメ',
  'spinach': 'ホウレンソウ',
  'starfish': 'ヒトデ',
  'stewardess': 'スチュワーデス',
  'stingray': 'エイ',
  'strawberry': 'イチゴ',
  'sun': '太陽',
  'subway': '地下鉄',
  'swallow': 'ツバメ',
  'sweater': 'セーター',
  'swimming': '水泳',
  'swing': 'ブランコ',
  'table': 'テーブル',
  'tambourine': 'タンバリン',
  'teacher': '先生',
  'tiger': 'トラ',
  'timpani': 'ティンパニ',
  'toad': 'ヒキガエル',
  'trampoline': 'トランポリン',
  'tree': '木',
  'triangle': '三角形',
  'truck': 'トラック',
  'trumpet': 'トランペット',
  'turtle': 'カメ',
  'typhoon': '台風',
  'unicorn': 'ユニコーン',
  'violin': 'バイオリン',
  'viking ship': 'バイキング船',
  'volcano': '火山',
  'volleyball': 'バレーボール',
  'vuvuzela': 'ブブゼラ',
  'waterfall': '滝',
  'watermelon': 'スイカ',
  'wave': '波',
  'whale': 'クジラ',
  'wind': '風',
  'window': '窓',
  'wolf': 'オオカミ',
  'woodpecker': 'キツツキ',
  'xylophone': 'シロフォン',
  'yacht': 'ヨット',
  'zebra': 'シマウマ',
};

final Map<String, String> chnItemList = {
  'accordian': '手风琴',
  'airplane': '飞机',
  'anaconda': '水蚺',
  'ant': '蚂蚁',
  'anteater': '食蚁兽',
  'apple': '苹果',
  'apricot': '杏',
  'archery': '射箭',
  'astronaut': '宇航员',
  'avocado': '鳄梨',
  'badminton': '羽毛球',
  'banana': '香蕉',
  'baseball': '棒球',
  'basketball': '篮球',
  'bassoon': '巴松管',
  'bat': '蝙蝠',
  'beach': '海滩',
  'bear': '熊',
  'bicycle': '自行车',
  'blackboard': '黑板',
  'blowfish': '河豚',
  'blueberries': '蓝莓',
  'boar': '野猪',
  'book': '书',
  'boots': '靴子',
  'bowling': '保龄球',
  'boxing': '拳击',
  'broccoli': '西兰花',
  'bumper car': '碰碰车',
  'bus': '公共汽车',
  'cabbage': '卷心菜',
  'camel': '骆驼',
  'canteen': '食堂',
  'carp': '鲤鱼',
  'carpenter': '木匠',
  'carrot': '胡萝卜',
  'castanets': '响板',
  'cat': '猫',
  'cello': '大提琴',
  'chameleon': '变色龙',
  'cheetah': '猎豹',
  'cherry': '樱桃',
  'chick': '小鸡',
  'chicken': '鸡',
  'clarinet': '单簧管',
  'classroom': '教室',
  'cloud': '云',
  'cobra': '眼镜蛇',
  'coconut': '椰子',
  'computer': '电脑',
  'conductor': '指挥',
  'contrabass': '低音提琴',
  'cook': '厨师',
  'corn': '玉米',
  'cow': '牛',
  'crab': '螃蟹',
  'crane': '起重机',
  'crocodile': '鳄鱼',
  'crow': '乌鸦',
  'cucumber': '黄瓜',
  'curling': '冰壶',
  'cymbals': '钹',
  'deer': '鹿',
  'dentist': '牙医',
  'desert': '沙漠',
  'doctor': '医生',
  'dog': '狗',
  'dolphin': '海豚',
  'drum': '鼓',
  'duck': '鸭子',
  'eagle': '鹰',
  'earthquake': '地震',
  'elephant': '大象',
  'exam': '考试',
  'farmer': '农民',
  'fencing': '击剑',
  'ferris wheel': '摩天轮',
  'fig': '无花果',
  'firefighter': '消防员',
  'fisherman': '渔夫',
  'flower': '花',
  'flute': '长笛',
  'fog': '雾',
  'forest': '森林',
  'fox': '狐狸',
  'friend': '朋友',
  'frog': '青蛙',
  'garlic': '大蒜',
  'ginger': '生姜',
  'ginseng': '人参',
  'giraffe': '长颈鹿',
  'gloves': '手套',
  'goat': '山羊',
  'golf': '高尔夫',
  'goose': '鹅',
  'gorilla': '大猩猩',
  'grape': '葡萄',
  'grapefruit': '葡萄柚',
  'guitar': '吉他',
  'hairdressor': '理发师',
  'hallway': '走廊',
  'harmonica': '口琴',
  'harp': '竖琴',
  'hat': '帽子',
  'hawk': '鹰',
  'helicopter': '直升机',
  'hippo': '河马',
  'hippocampus': '海马',
  'hockey': '曲棍球',
  'horse': '马',
  'hyena': '鬣狗',
  'iceberg': '冰山',
  'iguana': '鬣蜥',
  'jellyfish': '水母',
  'judge': '法官',
  'judo': '柔道',
  'jujube': '枣',
  'jungle': '丛林',
  'kangaroo': '袋鼠',
  'kiwi': '猕猴桃',
  'koala': '考拉',
  'lake': '湖',
  'lemon': '柠檬',
  'leopard': '豹',
  'lettuce': '生菜',
  'lightning': '闪电',
  'lion': '狮子',
  'lizard': '蜥蜴',
  'lobster': '龙虾',
  'magpie': '喜鹊',
  'mango': '芒果',
  'marathon': '马拉松',
  'meerkat': '猫鼬',
  'melon': '瓜',
  'Merry go round': '旋转木马',
  'mole': '鼹鼠',
  'monkey': '猴子',
  'moon': '月亮',
  'mountain': '山',
  'mouse': '老鼠',
  'mushroom': '蘑菇',
  'notebook': '笔记本',
  'ocarina': '陶笛',
  'ocean': '海洋',
  'octopus': '章鱼',
  'onion': '洋葱',
  'orange': '橙子',
  'orangutan': '猩猩',
  'orchestra': '管弦乐队',
  'ostrich': '鸵鸟',
  'owl': '猫头鹰',
  'painter': '画家',
  'pants': '裤子',
  'parrot': '鹦鹉',
  'parsley': '欧芹',
  'peach': '桃子',
  'peacock': '孔雀',
  'pelican': '鹈鹕',
  'pencil': '铅笔',
  'penguin': '企鹅',
  'pepper': '胡椒',
  'pharmacist': '药剂师',
  'piano': '钢琴',
  'pickle': '泡菜',
  'pig': '猪',
  'pigeon': '鸽子',
  'pilot': '飞行员',
  'pineapple': '菠萝',
  'platypus': '鸭嘴兽',
  'playground': '操场',
  'policeman': '警察',
  'pomegranate': '石榴',
  'potato': '土豆',
  'principal': '校长',
  'professor': '教授',
  'pumpkin': '南瓜',
  'rabbit': '兔子',
  'raccoon': '浣熊',
  'rain': '雨',
  'restroom': '洗手间',
  'rhino': '犀牛',
  'river': '河',
  'rock': '岩石',
  'saxophone': '萨克斯',
  'scientist': '科学家',
  'seagull': '海鸥',
  'seal': '海豹',
  'sesame': '芝麻',
  'shark': '鲨鱼',
  'sheep': '羊',
  'shirt': '衬衫',
  'singer': '歌手',
  'ski': '滑雪',
  'skunk': '臭鼬',
  'sky': '天空',
  'snail': '蜗牛',
  'snake': '蛇',
  'snow': '雪',
  'snowboard': '单板滑雪',
  'soccer': '足球',
  'socks': '袜子',
  'soil': '土壤',
  'soldier': '士兵',
  'space': '太空',
  'sparrow': '麻雀',
  'spinach': '菠菜',
  'starfish': '海星',
  'stewardess': '空姐',
  'stingray': '黄貂鱼',
  'strawberry': '草莓',
  'sun': '太阳',
  'subway': '地铁',
  'swallow': '燕子',
  'sweater': '毛衣',
  'swimming': '游泳',
  'swing': '秋千',
  'table': '桌子',
  'tambourine': '铃鼓',
  'teacher': '老师',
  'tiger': '老虎',
  'timpani': '定音鼓',
  'toad': '蟾蜍',
  'trampoline': '蹦床',
  'tree': '树',
  'triangle': '三角形',
  'truck': '卡车',
  'trumpet': '小号',
  'turtle': '乌龟',
  'typhoon': '台风',
  'unicorn': '独角兽',
  'violin': '小提琴',
  'viking ship': '维京船',
  'volcano': '火山',
  'volleyball': '排球',
  'vuvuzela': '呜呜祖拉',
  'waterfall': '瀑布',
  'watermelon': '西瓜',
  'wave': '波浪',
  'whale': '鲸鱼',
  'wind': '风',
  'window': '窗户',
  'wolf': '狼',
  'woodpecker': '啄木鸟',
  'xylophone': '木琴',
  'yacht': '游艇',
  'zebra': '斑马',
};

final Map<String, String> rusItemList = {
  'accordian': 'аккордеон',
  'airplane': 'самолет',
  'anaconda': 'анаконда',
  'ant': 'муравей',
  'anteater': 'муравьед',
  'apple': 'яблоко',
  'apricot': 'абрикос',
  'archery': 'стрельба из лука',
  'astronaut': 'астронавт',
  'avocado': 'авокадо',
  'badminton': 'бадминтон',
  'banana': 'банан',
  'baseball': 'бейсбол',
  'basketball': 'баскетбол',
  'bassoon': 'фагот',
  'bat': 'летучая мышь',
  'beach': 'пляж',
  'bear': 'медведь',
  'bicycle': 'велосипед',
  'blackboard': 'доска',
  'blowfish': 'рыба-фугу',
  'blueberries': 'черника',
  'boar': 'кабан',
  'book': 'книга',
  'boots': 'сапоги',
  'bowling': 'боулинг',
  'boxing': 'бокс',
  'broccoli': 'брокколи',
  'bumper car': 'автодром',
  'bus': 'автобус',
  'cabbage': 'капуста',
  'camel': 'верблюд',
  'canteen': 'столовая',
  'carp': 'карп',
  'carpenter': 'плотник',
  'carrot': 'морковь',
  'castanets': 'кастаньеты',
  'cat': 'кот',
  'cello': 'виолончель',
  'chameleon': 'хамелеон',
  'cheetah': 'гепард',
  'cherry': 'вишня',
  'chick': 'цыпленок',
  'chicken': 'курица',
  'clarinet': 'кларнет',
  'classroom': 'класс',
  'cloud': 'облако',
  'cobra': 'кобра',
  'coconut': 'кокос',
  'computer': 'компьютер',
  'conductor': 'дирижер',
  'contrabass': 'контрабас',
  'cook': 'повар',
  'corn': 'кукуруза',
  'cow': 'корова',
  'crab': 'краб',
  'crane': 'кран',
  'crocodile': 'крокодил',
  'crow': 'ворона',
  'cucumber': 'огурец',
  'curling': 'кёрлинг',
  'cymbals': 'тарелки',
  'deer': 'олень',
  'dentist': 'стоматолог',
  'desert': 'пустыня',
  'doctor': 'врач',
  'dog': 'собака',
  'dolphin': 'дельфин',
  'drum': 'барабан',
  'duck': 'утка',
  'eagle': 'орел',
  'earthquake': 'землетрясение',
  'elephant': 'слон',
  'exam': 'экзамен',
  'farmer': 'фермер',
  'fencing': 'фехтование',
  'ferris wheel': 'колесо обозрения',
  'fig': 'инжир',
  'firefighter': 'пожарный',
  'fisherman': 'рыбак',
  'flower': 'цветок',
  'flute': 'флейта',
  'fog': 'туман',
  'forest': 'лес',
  'fox': 'лиса',
  'friend': 'друг',
  'frog': 'лягушка',
  'garlic': 'чеснок',
  'ginger': 'имбирь',
  'ginseng': 'женьшень',
  'giraffe': 'жираф',
  'gloves': 'перчатки',
  'goat': 'коза',
  'golf': 'гольф',
  'goose': 'гусь',
  'gorilla': 'горилла',
  'grape': 'виноград',
  'grapefruit': 'грейпфрут',
  'guitar': 'гитара',
  'hairdressor': 'парикмахер',
  'hallway': 'коридор',
  'harmonica': 'гармоника',
  'harp': 'арфа',
  'hat': 'шляпа',
  'hawk': 'ястреб',
  'helicopter': 'вертолет',
  'hippo': 'бегемот',
  'hippocampus': 'морской конек',
  'hockey': 'хоккей',
  'horse': 'лошадь',
  'hyena': 'гиена',
  'iceberg': 'айсберг',
  'iguana': 'игуана',
  'jellyfish': 'медуза',
  'judge': 'судья',
  'judo': 'дзюдо',
  'jujube': 'зизифус',
  'jungle': 'джунгли',
  'kangaroo': 'кенгуру',
  'kiwi': 'киви',
  'koala': 'коала',
  'lake': 'озеро',
  'lemon': 'лимон',
  'leopard': 'леопард',
  'lettuce': 'салат',
  'lightning': 'молния',
  'lion': 'лев',
  'lizard': 'ящерица',
  'lobster': 'омар',
  'magpie': 'сорока',
  'mango': 'манго',
  'marathon': 'марафон',
  'meerkat': 'сурикат',
  'melon': 'дыня',
  'Merry go round': 'карусель',
  'mole': 'крот',
  'monkey': 'обезьяна',
  'moon': 'луна',
  'mountain': 'гора',
  'mouse': 'мышь',
  'mushroom': 'гриб',
  'notebook': 'тетрадь',
  'ocarina': 'окарина',
  'ocean': 'океан',
  'octopus': 'осьминог',
  'onion': 'лук',
  'orange': 'апельсин',
  'orangutan': 'орангутан',
  'orchestra': 'оркестр',
  'ostrich': 'страус',
  'owl': 'сова',
  'painter': 'художник',
  'pants': 'брюки',
  'parrot': 'попугай',
  'parsley': 'петрушка',
  'peach': 'персик',
  'peacock': 'павлин',
  'pelican': 'пеликан',
  'pencil': 'карандаш',
  'penguin': 'пингвин',
  'pepper': 'перец',
  'pharmacist': 'фармацевт',
  'piano': 'пианино',
  'pickle': 'соленый огурец',
  'pig': 'свинья',
  'pigeon': 'голубь',
  'pilot': 'пилот',
  'pineapple': 'ананас',
  'platypus': 'утконос',
  'playground': 'игровая площадка',
  'policeman': 'полицейский',
  'pomegranate': 'гранат',
  'potato': 'картофель',
  'principal': 'директор',
  'professor': 'профессор',
  'pumpkin': 'тыква',
  'rabbit': 'кролик',
  'raccoon': 'енот',
  'rain': 'дождь',
  'restroom': 'туалет',
  'rhino': 'ринoceronте',
  'river': 'река',
  'rock': 'скала',
  'saxophone': 'саксофон',
  'scientist': 'ученый',
  'seagull': 'чайка',
  'seal': 'фонарик',
  'sesame': 'самовар',
  'shark': 'акула',
  'sheep': 'овца',
  'shirt': 'рубашка',
  'singer': 'певец',
  'ski': 'лыжи',
  'skunk': 'старик',
  'sky': 'небо',
  'snail': 'улитка',
  'snake': 'змея',
  'snow': 'снег',
  'snowboard': 'сноуборд',
  'soccer': 'футбол',
  'socks': 'носки',
  'soil': 'почва',
  'soldier': 'солдат',
  'space': 'космос',
  'sparrow': 'воробей',
  'spinach': 'шпинат',
  'starfish': 'морская звезда',
  'stewardess': 'стюардесса',
  'stingray': 'скат',
  'strawberry': 'клубника',
  'sun': 'солнце',
  'subway': 'метро',
  'swallow': 'ласточка',
  'sweater': 'свитер',
  'swimming': 'плавание',
  'swing': 'качели',
  'table': 'стол',
  'tambourine': 'бубен',
  'teacher': 'учитель',
  'tiger': 'тигр',
  'timpani': 'литавры',
  'toad': 'жаба',
  'trampoline': 'батут',
  'tree': 'дерево',
  'triangle': 'треугольник',
  'truck': 'грузовик',
  'trumpet': 'труба',
  'turtle': 'черепаха',
  'typhoon': 'тайфун',
  'unicorn': 'единорог',
  'violin': 'скрипка',
  'viking ship': 'викингский корабль',
  'volcano': 'вулкан',
  'volleyball': 'волейбол',
  'vuvuzela': 'вувузела',
  'waterfall': 'водопад',
  'watermelon': 'арбуз',
  'wave': 'волна',
  'whale': 'кит',
  'wind': 'ветер',
  'window': 'окно',
  'wolf': 'волк',
  'woodpecker': 'дятел',
  'xylophone': 'ксилофон',
  'yacht': 'яхта',
  'zebra': 'зебра',
};

final Map<String, String> itaItemList = {
  'accordian': 'fisarmonica',
  'airplane': 'aereo',
  'anaconda': 'anaconda',
  'ant': 'formica',
  'anteater': 'formichiere',
  'apple': 'mela',
  'apricot': 'albicocca',
  'archery': 'tiro con l\'arco',
  'astronaut': 'astronauta',
  'avocado': 'avocado',
  'badminton': 'badminton',
  'banana': 'banana',
  'baseball': 'baseball',
  'basketball': 'pallacanestro',
  'bassoon': 'fagotto',
  'bat': 'pipistrello',
  'beach': 'spiaggia',
  'bear': 'orso',
  'bicycle': 'bicicletta',
  'blackboard': 'lavagna',
  'blowfish': 'pesce palla',
  'blueberries': 'mirtilli',
  'boar': 'cinghiale',
  'book': 'libro',
  'boots': 'stivali',
  'bowling': 'bowling',
  'boxing': 'pugilato',
  'broccoli': 'broccoli',
  'bumper car': 'autoscontro',
  'bus': 'autobus',
  'cabbage': 'cavolo',
  'camel': 'cammello',
  'canteen': 'mensa',
  'carp': 'carpa',
  'carpenter': 'carpentiere',
  'carrot': 'carota',
  'castanets': 'nacchere',
  'cat': 'gatto',
  'cello': 'violoncello',
  'chameleon': 'camaleonte',
  'cheetah': 'ghepardo',
  'cherry': 'ciliegia',
  'chick': 'pulcino',
  'chicken': 'pollo',
  'clarinet': 'clarinetto',
  'classroom': 'aula',
  'cloud': 'nuvola',
  'cobra': 'cobra',
  'coconut': 'noce di cocco',
  'computer': 'computer',
  'conductor': 'direttore d\'orchestra',
  'contrabass': 'contrabbasso',
  'cook': 'cuoco',
  'corn': 'mais',
  'cow': 'mucca',
  'crab': 'granchio',
  'crane': 'gru',
  'crocodile': 'coccodrillo',
  'crow': 'corvo',
  'cucumber': 'cetriolo',
  'curling': 'curling',
  'cymbals': 'piatti',
  'deer': 'cervo',
  'dentist': 'dentista',
  'desert': 'deserto',
  'doctor': 'medico',
  'dog': 'cane',
  'dolphin': 'delfino',
  'drum': 'tamburo',
  'duck': 'anatra',
  'eagle': 'aquila',
  'earthquake': 'terremoto',
  'elephant': 'elefante',
  'exam': 'esame',
  'farmer': 'contadino',
  'fencing': 'scherma',
  'ferris wheel': 'ruota panoramica',
  'fig': 'fico',
  'firefighter': 'pompiere',
  'fisherman': 'pescatore',
  'flower': 'fiore',
  'flute': 'flauto',
  'fog': 'nebbia',
  'forest': 'foresta',
  'fox': 'volpe',
  'friend': 'amico',
  'frog': 'rana',
  'garlic': 'aglio',
  'ginger': 'zenzero',
  'ginseng': 'ginseng',
  'giraffe': 'giraffa',
  'gloves': 'guanti',
  'goat': 'capra',
  'golf': 'golf',
  'goose': 'oca',
  'gorilla': 'gorilla',
  'grape': 'uva',
  'grapefruit': 'pompelmo',
  'guitar': 'chitarra',
  'hairdressor': 'parrucchiere',
  'hallway': 'corridoio',
  'harmonica': 'armonica',
  'harp': 'arpa',
  'hat': 'cappello',
  'hawk': 'falco',
  'helicopter': 'elicottero',
  'hippo': 'ippopotamo',
  'hippocampus': 'ippocampo',
  'hockey': 'hockey',
  'horse': 'cavallo',
  'hyena': 'iena',
  'iceberg': 'iceberg',
  'iguana': 'iguana',
  'jellyfish': 'medusa',
  'judge': 'giudice',
  'judo': 'judo',
  'jujube': 'giuggiola',
  'jungle': 'giungla',
  'kangaroo': 'canguro',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'lago',
  'lemon': 'limone',
  'leopard': 'leopardo',
  'lettuce': 'lattuga',
  'lightning': 'fulmine',
  'lion': 'leone',
  'lizard': 'lucertola',
  'lobster': 'aragosta',
  'magpie': 'gazza',
  'mango': 'mango',
  'marathon': 'maratona',
  'meerkat': 'suricato',
  'melon': 'melone',
  'Merry go round': 'giostra',
  'mole': 'talpa',
  'monkey': 'scimmia',
  'moon': 'luna',
  'mountain': 'montagna',
  'mouse': 'topo',
  'mushroom': 'fungo',
  'notebook': 'quaderno',
  'ocarina': 'ocarina',
  'ocean': 'oceano',
  'octopus': 'polpo',
  'onion': 'cipolla',
  'orange': 'arancia',
  'orangutan': 'orangotango',
  'orchestra': 'orchestra',
  'ostrich': 'struzzo',
  'owl': 'gufo',
  'painter': 'pittore',
  'pants': 'pantaloni',
  'parrot': 'pappagallo',
  'parsley': 'prezzemolo',
  'peach': 'pesca',
  'peacock': 'pavone',
  'pelican': 'pellicano',
  'pencil': 'matita',
  'penguin': 'pinguino',
  'pepper': 'pepe',
  'pharmacist': 'farmacista',
  'piano': 'pianoforte',
  'pickle': 'sottaceto',
  'pig': 'maiale',
  'pigeon': 'piccione',
  'pilot': 'pilota',
  'pineapple': 'ananas',
  'platypus': 'ornitorinco',
  'playground': 'parco giochi',
  'policeman': 'poliziotto',
  'pomegranate': 'melograno',
  'potato': 'patata',
  'principal': 'preside',
  'professor': 'professore',
  'pumpkin': 'zucca',
  'rabbit': 'coniglio',
  'raccoon': 'procione',
  'rain': 'pioggia',
  'restroom': 'bagno',
  'rhino': 'rinoceronte',
  'river': 'fiume',
  'rock': 'roccia',
  'saxophone': 'sassofono',
  'scientist': 'scienziato',
  'seagull': 'gabbiano',
  'seal': 'foca',
  'sesame': 'sesamo',
  'shark': 'squalo',
  'sheep': 'pecora',
  'shirt': 'camicia',
  'singer': 'cantante',
  'ski': 'sci',
  'skunk': 'puzzola',
  'sky': 'cielo',
  'snail': 'lumaca',
  'snake': 'serpente',
  'snow': 'neve',
  'snowboard': 'snowboard',
  'soccer': 'calcio',
  'socks': 'calzini',
  'soil': 'suolo',
  'soldier': 'soldato',
  'space': 'spazio',
  'sparrow': 'passero',
  'spinach': 'spinaci',
  'starfish': 'stella marina',
  'stewardess': 'assistente di volo',
  'stingray': 'razza',
  'strawberry': 'fragola',
  'sun': 'sole',
  'subway': 'metropolitana',
  'swallow': 'rondine',
  'sweater': 'maglione',
  'swimming': 'nuoto',
  'swing': 'altalena',
  'table': 'tavolo',
  'tambourine': 'tamburello',
  'teacher': 'insegnante',
  'tiger': 'tigre',
  'timpani': 'timpani',
  'toad': 'rospo',
  'trampoline': 'trampolino',
  'tree': 'albero',
  'triangle': 'triangolo',
  'truck': 'camion',
  'trumpet': 'tromba',
  'turtle': 'tartaruga',
  'typhoon': 'tifone',
  'unicorn': 'unicorno',
  'violin': 'violino',
  'viking ship': 'nave vichinga',
  'volcano': 'vulcano',
  'volleyball': 'pallavolo',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'cascata',
  'watermelon': 'anguria',
  'wave': 'onda',
  'whale': 'balena',
  'wind': 'vento',
  'window': 'finestra',
  'wolf': 'lupo',
  'woodpecker': 'picchio',
  'xylophone': 'xilofono',
  'yacht': 'yacht',
  'zebra': 'zebra',
};

final Map<String, String> porItemList = {
  'accordian': 'acordeão',
  'airplane': 'avião',
  'anaconda': 'anaconda',
  'ant': 'formiga',
  'anteater': 'tamanduá',
  'apple': 'maçã',
  'apricot': 'damasco',
  'archery': 'tiro com arco',
  'astronaut': 'astronauta',
  'avocado': 'abacate',
  'badminton': 'badminton',
  'banana': 'banana',
  'baseball': 'basebol',
  'basketball': 'basquetebol',
  'bassoon': 'fagote',
  'bat': 'morcego',
  'beach': 'praia',
  'bear': 'urso',
  'bicycle': 'bicicleta',
  'blackboard': 'quadro negro',
  'blowfish': 'baiacu',
  'blueberries': 'mirtilos',
  'boar': 'javali',
  'book': 'livro',
  'boots': 'botas',
  'bowling': 'bowling',
  'boxing': 'boxe',
  'broccoli': 'brócolos',
  'bumper car': 'carro de choque',
  'bus': 'autocarro',
  'cabbage': 'couve',
  'camel': 'camelo',
  'canteen': 'cantina',
  'carp': 'carpa',
  'carpenter': 'carpinteiro',
  'carrot': 'cenoura',
  'castanets': 'castanholas',
  'cat': 'gato',
  'cello': 'violoncelo',
  'chameleon': 'camaleão',
  'cheetah': 'chita',
  'cherry': 'cereja',
  'chick': 'pintainho',
  'chicken': 'frango',
  'clarinet': 'clarinete',
  'classroom': 'sala de aula',
  'cloud': 'nuvem',
  'cobra': 'cobra',
  'coconut': 'coco',
  'computer': 'computador',
  'conductor': 'maestro',
  'contrabass': 'contrabaixo',
  'cook': 'cozinheiro',
  'corn': 'milho',
  'cow': 'vaca',
  'crab': 'caranguejo',
  'crane': 'guindaste',
  'crocodile': 'crocodilo',
  'crow': 'corvo',
  'cucumber': 'pepino',
  'curling': 'curling',
  'cymbals': 'pratos',
  'deer': 'veado',
  'dentist': 'dentista',
  'desert': 'deserto',
  'doctor': 'médico',
  'dog': 'cão',
  'dolphin': 'golfinho',
  'drum': 'tambor',
  'duck': 'pato',
  'eagle': 'águia',
  'earthquake': 'terramoto',
  'elephant': 'elefante',
  'exam': 'exame',
  'farmer': 'agricultor',
  'fencing': 'esgrima',
  'ferris wheel': 'roda gigante',
  'fig': 'figo',
  'firefighter': 'bombeiro',
  'fisherman': 'pescador',
  'flower': 'flor',
  'flute': 'flauta',
  'fog': 'nevoeiro',
  'forest': 'floresta',
  'fox': 'raposa',
  'friend': 'amigo',
  'frog': 'rã',
  'garlic': 'alho',
  'ginger': 'gengibre',
  'ginseng': 'ginseng',
  'giraffe': 'girafa',
  'gloves': 'luvas',
  'goat': 'cabra',
  'golf': 'golfe',
  'goose': 'ganso',
  'gorilla': 'gorila',
  'grape': 'uva',
  'grapefruit': 'toranja',
  'guitar': 'guitarra',
  'hairdressor': 'cabeleireiro',
  'hallway': 'corredor',
  'harmonica': 'harmónica',
  'harp': 'harpa',
  'hat': 'chapéu',
  'hawk': 'falcão',
  'helicopter': 'helicóptero',
  'hippo': 'hipopótamo',
  'hippocampus': 'cavalo-marinho',
  'hockey': 'hóquei',
  'horse': 'cavalo',
  'hyena': 'hiena',
  'iceberg': 'icebergue',
  'iguana': 'iguana',
  'jellyfish': 'alforreca',
  'judge': 'juiz',
  'judo': 'judo',
  'jujube': 'jujuba',
  'jungle': 'selva',
  'kangaroo': 'canguru',
  'kiwi': 'kiwi',
  'koala': 'coala',
  'lake': 'lago',
  'lemon': 'limão',
  'leopard': 'leopardo',
  'lettuce': 'alface',
  'lightning': 'relâmpago',
  'lion': 'leão',
  'lizard': 'lagarto',
  'lobster': 'lagosta',
  'magpie': 'pêga',
  'mango': 'manga',
  'marathon': 'maratona',
  'meerkat': 'suricata',
  'melon': 'melão',
  'Merry go round': 'carrossel',
  'mole': 'toupeira',
  'monkey': 'macaco',
  'moon': 'lua',
  'mountain': 'montanha',
  'mouse': 'rato',
  'mushroom': 'cogumelo',
  'notebook': 'caderno',
  'ocarina': 'ocarina',
  'ocean': 'oceano',
  'octopus': 'polvo',
  'onion': 'cebola',
  'orange': 'laranja',
  'orangutan': 'orangotango',
  'orchestra': 'orquestra',
  'ostrich': 'avestruz',
  'owl': 'coruja',
  'painter': 'pintor',
  'pants': 'calças',
  'parrot': 'papagaio',
  'parsley': 'salsa',
  'peach': 'pêssego',
  'peacock': 'pavão',
  'pelican': 'pelicano',
  'pencil': 'lápis',
  'penguin': 'pinguim',
  'pepper': 'pimenta',
  'pharmacist': 'farmacêutico',
  'piano': 'piano',
  'pickle': 'picles',
  'pig': 'porco',
  'pigeon': 'pombo',
  'pilot': 'piloto',
  'pineapple': 'ananás',
  'platypus': 'ornitorrinco',
  'playground': 'parque infantil',
  'policeman': 'polícia',
  'pomegranate': 'romã',
  'potato': 'batata',
  'principal': 'diretor',
  'professor': 'professor',
  'pumpkin': 'abóbora',
  'rabbit': 'coelho',
  'raccoon': 'guaxinim',
  'rain': 'chuva',
  'restroom': 'casa de banho',
  'rhino': 'rinoceronte',
  'river': 'rio',
  'rock': 'rocha',
  'saxophone': 'saxofone',
  'scientist': 'cientista',
  'seagull': 'gaivota',
  'seal': 'foca',
  'sesame': 'sésamo',
  'shark': 'tubarão',
  'sheep': 'ovelha',
  'shirt': 'camisa',
  'singer': 'cantor',
  'ski': 'esqui',
  'skunk': 'cangambá',
  'sky': 'céu',
  'snail': 'caracol',
  'snake': 'cobra',
  'snow': 'neve',
  'snowboard': 'snowboard',
  'soccer': 'futebol',
  'socks': 'meias',
  'soil': 'solo',
  'soldier': 'soldado',
  'space': 'espaço',
  'sparrow': 'pardal',
  'spinach': 'espinafre',
  'starfish': 'estrela-do-mar',
  'stewardess': 'comissária de bordo',
  'stingray': 'arraia',
  'strawberry': 'morango',
  'sun': 'sol',
  'subway': 'metro',
  'swallow': 'andorinha',
  'sweater': 'camisola',
  'swimming': 'natação',
  'swing': 'baloiço',
  'table': 'mesa',
  'tambourine': 'pandeireta',
  'teacher': 'professor',
  'tiger': 'tigre',
  'timpani': 'tímpanos',
  'toad': 'sapo',
  'trampoline': 'trampolim',
  'tree': 'árvore',
  'triangle': 'triângulo',
  'truck': 'camião',
  'trumpet': 'trompete',
  'turtle': 'tartaruga',
  'typhoon': 'tufão',
  'unicorn': 'unicórnio',
  'violin': 'violino',
  'viking ship': 'navio viking',
  'volcano': 'vulcão',
  'volleyball': 'voleibol',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'cascata',
  'watermelon': 'melancia',
  'wave': 'onda',
  'whale': 'baleia',
  'wind': 'vento',
  'window': 'janela',
  'wolf': 'lobo',
  'woodpecker': 'pica-pau',
  'xylophone': 'xilofone',
  'yacht': 'iate',
  'zebra': 'zebra',
};

final Map<String, String> araItemList = {
  'accordian': 'أكورديون',
  'airplane': 'طائرة',
  'anaconda': 'أناكوندا',
  'ant': 'نملة',
  'anteater': 'آكل النمل',
  'apple': 'تفاح',
  'apricot': 'مشمش',
  'archery': 'رماية',
  'astronaut': 'رائد فضاء',
  'avocado': 'أفوكادو',
  'badminton': 'ريشة طائرة',
  'banana': 'موز',
  'baseball': 'بيسبول',
  'basketball': 'كرة سلة',
  'bassoon': 'باسون',
  'bat': 'خفاش',
  'beach': 'شاطئ',
  'bear': 'دب',
  'bicycle': 'دراجة',
  'blackboard': 'سبورة',
  'blowfish': 'سمكة منتفخة',
  'blueberries': 'توت أزرق',
  'boar': 'خنزير بري',
  'book': 'كتاب',
  'boots': 'أحذية',
  'bowling': 'بولينج',
  'boxing': 'ملاكمة',
  'broccoli': 'بروكلي',
  'bumper car': 'سيارة تصادم',
  'bus': 'حافلة',
  'cabbage': 'ملفوف',
  'camel': 'جمل',
  'canteen': 'مقصف',
  'carp': 'شبوط',
  'carpenter': 'نجار',
  'carrot': 'جزر',
  'castanets': 'كاستنيت',
  'cat': 'قطة',
  'cello': 'تشيلو',
  'chameleon': 'حرباء',
  'cheetah': 'فهد',
  'cherry': 'كرز',
  'chick': 'كتكوت',
  'chicken': 'دجاج',
  'clarinet': 'كلارينيت',
  'classroom': 'فصل دراسي',
  'cloud': 'سحابة',
  'cobra': 'كوبرا',
  'coconut': 'جوز الهند',
  'computer': 'حاسوب',
  'conductor': 'قائد أوركسترا',
  'contrabass': 'كونترباص',
  'cook': 'طباخ',
  'corn': 'ذرة',
  'cow': 'بقرة',
  'crab': 'سلطعون',
  'crane': 'رافعة',
  'crocodile': 'تمساح',
  'crow': 'غراب',
  'cucumber': 'خيار',
  'curling': 'كيرلنغ',
  'cymbals': 'صنجات',
  'deer': 'غزال',
  'dentist': 'طبيب أسنان',
  'desert': 'صحراء',
  'doctor': 'طبيب',
  'dog': 'كلب',
  'dolphin': 'دلفين',
  'drum': 'طبل',
  'duck': 'بطة',
  'eagle': 'نسر',
  'earthquake': 'زلزال',
  'elephant': 'فيل',
  'exam': 'امتحان',
  'farmer': 'مزارع',
  'fencing': 'مبارزة',
  'ferris wheel': 'عجلة فيريس',
  'fig': 'تين',
  'firefighter': 'رجل إطفاء',
  'fisherman': 'صياد',
  'flower': 'زهرة',
  'flute': 'ناي',
  'fog': 'ضباب',
  'forest': 'غابة',
  'fox': 'ثعلب',
  'friend': 'صديق',
  'frog': 'ضفدع',
  'garlic': 'ثوم',
  'ginger': 'زنجبيل',
  'ginseng': 'جينسنغ',
  'giraffe': 'زرافة',
  'gloves': 'قفازات',
  'goat': 'ماعز',
  'golf': 'غولف',
  'goose': 'إوزة',
  'gorilla': 'غوريلا',
  'grape': 'عنب',
  'grapefruit': 'جريب فروت',
  'guitar': 'قيثارة',
  'hairdressor': 'حلاق',
  'hallway': 'ممر',
  'harmonica': 'هارمونيكا',
  'harp': 'قيثارة',
  'hat': 'قبعة',
  'hawk': 'صقر',
  'helicopter': 'مروحية',
  'hippo': 'فرس النهر',
  'hippocampus': 'فرس البحر',
  'hockey': 'هوكي',
  'horse': 'حصان',
  'hyena': 'هينة',
  'iceberg': 'جبل جليدي',
  'iguana': 'إغوانا',
  'jellyfish': 'قنديل البحر',
  'judge': 'قاضي',
  'judo': 'جودو',
  'jujube': 'عناب',
  'jungle': 'أدغال',
  'kangaroo': 'كنغر',
  'kiwi': 'كيوي',
  'koala': 'كوالا',
  'lake': 'بحيرة',
  'lemon': 'ليمون',
  'leopard': 'نمر',
  'lettuce': 'خس',
  'lightning': 'برق',
  'lion': 'أسد',
  'lizard': 'سحلية',
  'lobster': 'جراد البحر',
  'magpie': 'عقعق',
  'mango': 'مانجو',
  'marathon': 'ماراثون',
  'meerkat': 'ميركات',
  'melon': 'بطيخ',
  'Merry go round': 'دوامة',
  'mole': 'خلد',
  'monkey': 'قرد',
  'moon': 'قمر',
  'mountain': 'جبل',
  'mouse': 'فأر',
  'mushroom': 'فطر',
  'notebook': 'دفتر',
  'ocarina': 'أوكارينا',
  'ocean': 'محيط',
  'octopus': 'أخطبوط',
  'onion': 'بصل',
  'orange': 'برتقال',
  'orangutan': 'إنسان الغاب',
  'orchestra': 'أوركسترا',
  'ostrich': 'نعامة',
  'owl': 'بومة',
  'painter': 'رسام',
  'pants': 'بنطلون',
  'parrot': 'ببغاء',
  'parsley': 'بقدونس',
  'peach': 'خوخ',
  'peacock': 'طاووس',
  'pelican': 'بجع',
  'pencil': 'قلم رصاص',
  'penguin': 'بطريق',
  'pepper': 'فلفل',
  'pharmacist': 'صيدلي',
  'piano': 'بيانو',
  'pickle': 'مخلل',
  'pig': 'خنزير',
  'pigeon': 'حمامة',
  'pilot': 'طيار',
  'pineapple': 'أناناس',
  'platypus': 'منقار البط',
  'playground': 'ملعب',
  'policeman': 'شرطي',
  'pomegranate': 'رمان',
  'potato': 'بطاطس',
  'principal': 'مدير',
  'professor': 'أستاذ',
  'pumpkin': 'قرع',
  'rabbit': 'أرنب',
  'raccoon': 'راكون',
  'rain': 'مطر',
  'restroom': 'حمام',
  'rhino': 'وحيد القرن',
  'river': 'نهر',
  'rock': 'صخرة',
  'saxophone': 'ساكسفون',
  'scientist': 'عالم',
  'seagull': 'نورس',
  'seal': 'فقمة',
  'sesame': 'سمسم',
  'shark': 'أقنوم',
  'sheep': 'خروف',
  'shirt': 'قميص',
  'singer': 'مغني',
  'ski': 'تزلج',
  'skunk': 'ظربان',
  'sky': 'سماء',
  'snail': 'حلزون',
  'snake': 'ثعبان',
  'snow': 'ثلج',
  'snowboard': 'لوح التزلج',
  'soccer': 'كرة القدم',
  'socks': 'جوارب',
  'soil': 'تربة',
  'soldier': 'جندي',
  'space': 'فضاء',
  'sparrow': 'عصفور',
  'spinach': 'سبانخ',
  'starfish': 'نجم البحر',
  'stewardess': 'مضيفة طيران',
  'stingray': 'شفنين',
  'strawberry': 'فراولة',
  'sun': 'شمس',
  'subway': 'مترو الأنفاق',
  'swallow': 'سنونو',
  'sweater': 'سترة',
  'swimming': 'سباحة',
  'swing': 'أرجوحة',
  'table': 'طاولة',
  'tambourine': 'دف',
  'teacher': 'معلم',
  'tiger': 'نمر',
  'timpani': 'طبول',
  'toad': 'علجوم',
  'trampoline': 'ترامبولين',
  'tree': 'شجرة',
  'triangle': 'مثلث',
  'truck': 'شاحنة',
  'trumpet': 'بوق',
  'turtle': 'سلحفاة',
  'typhoon': 'إعصار',
  'unicorn': 'وحيد القرن',
  'violin': 'كمان',
  'viking ship': 'سفينة الفايكنج',
  'volcano': 'بركان',
  'volleyball': 'كرة الطائرة',
  'vuvuzela': 'فوفوزيلا',
  'waterfall': 'شلال',
  'watermelon': 'بطيخ',
  'wave': 'موجة',
  'whale': 'حوت',
  'wind': 'رياح',
  'window': 'نافذة',
  'wolf': 'ذئب',
  'woodpecker': 'نقار الخشب',
  'xylophone': 'إكسيليفون',
  'yacht': 'يخت',
  'zebra': 'حمار وحشي',
};

final Map<String, String> turItemList = {
  'accordian': 'akordeon',
  'airplane': 'uçak',
  'anaconda': 'anakonda',
  'ant': 'karınca',
  'anteater': 'karıncayiyen',
  'apple': 'elma',
  'apricot': 'kayısı',
  'archery': 'okçuluk',
  'astronaut': 'astronot',
  'avocado': 'avokado',
  'badminton': 'badminton',
  'banana': 'muz',
  'baseball': 'beyzbol',
  'basketball': 'basketbol',
  'bassoon': 'fagot',
  'bat': 'yarasa',
  'beach': 'plaj',
  'bear': 'ayı',
  'bicycle': 'bisiklet',
  'blackboard': 'kara tahta',
  'blowfish': 'balon balığı',
  'blueberries': 'yaban mersini',
  'boar': 'yaban domuzu',
  'book': 'kitap',
  'boots': 'botlar',
  'bowling': 'bovling',
  'boxing': 'boks',
  'broccoli': 'brokoli',
  'bumper car': 'çarpışan araba',
  'bus': 'otobüs',
  'cabbage': 'lahana',
  'camel': 'deve',
  'canteen': 'kantin',
  'carp': 'sazan',
  'carpenter': 'marangoz',
  'carrot': 'havuç',
  'castanets': 'kastanyet',
  'cat': 'kedi',
  'cello': 'çello',
  'chameleon': 'bukalemun',
  'cheetah': 'çita',
  'cherry': 'kiraz',
  'chick': 'civciv',
  'chicken': 'tavuk',
  'clarinet': 'klarnet',
  'classroom': 'sınıf',
  'cloud': 'bulut',
  'cobra': 'kobra',
  'coconut': 'hindistancevizi',
  'computer': 'bilgisayar',
  'conductor': 'orkestra şefi',
  'contrabass': 'kontrbas',
  'cook': 'aşçı',
  'corn': 'mısır',
  'cow': 'inek',
  'crab': 'yengeç',
  'crane': 'vinç',
  'crocodile': 'timsah',
  'crow': 'karga',
  'cucumber': 'salatalık',
  'curling': 'körling',
  'cymbals': 'zil',
  'deer': 'geyik',
  'dentist': 'diş hekimi',
  'desert': 'çöl',
  'doctor': 'doktor',
  'dog': 'köpek',
  'dolphin': 'yunus',
  'drum': 'davul',
  'duck': 'ördek',
  'eagle': 'kartal',
  'earthquake': 'deprem',
  'elephant': 'fil',
  'exam': 'sınav',
  'farmer': 'çiftçi',
  'fencing': 'eskrim',
  'ferris wheel': 'dönme dolap',
  'fig': 'incir',
  'firefighter': 'itfaiyeci',
  'fisherman': 'balıkçı',
  'flower': 'çiçek',
  'flute': 'flüt',
  'fog': 'sis',
  'forest': 'orman',
  'fox': 'tilki',
  'friend': 'arkadaş',
  'frog': 'kurbağa',
  'garlic': 'sarımsak',
  'ginger': 'zencefil',
  'ginseng': 'ginseng',
  'giraffe': 'zürafa',
  'gloves': 'eldiven',
  'goat': 'keçi',
  'golf': 'golf',
  'goose': 'kaz',
  'gorilla': 'goril',
  'grape': 'üzüm',
  'grapefruit': 'greyfurt',
  'guitar': 'gitar',
  'hairdressor': 'kuaför',
  'hallway': 'koridor',
  'harmonica': 'armonika',
  'harp': 'arpa',
  'hat': 'şapka',
  'hawk': 'şahin',
  'helicopter': 'helikopter',
  'hippo': 'su aygırı',
  'hippocampus': 'denizatı',
  'hockey': 'hokey',
  'horse': 'at',
  'hyena': 'sırtlan',
  'iceberg': 'buzdağı',
  'iguana': 'iguana',
  'jellyfish': 'denizanası',
  'judge': 'hakim',
  'judo': 'judo',
  'jujube': 'hünnap',
  'jungle': 'orman',
  'kangaroo': 'kanguru',
  'kiwi': 'kivi',
  'koala': 'koala',
  'lake': 'göl',
  'lemon': 'limon',
  'leopard': 'leopar',
  'lettuce': 'marul',
  'lightning': 'şimşek',
  'lion': 'aslan',
  'lizard': 'kertenkele',
  'lobster': 'ıstakoz',
  'magpie': 'saksağan',
  'mango': 'mango',
  'marathon': 'maraton',
  'meerkat': 'mirket',
  'melon': 'kavun',
  'Merry go round': 'atlıkarınca',
  'mole': 'köstebek',
  'monkey': 'maymun',
  'moon': 'ay',
  'mountain': 'dağ',
  'mouse': 'fare',
  'mushroom': 'mantar',
  'notebook': 'defter',
  'ocarina': 'okarina',
  'ocean': 'okyanus',
  'octopus': 'ahtapot',
  'onion': 'soğan',
  'orange': 'portakal',
  'orangutan': 'orangutan',
  'orchestra': 'orchestre',
  'ostrich': 'devekuşu',
  'owl': 'baykuş',
  'painter': 'ressam',
  'pants': 'pantolon',
  'parrot': 'papağan',
  'parsley': 'maydanoz',
  'peach': 'şeftali',
  'peacock': 'tavus kuşu',
  'pelican': 'pelikan',
  'pencil': 'kurşun kalem',
  'penguin': 'penguen',
  'pepper': 'biber',
  'pharmacist': 'eczacı',
  'piano': 'piyano',
  'pickle': 'turşu',
  'pig': 'domuz',
  'pigeon': 'güvercin',
  'pilot': 'pilot',
  'pineapple': 'ananas',
  'platypus': 'ornitorenk',
  'playground': 'oyun alanı',
  'policeman': 'polis',
  'pomegranate': 'nar',
  'potato': 'patates',
  'principal': 'müdür',
  'professor': 'profesör',
  'pumpkin': 'balkabağı',
  'rabbit': 'tavşan',
  'raccoon': 'rakun',
  'rain': 'yağmur',
  'restroom': 'tuvalet',
  'rhino': 'gergedan',
  'river': 'nehir',
  'rock': 'kaya',
  'saxophone': 'saksafon',
  'scientist': 'bilim insanı',
  'seagull': 'martı',
  'seal': 'fok',
  'sesame': 'susam',
  'shark': 'köpekbalığı',
  'sheep': 'koyun',
  'shirt': 'gömlek',
  'singer': 'şarkıcı',
  'ski': 'kayak',
  'skunk': 'kokarca',
  'sky': 'gökyüzü',
  'snail': 'salyangoz',
  'snake': 'yılan',
  'snow': 'kar',
  'snowboard': 'kar kayağı',
  'soccer': 'futbol',
  'socks': 'çorap',
  'soil': 'toprak',
  'soldier': 'asker',
  'space': 'uzay',
  'sparrow': 'serçe',
  'spinach': 'ıspanak',
  'starfish': 'denizyıldızı',
  'stewardess': 'hostes',
  'stingray': 'vatoz',
  'strawberry': 'çilek',
  'sun': 'güneş',
  'subway': 'metro',
  'swallow': 'kırlangıç',
  'sweater': 'kazak',
  'swimming': 'yüzme',
  'swing': 'salıncak',
  'table': 'masa',
  'tambourine': 'tef',
  'teacher': 'öğretmen',
  'tiger': 'kaplan',
  'timpani': 'timpani',
  'toad': 'karakurbağası',
  'trampoline': 'trambolin',
  'tree': 'ağaç',
  'triangle': 'üçgen',
  'truck': 'kamyon',
  'trumpet': 'trompet',
  'turtle': 'kaplumbağa',
  'typhoon': 'tayfun',
  'unicorn': 'tek boynuzlu at',
  'violin': 'keman',
  'viking ship': 'viking gemisi',
  'volcano': 'volkan',
  'volleyball': 'voleybol',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'şelale',
  'watermelon': 'karpuz',
  'wave': 'dalga',
  'whale': 'balina',
  'wind': 'rüzgar',
  'window': 'pencere',
  'wolf': 'loup',
  'woodpecker': 'ağaçkakan',
  'xylophone': 'ksilofon',
  'yacht': 'yat',
  'zebra': 'zebra',
};

final Map<String, String> vieItemList = {
  'accordian': 'đàn accordion',
  'airplane': 'máy bay',
  'anaconda': 'trăn anaconda',
  'ant': 'kiến',
  'anteater': 'thú ăn kiến',
  'apple': 'táo',
  'apricot': 'mơ',
  'archery': 'bắn cung',
  'astronaut': 'phi hành gia',
  'avocado': 'bơ',
  'badminton': 'cầu lông',
  'banana': 'chuối',
  'baseball': 'bóng chày',
  'basketball': 'bóng rổ',
  'bassoon': 'kèn bassoon',
  'bat': 'dơi',
  'beach': 'bãi biển',
  'bear': 'gấu',
  'bicycle': 'xe đạp',
  'blackboard': 'bảng đen',
  'blowfish': 'cá nóc',
  'blueberries': 'việt quất',
  'boar': 'lợn rừng',
  'book': 'sách',
  'boots': 'giày ủng',
  'bowling': 'bowling',
  'boxing': 'quyền anh',
  'broccoli': 'bông cải xanh',
  'bumper car': 'xe điện đụng',
  'bus': 'xe buýt',
  'cabbage': 'bắp cải',
  'camel': 'lạc đà',
  'canteen': 'căng tin',
  'carp': 'cá chép',
  'carpenter': 'thợ mộc',
  'carrot': 'cà rốt',
  'castanets': 'catanh',
  'cat': 'mèo',
  'cello': 'đàn cello',
  'chameleon': 'tắc kè hoa',
  'cheetah': 'báo gêpa',
  'cherry': 'anh đào',
  'chick': 'gà con',
  'chicken': 'gà',
  'clarinet': 'kèn clarinet',
  'classroom': 'lớp học',
  'cloud': 'mây',
  'cobra': 'rắn hổ mang',
  'coconut': 'dừa',
  'computer': 'máy tính',
  'conductor': 'nhạc trưởng',
  'contrabass': 'đàn contrabass',
  'cook': 'đầu bếp',
  'corn': 'ngô',
  'cow': 'bò',
  'crab': 'cua',
  'crane': 'cần cẩu',
  'crocodile': 'cá sấu',
  'crow': 'quạ',
  'cucumber': 'dưa chuột',
  'curling': 'môn curling',
  'cymbals': 'chũm chọe',
  'deer': 'hươu',
  'dentist': 'nha sĩ',
  'desert': 'sa mạc',
  'doctor': 'bác sĩ',
  'dog': 'chó',
  'dolphin': 'cá heo',
  'drum': 'trống',
  'duck': 'vịt',
  'eagle': 'đại bàng',
  'earthquake': 'động đất',
  'elephant': 'voi',
  'exam': 'kỳ thi',
  'farmer': 'nông dân',
  'fencing': 'đấu kiếm',
  'ferris wheel': 'vòng đu quay',
  'fig': 'sung',
  'firefighter': 'lính cứu hỏa',
  'fisherman': 'ngư dân',
  'flower': 'hoa',
  'flute': 'sáo',
  'fog': 'sương mù',
  'forest': 'rừng',
  'fox': 'cáo',
  'friend': 'bạn',
  'frog': 'ếch',
  'garlic': 'tỏi',
  'ginger': 'gừng',
  'ginseng': 'nhân sâm',
  'giraffe': 'hươu cao cổ',
  'gloves': 'găng tay',
  'goat': 'dê',
  'golf': 'gôn',
  'goose': 'ngỗng',
  'gorilla': 'khỉ đột',
  'grape': 'nho',
  'grapefruit': 'bưởi',
  'guitar': 'đàn guitar',
  'hairdressor': 'thợ làm tóc',
  'hallway': 'hành lang',
  'harmonica': 'kèn harmonica',
  'harp': 'đàn hạc',
  'hat': 'mũ',
  'hawk': 'diều hâu',
  'helicopter': 'trực thăng',
  'hippo': 'hà mã',
  'hippocampus': 'cá ngựa',
  'hockey': 'khúc côn cầu',
  'horse': 'ngựa',
  'hyena': 'linh cẩu',
  'iceberg': 'tảng băng trôi',
  'iguana': 'kỳ nhông',
  'jellyfish': 'sứa',
  'judge': 'thẩm phán',
  'judo': 'judo',
  'jujube': 'táo tàu',
  'jungle': 'rừng nhiệt đới',
  'kangaroo': 'chuột túi',
  'kiwi': 'kiwi',
  'koala': 'gấu túi',
  'lake': 'hồ',
  'lemon': 'chanh',
  'leopard': 'báo',
  'lettuce': 'xà lách',
  'lightning': 'sét',
  'lion': 'sư tử',
  'lizard': 'thằn lằn',
  'lobster': 'tôm hùm',
  'magpie': 'chim ác là',
  'mango': 'xoài',
  'marathon': 'marathon',
  'meerkat': 'cầy vằn',
  'melon': 'dưa',
  'Merry go round': 'vòng quay ngựa gỗ',
  'mole': 'chuột chũi',
  'monkey': 'khỉ',
  'moon': 'mặt trăng',
  'mountain': 'núi',
  'mouse': 'chuột',
  'mushroom': 'nấm',
  'notebook': 'vở',
  'ocarina': 'đàn ocarina',
  'ocean': 'đại dương',
  'octopus': 'bạch tuộc',
  'onion': 'hành',
  'orange': 'cam',
  'orangutan': 'đười ươi',
  'orchestra': 'dàn nhạc',
  'ostrich': 'đà điểu',
  'owl': 'cú',
  'painter': 'họa sĩ',
  'pants': 'quần',
  'parrot': 'vẹt',
  'parsley': 'ngò tây',
  'peach': 'đào',
  'peacock': 'công',
  'pelican': 'bồ nông',
  'pencil': 'bút chì',
  'penguin': 'chim cánh cụt',
  'pepper': 'hạt tiêu',
  'pharmacist': 'dược sĩ',
  'piano': 'đàn piano',
  'pickle': 'dưa muối',
  'pig': 'lợn',
  'pigeon': 'bồ câu',
  'pilot': 'phi công',
  'pineapple': 'dứa',
  'platypus': 'thú mỏ vịt',
  'playground': 'sân chơi',
  'policeman': 'cảnh sát',
  'pomegranate': 'lựu',
  'potato': 'khoai tây',
  'principal': 'hiệu trưởng',
  'professor': 'giáo sư',
  'pumpkin': 'bí ngô',
  'rabbit': 'thỏ',
  'raccoon': 'gấu mèo',
  'rain': 'mưa',
  'restroom': 'nhà vệ sinh',
  'rhino': 'tê giác',
  'river': 'sông',
  'rock': 'đá',
  'saxophone': 'kèn saxophone',
  'scientist': 'nhà khoa học',
  'seagull': 'mòng biển',
  'seal': 'hải cẩu',
  'sesame': 'vừng',
  'shark': 'cá mập',
  'sheep': 'cừu',
  'shirt': 'áo sơ mi',
  'singer': 'ca sĩ',
  'ski': 'trượt tuyết',
  'skunk': 'chồn hôi',
  'sky': 'bầu trời',
  'snail': 'ốc sên',
  'snake': 'rắn',
  'snow': 'tuyết',
  'snowboard': 'ván trượt tuyết',
  'soccer': 'bóng đá',
  'socks': 'tất',
  'soil': 'đất',
  'soldier': 'lính',
  'space': 'không gian',
  'sparrow': 'chim sẻ',
  'spinach': 'rau chân vịt',
  'starfish': 'sao biển',
  'stewardess': 'tiếp viên hàng không',
  'stingray': 'cá đuối',
  'strawberry': 'dâu tây',
  'sun': 'mặt trời',
  'subway': 'tàu điện ngầm',
  'swallow': 'chim én',
  'sweater': 'áo len',
  'swimming': 'bơi lội',
  'swing': 'xích đu',
  'table': 'bàn',
  'tambourine': 'trống lục lạc',
  'teacher': 'giáo viên',
  'tiger': 'hổ',
  'timpani': 'trống định âm',
  'toad': 'cóc',
  'trampoline': 'bạt nhún',
  'tree': 'cây',
  'triangle': 'tam giác',
  'truck': 'xe tải',
  'trumpet': 'kèn trumpet',
  'turtle': 'rùa',
  'typhoon': 'bão',
  'unicorn': 'kỳ lân',
  'violin': 'đàn violin',
  'viking ship': 'tàu viking',
  'volcano': 'núi lửa',
  'volleyball': 'bóng chuyền',
  'vuvuzela': 'kèn vuvuzela',
  'waterfall': 'thác nước',
  'watermelon': 'dưa hấu',
  'wave': 'sóng',
  'whale': 'cá voi',
  'wind': 'gió',
  'window': 'cửa sổ',
  'wolf': 'sói',
  'woodpecker': 'chim gõ kiến',
  'xylophone': 'đàn xylophone',
  'yacht': 'du thuyền',
  'zebra': 'ngựa vằn',
};

final Map<String, String> dutItemList = {
  'accordian': 'accordeon',
  'airplane': 'vliegtuig',
  'anaconda': 'anaconda',
  'ant': 'mier',
  'anteater': 'miereneter',
  'apple': 'appel',
  'apricot': 'abrikoos',
  'archery': 'boogschieten',
  'astronaut': 'astronaut',
  'avocado': 'avocado',
  'badminton': 'badminton',
  'banana': 'banaan',
  'baseball': 'honkbal',
  'basketball': 'basketbal',
  'bassoon': 'fagot',
  'bat': 'vleermuis',
  'beach': 'strand',
  'bear': 'beer',
  'bicycle': 'fiets',
  'blackboard': 'schoolbord',
  'blowfish': 'kogelvis',
  'blueberries': 'bosbessen',
  'boar': 'wild zwijn',
  'book': 'boek',
  'boots': 'laarzen',
  'bowling': 'bowlen',
  'boxing': 'boksen',
  'broccoli': 'broccoli',
  'bumper car': 'botsauto',
  'bus': 'bus',
  'cabbage': 'kool',
  'camel': 'kameel',
  'canteen': 'kantine',
  'carp': 'karper',
  'carpenter': 'timmerman',
  'carrot': 'wortel',
  'castanets': 'castagnetten',
  'cat': 'kat',
  'cello': 'cello',
  'chameleon': 'kameleon',
  'cheetah': 'jachtluipaard',
  'cherry': 'kers',
  'chick': 'kuiken',
  'chicken': 'kip',
  'clarinet': 'klarinet',
  'classroom': 'klaslokaal',
  'cloud': 'wolk',
  'cobra': 'cobra',
  'coconut': 'kokosnoot',
  'computer': 'computer',
  'conductor': 'dirigent',
  'contrabass': 'contrabas',
  'cook': 'kok',
  'corn': 'maïs',
  'cow': 'koe',
  'crab': 'krab',
  'crane': 'kraan',
  'crocodile': 'krokodil',
  'crow': 'kraai',
  'cucumber': 'komkommer',
  'curling': 'curling',
  'cymbals': 'bekkens',
  'deer': 'hert',
  'dentist': 'tandarts',
  'desert': 'woestijn',
  'doctor': 'dokter',
  'dog': 'hond',
  'dolphin': 'dolfijn',
  'drum': 'drum',
  'duck': 'eend',
  'eagle': 'adelaar',
  'earthquake': 'aardbeving',
  'elephant': 'olifant',
  'exam': 'examen',
  'farmer': 'boer',
  'fencing': 'schermen',
  'ferris wheel': 'reuzenrad',
  'fig': 'vijg',
  'firefighter': 'brandweerman',
  'fisherman': 'visser',
  'flower': 'bloem',
  'flute': 'fluit',
  'fog': 'mist',
  'forest': 'bos',
  'fox': 'vos',
  'friend': 'vriend',
  'frog': 'kikker',
  'garlic': 'knoflook',
  'ginger': 'gember',
  'ginseng': 'ginseng',
  'giraffe': 'giraf',
  'gloves': 'handschoenen',
  'goat': 'geit',
  'golf': 'golf',
  'goose': 'gans',
  'gorilla': 'gorilla',
  'grape': 'druif',
  'grapefruit': 'grapefruit',
  'guitar': 'gitaar',
  'hairdressor': 'kapper',
  'hallway': 'gang',
  'harmonica': 'mondharmonica',
  'harp': 'harp',
  'hat': 'hoed',
  'hawk': 'havik',
  'helicopter': 'helikopter',
  'hippo': 'nijlpaard',
  'hippocampus': 'zeepaardje',
  'hockey': 'hockey',
  'horse': 'paard',
  'hyena': 'hyena',
  'iceberg': 'ijsberg',
  'iguana': 'leguaan',
  'jellyfish': 'kwal',
  'judge': 'rechter',
  'judo': 'judo',
  'jujube': 'jujube',
  'jungle': 'jungle',
  'kangaroo': 'kangoeroe',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'meer',
  'lemon': 'citroen',
  'leopard': 'luipaard',
  'lettuce': 'sla',
  'lightning': 'bliksem',
  'lion': 'leeuw',
  'lizard': 'hagedis',
  'lobster': 'kreeft',
  'magpie': 'ekster',
  'mango': 'mango',
  'marathon': 'marathon',
  'meerkat': 'stokstaartje',
  'melon': 'meloen',
  'Merry go round': 'draaimolen',
  'mole': 'mol',
  'monkey': 'aap',
  'moon': 'maan',
  'mountain': 'berg',
  'mouse': 'muis',
  'mushroom': 'paddenstoel',
  'notebook': 'notitieboek',
  'ocarina': 'ocarina',
  'ocean': 'oceaan',
  'octopus': 'octopus',
  'onion': 'ui',
  'orange': 'sinaasappel',
  'orangutan': 'orang-oetan',
  'orchestra': 'orkest',
  'ostrich': 'struisvogel',
  'owl': 'uil',
  'painter': 'schilder',
  'pants': 'broek',
  'parrot': 'papegaai',
  'parsley': 'peterselie',
  'peach': 'perzik',
  'peacock': 'pauw',
  'pelican': 'pelikaan',
  'pencil': 'potlood',
  'penguin': 'pinguïn',
  'pepper': 'peper',
  'pharmacist': 'apotheker',
  'piano': 'piano',
  'pickle': 'augurk',
  'pig': 'varken',
  'pigeon': 'duif',
  'pilot': 'piloot',
  'pineapple': 'ananas',
  'platypus': 'vogelbekdier',
  'playground': 'speelplaats',
  'policeman': 'politieagent',
  'pomegranate': 'granaatappel',
  'potato': 'aardappel',
  'principal': 'directeur',
  'professor': 'professor',
  'pumpkin': 'pompoen',
  'rabbit': 'konijn',
  'raccoon': 'wasbeer',
  'rain': 'regen',
  'restroom': 'toilet',
  'rhino': 'neushoorn',
  'river': 'rivier',
  'rock': 'rots',
  'saxophone': 'saxofoon',
  'scientist': 'wetenschapper',
  'seagull': 'meeuw',
  'seal': 'zeehond',
  'sesame': 'sesam',
  'shark': 'haai',
  'sheep': 'schaap',
  'shirt': 'hemd',
  'singer': 'zanger',
  'ski': 'skiën',
  'skunk': 'stinkdier',
  'sky': 'lucht',
  'snail': 'slak',
  'snake': 'slang',
  'snow': 'sneeuw',
  'snowboard': 'snowboard',
  'soccer': 'voetbal',
  'socks': 'sokken',
  'soil': 'grond',
  'soldier': 'soldaat',
  'space': 'ruimte',
  'sparrow': 'mus',
  'spinach': 'spinazie',
  'starfish': 'zeester',
  'stewardess': 'stewardess',
  'stingray': 'rog',
  'strawberry': 'aardbei',
  'sun': 'zon',
  'subway': 'metro',
  'swallow': 'zwaluw',
  'sweater': 'trui',
  'swimming': 'zwemmen',
  'swing': 'schommel',
  'table': 'tafel',
  'tambourine': 'tamboerijn',
  'teacher': 'leraar',
  'tiger': 'tijger',
  'timpani': 'pauken',
  'toad': 'pad',
  'trampoline': 'trampoline',
  'tree': 'boom',
  'triangle': 'driehoek',
  'truck': 'vrachtwagen',
  'trumpet': 'trompet',
  'turtle': 'schildpad',
  'typhoon': 'tyfoon',
  'unicorn': 'eenhoorn',
  'violin': 'viool',
  'viking ship': 'vikingschip',
  'volcano': 'vulkaan',
  'volleyball': 'volleybal',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'waterval',
  'watermelon': 'watermeloen',
  'wave': 'golf',
  'whale': 'walvis',
  'wind': 'wind',
  'window': 'raam',
  'wolf': 'wolf',
  'woodpecker': 'specht',
  'xylophone': 'xilofoon',
  'yacht': 'jacht',
  'zebra': 'zebra',
};

final Map<String, String> czeItemList = {
  'accordian': 'akordeon',
  'airplane': 'letadlo',
  'anaconda': 'anakonda',
  'ant': 'mravenec',
  'anteater': 'mravenečník',
  'apple': 'jablko',
  'apricot': 'meruňka',
  'archery': 'lukostřelba',
  'astronaut': 'astronaut',
  'avocado': 'avokádo',
  'badminton': 'badminton',
  'banana': 'banán',
  'baseball': 'baseball',
  'basketball': 'basketbal',
  'bassoon': 'fagot',
  'bat': 'netopýr',
  'beach': 'pláž',
  'bear': 'medvěd',
  'bicycle': 'kolo',
  'blackboard': 'tabule',
  'blowfish': 'čtverzubec',
  'blueberries': 'borůvky',
  'boar': 'divočák',
  'book': 'kniha',
  'boots': 'boty',
  'bowling': 'bowling',
  'boxing': 'box',
  'broccoli': 'brokolice',
  'bumper car': 'autodrom',
  'bus': 'autobus',
  'cabbage': 'zelí',
  'camel': 'velbloud',
  'canteen': 'jídelna',
  'carp': 'kapr',
  'carpenter': 'tesař',
  'carrot': 'mrkev',
  'castanets': 'kastaněty',
  'cat': 'kočka',
  'cello': 'violoncello',
  'chameleon': 'chameleon',
  'cheetah': 'gepard',
  'cherry': 'třešeň',
  'chick': 'kuře',
  'chicken': 'slepice',
  'clarinet': 'klarinet',
  'classroom': 'třída',
  'cloud': 'mrak',
  'cobra': 'kobra',
  'coconut': 'kokos',
  'computer': 'počítač',
  'conductor': 'dirigent',
  'contrabass': 'kontrabas',
  'cook': 'kuchař',
  'corn': 'kukuřice',
  'cow': 'kráva',
  'crab': 'krab',
  'crane': 'jeřáb',
  'crocodile': 'krokodýl',
  'crow': 'vrána',
  'cucumber': 'okurka',
  'curling': 'curling',
  'cymbals': 'činely',
  'deer': 'jelen',
  'dentist': 'zubař',
  'desert': 'poušť',
  'doctor': 'doktor',
  'dog': 'pes',
  'dolphin': 'delfín',
  'drum': 'buben',
  'duck': 'kachna',
  'eagle': 'orel',
  'earthquake': 'zemětřesení',
  'elephant': 'slon',
  'exam': 'zkouška',
  'farmer': 'farmář',
  'fencing': 'šerm',
  'ferris wheel': 'ruské kolo',
  'fig': 'fíkovník',
  'firefighter': 'hasič',
  'fisherman': 'rybář',
  'flower': 'květina',
  'flute': 'flétna',
  'fog': 'mlha',
  'forest': 'les',
  'fox': 'liška',
  'friend': 'přítel',
  'frog': 'žába',
  'garlic': 'česnek',
  'ginger': 'zázvor',
  'ginseng': 'ženšen',
  'giraffe': 'žirafa',
  'gloves': 'rukavice',
  'goat': 'koza',
  'golf': 'golf',
  'goose': 'husa',
  'gorilla': 'gorila',
  'grape': 'hroznové víno',
  'grapefruit': 'grep',
  'guitar': 'kytara',
  'hairdressor': 'kadeřník',
  'hallway': 'chodba',
  'harmonica': 'foukací harmonika',
  'harp': 'harfa',
  'hat': 'klobouk',
  'hawk': 'jestřáb',
  'helicopter': 'vrtulník',
  'hippo': 'hroch',
  'hippocampus': 'mořský koník',
  'hockey': 'hokej',
  'horse': 'kůň',
  'hyena': 'hyena',
  'iceberg': 'ledovec',
  'iguana': 'leguán',
  'jellyfish': 'medúza',
  'judge': 'soudce',
  'judo': 'judo',
  'jujube': 'jujuba',
  'jungle': 'džungle',
  'kangaroo': 'klokan',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'jezero',
  'lemon': 'citron',
  'leopard': 'levhart',
  'lettuce': 'salát',
  'lightning': 'blesk',
  'lion': 'lev',
  'lizard': 'ještěrka',
  'lobster': 'humr',
  'magpie': 'straka',
  'mango': 'mango',
  'marathon': 'maraton',
  'meerkat': 'surikata',
  'melon': 'meloun',
  'Merry go round': 'kolotoč',
  'mole': 'krtek',
  'monkey': 'opice',
  'moon': 'měsíc',
  'mountain': 'hora',
  'mouse': 'myš',
  'mushroom': 'houba',
  'notebook': 'sešit',
  'ocarina': 'okarína',
  'ocean': 'oceán',
  'octopus': 'chobotnice',
  'onion': 'cibule',
  'orange': 'pomeranč',
  'orangutan': 'orangutan',
  'orchestra': 'orchestr',
  'ostrich': 'pštros',
  'owl': 'sova',
  'painter': 'malíř',
  'pants': 'kalhoty',
  'parrot': 'papoušek',
  'parsley': 'petržel',
  'peach': 'broskev',
  'peacock': 'páv',
  'pelican': 'pelikán',
  'pencil': 'tužka',
  'penguin': 'tučňák',
  'pepper': 'pepř',
  'pharmacist': 'lékárník',
  'piano': 'klavír',
  'pickle': 'nakládaná okurka',
  'pig': 'prase',
  'pigeon': 'holub',
  'pilot': 'pilot',
  'pineapple': 'ananas',
  'platypus': 'ptakopysk',
  'playground': 'hřiště',
  'policeman': 'policista',
  'pomegranate': 'granátové jablko',
  'potato': 'brambor',
  'principal': 'ředitel',
  'professor': 'profesor',
  'pumpkin': 'dýně',
  'rabbit': 'králík',
  'raccoon': 'mýval',
  'rain': 'déšť',
  'restroom': 'toaleta',
  'rhino': 'nosorožec',
  'river': 'řeka',
  'rock': 'skála',
  'saxophone': 'saxofon',
  'scientist': 'vědec',
  'seagull': 'racek',
  'seal': 'tuleň',
  'sesame': 'sezam',
  'shark': 'žralok',
  'sheep': 'ovce',
  'shirt': 'košile',
  'singer': 'zpěvák',
  'ski': 'lyže',
  'skunk': 'skunk',
  'sky': 'nebe',
  'snail': 'šneček',
  'snake': 'had',
  'snow': 'sníh',
  'snowboard': 'snowboard',
  'soccer': 'fotbal',
  'socks': 'ponožky',
  'soil': 'půda',
  'soldier': 'voják',
  'space': 'vesmír',
  'sparrow': 'vrabec',
  'spinach': 'špenát',
  'starfish': 'hvězdice',
  'stewardess': 'letuška',
  'stingray': 'rejnok',
  'strawberry': 'jahoda',
  'sun': 'slunce',
  'subway': 'metro',
  'swallow': 'vlaštovka',
  'sweater': 'svetr',
  'swimming': 'plavání',
  'swing': 'houpačka',
  'table': 'stůl',
  'tambourine': 'tamburína',
  'teacher': 'učitel',
  'tiger': 'tygr',
  'timpani': 'timpány',
  'toad': 'ropucha',
  'trampoline': 'trampolína',
  'tree': 'strom',
  'triangle': 'trojúhelník',
  'truck': 'nákladní auto',
  'trumpet': 'trubka',
  'turtle': 'želva',
  'typhoon': 'tajfun',
  'unicorn': 'jednorožec',
  'violin': 'housle',
  'viking ship': 'vikingská loď',
  'volcano': 'sopka',
  'volleyball': 'volejbal',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'vodopád',
  'watermelon': 'vodní meloun',
  'wave': 'vlna',
  'whale': 'velryba',
  'wind': 'vítr',
  'window': 'okno',
  'wolf': 'vlk',
  'woodpecker': 'datel',
  'xylophone': 'xylofon',
  'yacht': 'jachta',
  'zebra': 'zebra',
};

final Map<String, String> polItemList = {
  'accordian': 'akordeon',
  'airplane': 'samolot',
  'anaconda': 'anakonda',
  'ant': 'mrówka',
  'anteater': 'mrówkojad',
  'apple': 'jabłko',
  'apricot': 'morela',
  'archery': 'łucznictwo',
  'astronaut': 'astronauta',
  'avocado': 'awokado',
  'badminton': 'badminton',
  'banana': 'banan',
  'baseball': 'baseball',
  'basketball': 'koszykówka',
  'bassoon': 'fagot',
  'bat': 'nietoperz',
  'beach': 'plaża',
  'bear': 'niedźwiedź',
  'bicycle': 'rower',
  'blackboard': 'tablica',
  'blowfish': 'rozdymka',
  'blueberries': 'borówki',
  'boar': 'dzik',
  'book': 'książka',
  'boots': 'buty',
  'bowling': 'kręgle',
  'boxing': 'boks',
  'broccoli': 'brokuły',
  'bumper car': 'samochód zderzakowy',
  'bus': 'autobus',
  'cabbage': 'kapusta',
  'camel': 'wielbłąd',
  'canteen': 'stołówka',
  'carp': 'karp',
  'carpenter': 'cieśla',
  'carrot': 'marchewka',
  'castanets': 'kastaniety',
  'cat': 'kot',
  'cello': 'wiolonczela',
  'chameleon': 'kameleon',
  'cheetah': 'gepard',
  'cherry': 'wiśnia',
  'chick': 'pisklę',
  'chicken': 'kurczak',
  'clarinet': 'klarnet',
  'classroom': 'klasa',
  'cloud': 'chmura',
  'cobra': 'kobra',
  'coconut': 'kokos',
  'computer': 'komputer',
  'conductor': 'dyrygent',
  'contrabass': 'kontrabas',
  'cook': 'kucharz',
  'corn': 'kukurydza',
  'cow': 'krowa',
  'crab': 'krab',
  'crane': 'żuraw',
  'crocodile': 'krokodyl',
  'crow': 'wrona',
  'cucumber': 'ogórek',
  'curling': 'curling',
  'cymbals': 'talerze',
  'deer': 'jeleń',
  'dentist': 'dentysta',
  'desert': 'pustynia',
  'doctor': 'lekarz',
  'dog': 'pies',
  'dolphin': 'delfin',
  'drum': 'bęben',
  'duck': 'kaczka',
  'eagle': 'orzeł',
  'earthquake': 'trzęsienie ziemi',
  'elephant': 'słoń',
  'exam': 'egzamin',
  'farmer': 'rolnik',
  'fencing': 'szermierka',
  'ferris wheel': 'diabelski młyn',
  'fig': 'figa',
  'firefighter': 'strażak',
  'fisherman': 'rybak',
  'flower': 'kwiat',
  'flute': 'flet',
  'fog': 'mgła',
  'forest': 'las',
  'fox': 'lis',
  'friend': 'przyjaciel',
  'frog': 'żaba',
  'garlic': 'czosnek',
  'ginger': 'imbir',
  'ginseng': 'żeń-szeń',
  'giraffe': 'żyrafa',
  'gloves': 'rękawiczki',
  'goat': 'koza',
  'golf': 'golf',
  'goose': 'gęś',
  'gorilla': 'goryl',
  'grape': 'winogrono',
  'grapefruit': 'grejpfrut',
  'guitar': 'gitara',
  'hairdressor': 'fryzjer',
  'hallway': 'korytarz',
  'harmonica': 'harmonijka',
  'harp': 'harfa',
  'hat': 'kapelusz',
  'hawk': 'jastrząb',
  'helicopter': 'helikopter',
  'hippo': 'hipopotam',
  'hippocampus': 'konik morski',
  'hockey': 'hokej',
  'horse': 'koń',
  'hyena': 'hiena',
  'iceberg': 'góra lodowa',
  'iguana': 'legwan',
  'jellyfish': 'meduza',
  'judge': 'sędzia',
  'judo': 'judo',
  'jujube': 'głożyna',
  'jungle': 'dżungla',
  'kangaroo': 'kangur',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'jezioro',
  'lemon': 'cytryna',
  'leopard': 'lampart',
  'lettuce': 'sałata',
  'lightning': 'błyskawica',
  'lion': 'lew',
  'lizard': 'jaszczurka',
  'lobster': 'homar',
  'magpie': 'sroka',
  'mango': 'mango',
  'marathon': 'maraton',
  'meerkat': 'surykatka',
  'melon': 'melon',
  'Merry go round': 'karuzela',
  'mole': 'kret',
  'monkey': 'małpa',
  'moon': 'księżyc',
  'mountain': 'góra',
  'mouse': 'mysz',
  'mushroom': 'grzyb',
  'notebook': 'zeszyt',
  'ocarina': 'okaryna',
  'ocean': 'ocean',
  'octopus': 'ośmiornica',
  'onion': 'cebula',
  'orange': 'pomarańcza',
  'orangutan': 'orangutan',
  'orchestra': 'orkiestra',
  'ostrich': 'struś',
  'owl': 'sowa',
  'painter': 'malarz',
  'pants': 'spodnie',
  'parrot': 'papuga',
  'parsley': 'pietruszka',
  'peach': 'brzoskwinia',
  'peacock': 'paw',
  'pelican': 'pelikan',
  'pencil': 'ołówek',
  'penguin': 'pingwin',
  'pepper': 'pieprz',
  'pharmacist': 'farmaceuta',
  'piano': 'fortepian',
  'pickle': 'ogórek kiszony',
  'pig': 'świnia',
  'pigeon': 'gołąb',
  'pilot': 'pilot',
  'pineapple': 'ananas',
  'platypus': 'dziobak',
  'playground': 'plac zabaw',
  'policeman': 'policjant',
  'pomegranate': 'granat',
  'potato': 'ziemniak',
  'principal': 'dyrektor',
  'professor': 'profesor',
  'pumpkin': 'dynia',
  'rabbit': 'królik',
  'raccoon': 'szop pracz',
  'rain': 'deszcz',
  'restroom': 'toaleta',
  'rhino': 'nosorożec',
  'river': 'rzeka',
  'rock': 'skała',
  'saxophone': 'saksofon',
  'scientist': 'naukowiec',
  'seagull': 'mewa',
  'seal': 'foka',
  'sesame': 'sezam',
  'shark': 'rekin',
  'sheep': 'owca',
  'shirt': 'koszula',
  'singer': 'piosenkarz',
  'ski': 'narty',
  'skunk': 'skunks',
  'sky': 'niebo',
  'snail': 'ślimak',
  'snake': 'wąż',
  'snow': 'śnieg',
  'snowboard': 'snowboard',
  'soccer': 'piłka nożna',
  'socks': 'skarpetki',
  'soil': 'gleba',
  'soldier': 'żołnierz',
  'space': 'przestrzeń',
  'sparrow': 'wróbel',
  'spinach': 'szpinak',
  'starfish': 'rozgwiazda',
  'stewardess': 'stewardesa',
  'stingray': 'płaszczka',
  'strawberry': 'truskawka',
  'sun': 'słońce',
  'subway': 'metro',
  'swallow': 'jaskółka',
  'sweater': 'sweter',
  'swimming': 'pływanie',
  'swing': 'huśtawka',
  'table': 'stół',
  'tambourine': 'tamburyn',
  'teacher': 'nauczyciel',
  'tiger': 'tygrys',
  'timpani': 'kotły',
  'toad': 'ropucha',
  'trampoline': 'trampolina',
  'tree': 'drzewo',
  'triangle': 'trójkąt',
  'truck': 'ciężarówka',
  'trumpet': 'trąbka',
  'turtle': 'żółw',
  'typhoon': 'tajfun',
  'unicorn': 'jednorożec',
  'violin': 'skrzypce',
  'viking ship': 'statek wikingów',
  'volcano': 'wulkan',
  'volleyball': 'siatkówka',
  'vuvuzela': 'wuwuzela',
  'waterfall': 'wodospad',
  'watermelon': 'arbuz',
  'wave': 'fala',
  'whale': 'wieloryb',
  'wind': 'wiatr',
  'window': 'okno',
  'wolf': 'wilk',
  'woodpecker': 'dzięcioł',
  'xylophone': 'ksylofon',
  'yacht': 'jacht',
  'zebra': 'zebra',
};

final Map<String, String> hunItemList = {
  'accordian': 'harmonika',
  'airplane': 'repülőgép',
  'anaconda': 'anakonda',
  'ant': 'hangya',
  'anteater': 'hangyász',
  'apple': 'alma',
  'apricot': 'sárgabarack',
  'archery': 'íjászat',
  'astronaut': 'űrhajós',
  'avocado': 'avokádó',
  'badminton': 'tollaslabda',
  'banana': 'banán',
  'baseball': 'baseball',
  'basketball': 'kosárlabda',
  'bassoon': 'fagott',
  'bat': 'denevér',
  'beach': 'tengerpart',
  'bear': 'medve',
  'bicycle': 'kerékpár',
  'blackboard': 'tábla',
  'blowfish': 'gömbhal',
  'blueberries': 'áfonya',
  'boar': 'vaddisznó',
  'book': 'könyv',
  'boots': 'csizma',
  'bowling': 'bowling',
  'boxing': 'ökölvívás',
  'broccoli': 'brokkoli',
  'bumper car': 'dodzsem',
  'bus': 'busz',
  'cabbage': 'káposzta',
  'camel': 'teve',
  'canteen': 'menza',
  'carp': 'ponty',
  'carpenter': 'ács',
  'carrot': 'sárgarépa',
  'castanets': 'kasztanyetta',
  'cat': 'macska',
  'cello': 'cselló',
  'chameleon': 'kaméleon',
  'cheetah': 'gepárd',
  'cherry': 'cseresznye',
  'chick': 'csibe',
  'chicken': 'csirke',
  'clarinet': 'klarinét',
  'classroom': 'osztályterem',
  'cloud': 'felhő',
  'cobra': 'kobra',
  'coconut': 'kókusz',
  'computer': 'számítógép',
  'conductor': 'karmester',
  'contrabass': 'nagybőgő',
  'cook': 'szakács',
  'corn': 'kukorica',
  'cow': 'tehén',
  'crab': 'rák',
  'crane': 'daru',
  'crocodile': 'krokodil',
  'crow': 'varjú',
  'cucumber': 'uborka',
  'curling': 'curling',
  'cymbals': 'cintányér',
  'deer': 'szarvas',
  'dentist': 'fogorvos',
  'desert': 'sivatag',
  'doctor': 'orvos',
  'dog': 'kutya',
  'dolphin': 'delfin',
  'drum': 'dob',
  'duck': 'kacsa',
  'eagle': 'sas',
  'earthquake': 'földrengés',
  'elephant': 'elefánt',
  'exam': 'vizsga',
  'farmer': 'farmer',
  'fencing': 'vívás',
  'ferris wheel': 'óriáskerék',
  'fig': 'füge',
  'firefighter': 'tűzoltó',
  'fisherman': 'halász',
  'flower': 'virág',
  'flute': 'fuvola',
  'fog': 'köd',
  'forest': 'erdő',
  'fox': 'róka',
  'friend': 'barát',
  'frog': 'béka',
  'garlic': 'fokhagyma',
  'ginger': 'gyömbér',
  'ginseng': 'ginzeng',
  'giraffe': 'zsiráf',
  'gloves': 'kesztyű',
  'goat': 'kecske',
  'golf': 'golf',
  'goose': 'lúd',
  'gorilla': 'gorilla',
  'grape': 'szőlő',
  'grapefruit': 'grapefruit',
  'guitar': 'gitár',
  'hairdressor': 'fodrász',
  'hallway': 'folyosó',
  'harmonica': 'szájharmonika',
  'harp': 'hárfa',
  'hat': 'kalap',
  'hawk': 'héja',
  'helicopter': 'helikopter',
  'hippo': 'víziló',
  'hippocampus': 'csikóhal',
  'hockey': 'jégkorong',
  'horse': 'ló',
  'hyena': 'hiéna',
  'iceberg': 'jéghegy',
  'iguana': 'leguán',
  'jellyfish': 'medúza',
  'judge': 'bíró',
  'judo': 'dzsúdó',
  'jujube': 'datolyaszilva',
  'jungle': 'dzsungel',
  'kangaroo': 'kenguru',
  'kiwi': 'kivi',
  'koala': 'koala',
  'lake': 'tó',
  'lemon': 'citrom',
  'leopard': 'párduc',
  'lettuce': 'saláta',
  'lightning': 'villám',
  'lion': 'oroszlán',
  'lizard': 'gyík',
  'lobster': 'homár',
  'magpie': 'szarka',
  'mango': 'mangó',
  'marathon': 'maraton',
  'meerkat': 'szurikáta',
  'melon': 'dinnye',
  'Merry go round': 'körhinta',
  'mole': 'vakond',
  'monkey': 'majom',
  'moon': 'hold',
  'mountain': 'hegy',
  'mouse': 'egér',
  'mushroom': 'gomba',
  'notebook': 'füzet',
  'ocarina': 'okarina',
  'ocean': 'óceán',
  'octopus': 'polip',
  'onion': 'hagyma',
  'orange': 'narancs',
  'orangutan': 'orangután',
  'orchestra': 'zenekar',
  'ostrich': 'strucc',
  'owl': 'bagoly',
  'painter': 'festő',
  'pants': 'nadrág',
  'parrot': 'papagáj',
  'parsley': 'petrezselyem',
  'peach': 'őszibarack',
  'peacock': 'páva',
  'pelican': 'pelikán',
  'pencil': 'ceruza',
  'penguin': 'pingvin',
  'pepper': 'bors',
  'pharmacist': 'gyógyszerész',
  'piano': 'zongora',
  'pickle': 'savanyúság',
  'pig': 'disznó',
  'pigeon': 'galamb',
  'pilot': 'pilóta',
  'pineapple': 'ananász',
  'platypus': 'kacsacsőrű emlős',
  'playground': 'játszótér',
  'policeman': 'rendőr',
  'pomegranate': 'gránátalma',
  'potato': 'burgonya',
  'principal': 'igazgató',
  'professor': 'professzor',
  'pumpkin': 'tök',
  'rabbit': 'nyúl',
  'raccoon': 'mosómedve',
  'rain': 'eső',
  'restroom': 'mosdó',
  'rhino': 'orrszarvú',
  'river': 'folyó',
  'rock': 'szikla',
  'saxophone': 'szaxofon',
  'scientist': 'tudós',
  'seagull': 'sirály',
  'seal': 'fóka',
  'sesame': 'szezám',
  'shark': 'cápa',
  'sheep': 'juh',
  'shirt': 'ing',
  'singer': 'énekes',
  'ski': 'sí',
  'skunk': 'bűzösborz',
  'sky': 'ég',
  'snail': 'csiga',
  'snake': 'kígyó',
  'snow': 'hó',
  'snowboard': 'hódeszka',
  'soccer': 'foci',
  'socks': 'zokni',
  'soil': 'talaj',
  'soldier': 'katona',
  'space': 'űr',
  'sparrow': 'veréb',
  'spinach': 'spenót',
  'starfish': 'tengeri csillag',
  'stewardess': 'légiutas-kísérő',
  'stingray': 'rája',
  'strawberry': 'eper',
  'sun': 'nap',
  'subway': 'metró',
  'swallow': 'fecske',
  'sweater': 'pulóver',
  'swimming': 'úszás',
  'swing': 'hinta',
  'table': 'asztal',
  'tambourine': 'csörgődob',
  'teacher': 'tanár',
  'tiger': 'tigris',
  'timpani': 'üstdob',
  'toad': 'varangy',
  'trampoline': 'trambulin',
  'tree': 'fa',
  'triangle': 'háromszög',
  'truck': 'teherautó',
  'trumpet': 'trombita',
  'turtle': 'teknős',
  'typhoon': 'tájfun',
  'unicorn': 'egyszarvú',
  'violin': 'hegedű',
  'viking ship': 'viking hajó',
  'volcano': 'vulkán',
  'volleyball': 'röplabda',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'vízesés',
  'watermelon': 'görögdinnye',
  'wave': 'hullám',
  'whale': 'bálna',
  'wind': 'szél',
  'window': 'ablak',
  'wolf': 'farkas',
  'woodpecker': 'harkály',
  'xylophone': 'xilofon',
  'yacht': 'jacht',
  'zebra': 'zebra',
};
