final Map<String, String> albanianItemList = {

  'accordian': 'akordion',
  'airplane': 'avion',
  'anaconda': 'anakonda',
  'ant': 'formikë',
  'anteater': 'haxhëtues i formikëve',
  'apple': 'mollë',
  'apricot': 'kajsi',
  'archery': 'të gjuajturit me hark',
  'astronaut': 'astronaut',
  'avocado': 'avokado',
  'badminton': 'badminton',
  'banana': 'banane',
  'baseball': 'bejzbol',
  'basketball': 'basketboll',
  'bassoon': 'basun',
  'bat': 'çikëll',
  'beach': 'plazh',
  'bear': 'derrake',
  'bicycle': 'bicikletë',
  'blackboard': 'tavë e zezë',
  'blowfish': 'peshk fryrës',
  'blueberries': 'boronicë',
  'boar': 'drek i egër',
  'book': 'libër',
  'boots': 'çizme',
  'bowling': 'kuglanje',
  'boxing': 'boks',
  'broccoli': 'brokoli',
  'bumper car': 'makinë për përplasje',
  'bus': 'autobuz',
  'cabbage': 'lakër',
  'camel': 'dromader',
  'carp': 'karp',
  'carpenter': 'zemërrojtës',
  'carrot': 'karotë',
  'castanets': 'kastanetë',
  'cat': 'macë',
  'cello': 'çelo',
  'chameleon': 'kameleont',
  'cheetah': 'gepard',
  'cherry': 'qershi',
  'chick': 'pulëz',
  'chicken': 'pulë',
  'clarinet': 'klarinetë',
  'classroom': 'klasë',
  'cloud': 're',
  'cobra': 'kobra',
  'coconut': 'kokos',
  'computer': 'kompjuter',
  'conductor': 'dirigent',
  'contrabass': 'kontrabas',
  'cook': 'gatues',
  'corn': 'misër',
  'cow': 'lopë',
  'crab': 'krap',
  'crane': 'katraka',
  'crocodile': 'krokodil',
  'crow': 'kukur',
  'cucumber': 'kastravec',
  'curling': 'curling',
  'cymbals': 'cimbalë',
  'deer': 'ri',
  'dentist': 'dentist',
  'desert': 'shkretëtirë',
  'doctor': 'mjek',
  'dog': 'qen',
  'dolphin': 'delfin',
  'drum': 'tamburinë',
  'duck': 'eja',
  'eagle': 'shqiponjë',
  'earthquake': 'tërmet',
  'elephant': 'elefant',
  'exam': 'provim',
  'farmer': 'fermier',
  'fencing': 'sulm me spadë',
  'ferris wheel': 'rrota e lumturisë',
  'fig': 'fiken',
  'firefighter': 'fitor',
  'fisherman': 'peshkatar',
  'flower': 'lule',
  'flute': 'flautë',
  'fog': 'mjellmë',
  'forest': 'pyll',
  'fox': 'dhelpër',
  'friend': 'shok',
  'frog': 'bretkos',
  'garlic': 'hudhrë',
  'ginger': 'xhenxhe',
  'ginseng': 'xhenxheng',
  'giraffe': 'xirafë',
  'gloves': 'doreza',
  'goat': 'dhëmbë',
  'golf': 'golf',
  'goose': 'gështë',
  'gorilla': 'gorilë',
  'grape': 'rrush',
  'grapefruit': 'grejpfrut',
  'guitar': 'kitare',
  'hairdressor': 'parukier',
  'hallway': 'hapësirë e ngushtë',
  'harmonica': 'harmonikë',
  'harp': 'arpa',
  'hat': 'kapelë',
  'hawk': 'shqiponjë e vogël',
  'helicopter': 'helikopter',
  'hippo': 'hipopotam',
  'hippocampus': 'hipokampus',
  'hockey': 'hokey',
  'horse': 'kalë',
  'hyena': 'hijenë',
  'iceberg': 'akullbjerg',
  'iguana': 'iguana',
  'jellyfish': 'meduzë',
  'judge': 'gjykatës',
  'judo': 'xudo',
  'jujube': 'xuxhube',
  'jungle': 'xungullë',
  'kangaroo': 'kanguro',
  'kiwi': 'kiui',
  'koala': 'koala',
  'lake': 'liqen',
  'lemon': 'limon',
  'leopard': 'leopard',
  'lettuce': 'salatë',
  'lightning': 'rrufe',
  'lion': 'luan',
  'lizard': 'guaj',
  'lobster': 'jastog',
  'magpie': 'magpi',
  'mango': 'mango',
  'marathon': 'maraton',
  'meerkat': 'meerkat',
  'melon': 'dinjë',
  'Merry go round': 'karusel',
  'mole': 'mol',
  'monkey': 'majmun',
  'moon': 'hënë',
  'mountain': 'mal',
  'mouse': 'miu',
  'mushroom': 'qymyri',
  'notebook': 'shënues',
  'ocarina': 'okarina',
  'ocean': 'det',
  'octopus': 'polip',
  'onion': 'qep',
  'orange': 'portokall',
  'orangutan': 'orangutan',
  'orchestra': 'orkestër',
  'ostrich': 'struç',
  'owl': 'buçëll',
  'painter': 'piktor',
  'pants': 'pantallona',
  'parrot': 'papagaj',
  'parsley': 'peterselie',
  'peach': 'piersikë',
  'peacock': 'paun',
  'pelican': 'pelikan',
  'pencil': 'llapis',
  'penguin': 'pingvin',
  'pepper': 'piper',
  'pharmacist': 'farmacist',
  'piano': 'piano',
  'pickle': 'turshi',
  'pig': 'derr',
  'pigeon': 'pule',
  'pilot': 'pilot',
  'pineapple': 'ananas',
  'platypus': 'platipus',
  'playground': 'këndë lojrash',
  'policeman': 'polic',
  'pomegranate': 'granatë',
  'potato': 'patate',
  'principal': 'drejtor',
  'professor': 'profesor',
  'pumpkin': 'kungull',
  'rabbit': 'lepur',
  'raccoon': 'rakun',
  'rain': 'shi',
  'restroom': 'tualetë',
  'rhino': 'nosorog',
  'river': 'lumë',
  'rock': 'shkëmb',
  'saxophone': 'saksofon',
  'scientist': 'shkencëtar',
  'seagull': 'valëbardhë',
  'seal': 'foka',
  'sesame': 'susam',
  'shark': 'peshk-sulm',
  'sheep': 'dele',
  'shirt': 'këmishë',
  'singer': 'kantëtar',
  'ski': 'ski',
  'skunk': 'skunk',
  'sky': 'qiell',
  'snail': 'pjell',
  'snake': 'gjarpër',
  'snow': 'borë',
  'snowboard': 'snowboard',
  'soccer': 'futboll',
  'socks': 'çorape',
  'soil': 'tokë',
  'soldier': 'ushtar',
  'space': 'hapësirë',
  'sparrow': 'vrabë',
  'spinach': 'spinaq',
  'starfish': 'peshk ylli',
  'stewardess': 'stjuardesë',
  'stingray': 'peshk rrallë',
  'strawberry': 'fragë',
  'sun': 'diell',
  'subway': 'metro',
  'swallow': 'çutër',
  'sweater': 'triko',
  'swimming': 'not',
  'swing': 'luhat',
  'table': 'tryezë',
  'tambourine': 'tamburinë',
  'teacher': 'mësues',
  'tiger': 'tiger',
  'timpani': 'timpani',
  'toad': 'toad',
  'trampoline': 'trampoline',
  'tree': 'pemë',
  'triangle': 'trëndëkat',
  'truck': 'kamion',
  'trumpet': 'trumpetë',
  'turtle': 'kornjaçë',
  'typhoon': 'taifun',
  'unicorn': 'jednorog',
  'violin': 'violino',
  'viking ship': 'anije vikinge',
  'volcano': 'vulkan',
  'volleyball': 'odbojka',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'ujëfalë',
  'watermelon': 'lubenica',
  'wave': 'valë',
  'whale': 'balenë',
  'wind': 'erë',
  'window': 'dritare',
  'wolf': 'ujk',
  'woodpecker': 'pupeç',
  'xylophone': 'ksilofon',
  'yacht': 'jaht',
  'zebra': 'zebrë',
  'library': 'biblioteka',
  'post office': 'postë',
  'traffic light': 'semafor',
  'clock tower': 'kulla e orës',
  'pebble': 'gur i vogël',
  'moss': 'myshk',
  'cactus': 'kaktus',
  'rainbow': 'ylber',
  'toast': 'tost',
  'cookie': 'biskotë',
  'ice cream': 'akullore',
  'jelly': 'xhel',
  'writer': 'shkrimtar',
  'actor': 'aktor',
  'crown': 'kurorë',
  'compass': 'busull',
  'flowerpot': 'tenxhere lulesh',
  'roller skates': 'patina',
  'airport': 'aeroport',
  'goldfish': 'peshk i artë',
  'spider': 'merimangë',
  'light bulb': 'llambë',
  'mirror': 'pasqyrë',
  'magnet': 'magnet',
  'toothbrush': 'furçë dhëmbësh',
  'soap': 'sapun',
  'plate': 'pjatë',
  'spoon': 'lugë',
  'mobile phone': 'telefon celular',
  'key': 'çelës',
  'newspaper': 'gazetë',
  'calendar': 'kalendar',
  'chair': 'karrige',
  'sofa': 'divan',
  'refrigerator': 'frigorifer',
  'stairs': 'shkallë',
  'pillow': 'jastëk',
  'candle': 'qiri',
  'bank': 'bankë',
  'beetle': 'brumbull',
  'cicada': 'cikadë',
  'dragonfly': 'libellulë',
  'earthworm': 'krimb toke',
  'komodo dragon': 'dragon komodo',
  'mantis': 'mantis',
  'mosquito': 'mushkonjë',
  'silkworm': 'krimb mëndafshi',
  'stag beetle': 'brumbull drej',
  'table tennis': 'tenis tryeze',
  'train': 'tren',
  'squid': 'kalamar',
  'butterfly': 'flutur',
  'bee': 'bletë',
  'squirrel': 'ketër',
  'nurse': 'infermiere',
  'slide': 'rrëshqitje',
  'picnic': 'piknik',
  'jacket': 'xhaketë',
  'shoes': 'këpucë',
  'tennis': 'tenis'
};