final Map<String, String> amharicItemList = {

  'accordian': 'አኮርዲዮን',
  'airplane': 'አውሮፕላን',
  'anaconda': 'አናኮንዳ',
  'ant': 'አንት',
  'anteater': 'አንተኢተር',
  'apple': 'ፖም',
  'apricot': 'አፕሪኮት',
  'archery': 'አርቸሪ',
  'astronaut': 'አስትራኖት',
  'avocado': 'አቮካዶ',
  'badminton': 'ባድሚንተን',
  'banana': 'ሙዝ',
  'baseball': 'ቤዝቦል',
  'basketball': 'ባስኬትቦል',
  'bassoon': 'ባሱን',
  'bat': 'አንባሳ ጫማ',
  'beach': 'የባህር ዳርቻ',
  'bear': 'ድብ',
  'bicycle': 'ብስክሌት',
  'blackboard': 'ጥቁር ሰሌዳ',
  'blowfish': 'ብሎውፊሽ',
  'blueberries': 'ብሉቤሪዎች',
  'boar': 'ዱር ዝሆን',
  'book': 'መጽሐፍ',
  'boots': 'ቡት',
  'bowling': 'ቦውሊንግ',
  'boxing': 'ቦክሲንግ',
  'broccoli': 'ብሮኮሊ',
  'bumper car': 'ቡምፐር መኪና',
  'bus': 'ባስ',
  'cabbage': 'ቀብስ',
  'camel': 'ካሜል',
  'carp': 'ካርፕ',
  'carpenter': 'መሠረታዊ ጠራር',
  'carrot': 'ካሮት',
  'castanets': 'ካስታኔት',
  'cat': 'ድመት',
  'cello': 'ቼሎ',
  'chameleon': 'ካሜሎን',
  'cheetah': 'ቺታ',
  'cherry': 'ቸሪ',
  'chick': 'ብዙሃን',
  'chicken': 'ዶሮ',
  'clarinet': 'ክላሪኔት',
  'classroom': 'ክፍል ትምህርት',
  'cloud': 'ደመና',
  'cobra': 'ኮብራ',
  'coconut': 'ኮኮናት',
  'computer': 'ኮምፒውተር',
  'conductor': 'መሪ',
  'contrabass': 'ኮንትራባስ',
  'cook': 'የምግብ አብራሪ',
  'corn': 'አንገት',
  'cow': 'ላም',
  'crab': 'ጭልፊት',
  'crane': 'ክሬን',
  'crocodile': 'አሳማ',
  'crow': 'ድመት ወፍ',
  'cucumber': 'ቆንድራ',
  'curling': 'ኩርሊንግ',
  'cymbals': 'ሲምባል',
  'deer': 'ሌላ ተለዋዋጭ',
  'dentist': 'የጥርስ ሐኪም',
  'desert': 'ምድረ በዳ',
  'doctor': 'ሐኪም',
  'dog': 'ውሻ',
  'dolphin': 'ዶልፊን',
  'drum': 'ድራም',
  'duck': 'ዳክ',
  'eagle': 'አይጋል',
  'earthquake': 'ምድር መለወጥ',
  'elephant': 'ዝሆን',
  'exam': 'ፈተና',
  'farmer': 'ገበሬ',
  'fencing': 'በረከት',
  'ferris wheel': 'ፈሪስ ቪል',
  'fig': 'ጣፋጭ ፍሪት',
  'firefighter': 'እሳት ጠፊ',
  'fisherman': 'አሳ ሰራተኛ',
  'flower': 'አበባ',
  'flute': 'ፍሉት',
  'fog': 'ጭጋግ',
  'forest': 'ጫካ',
  'fox': 'ቀበሮ',
  'friend': 'ጓደኛ',
  'frog': 'ተራ አውታር',
  'garlic': 'ሽንኩርት',
  'ginger': 'እንጉዴ',
  'ginseng': 'ጂንሰንግ',
  'giraffe': 'ጊራፍ',
  'gloves': 'መጠበቂያ ልብስ',
  'goat': 'ፍየል',
  'golf': 'ጎልፍ',
  'goose': 'ወፍ',
  'gorilla': 'ጎሪላ',
  'grape': 'ወይን',
  'grapefruit': 'ግራፕፍሩት',
  'guitar': 'ጊታር',
  'hairdresser': 'ፀጉር ቆራሪ',
  'hallway': 'መንገድ',
  'harmonica': 'ሀርሞኒካ',
  'harp': 'ሀርፕ',
  'hat': 'ቦት',
  'hawk': 'አርጋ',
  'helicopter': 'ሄሊኮፕተር',
  'hippo': 'ሂፖ',
  'hippocampus': 'ሂፖካምፖስ',
  'hockey': 'ሆኪ',
  'horse': 'ፈረስ',
  'hyena': 'ሃይና',
  'iceberg': 'በረዶ ተራራ',
  'iguana': 'ኢጓና',
  'jellyfish': 'ጅሊ አሳ',
  'judge': 'ዳኛ',
  'judo': 'ጁዶ',
  'jujube': 'ጁጁቤ',
  'jungle': 'ጫካ',
  'kangaroo': 'ካንጋሩ',
  'kiwi': 'ኪዊ',
  'koala': 'ኮአላ',
  'lake': 'ሐይቅ',
  'lemon': 'ሎሚ',
  'leopard': 'ነብር',
  'lettuce': 'ሰላጣ',
  'lightning': 'መብረቅ',
  'lion': 'አንበሳ',
  'lizard': 'ሳይታ',
  'lobster': 'ሎብስተር',
  'magpie': 'ማግፓይ',
  'mango': 'ማንጎ',
  'marathon': 'ማራቶን',
  'meerkat': 'ሜርካት',
  'melon': 'ሜሎን',
  'Merry go round': 'መሪ ጎ ራውንድ',
  'mole': 'ሞል',
  'monkey': 'ሙንኪ',
  'moon': 'ጨረቃ',
  'mountain': 'ተራራ',
  'mouse': 'አይጥ',
  'mushroom': 'አንባሳ',
  'notebook': 'ኖትቡክ',
  'ocarina': 'ኦካሪና',
  'ocean': 'ውቅያኖስ',
  'octopus': 'ኦክቶፑስ',
  'onion': 'ሽንኩርት',
  'orange': 'ብርቱካን',
  'orangutan': 'ኦራንጉታን',
  'orchestra': 'ኦርኬስትራ',
  'ostrich': 'ስትራውች',
  'owl': 'አውል',
  'painter': 'ሰዓሊ',
  'pants': 'ሱሪ',
  'parrot': 'ፓሮት',
  'parsley': 'ፓርስሌይ',
  'peach': 'ፒች',
  'peacock': 'ፒካክ',
  'pelican': 'ፔሊካን',
  'pencil': 'አስተምህረት',
  'penguin': 'ፔንጊን',
  'pepper': 'በርበሬ',
  'pharmacist': 'ፋርማሲስት',
  'piano': 'ፒያኖ',
  'pickle': 'ፒክል',
  'pig': 'ድንብል',
  'pigeon': 'ድብ ወፍ',
  'pilot': 'ፓይሎት',
  'pineapple': 'አናናስ',
  'platypus': 'ፕላቲፖስ',
  'playground': 'መስክ',
  'policeman': 'ፖሊስ',
  'pomegranate': 'ሮማን',
  'potato': 'ድንች',
  'principal': 'ዋና መምህር',
  'professor': 'ፕሮፌሰር',
  'pumpkin': 'ዱባ',
  'rabbit': 'አንበሳ',
  'raccoon': 'ራኮን',
  'rain': 'ዝናብ',
  'restroom': 'መጸዳጃ',
  'rhino': 'ሮይኖ',
  'river': 'ወንዝ',
  'rock': 'ድንጋይ',
  'saxophone': 'ሳክስፎን',
  'scientist': 'ሳይንቲስት',
  'seagull': 'የባህር ወፍ',
  'seal': 'ሲል',
  'sesame': 'ሰሰሜ',
  'shark': 'አሳ',
  'sheep': 'በግ',
  'shirt': 'ሸሚዝ',
  'singer': 'ዘፋኝ',
  'ski': 'ስኪ',
  'skunk': 'ስካንክ',
  'sky': 'ሰማይ',
  'snail': 'ስኔይል',
  'snake': 'እባብ',
  'snow': 'በረዶ',
  'snowboard': 'ስኖቭ ቦርድ',
  'soccer': 'እግር ኳስ',
  'socks': 'የእግር ጫማ',
  'soil': 'መሬት',
  'soldier': 'ወታደር',
  'space': 'ሰማይ',
  'sparrow': 'ስፓሮ',
  'spinach': 'ስፒናች',
  'starfish': 'ኮከብ አሳ',
  'stewardess': 'አስተባባሪ',
  'stingray': 'ስቲንግሬ',
  'strawberry': 'ስትሮቤሪ',
  'sun': 'ፀሐይ',
  'subway': 'ከታች ባቡር',
  'swallow': 'ዋላ',
  'sweater': 'ሱዌተር',
  'swimming': 'ውሃ ማረፍ',
  'swing': 'ሰው ገምጋሚ',
  'table': 'ጠረጴዛ',
  'tambourine': 'ታምቡሪን',
  'teacher': 'መምህር',
  'tiger': 'ነብር',
  'timpani': 'ቲምፓኒ',
  'toad': 'ውኃ ተክል',
  'trampoline': 'ትራምፖሊን',
  'tree': 'ዛፍ',
  'triangle': 'ሶስት ማእዝን',
  'truck': 'ትራክ',
  'trumpet': 'ትራምፔት',
  'turtle': 'አንበሳ አሳ',
  'typhoon': 'ታይፎን',
  'unicorn': 'ዩኒኮርን',
  'violin': 'ቫዮሊን',
  'viking ship': 'ቪኪንግ መርከብ',
  'volcano': 'እሳተ ገሞራ',
  'volleyball': 'ቮሊባል',
  'vuvuzela': 'ቩቩዜላ',
  'waterfall': 'ወንዝ ዝናብ',
  'watermelon': 'ውሃ ፍሬ',
  'wave': 'ማዕበል',
  'whale': 'አንድ ዓሣ',
  'wind': 'ነፋስ',
  'window': 'መስኮት',
  'wolf': 'ተኵላ',
  'woodpecker': 'የዛፍ ወፍ',
  'xylophone': 'ዚሎፎን',
  'yacht': 'ያት',
  'zebra': 'ዘብራ',
  'library': 'ቤተ መጻሕፍት',
  'post office': 'ፖስታ',
  'traffic light': 'ትራፊክ መብራት',
  'clock tower': 'ሰዓት ግንብ',
  'pebble': 'አነስተኛ ድንጋይ',
  'moss': 'ሞስ',
  'cactus': 'ካክተስ',
  'rainbow': 'ቀስተ ደመና',
  'toast': 'ተቀቅሎ የተሰራ እንጀራ',
  'cookie': 'ኩኪ',
  'ice cream': 'አይስ ክሬም',
  'jelly': 'ጄሊ',
  'writer': 'ጸሐፊ',
  'actor': 'ተዋናይ',
  'crown': 'አክሊል',
  'compass': 'ኮምፓስ',
  'flowerpot': 'አበባ ዕቃ',
  'roller skates': 'ሮለር ስኬት',
  'airport': 'አውሮፕላን መርከብ',
  'goldfish': 'ወርቅ ዓሣ',
  'spider': 'ሸረሪት',
  'light bulb': 'ብርሃን ቡልብ',
  'mirror': 'መስታወት',
  'magnet': 'ማግኔት',
  'toothbrush': 'የጥርስ ብሩሽ',
  'soap': 'ሳሙና',
  'plate': 'ጋሻ',
  'spoon': 'ማንኪያ',
  'mobile phone': 'ሞባይል ስልክ',
  'key': 'ቁልፍ',
  'newspaper': 'ዜና ወረጃ',
  'calendar': 'ቀን መቁጠሪያ',
  'chair': 'መቀመጫ',
  'sofa': 'ሶፋ',
  'refrigerator': 'ማቀዝቀዣ',
  'stairs': 'ደረጃዎች',
  'pillow': 'መንጋጋ',
  'candle': 'ሻምድ',
  'bank': 'ባንክ',
  'beetle': 'ማብረያ',
  'cicada': 'ሲካዳ',
  'dragonfly': 'ድራጎን ፍላይ',
  'earthworm': 'አፈር ተርማ',
  'komodo dragon': 'ኮሞዶ ድራጎን',
  'mantis': 'ማንቲስ',
  'mosquito': 'ሞስኪቶ',
  'silkworm': 'ሲልክ ተርማ',
  'stag beetle': 'ስታግ ቢትል',
  'table tennis': 'ቴብል ቴኒስ',
  'train': 'ባቡር',
  'squid': 'ስኩይድ',
  'butterfly': 'ቢራቢሮ',
  'bee': 'ንብ',
  'squirrel': 'ስኩይሪል',
  'nurse': 'ነርስ',
  'slide': 'ስላይድ',
  'picnic': 'ፒክኒክ',
  'jacket': 'ጃኬት',
  'shoes': 'ጫማዎች',
  'tennis': 'ቴኒስ'
};