final Map<String, String> araItemList = {

  'accordian': 'أكورديون',
  'airplane': 'طائرة',
  'anaconda': 'أناكوندا',
  'ant': 'نملة',
  'anteater': 'آكل النمل',
  'apple': 'تفاح',
  'apricot': 'مشمش',
  'archery': 'رماية',
  'astronaut': 'رائد فضاء',
  'avocado': 'أفوكادو',
  'badminton': 'ريشة طائرة',
  'banana': 'موز',
  'baseball': 'بيسبول',
  'basketball': 'كرة سلة',
  'bassoon': 'باسون',
  'bat': 'خفاش',
  'beach': 'شاطئ',
  'bear': 'دب',
  'bicycle': 'دراجة',
  'blackboard': 'سبورة',
  'blowfish': 'سمكة منتفخة',
  'blueberries': 'توت أزرق',
  'boar': 'خنزير بري',
  'book': 'كتاب',
  'boots': 'أحذية',
  'bowling': 'بولينج',
  'boxing': 'ملاكمة',
  'broccoli': 'بروكلي',
  'bumper car': 'سيارة تصادم',
  'bus': 'حافلة',
  'cabbage': 'ملفوف',
  'camel': 'جمل',
  'carp': 'شبوط',
  'carpenter': 'نجار',
  'carrot': 'جزر',
  'castanets': 'كاستنيت',
  'cat': 'قطة',
  'cello': 'تشيلو',
  'chameleon': 'حرباء',
  'cheetah': 'فهد',
  'cherry': 'كرز',
  'chick': 'كتكوت',
  'chicken': 'دجاج',
  'clarinet': 'كلارينيت',
  'classroom': 'فصل دراسي',
  'cloud': 'سحابة',
  'cobra': 'كوبرا',
  'coconut': 'جوز الهند',
  'computer': 'حاسوب',
  'conductor': 'قائد أوركسترا',
  'contrabass': 'كونترباص',
  'cook': 'طباخ',
  'corn': 'ذرة',
  'cow': 'بقرة',
  'crab': 'سلطعون',
  'crane': 'رافعة',
  'crocodile': 'تمساح',
  'crow': 'غراب',
  'cucumber': 'خيار',
  'curling': 'كيرلنغ',
  'cymbals': 'صنجات',
  'deer': 'غزال',
  'dentist': 'طبيب أسنان',
  'desert': 'صحراء',
  'doctor': 'طبيب',
  'dog': 'كلب',
  'dolphin': 'دلفين',
  'drum': 'طبل',
  'duck': 'بطة',
  'eagle': 'نسر',
  'earthquake': 'زلزال',
  'elephant': 'فيل',
  'exam': 'امتحان',
  'farmer': 'مزارع',
  'fencing': 'مبارزة',
  'ferris wheel': 'عجلة فيريس',
  'fig': 'تين',
  'firefighter': 'رجل إطفاء',
  'fisherman': 'صياد',
  'flower': 'زهرة',
  'flute': 'ناي',
  'fog': 'ضباب',
  'forest': 'غابة',
  'fox': 'ثعلب',
  'friend': 'صديق',
  'frog': 'ضفدع',
  'garlic': 'ثوم',
  'ginger': 'زنجبيل',
  'ginseng': 'جينسنغ',
  'giraffe': 'زرافة',
  'gloves': 'قفازات',
  'goat': 'ماعز',
  'golf': 'غولف',
  'goose': 'إوزة',
  'gorilla': 'غوريلا',
  'grape': 'عنب',
  'grapefruit': 'جريب فروت',
  'guitar': 'قيثارة',
  'hairdressor': 'حلاق',
  'hallway': 'ممر',
  'harmonica': 'هارمونيكا',
  'harp': 'قيثارة',
  'hat': 'قبعة',
  'hawk': 'صقر',
  'helicopter': 'مروحية',
  'hippo': 'فرس النهر',
  'hippocampus': 'فرس البحر',
  'hockey': 'هوكي',
  'horse': 'حصان',
  'hyena': 'هينة',
  'iceberg': 'جبل جليدي',
  'iguana': 'إغوانا',
  'jellyfish': 'قنديل البحر',
  'judge': 'قاضي',
  'judo': 'جودو',
  'jujube': 'عناب',
  'jungle': 'أدغال',
  'kangaroo': 'كنغر',
  'kiwi': 'كيوي',
  'koala': 'كوالا',
  'lake': 'بحيرة',
  'lemon': 'ليمون',
  'leopard': 'نمر',
  'lettuce': 'خس',
  'lightning': 'برق',
  'lion': 'أسد',
  'lizard': 'سحلية',
  'lobster': 'جراد البحر',
  'magpie': 'عقعق',
  'mango': 'مانجو',
  'marathon': 'ماراثون',
  'meerkat': 'ميركات',
  'melon': 'بطيخ',
  'Merry go round': 'دوامة',
  'mole': 'خلد',
  'monkey': 'قرد',
  'moon': 'قمر',
  'mountain': 'جبل',
  'mouse': 'فأر',
  'mushroom': 'فطر',
  'notebook': 'دفتر',
  'ocarina': 'أوكارينا',
  'ocean': 'محيط',
  'octopus': 'أخطبوط',
  'onion': 'بصل',
  'orange': 'برتقال',
  'orangutan': 'إنسان الغاب',
  'orchestra': 'أوركسترا',
  'ostrich': 'نعامة',
  'owl': 'بومة',
  'painter': 'رسام',
  'pants': 'بنطلون',
  'parrot': 'ببغاء',
  'parsley': 'بقدونس',
  'peach': 'خوخ',
  'peacock': 'طاووس',
  'pelican': 'بجع',
  'pencil': 'قلم رصاص',
  'penguin': 'بطريق',
  'pepper': 'فلفل',
  'pharmacist': 'صيدلي',
  'piano': 'بيانو',
  'pickle': 'مخلل',
  'pig': 'خنزير',
  'pigeon': 'حمامة',
  'pilot': 'طيار',
  'pineapple': 'أناناس',
  'platypus': 'منقار البط',
  'playground': 'ملعب',
  'policeman': 'شرطي',
  'pomegranate': 'رمان',
  'potato': 'بطاطس',
  'principal': 'مدير',
  'professor': 'أستاذ',
  'pumpkin': 'قرع',
  'rabbit': 'أرنب',
  'raccoon': 'راكون',
  'rain': 'مطر',
  'restroom': 'حمام',
  'rhino': 'وحيد القرن',
  'river': 'نهر',
  'rock': 'صخرة',
  'saxophone': 'ساكسفون',
  'scientist': 'عالم',
  'seagull': 'نورس',
  'seal': 'فقمة',
  'sesame': 'سمسم',
  'shark': 'أقنوم',
  'sheep': 'خروف',
  'shirt': 'قميص',
  'singer': 'مغني',
  'ski': 'تزلج',
  'skunk': 'ظربان',
  'sky': 'سماء',
  'snail': 'حلزون',
  'snake': 'ثعبان',
  'snow': 'ثلج',
  'snowboard': 'لوح التزلج',
  'soccer': 'كرة القدم',
  'socks': 'جوارب',
  'soil': 'تربة',
  'soldier': 'جندي',
  'space': 'فضاء',
  'sparrow': 'عصفور',
  'spinach': 'سبانخ',
  'starfish': 'نجم البحر',
  'stewardess': 'مضيفة طيران',
  'stingray': 'شفنين',
  'strawberry': 'فراولة',
  'sun': 'شمس',
  'subway': 'مترو الأنفاق',
  'swallow': 'سنونو',
  'sweater': 'سترة',
  'swimming': 'سباحة',
  'swing': 'أرجوحة',
  'table': 'طاولة',
  'tambourine': 'دف',
  'teacher': 'معلم',
  'tiger': 'نمر',
  'timpani': 'طبول',
  'toad': 'علجوم',
  'trampoline': 'ترامبولين',
  'tree': 'شجرة',
  'triangle': 'مثلث',
  'truck': 'شاحنة',
  'trumpet': 'بوق',
  'turtle': 'سلحفاة',
  'typhoon': 'إعصار',
  'unicorn': 'وحيد القرن',
  'violin': 'كمان',
  'viking ship': 'سفينة الفايكنج',
  'volcano': 'بركان',
  'volleyball': 'كرة الطائرة',
  'vuvuzela': 'فوفوزيلا',
  'waterfall': 'شلال',
  'watermelon': 'بطيخ',
  'wave': 'موجة',
  'whale': 'حوت',
  'wind': 'رياح',
  'window': 'نافذة',
  'wolf': 'ذئب',
  'woodpecker': 'نقار الخشب',
  'xylophone': 'إكسيليفون',
  'yacht': 'يخت',
  'zebra': 'حمار وحشي',
  'library': 'مكتبة',
  'post office': 'مكتب البريد',
  'traffic light': 'إشارة المرور',
  'clock tower': 'برج الساعة',
  'pebble': 'حصاة',
  'moss': 'طحلب',
  'cactus': 'صبار',
  'rainbow': 'قوس قزح',
  'toast': 'توست',
  'cookie': 'بسكويت',
  'ice cream': 'آيس كريم',
  'jelly': 'جيلي',
  'writer': 'كاتب',
  'actor': 'ممثل',
  'crown': 'تاج',
  'compass': 'بوصلة',
  'flowerpot': 'وعاء الزهور',
  'roller skates': 'تزلج على العجلات',
  'airport': 'مطار',
  'goldfish': 'سمكة ذهبية',
  'spider': 'عنكبوت',
  'light bulb': 'مصباح',
  'mirror': 'مرآة',
  'magnet': 'مغناطيس',
  'toothbrush': 'فرشاة أسنان',
  'soap': 'صابون',
  'plate': 'طبق',
  'spoon': 'ملعقة',
  'mobile phone': 'هاتف محمول',
  'key': 'مفتاح',
  'newspaper': 'صحيفة',
  'calendar': 'تقويم',
  'chair': 'كرسي',
  'sofa': 'أريكة',
  'refrigerator': 'ثلاجة',
  'stairs': 'سلالم',
  'pillow': 'وسادة',
  'candle': 'شمعة',
  'bank': 'بنك',
  'beetle': 'خنفساء',
  'cicada': 'زيز',
  'dragonfly': 'يعسوب',
  'earthworm': 'دودة أرضية',
  'komodo dragon': 'تنين كومودو',
  'mantis': 'فرس النبي',
  'mosquito': 'بعوضة',
  'silkworm': 'دودة القز',
  'stag beetle': 'خنفساء الأيل',
  'table tennis': 'تنس الطاولة',
  'train': 'قطار',
  'squid': 'حبار',
  'butterfly': 'فراشة',
  'bee': 'نحلة',
  'squirrel': 'سنجاب',
  'nurse': 'ممرضة',
  'slide': 'زحليقة',
  'picnic': 'نزهة',
  'jacket': 'سترة',
  'shoes': 'أحذية',
  'tennis': 'تنس'
};