final Map<String, String> fraItemList = {

  'accordian': 'accordéon',
  'airplane': 'avion',
  'anaconda': 'anaconda',
  'ant': 'fourmi',
  'anteater': 'fourmilier',
  'apple': 'pomme',
  'apricot': 'abricot',
  'archery': 'tir à l\'arc',
  'astronaut': 'astronaute',
  'avocado': 'avocat',
  'badminton': 'badminton',
  'banana': 'banane',
  'baseball': 'base-ball',
  'basketball': 'basket-ball',
  'bassoon': 'basson',
  'bat': 'chauve-souris',
  'beach': 'plage',
  'bear': 'ours',
  'bicycle': 'vélo',
  'blackboard': 'tableau noir',
  'blowfish': 'poisson-globe',
  'blueberries': 'myrtilles',
  'boar': 'sanglier',
  'book': 'livre',
  'boots': 'bottes',
  'bowling': 'bowling',
  'boxing': 'boxe',
  'broccoli': 'brocoli',
  'bumper car': 'auto tamponneuse',
  'bus': 'bus',
  'cabbage': 'chou',
  'camel': 'chameau',
  'carp': 'carpe',
  'carpenter': 'charpentier',
  'carrot': 'carotte',
  'castanets': 'castagnettes',
  'cat': 'chat',
  'cello': 'violoncelle',
  'chameleon': 'caméléon',
  'cheetah': 'guépard',
  'cherry': 'cerise',
  'chick': 'poussin',
  'chicken': 'poulet',
  'clarinet': 'clarinette',
  'classroom': 'salle de classe',
  'cloud': 'nuage',
  'cobra': 'cobra',
  'coconut': 'noix de coco',
  'computer': 'ordinateur',
  'conductor': 'chef d\'orchestre',
  'contrabass': 'contrebasse',
  'cook': 'cuisinier',
  'corn': 'maïs',
  'cow': 'vache',
  'crab': 'crabe',
  'crane': 'grue',
  'crocodile': 'crocodile',
  'crow': 'corbeau',
  'cucumber': 'concombre',
  'curling': 'curling',
  'cymbals': 'cymbales',
  'deer': 'cerf',
  'dentist': 'dentiste',
  'desert': 'désert',
  'doctor': 'médecin',
  'dog': 'chien',
  'dolphin': 'dauphin',
  'drum': 'tambour',
  'duck': 'canard',
  'eagle': 'aigle',
  'earthquake': 'tremblement de terre',
  'elephant': 'éléphant',
  'exam': 'examen',
  'farmer': 'fermier',
  'fencing': 'escrime',
  'ferris wheel': 'grande roue',
  'fig': 'figue',
  'firefighter': 'pompier',
  'fisherman': 'pêcheur',
  'flower': 'fleur',
  'flute': 'flûte',
  'fog': 'brouillard',
  'forest': 'forêt',
  'fox': 'renard',
  'friend': 'ami',
  'frog': 'rana',
  'garlic': 'ail',
  'ginger': 'gingembre',
  'ginseng': 'ginseng',
  'giraffe': 'girafe',
  'gloves': 'gants',
  'goat': 'chèvre',
  'golf': 'golf',
  'goose': 'oie',
  'gorilla': 'gorille',
  'grape': 'raisin',
  'grapefruit': 'pamplemousse',
  'guitar': 'guitare',
  'hairdressor': 'coiffeur',
  'hallway': 'couloir',
  'harmonica': 'harmonica',
  'harp': 'harpe',
  'hat': 'chapeau',
  'hawk': 'faucon',
  'helicopter': 'hélicoptère',
  'hippo': 'hippopotame',
  'hippocampus': 'hippocampe',
  'hockey': 'hockey',
  'horse': 'cheval',
  'hyena': 'hyène',
  'iceberg': 'iceberg',
  'iguana': 'iguane',
  'jellyfish': 'méduse',
  'judge': 'juge',
  'judo': 'judo',
  'jujube': 'jujube',
  'jungle': 'jungle',
  'kangaroo': 'kangourou',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'lac',
  'lemon': 'citron',
  'leopard': 'léopard',
  'lettuce': 'laitue',
  'lightning': 'éclair',
  'lion': 'lion',
  'lizard': 'lézard',
  'lobster': 'homard',
  'magpie': 'pie',
  'mango': 'mangue',
  'marathon': 'marathon',
  'meerkat': 'suricate',
  'melon': 'melon',
  'Merry go round': 'manège',
  'mole': 'taupe',
  'monkey': 'singe',
  'moon': 'lune',
  'mountain': 'montagne',
  'mouse': 'souris',
  'mushroom': 'champignon',
  'notebook': 'cahier',
  'ocarina': 'ocarina',
  'ocean': 'océan',
  'octopus': 'poulpe',
  'onion': 'oignon',
  'orange': 'orange',
  'orangutan': 'orang-outan',
  'orchestra': 'orchestre',
  'ostrich': 'autruche',
  'owl': 'hibou',
  'painter': 'peintre',
  'pants': 'pantalon',
  'parrot': 'perroquet',
  'parsley': 'persil',
  'peach': 'pêche',
  'peacock': 'paon',
  'pelican': 'pélican',
  'pencil': 'crayon',
  'penguin': 'pingouin',
  'pepper': 'poivre',
  'pharmacist': 'pharmacien',
  'piano': 'piano',
  'pickle': 'cornichon',
  'pig': 'cochon',
  'pigeon': 'pigeon',
  'pilot': 'pilote',
  'pineapple': 'ananas',
  'platypus': 'ornithorynque',
  'playground': 'aire de jeux',
  'policeman': 'policier',
  'pomegranate': 'grenade',
  'potato': 'pomme de terre',
  'principal': 'directeur',
  'professor': 'professeur',
  'pumpkin': 'citrouille',
  'rabbit': 'lapin',
  'raccoon': 'raton laveur',
  'rain': 'pluie',
  'restroom': 'toilettes',
  'rhino': 'rhinocéros',
  'river': 'rivière',
  'rock': 'rocher',
  'saxophone': 'saxophone',
  'scientist': 'scientifique',
  'seagull': 'mouette',
  'seal': 'phoque',
  'sesame': 'sésame',
  'shark': 'squalo',
  'sheep': 'pecora',
  'shirt': 'chemise',
  'singer': 'chanteur',
  'ski': 'ski',
  'skunk': 'moufette',
  'sky': 'ciel',
  'snail': 'escargot',
  'snake': 'serpent',
  'snow': 'neige',
  'snowboard': 'snowboard',
  'soccer': 'football',
  'socks': 'chaussettes',
  'soil': 'sol',
  'soldier': 'soldat',
  'space': 'espace',
  'sparrow': 'moineau',
  'spinach': 'épinard',
  'starfish': 'étoile de mer',
  'stewardess': 'hôtesse de l\'air',
  'stingray': 'razza',
  'strawberry': 'fragola',
  'sun': 'soleil',
  'subway': 'métro',
  'swallow': 'hirondelle',
  'sweater': 'pull',
  'swimming': 'natation',
  'swing': 'balançoire',
  'table': 'table',
  'tambourine': 'tambourin',
  'teacher': 'enseignant',
  'tiger': 'tigre',
  'timpani': 'timbales',
  'toad': 'crapaud',
  'trampoline': 'trampoline',
  'tree': 'arbre',
  'triangle': 'triangle',
  'truck': 'camion',
  'trumpet': 'trompette',
  'turtle': 'tortue',
  'typhoon': 'typhon',
  'unicorn': 'licorne',
  'violin': 'violon',
  'viking ship': 'drakkar',
  'volcano': 'volcan',
  'volleyball': 'volley-ball',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'cascade',
  'watermelon': 'pastèque',
  'wave': 'vague',
  'whale': 'baleine',
  'wind': 'vent',
  'window': 'fenêtre',
  'wolf': 'loup',
  'woodpecker': 'pic',
  'xylophone': 'xylophone',
  'yacht': 'yacht',
  'zebra': 'zèbre',
  'library': 'bibliothèque',
  'post office': 'bureau de poste',
  'traffic light': 'feu de circulation',
  'clock tower': 'tour d\'horloge',
  'pebble': 'caillou',
  'moss': 'mousse',
  'cactus': 'cactus',
  'rainbow': 'arc-en-ciel',
  'toast': 'toast',
  'cookie': 'biscuit',
  'ice cream': 'glace',
  'jelly': 'gelée',
  'writer': 'écrivain',
  'actor': 'acteur',
  'crown': 'couronne',
  'compass': 'boussole',
  'flowerpot': 'pot de fleurs',
  'roller skates': 'patins à roulettes',
  'airport': 'aéroport',
  'goldfish': 'poisson rouge',
  'spider': 'araignée',
  'light bulb': 'ampoule',
  'mirror': 'miroir',
  'magnet': 'aimant',
  'toothbrush': 'brosse à dents',
  'soap': 'savon',
  'plate': 'assiette',
  'spoon': 'cuillère',
  'mobile phone': 'téléphone portable',
  'key': 'clé',
  'newspaper': 'journal',
  'calendar': 'calendrier',
  'chair': 'chaise',
  'sofa': 'canapé',
  'refrigerator': 'réfrigérateur',
  'stairs': 'escalier',
  'pillow': 'oreiller',
  'candle': 'bougie',
  'bank': 'banque',
  'beetle': 'scarabée',
  'cicada': 'cigale',
  'dragonfly': 'libellule',
  'earthworm': 'ver de terre',
  'komodo dragon': 'dragon de komodo',
  'mantis': 'mante religieuse',
  'mosquito': 'moustique',
  'silkworm': 'ver à soie',
  'stag beetle': 'lucane cerf-volant',
  'table tennis': 'tennis de table',
  'train': 'train',
  'squid': 'calmar',
  'butterfly': 'papillon',
  'bee': 'abeille',
  'squirrel': 'écureuil',
  'nurse': 'infirmière',
  'slide': 'toboggan',
  'picnic': 'pique-nique',
  'jacket': 'veste',
  'shoes': 'chaussures',
  'tennis': 'tennis'
};