final Map<String, String> gujaratiItemList = {

  'accordian': 'એકોર્ડિયન',
  'airplane': 'વિમાન',
  'anaconda': 'એનાકોન્ડા',
  'ant': 'ચીંટી',
  'anteater': 'ચીંટી ખાવનાર',
  'apple': 'સફરજન',
  'apricot': 'અપ્રિકોટ',
  'archery': 'તીરંદાજી',
  'astronaut': 'અંતરિક્ષયાત્રી',
  'avocado': 'એવોકાડો',
  'badminton': 'બેડમિન્ટન',
  'banana': 'કેળું',
  'baseball': 'બેસબોલ',
  'basketball': 'બાસ્કેટબોલ',
  'bassoon': 'બેસૂન',
  'bat': 'ચમગાદડ',
  'beach': 'સાગર કિનારો',
  'bear': 'ભાલુ',
  'bicycle': 'સાયકલ',
  'blackboard': 'કાળો બોર્ડ',
  'blowfish': 'બ્લોફિશ',
  'blueberries': 'બ્લૂબેરી',
  'boar': 'જંગલી ડુક્કર',
  'book': 'પુસ્તક',
  'boots': 'બૂટ',
  'bowling': 'બોલિંગ',
  'boxing': 'બોક્સિંગ',
  'broccoli': 'બ્રોકોલી',
  'bumper car': 'બમ્પર કાર',
  'bus': 'બસ',
  'cabbage': 'પતાકોબી',
  'camel': 'ઉંટ',
  'carp': 'કાર્પ',
  'carpenter': 'તુંકુદાર',
  'carrot': 'ગાજર',
  'castanets': 'કાસ્ટાનેટ્સ',
  'cat': 'બિલ્લી',
  'cello': 'સેલ્લો',
  'chameleon': 'કેમેલિયન',
  'cheetah': 'ચીતા',
  'cherry': 'ચેરી',
  'chick': 'નાનો પોળટું',
  'chicken': 'કુકડું',
  'clarinet': 'ક્લેરિનેટ',
  'classroom': 'વર્ગખંડ',
  'cloud': 'મેઘ',
  'cobra': 'કોબ્રા',
  'coconut': 'નારિયળ',
  'computer': 'કમ્પ્યુટર',
  'conductor': 'કન્ડક્ટર',
  'contrabass': 'કોન્ટ્રાબાસ',
  'cook': 'રસોઈઆાળો',
  'corn': 'મકાઈ',
  'cow': 'ગાય',
  'crab': 'ક્રેબ',
  'crane': 'ક્રેન',
  'crocodile': 'મગર',
  'crow': 'કાગડો',
  'cucumber': 'કાકડી',
  'curling': 'કર્લિંગ',
  'cymbals': 'સિમ્બલ્સ',
  'deer': 'હરણ',
  'dentist': 'દંતચિકિત્સક',
  'desert': 'મરુભૂમિ',
  'doctor': 'ડોક્ટર',
  'dog': 'કૂતરો',
  'dolphin': 'ડોલ્ફિન',
  'drum': 'ઢોલ',
  'duck': 'બતાખ',
  'eagle': 'ગરુડ',
  'earthquake': 'ભૂકંપ',
  'elephant': 'હાથી',
  'exam': 'પરીક્ષા',
  'farmer': 'ખેડૂત',
  'fencing': 'ફેન્સિંગ',
  'ferris wheel': 'ફેરિસ વ્હીલ',
  'fig': 'અંજીર',
  'firefighter': 'અગ્નિશામક',
  'fisherman': 'માછીમાર',
  'flower': 'ફૂલ',
  'flute': 'બાંસરી',
  'fog': 'ધૂંધળું',
  'forest': 'વન',
  'fox': 'શિયાળ',
  'friend': 'મિત્ર',
  'frog': 'બેડક',
  'garlic': 'લસણ',
  'ginger': 'આદુ',
  'ginseng': 'જિન્સેંગ',
  'giraffe': 'જિરાફ',
  'gloves': 'ગ્લોવ્સ',
  'goat': 'મેક',
  'golf': 'ગોલ્ફ',
  'goose': 'હંસ',
  'gorilla': 'ગોરિલ્લા',
  'grape': 'દ્રાક્ષ',
  'grapefruit': 'ગ્રેપફ્રૂટ',
  'guitar': 'ગિટાર',
  'hairdressor': 'કેસ કાપનાર',
  'hallway': 'ગલી',
  'harmonica': 'હાર્મોનિકા',
  'harp': 'હાર્પ',
  'hat': 'ટોપી',
  'hawk': 'બાજ',
  'helicopter': 'હેલિકોપ્ટર',
  'hippo': 'હિપ્પોપોટેમસ',
  'hippocampus': 'હિપ્પોકેમ્પસ',
  'hockey': 'હોકી',
  'horse': 'ઘોડો',
  'hyena': 'હાયીના',
  'iceberg': 'આઇસબર્ગ',
  'iguana': 'ઇગુઆના',
  'jellyfish': 'જેલીફિશ',
  'judge': 'ન્યાયાધીશ',
  'judo': 'જૂડો',
  'jujube': 'જુજુબ',
  'jungle': 'જંગલ',
  'kangaroo': 'કંગરુ',
  'kiwi': 'કીવી',
  'koala': 'કોલા',
  'lake': 'તળાવ',
  'lemon': 'નિમ્બુ',
  'leopard': 'તेंदુઆ',
  'lettuce': 'લેટ્યૂસ',
  'lightning': 'વિજળીનો ઝપક',
  'lion': 'સિંહ',
  'lizard': 'છિપકળી',
  'lobster': 'લોબ્સ્ટર',
  'magpie': 'મેગપાઈ',
  'mango': 'આંબો',
  'marathon': 'મેરેથોન',
  'meerkat': 'મીરકૅટ',
  'melon': 'તરબૂચ',
  'Merry go round': 'મેરી ગો રાઉન્ડ',
  'mole': 'મોલ',
  'monkey': 'બંદર',
  'moon': 'ચંદ્ર',
  'mountain': 'પર્વત',
  'mouse': 'ઉંદર',
  'mushroom': 'મશરૂમ',
  'notebook': 'નોટબુક',
  'ocarina': 'ઓકારિના',
  'ocean': 'મહાસાગર',
  'octopus': 'ઓક્ટોપસ',
  'onion': 'ડુંગળી',
  'orange': 'નારંગી',
  'orangutan': 'ઓરેંગુટાન',
  'orchestra': 'ઓર્કેસ્ટ્રા',
  'ostrich': 'ઓસ્ટ્રિચ',
  'owl': 'ઉલૂ',
  'painter': 'ચિત્રકાર',
  'pants': 'પેન્ટ',
  'parrot': 'તોતા',
  'parsley': 'પાર્સ્લી',
  'peach': 'પીચ',
  'peacock': 'મયૂર',
  'pelican': 'પેલિકન',
  'pencil': 'પેન્સિલ',
  'penguin': 'પેંગ્વિન',
  'pepper': 'મરી',
  'pharmacist': 'ફાર્માસિસ્ટ',
  'piano': 'પિયાનો',
  'pickle': 'અચાર',
  'pig': 'પોરક',
  'pigeon': 'કબૂતર',
  'pilot': 'પાઈલટ',
  'pineapple': 'અન્નાસ',
  'platypus': 'પ્લાટિપસ',
  'playground': 'રમતનું મેદાન',
  'policeman': 'પોલીસ',
  'pomegranate': 'દાડમ',
  'potato': 'બટાકા',
  'principal': 'પ્રિન્સિપલ',
  'professor': 'પ્રોફેસર',
  'pumpkin': 'પમ્પકિન',
  'rabbit': 'ખરગોશ',
  'raccoon': 'રેકૂન',
  'rain': 'વરસાદ',
  'restroom': 'શૌચાલય',
  'rhino': 'રાઇનો',
  'river': 'નદી',
  'rock': 'પથ્થર',
  'saxophone': 'સૅક્સોફોન',
  'scientist': 'વિજ્ઞાનિક',
  'seagull': 'સમુદ્રપક્ષી',
  'seal': 'સીલ',
  'sesame': 'તલ',
  'shark': 'શાર્ક',
  'sheep': 'દેડ',
  'shirt': 'કમીજ',
  'singer': 'ગાયક',
  'ski': 'સ્કી',
  'skunk': 'સ્કંક',
  'sky': 'આકાશ',
  'snail': 'સ્નેલ',
  'snake': 'સાપ',
  'snow': 'બરફ',
  'snowboard': 'સ્નોબોર્ડ',
  'soccer': 'ફુટબોલ',
  'socks': 'મોજા',
  'soil': 'માટી',
  'soldier': 'સૈનિક',
  'space': 'અંતરિક્ષ',
  'sparrow': 'ચિરપટક',
  'spinach': 'પાલકોર',
  'starfish': 'તારામાછલી',
  'stewardess': 'સ્ટ્યુઅર્ડેસ',
  'stingray': 'સ્ટિંગરે',
  'strawberry': 'સ્ટ્રોબેરી',
  'sun': 'સૂર્ય',
  'subway': 'સબવે',
  'swallow': 'સ્વોલો',
  'sweater': 'સ્વેટર',
  'swimming': 'તરણ',
  'swing': 'દોલવું',
  'table': 'મેજ',
  'tambourine': 'ટેમ્બોરિન',
  'teacher': 'શિક્ષક',
  'tiger': 'વાઘ',
  'timpani': 'ટિમ્પાની',
  'toad': 'ટોડ',
  'trampoline': 'ટ્રામ્પોલિન',
  'tree': 'વೃક્ષ',
  'triangle': 'ત્રિકોણ',
  'truck': 'ટ્રક',
  'trumpet': 'ટ્રમ્પેટ',
  'turtle': 'કચ્છપ',
  'typhoon': 'તૂફાન',
  'unicorn': 'યૂનિકોર્ન',
  'violin': 'વાયોલિન',
  'viking ship': 'વાઇકિંગ શિપ',
  'volcano': 'અગ્નિ પર્વત',
  'volleyball': 'વોલીબોલ',
  'vuvuzela': 'વુવુઝેલા',
  'waterfall': 'ઝરણું',
  'watermelon': 'તરબૂચ',
  'wave': 'તરંગ',
  'whale': 'તીમિગલ',
  'wind': 'હવા',
  'window': 'જણલ',
  'wolf': 'વોલ્ફ',
  'woodpecker': 'વુડપેકર',
  'xylophone': 'જાઈલોફોન',
  'yacht': 'યાખ્ટ',
  'zebra': 'ઝેબ્રા',
  'library': 'પુસ્તકાલય',
  'post office': 'પોસ્ટ ઓફિસ',
  'traffic light': 'ટ્રાફિક લાઇટ',
  'clock tower': 'ઘડિયાળ ટાવર',
  'pebble': 'નાનો પથ્થર',
  'moss': 'શેવાળ',
  'cactus': 'કેક્ટસ',
  'rainbow': 'ઇન્દ્રધનુષ્ય',
  'toast': 'ટોસ્ટ',
  'cookie': 'કુકી',
  'ice cream': 'આઇસ ક્રીમ',
  'jelly': 'જેલી',
  'writer': 'લેખક',
  'actor': 'અભિનેતા',
  'crown': 'મુકુટ',
  'compass': 'કમ્પાસ',
  'flowerpot': 'ફૂલનો ઘડો',
  'roller skates': 'રોલર સ્કેટ',
  'airport': 'હવાઈ મથક',
  'goldfish': 'સોનાની માછલી',
  'spider': 'મકડી',
  'light bulb': 'લાઇટ બલ્બ',
  'mirror': 'અરીસો',
  'magnet': 'ચુંબક',
  'toothbrush': 'દાંત બ્રશ',
  'soap': 'સાબુ',
  'plate': 'પ્લેટ',
  'spoon': 'ચમચી',
  'mobile phone': 'મોબાઇલ ફોન',
  'key': 'ચાવી',
  'newspaper': 'અખબાર',
  'calendar': 'કેલેન્ડર',
  'chair': 'ખુરસી',
  'sofa': 'સોફા',
  'refrigerator': 'રેફ્રિજરેટર',
  'stairs': 'સીડી',
  'pillow': 'તકિયો',
  'candle': 'મીણબત્તી',
  'bank': 'બેંક',
  'beetle': 'વીલ્ડ',
  'cicada': 'સિકાડા',
  'dragonfly': 'ડ્રેગન ફ્લાય',
  'earthworm': 'ભૂમિ પુરુગ',
  'komodo dragon': 'કોમોડો ડ્રેગન',
  'mantis': 'મેન્ટિસ',
  'mosquito': 'મચ્છર',
  'silkworm': 'પટ પુરુગ',
  'stag beetle': 'સ્ટેગ બીટલ',
  'table tennis': 'ટેબલ ટેનિસ',
  'train': 'ટ્રેન',
  'squid': 'સ્ક્વિડ',
  'butterfly': 'ફૂદડી',
  'bee': 'મધમાખી',
  'squirrel': 'ખિસકોલી',
  'nurse': 'નર્સ',
  'slide': 'સ્લાઇડ',
  'picnic': 'પિકનિક',
  'jacket': 'જેકેટ',
  'shoes': 'જૂતા',
  'tennis': 'ટેનિસ'
};