final Map<String, String> hebrewItemList = {

  'accordian': 'אקורדיון',
  'airplane': 'מטוס',
  'anaconda': 'אנקונדה',
  'ant': 'נמלה',
  'anteater': 'אנט-איטר',
  'apple': 'תפוח',
  'apricot': 'משמש',
  'archery': 'קשתות',
  'astronaut': 'אסטרונאוט',
  'avocado': 'אבוקדו',
  'badminton': 'בדמינטון',
  'banana': 'בננה',
  'baseball': 'בייסבול',
  'basketball': 'כדורסל',
  'bassoon': 'בַּסוּן',
  'bat': 'עטלף',
  'beach': 'חוף',
  'bear': 'דוב',
  'bicycle': 'אופניים',
  'blackboard': 'לוח שחור',
  'blowfish': 'דג נפוח',
  'blueberries': 'אוכמניות',
  'boar': 'חזיר בר',
  'book': 'ספר',
  'boots': 'מגפיים',
  'bowling': 'בולינג',
  'boxing': 'בוקס',
  'broccoli': 'ברוקולי',
  'bumper car': 'מכונית מתנגשת',
  'bus': 'אוטובוס',
  'cabbage': 'כרוב',
  'camel': 'גמל',
  'carp': 'קרפ',
  'carpenter': 'נגר',
  'carrot': 'גזר',
  'castanets': 'קסטנטס',
  'cat': 'חתול',
  'cello': 'צ׳לו',
  'chameleon': 'זיקית',
  'cheetah': 'צ׳יטה',
  'cherry': 'דובדבן',
  'chick': 'גוזל',
  'chicken': 'תרנגולת',
  'clarinet': 'קלרינט',
  'classroom': 'כיתה',
  'cloud': 'ענן',
  'cobra': 'קוברה',
  'coconut': 'אגוז קוקוס',
  'computer': 'מחשב',
  'conductor': 'מנצח',
  'contrabass': 'קונטרבאס',
  'cook': 'טבח',
  'corn': 'תירס',
  'cow': 'פרה',
  'crab': 'שרטן',
  'crane': 'מנוף',
  'crocodile': 'קוקודיל',
  'crow': 'עורב',
  'cucumber': 'מלפפון',
  'curling': 'קרלינג',
  'cymbals': 'צימבילים',
  'deer': 'איל',
  'dentist': 'רופא שיניים',
  'desert': 'מדבר',
  'doctor': 'רופא',
  'dog': 'כלב',
  'dolphin': 'דולפין',
  'drum': 'תוף',
  'duck': 'ברווז',
  'eagle': 'עיט',
  'earthquake': 'רעידת אדמה',
  'elephant': 'פיל',
  'exam': 'מבחן',
  'farmer': 'חקלאי',
  'fencing': 'פנסינג',
  'ferris wheel': 'גלגל ענק',
  'fig': 'תאנה',
  'firefighter': 'כבאי',
  'fisherman': 'דייג',
  'flower': 'פרח',
  'flute': 'פלוט',
  'fog': 'ערפל',
  'forest': 'יער',
  'fox': 'שועל',
  'friend': 'חבר',
  'frog': 'צפרדע',
  'garlic': 'שום',
  'ginger': 'זנגביל',
  'ginseng': 'ג׳ינסנג',
  'giraffe': 'ג׳ירפה',
  'gloves': 'כפפות',
  'goat': 'עז',
  'golf': 'גולף',
  'goose': 'האנוס',
  'gorilla': 'גורילה',
  'grape': 'ענב',
  'grapefruit': 'גרייפפрут',
  'guitar': 'גיטרה',
  'hairdressor': 'מעצב שיער',
  'hallway': 'מסדרון',
  'harmonica': 'הרמוניקה',
  'harp': 'הארפ',
  'hat': 'כובע',
  'hawk': 'יָסְטְרֵב',
  'helicopter': 'מסוק',
  'hippo': 'היפופוטם',
  'hippocampus': 'היפוקמפוס',
  'hockey': 'הוקי',
  'horse': 'סוס',
  'hyena': 'היינה',
  'iceberg': 'אייסברג',
  'iguana': 'איגואנה',
  'jellyfish': 'מדוזה',
  'judge': 'שופט',
  'judo': 'ג׳ודו',
  'jujube': 'ג׳וג׳וב',
  'jungle': 'ג׳ונגל',
  'kangaroo': 'קנגורו',
  'kiwi': 'קיוי',
  'koala': 'קואלה',
  'lake': 'אגם',
  'lemon': 'לימון',
  'leopard': 'נמר',
  'lettuce': 'חסה',
  'lightning': 'ברק',
  'lion': 'אריה',
  'lizard': 'לטאה',
  'lobster': 'לובסטר',
  'magpie': 'מאגפאי',
  'mango': 'מנגו',
  'marathon': 'מרתון',
  'meerkat': 'מירקאט',
  'melon': 'מלון',
  'Merry go round': 'קרוסלה',
  'mole': 'מול',
  'monkey': 'קוף',
  'moon': 'ירח',
  'mountain': 'הר',
  'mouse': 'עכבר',
  'mushroom': 'פטריה',
  'notebook': 'מחברת',
  'ocarina': 'אוקרינה',
  'ocean': 'אוקיינוס',
  'octopus': 'תמנון',
  'onion': 'בצל',
  'orange': 'תפוז',
  'orangutan': 'אורנגוטן',
  'orchestra': 'תזמורת',
  'ostrich': 'שטרוס',
  'owl': 'ינשוף',
  'painter': 'צייר',
  'pants': 'מכנסיים',
  'parrot': 'תוכי',
  'parsley': 'פטרוזיליה',
  'peach': 'אפרסק',
  'peacock': 'טווס',
  'pelican': 'פליקן',
  'pencil': 'עפרון',
  'penguin': 'פינגווין',
  'pepper': 'פלפל',
  'pharmacist': 'פארמציסט',
  'piano': 'פסנתר',
  'pickle': 'מלפפון כבוש',
  'pig': 'חזיר',
  'pigeon': 'יונה',
  'pilot': 'טייס',
  'pineapple': 'אננס',
  'platypus': 'פלאטיפוס',
  'playground': 'מגרש משחקים',
  'policeman': 'שוטר',
  'pomegranate': 'רימון',
  'potato': 'תפוח אדמה',
  'principal': 'מנהל בית הספר',
  'professor': 'פרופסור',
  'pumpkin': 'דלעת',
  'rabbit': 'ארנב',
  'raccoon': 'ראקון',
  'rain': 'גשם',
  'restroom': 'שירותים',
  'rhino': 'קרנף',
  'river': 'נחל',
  'rock': 'סלע',
  'saxophone': 'סקסופון',
  'scientist': 'מדען',
  'seagull': 'שחף',
  'seal': 'כליליה',
  'sesame': 'שומשום',
  'shark': 'כריש',
  'sheep': 'כבש',
  'shirt': 'חולצה',
  'singer': 'זמר',
  'ski': 'סקי',
  'skunk': 'סקנק',
  'sky': 'שמיים',
  'snail': 'שבלול',
  'snake': 'נחש',
  'snow': 'שלג',
  'snowboard': 'סנובורד',
  'soccer': 'כדורגל',
  'socks': 'גרביים',
  'soil': 'אדמה',
  'soldier': 'חייל',
  'space': 'חלל',
  'sparrow': 'דרור',
  'spinach': 'תרד',
  'starfish': 'כוכב ים',
  'stewardess': 'דיילת',
  'stingray': 'סקט',
  'strawberry': 'תות',
  'sun': 'שמש',
  'subway': 'רכבת תחתית',
  'swallow': 'סוואלו',
  'sweater': 'סוודר',
  'swimming': 'שחייה',
  'swing': 'נדנדה',
  'table': 'שולחן',
  'tambourine': 'טמבורין',
  'teacher': 'מורה',
  'tiger': 'נמר',
  'timpani': 'טימפאני',
  'toad': 'צפרדע',
  'trampoline': 'טרמפולינה',
  'tree': 'עץ',
  'triangle': 'משולש',
  'truck': 'משאית',
  'trumpet': 'חצוצרה',
  'turtle': 'צב',
  'typhoon': 'טייפון',
  'unicorn': 'חד-קרן',
  'violin': 'כינור',
  'viking ship': 'ספינת וייקינג',
  'volcano': 'הר געש',
  'volleyball': 'וולי-בול',
  'vuvuzela': 'וובוזלה',
  'waterfall': 'מפל',
  'watermelon': 'אבטיח',
  'wave': 'גל',
  'whale': 'לוויתן',
  'wind': 'רוח',
  'window': 'חלון',
  'wolf': 'זאב',
  'woodpecker': 'וודפקר',
  'xylophone': 'קסילופון',
  'yacht': 'יאכטה',
  'zebra': 'זברה',
  'library': 'ספרייה',
  'post office': 'דואר',
  'traffic light': 'רמזור',
  'clock tower': 'מגדל שעון',
  'pebble': 'חלוק נחל',
  'moss': 'טחב',
  'cactus': 'קקטוס',
  'rainbow': 'קשת בענן',
  'toast': 'טוסט',
  'cookie': 'עוגייה',
  'ice cream': 'גלידה',
  'jelly': 'ריבה',
  'writer': 'סופר',
  'actor': 'שחקן',
  'crown': 'כתר',
  'compass': 'מצפן',
  'flowerpot': 'עציץ',
  'roller skates': 'גלגיליות',
  'airport': 'שדה תעופה',
  'goldfish': 'דג זהב',
  'spider': 'עכביש',
  'light bulb': 'נורה',
  'mirror': 'מראה',
  'magnet': 'מגנט',
  'toothbrush': 'מברשת שיניים',
  'soap': 'סבון',
  'plate': 'צלחת',
  'spoon': 'כפית',
  'mobile phone': 'טלפון נייד',
  'key': 'מפתח',
  'newspaper': 'עיתון',
  'calendar': 'לוח שנה',
  'chair': 'כיסא',
  'sofa': 'ספה',
  'refrigerator': 'מקרר',
  'stairs': 'מדרגות',
  'pillow': 'כרית',
  'candle': 'נר',
  'bank': 'בנק',
  'beetle': 'חיפושית',
  'cicada': 'צרצר',
  'dragonfly': 'שפירית',
  'earthworm': 'תולעת אדמה',
  'komodo dragon': 'דרקון קומודו',
  'mantis': 'גמל שלמה',
  'mosquito': 'יתוש',
  'silkworm': 'תולעת משי',
  'stag beetle': 'חיפושית איילים',
  'table tennis': 'טניס שולחן',
  'train': 'רכבת',
  'squid': 'דיונון',
  'butterfly': 'פרפר',
  'bee': 'דבורה',
  'squirrel': 'סנאי',
  'nurse': 'אחות',
  'slide': 'מגלשה',
  'picnic': 'פיקניק',
  'jacket': 'מעיל',
  'shoes': 'נעליים',
  'tennis': 'טניס'
};