final Map<String, String> hindiItemList = {

  'accordian': 'अकॉर्डियन',
  'airplane': 'हवाई जहाज़',
  'anaconda': 'एनाकोंडा',
  'ant': 'चींटी',
  'anteater': 'चींटीखोर',
  'apple': 'सेब',
  'apricot': 'खुबानी',
  'archery': 'तीरंदाजी',
  'astronaut': 'अंतरिक्ष यात्री',
  'avocado': 'एवोकाडो',
  'badminton': 'बैडमिंटन',
  'banana': 'केला',
  'baseball': 'बेसबॉल',
  'basketball': 'बास्केटबॉल',
  'bassoon': 'बैसून',
  'bat': 'चमगादड़',
  'beach': 'समुद्र तट',
  'bear': 'भालू',
  'bicycle': 'साइकिल',
  'blackboard': 'काला फलक',
  'blowfish': 'ब्लोफिश',
  'blueberries': 'ब्लूबेरी',
  'boar': 'जंगली सूअर',
  'book': 'किताब',
  'boots': 'बूट',
  'bowling': 'बॉलिंग',
  'boxing': 'मुक्केबाज़ी',
  'broccoli': 'ब्रोकली',
  'bumper car': 'बम्पर कार',
  'bus': 'बस',
  'cabbage': 'पत्तागोभी',
  'camel': 'ऊंट',
  'carp': 'कार्प',
  'carpenter': 'बढ़ई',
  'carrot': 'गाजर',
  'castanets': 'कैस्टनेट्स',
  'cat': 'बिल्ली',
  'cello': 'सेलो',
  'chameleon': 'गिरगिट',
  'cheetah': 'चीता',
  'cherry': 'चेरी',
  'chick': 'चूजा',
  'chicken': 'मुर्गी',
  'clarinet': 'क्लैरिनेट',
  'classroom': 'कक्षा',
  'cloud': 'बादल',
  'cobra': 'कोबरा',
  'coconut': 'नारियल',
  'computer': 'कंप्यूटर',
  'conductor': 'कंडक्टर',
  'contrabass': 'कॉन्ट्राबास',
  'cook': 'रसोइया',
  'corn': 'मक्का',
  'cow': 'गाय',
  'crab': 'केकड़ा',
  'crane': 'क्रेन',
  'crocodile': 'मगरमच्छ',
  'crow': 'कौवा',
  'cucumber': 'खीरा',
  'curling': 'करलिंग',
  'cymbals': 'झाँझ',
  'deer': 'हिरण',
  'dentist': 'दंत चिकित्सक',
  'desert': 'रेगिस्तान',
  'doctor': 'डॉक्टर',
  'dog': 'कुत्ता',
  'dolphin': 'डॉल्फिन',
  'drum': 'ढोल',
  'duck': 'बतख',
  'eagle': 'गरुड़',
  'earthquake': 'भूकंप',
  'elephant': 'हाथी',
  'exam': 'परीक्षा',
  'farmer': 'किसान',
  'fencing': 'फेंसिंग',
  'ferris wheel': 'फेरिस व्हील',
  'fig': 'अंजीर',
  'firefighter': 'दमकलकर्मी',
  'fisherman': 'मछुआरा',
  'flower': 'फूल',
  'flute': 'बांसुरी',
  'fog': 'कोहरा',
  'forest': 'जंगल',
  'fox': 'लोमड़ी',
  'friend': 'दोस्त',
  'frog': 'मेंढक',
  'garlic': 'लहसुन',
  'ginger': 'अदरक',
  'ginseng': 'जिनसेंग',
  'giraffe': 'जिराफ',
  'gloves': 'दस्ताने',
  'goat': 'बकरी',
  'golf': 'गॉल्फ',
  'goose': 'हंस',
  'gorilla': 'गोरिल्ला',
  'grape': 'अंगूर',
  'grapefruit': 'ग्रेपफ्रूट',
  'guitar': 'गिटार',
  'hairdressor': 'हेयरड्रेसर',
  'hallway': 'हॉलवे',
  'harmonica': 'हार्मोनिका',
  'harp': 'वीणा',
  'hat': 'टोपी',
  'hawk': 'बाज',
  'helicopter': 'हेलीकॉप्टर',
  'hippo': 'हिप्पोपोटामस',
  'hippocampus': 'हिप्पोकैम्पस',
  'hockey': 'हॉकी',
  'horse': 'घोड़ा',
  'hyena': 'हाइना',
  'iceberg': 'आइसबर्ग',
  'iguana': 'इगुआना',
  'jellyfish': 'जेलीफ़िश',
  'judge': 'न्यायाधीश',
  'judo': 'जूडो',
  'jujube': 'जूजूबी',
  'jungle': 'अरण्य',
  'kangaroo': 'कंगारू',
  'kiwi': 'कीवी',
  'koala': 'कोआला',
  'lake': 'झील',
  'lemon': 'नींबू',
  'leopard': 'तेंदुआ',
  'lettuce': 'लेटस',
  'lightning': 'बिजली',
  'lion': 'शेर',
  'lizard': 'छिपकली',
  'lobster': 'लोब्स्टर',
  'magpie': 'मैगपाई',
  'mango': 'आम',
  'marathon': 'मैरेथन',
  'meerkat': 'मीरकैट',
  'melon': 'खरबूजा',
  'Merry go round': 'घूमती सवारी',
  'mole': 'मोल',
  'monkey': 'बंदर',
  'moon': 'चाँद',
  'mountain': 'पहाड़',
  'mouse': 'चूहा',
  'mushroom': 'मशरूम',
  'notebook': 'नोटबुक',
  'ocarina': 'ओकारिना',
  'ocean': 'महासागर',
  'octopus': 'ऑक्टोपस',
  'onion': 'प्याज',
  'orange': 'संतरा',
  'orangutan': 'ओरंगुटान',
  'orchestra': 'वाद्यवृंद',
  'ostrich': 'शुतुरमुर्ग',
  'owl': 'उल्लू',
  'painter': 'चित्रकार',
  'pants': 'पैंट',
  'parrot': 'तोता',
  'parsley': 'पार्सले',
  'peach': 'आड़ू',
  'peacock': 'मोर',
  'pelican': 'पेलिकन',
  'pencil': 'पेंसिल',
  'penguin': 'पेंगुइन',
  'pepper': 'मिर्च',
  'pharmacist': 'औषधि विक्रेता',
  'piano': 'पियानो',
  'pickle': 'अचार',
  'pig': 'सुअर',
  'pigeon': 'कबूतर',
  'pilot': 'पायलट',
  'pineapple': 'अनानास',
  'platypus': 'प्लैटिपस',
  'playground': 'खेल का मैदान',
  'policeman': 'पुलिस वाला',
  'pomegranate': 'अनार',
  'potato': 'आलू',
  'principal': 'प्रधानाचार्य',
  'professor': 'प्रोफेसर',
  'pumpkin': 'कद्दू',
  'rabbit': 'खरगोश',
  'raccoon': 'रैकून',
  'rain': 'बारिश',
  'restroom': 'शौचालय',
  'rhino': 'गैंडा',
  'river': 'नदी',
  'rock': 'चट्टान',
  'saxophone': 'सैक्सोफोन',
  'scientist': 'वैज्ञानिक',
  'seagull': 'सीगल',
  'seal': 'सील',
  'sesame': 'तिल',
  'shark': 'शार्क',
  'sheep': 'भेड़',
  'shirt': 'कमीज़',
  'singer': 'गायक',
  'ski': 'स्की',
  'skunk': 'स्कंक',
  'sky': 'आकाश',
  'snail': 'घोंघा',
  'snake': 'साँप',
  'snow': 'बर्फ',
  'snowboard': 'स्नोबोर्ड',
  'soccer': 'फुटबॉल',
  'socks': 'मोजे',
  'soil': 'मिट्टी',
  'soldier': 'सैनिक',
  'space': 'अंतरिक्ष',
  'sparrow': 'गौरैया',
  'spinach': 'पालक',
  'starfish': 'तारा मछली',
  'stewardess': 'वेट्रेस',
  'stingray': 'स्टिंगरे',
  'strawberry': 'स्ट्रॉबेरी',
  'sun': 'सूरज',
  'subway': 'सबवे',
  'swallow': 'स्वैलो',
  'sweater': 'स्वेटर',
  'swimming': 'तैराकी',
  'swing': 'झूला',
  'table': 'मेज',
  'tambourine': 'टैम्बोरिन',
  'teacher': 'अध्यापक',
  'tiger': 'बाघ',
  'timpani': 'टिम्पानी',
  'toad': 'टोड',
  'trampoline': 'ट्रैम्पोलिन',
  'tree': 'वृक्ष',
  'triangle': 'त्रिकोण',
  'truck': 'ट्रक',
  'trumpet': 'ट्रंपेट',
  'turtle': 'कछुआ',
  'typhoon': 'तूफान',
  'unicorn': 'यूनिकॉर्न',
  'violin': 'वायलिन',
  'viking ship': 'वाइकिंग जहाज',
  'volcano': 'ज्वालामुखी',
  'volleyball': 'वॉलीबॉल',
  'vuvuzela': 'वुवुजेला',
  'waterfall': 'झरना',
  'watermelon': 'तरबूज',
  'wave': 'लहर',
  'whale': 'व्हेल',
  'wind': 'हवा',
  'window': 'खिड़की',
  'wolf': 'भेड़िया',
  'woodpecker': 'लकड़हारा पक्षी',
  'xylophone': 'ज़ाइलोफ़ोन',
  'yacht': 'यॉट',
  'zebra': 'ज़ेबरा',
  'library': 'पुस्तकालय',
  'post office': 'डाकघर',
  'traffic light': 'ट्रैफिक लाइट',
  'clock tower': 'घड़ी टावर',
  'pebble': 'छोटा पत्थर',
  'moss': 'काई',
  'cactus': 'कैक्टस',
  'rainbow': 'इंद्रधनुष',
  'toast': 'टोस्ट',
  'cookie': 'कुकी',
  'ice cream': 'आइसक्रीम',
  'jelly': 'जेली',
  'writer': 'लेखक',
  'actor': 'अभिनेता',
  'crown': 'मुकुट',
  'compass': 'कम्पास',
  'flowerpot': 'फूलों का गमला',
  'roller skates': 'रोलर स्केट',
  'airport': 'हवाई अड्डा',
  'goldfish': 'सुनहरी मछली',
  'spider': 'मकड़ी',
  'light bulb': 'बल्ब',
  'mirror': 'आईना',
  'magnet': 'चुंबक',
  'toothbrush': 'टूथब्रश',
  'soap': 'साबुन',
  'plate': 'प्लेट',
  'spoon': 'चम्मच',
  'mobile phone': 'मोबाइल फोन',
  'key': 'चाभी',
  'newspaper': 'अखबार',
  'calendar': 'कैलेंडर',
  'chair': 'कुर्सी',
  'sofa': 'सोफा',
  'refrigerator': 'फ्रिज',
  'stairs': 'सीढ़ी',
  'pillow': 'तकिया',
  'candle': 'मोमबत्ती',
  'bank': 'बैंक',
  'beetle': 'भटकाव',
  'cicada': 'सिकाडा',
  'dragonfly': 'ड्रैगनफ्लाई',
  'earthworm': 'केंचुआ',
  'komodo dragon': 'कोमोडो ड्रैगन',
  'mantis': 'मेंटिस',
  'mosquito': 'मच्छर',
  'silkworm': 'रेशम कृमि',
  'stag beetle': 'स्टैग बीटल',
  'table tennis': 'टेबल टेनिस',
  'train': 'ट्रेन',
  'squid': 'स्क्विड',
  'butterfly': 'तितली',
  'bee': 'शहद की मक्खी',
  'squirrel': 'गिलहरी',
  'nurse': 'नर्स',
  'slide': 'स्लाइड',
  'picnic': 'पिकनिक',
  'jacket': 'जैकेट',
  'shoes': 'जूते',
  'tennis': 'टेनिस'
};