final Map<String, String> kannadaItemList = {

  'accordian': 'ಅಕಾರ್ಡಿಯನ್',
  'airplane': 'ವಿಮಾನ',
  'anaconda': 'ಅನಕೊಂಡ',
  'ant': 'ಕೀಟ',
  'anteater': 'ಕೀಟಾಹಾರಿ',
  'apple': 'ಸೇಬು',
  'apricot': 'ಅಪ್ರಿಕಾಟ್',
  'archery': 'ಧನುಸ್ಸು ಬಳಕೆ',
  'astronaut': 'ಅಂತರಿಕ್ಷಯಾತ್ರಿಕ',
  'avocado': 'ಅವೊಕಾಡೊ',
  'badminton': 'ಬ್ಯಾಡ್ಮಿಂಟನ್',
  'banana': 'ಬಾಳೆಹಣ್ಣು',
  'baseball': 'ಬೇಸ್‌ಬಾಲ್',
  'basketball': 'ಬಾಸ್ಕೆಟ್‌ಬಾಲ್',
  'bassoon': 'ಬ್ಯಾಸೂನ್',
  'bat': 'ಚಮಗಾದಡ',
  'beach': 'ತೀರ',
  'bear': 'ಕರಡಿ',
  'bicycle': 'ಸೈಕಲ್',
  'blackboard': 'ಕಪ್ಪು ಬೋರ್ಡ್',
  'blowfish': 'ಬ್ಲೋಫಿಶ್',
  'blueberries': 'ನೀಲಿ ಹಣ್ಣುಗಳು',
  'boar': 'ಕಾಡು ಹಂದಿ',
  'book': 'ಪುಸ್ತಕ',
  'boots': 'ಬೂಟ್',
  'bowling': 'ಬೌಲಿಂಗ್',
  'boxing': 'ಬಾಕ್ಸಿಂಗ್',
  'broccoli': 'ಬ್ರೊಕೊಲಿ',
  'bumper car': 'ಬಂಪರ್ ಕಾರ್',
  'bus': 'ಬಸ್',
  'cabbage': 'ಕೊತ್ತಂಬರಿ ಸೊಪ್ಪು (ಕ್ಯಾಬೇಜ್)',
  'camel': 'ಒಂಟೆ',
  'carp': 'ಕಾರ್ಪ್',
  'carpenter': 'ತರಗತಿ ಕರ್ಮಿ',
  'carrot': 'ಗಾಜರ',
  'castanets': 'ಕ್ಯಾಸ್ಟನೆಟ್ಸ್',
  'cat': 'ಬೆಕ್ಕು',
  'cello': 'ಸೆಲ್ಲೋ',
  'chameleon': 'ಬದಲಾವಣೆಯ ಹಾವು',
  'cheetah': 'ಚೀತಾ',
  'cherry': 'ಚೆರ್ರಿ',
  'chick': 'ಕುಣ್ಡಿ ಹಕ್ಕಿ',
  'chicken': 'ಕೋಳಿ',
  'clarinet': 'ಕ್ಲಾರಿನೆಟ್',
  'classroom': 'ವರ್ಗಮನೆ',
  'cloud': 'ಮೇಘ',
  'cobra': 'ಕೋಬ್ರಾ',
  'coconut': 'ತೆಂಗು',
  'computer': 'ಕಂಪ್ಯೂಟರ್',
  'conductor': 'ಕಂಡಕ್ಟರ್',
  'contrabass': 'ಕಾಂಟ್ರಾಬಾಸ್',
  'cook': 'ಅಡುಗೆಗಾರ',
  'corn': 'ಮಕ್ಕಾಯಿ',
  'cow': 'ಗಾಯ',
  'crab': 'ರೆಕ್ಕು',
  'crane': 'ಕ್ರೇನ್',
  'crocodile': 'ಮಗರ್',
  'crow': 'ಕಾಗೆ',
  'cucumber': 'ದೋಸಕಾಯಿ',
  'curling': 'ಕರ್ಲಿಂಗ್',
  'cymbals': 'ಸಿಂಬಲ್ಸ್',
  'deer': 'ಮರಿ',
  'dentist': 'ದಂತ ವೈದ್ಯ',
  'desert': 'ಮರುಭೂಮಿ',
  'doctor': 'ವೈದ್ಯ',
  'dog': 'ನಾಯಿ',
  'dolphin': 'ಡಾಲ್ಫಿನ್',
  'drum': 'ಡ್ರಮ್',
  'duck': 'ಬಾತುಕ',
  'eagle': 'ಗಿರಡಿ',
  'earthquake': 'ಭೂಕಂಪ',
  'elephant': 'ಆನೆ',
  'exam': 'ಪರೀಕ್ಷೆ',
  'farmer': 'ಕೃಷಿಕ',
  'fencing': 'ರಕ್ಷಣಾ ಕ್ರೀಡೆ',
  'ferris wheel': 'ಫೆರಿಸ್ ವೀಲ್',
  'fig': 'ಅತ್ತಿಪಣ್ಣು',
  'firefighter': 'ಅಗ್ನಿಶಾಮಕ',
  'fisherman': 'ಮೀನುಗಾರ',
  'flower': 'ಹೂವು',
  'flute': 'ಮುರಳಿ',
  'fog': 'ಮಬ್ಬು',
  'forest': 'ಕಾಡು',
  'fox': 'ನರಿ',
  'friend': 'ಮಿತ್ರ',
  'frog': 'ಕಪ್ಪೆ',
  'garlic': 'ಬೆಳ್ಳುಳ್ಳಿ',
  'ginger': 'ಇಂಗು',
  'ginseng': 'ಜಿನ್ಸೆಂಗ್',
  'giraffe': 'ಜಿರಾಫೆ',
  'gloves': 'ಗ್ಲವ್ಸ್',
  'goat': 'ಮೇಕೆ',
  'golf': 'ಗಾಲ್ಫ್',
  'goose': 'ಹಂಸ',
  'gorilla': 'ಗೊರಿಲ್ಲಾ',
  'grape': 'ದ್ರಾಕ್ಷಿ',
  'grapefruit': 'ಗ್ರೇಪ್‌ಫ್ರೂಟ್',
  'guitar': 'ಗಿಟಾರ್',
  'hairdressor': 'ಕೇಶ ಉಡುಪು ಮಾಡುವವನು',
  'hallway': 'ಮಾರ್ಗ',
  'harmonica': 'ಹಾರ್ಮೋನಿಕ',
  'harp': 'ಹಾರ್ಪ್',
  'hat': 'ಟೊಪಿ',
  'hawk': 'ಹಾಕ್',
  'helicopter': 'ಹೆಲಿಕಾಪ್ಟರ್',
  'hippo': 'ಹಿಪ್ಪೊಪೋಟಾಮಸ್',
  'hippocampus': 'ಹಿಪ್ಪೋಕ್ಯಾಂಪಸ್',
  'hockey': 'ಹಾಕಿ',
  'horse': 'ಕುದುರೆ',
  'hyena': 'ಹೈಯೆನಾ',
  'iceberg': 'ಐಸ್‌ಬರ್ಗ್',
  'iguana': 'ಇಗುವಾನ',
  'jellyfish': 'ಜೆಲ್ಲಿಫಿಶ್',
  'judge': 'ನ್ಯಾಯಾಧೀಶ',
  'judo': 'ಜೂಡೋ',
  'jujube': 'ಜೂಜೂಬ್',
  'jungle': 'ಅರಣ್ಯ',
  'kangaroo': 'ಕ್ಯಾಂಗರು',
  'kiwi': 'ಕಿವಿ',
  'koala': 'ಕೊಆಲ',
  'lake': 'ಕೆರೆ',
  'lemon': 'ನಿಂಬು',
  'leopard': 'ತेंदುವ',
  'lettuce': 'ಲೆಟ್ಯೂಸ್',
  'lightning': 'ಮಿಂಚು',
  'lion': 'ಸಿಂಹ',
  'lizard': 'ಉಡುವ ಹಾವು',
  'lobster': 'ಲಾಬ್ಸ್ಟರ್',
  'magpie': 'ಮ್ಯಾಗ್‌ಪೈ',
  'mango': 'ಮಾವಿನಹಣ್ಣು',
  'marathon': 'ಮಾರಥಾನ್',
  'meerkat': 'ಮೀರಕ್ಯಾಟ್',
  'melon': 'ತರಬೂಚು',
  'Merry go round': 'ಚಕ್ರವಾತ',
  'mole': 'ಮೊಲ್',
  'monkey': 'ಕೋತಿ',
  'moon': 'ಚಂದ್ರ',
  'mountain': 'ಪರ್ವತ',
  'mouse': 'ಎಲಿಕ',
  'mushroom': 'ಅಣಬೆ',
  'notebook': 'ನೋಟ್‌ಬುಕ್',
  'ocarina': 'ಒಕಾರಿನ',
  'ocean': 'ಸಮುದ್ರ',
  'octopus': 'ಆಕ್ಟೋಪಸ್',
  'onion': 'ಉಳ್ಳಿಪಾಯಿ',
  'orange': 'ಕಿತ್ತಳೆ',
  'orangutan': 'ಓರೆಂಜುಟಾನ್',
  'orchestra': 'ಆರ್ಕೆಸ್ಟ್ರಾ',
  'ostrich': 'ಒಸ್ಟ್ರಿಚ್',
  'owl': 'ಗುಗುಲಿ ಹಕ್ಕಿ',
  'painter': 'ಚಿತ್ರಕಾರ',
  'pants': 'ಪ್ಯಾಂಟ್ಸ್',
  'parrot': 'ನಕ್ಕಿ',
  'parsley': 'ಪಾರ್ಸ್ಲಿ',
  'peach': 'ಪೀಚ್',
  'peacock': 'ಮಯೂರ',
  'pelican': 'ಪೆಲಿಕನ್',
  'pencil': 'ಪೆನ್ಸಿಲ್',
  'penguin': 'ಪೆಂಗ್ವಿನ್',
  'pepper': 'ಮೆಣಸು',
  'pharmacist': 'ಔಷಧ ಮಾರುವವನು',
  'piano': 'ಪಿಯಾನೋ',
  'pickle': 'ಅچار',
  'pig': 'ಹಂದಿ',
  'pigeon': 'ಗಬ್ಬ',
  'pilot': 'ಪೈಲಟ್',
  'pineapple': 'ಅನಾನಸ್',
  'platypus': 'ಪ್ಲಾಟಿಪಸ್',
  'playground': 'ಆಟದಂಗಣ',
  'policeman': 'ಪೋಲೀಸ್',
  'pomegranate': 'ದಾಳಿಂಬ',
  'potato': 'ಆಲೂಗಡ್ಡೆ',
  'principal': 'ಪ್ರಧಾನ ಅಧ್ಯಾಪಕ',
  'professor': 'ಪ್ರೊಫೆಸರ್',
  'pumpkin': 'ಕುಂಬಳಕಾಯಿ',
  'rabbit': 'ಖರಗೋಶ',
  'raccoon': 'ರಾಕೂನ್',
  'rain': 'ವರ್ಷೆ',
  'restroom': 'ಶೌಚಾಲಯ',
  'rhino': 'ಗಂಡೆ ಆನೆ',
  'river': 'ನದಿ',
  'rock': 'ಗುಂಡ',
  'saxophone': 'ಸ್ಯಾಕ್ಸೋಫೋನ್',
  'scientist': 'ವಿಜ್ಞಾನಿ',
  'seagull': 'ಸಮುದ್ರ ಹಕ್ಕಿ',
  'seal': 'ಸೀಲ್',
  'sesame': 'ಎಳ್ಳು',
  'shark': 'ಸರ್ಕ್',
  'sheep': 'ಮೇಕ್',
  'shirt': 'ಶರ್ಟ್',
  'singer': 'ಗಾಯಕ',
  'ski': 'ಸ್ಕೀ',
  'skunk': 'ಸ್ಕಂಕ್',
  'sky': 'ಆಕಾಶ',
  'snail': 'ಗಾಲಿಪಟಿ',
  'snake': 'ಪಾಮ்பு',
  'snow': 'ಹಿಮ',
  'snowboard': 'ಸ್ನೋಬೋರ್ಡ್',
  'soccer': 'ಫುಟ್‌ಬಾಲ್',
  'socks': 'ಮೋಜೆ',
  'soil': 'ಮಣ್ಣು',
  'soldier': 'ಸೈನಿಕ',
  'space': 'ಅಂತರಿಕ್ಷ',
  'sparrow': 'ಚಿಟ್ಟೆ',
  'spinach': 'ಆಲಿಪುಳಿ ಸೊಪ್ಪು',
  'starfish': 'ನಕ್ಷತ್ರ ಮೀನು',
  'stewardess': 'ಸ್ಟುವರ್ಡೆಸ್',
  'stingray': 'ಸ್ಟಿಂಗ್‌ರೇ',
  'strawberry': 'ಸ್ಟ್ರಾಬೆರಿ',
  'sun': 'ಸೂರ್ಯ',
  'subway': 'ಸಬ್‌ವೇ',
  'swallow': 'ನೀರಿನ ಹಕ್ಕಿ',
  'sweater': 'ಸ್ವೆಟರ್',
  'swimming': 'ಈರು', // "swimming" can be translated as "ತೇರು" as well.
  'swing': 'ದೋಣಿಯ',
  'table': 'ಮೆಜ್',
  'tambourine': 'ಟ್ಯಾಂಬೋರಿನ್',
  'teacher': 'ಗುರು',
  'tiger': 'ಹುಲಿ',
  'timpani': 'ಟಿಂಪಾನಿ',
  'toad': 'ಕಪ್ಪಲು',
  'trampoline': 'ಟ್ರಾಂಪೋಲಿನ್',
  'tree': 'ಮರವ',
  'triangle': 'ತ್ರಿಭುಜ',
  'truck': 'ಟ್ರಕ್',
  'trumpet': 'ಟ್ರಂಪೆಟ್',
  'turtle': 'ಆಮೆ',
  'typhoon': 'ತೂಫಾನ್',
  'unicorn': 'ಯೂನಿಕಾರ್ನ್',
  'violin': 'ವಯಲಿನ್',
  'viking ship': 'ವೈಕಿಂಗ್ ಹಡಗು',
  'volcano': 'ಅಗ್ನಿಪರ್ವತ',
  'volleyball': 'ವಾಲಿಬಾಲ್',
  'vuvuzela': 'ವುವುಝೆಲಾ',
  'waterfall': 'ಜಲಪಾತ',
  'watermelon': 'ತರಬೂಚು',
  'wave': 'ತರಂಗ',
  'whale': 'ತಿಮಿಂಗಿಲ',
  'wind': 'ಗಾಳಿ',
  'window': 'ಕಿಟಕಿ',
  'wolf': 'ವೃಕ್ಷಕ',
  'woodpecker': 'ಮರಹಕ್ಕಿ',
  'xylophone': 'ಜೈಲೋಫೋನ್',
  'yacht': 'ಯಾಚ್ಟ್',
  'zebra': 'ಜೆಬ್ರಾ',
  'library': 'ಗ್ರಂಥಾಲಯ',
  'post office': 'ಅಂಚೆ ಕಚೇರಿ',
  'traffic light': 'ಟ್ರಾಫಿಕ್ ಲೈಟ್',
  'clock tower': 'ಗಡಿಯಾರ ಗೋಪುರ',
  'pebble': 'ಸಣ್ಣ ಕಲ್ಲು',
  'moss': 'ಶೈವಾಲ',
  'cactus': 'ಕ್ಯಾಕ್ಟಸ್',
  'rainbow': 'ಮಳೆಬಿಲ್ಲು',
  'toast': 'ಟೋಸ್ಟ್',
  'cookie': 'ಕುಕಿ',
  'ice cream': 'ಐಸ್ ಕ್ರೀಮ್',
  'jelly': 'ಜೆಲ್ಲಿ',
  'writer': 'ಬರಹಗಾರ',
  'actor': 'ನಟ',
  'crown': 'ಮುಕುಟ',
  'compass': 'ದಿಕ್ಸೂಚಿ',
  'flowerpot': 'ಹೂವಿನ ಮಡಕೆ',
  'roller skates': 'ರೋಲರ್ ಸ್ಕೇಟ್',
  'airport': 'ವಿಮಾನ ನಿಲ್ದಾಣ',
  'goldfish': 'ಚಿನ್ನದ ಮೀನು',
  'spider': 'ಜೇಡ',
  'light bulb': 'ಲೈಟ್ ಬಲ್ಬ್',
  'mirror': 'ಕನ್ನಡಿ',
  'magnet': 'ಅಯಸ್ಕಾಂತ',
  'toothbrush': 'ದಂತ ಶುಚಿಗೊಳಿಸುವ',
  'soap': 'ಸಾಬೂನು',
  'plate': 'ಪ್ಲೇಟ್',
  'spoon': 'ಚಮಚ',
  'mobile phone': 'ಮೊಬೈಲ್ ಫೋನ್',
  'key': 'ಕೀಲಿ',
  'newspaper': 'ವೃತ್ತಪತ್ರಿಕೆ',
  'calendar': 'ಕ್ಯಾಲೆಂಡರ್',
  'chair': 'ಕುರ್ಚಿ',
  'sofa': 'ಸೋಫಾ',
  'refrigerator': 'ರೆಫ್ರಿಜರೇಟರ್',
  'stairs': 'ಮೆಟ್ಟಿಲುಗಳು',
  'pillow': 'ದಿಂಬು',
  'candle': 'ಮೇಣದಬತ್ತಿ',
  'bank': 'ಬ್ಯಾಂಕ್',
  'beetle': 'ವೀಲ್ಡ್',
  'cicada': 'ಸಿಕಾಡ',
  'dragonfly': 'ಡ್ರಾಗನ್ ಫ್ಲೈ',
  'earthworm': 'ಭೂಮಿ ಹುಳು',
  'komodo dragon': 'ಕೋಮೊಡೊ ಡ್ರಾಗನ್',
  'mantis': 'ಮಾಂಟಿಸ್',
  'mosquito': 'ಸೊಳ್ಳೆ',
  'silkworm': 'ರೇಷ್ಮೆ ಹುಳು',
  'stag beetle': 'ಸ್ಟ್ಯಾಗ್ ಬೀಟಲ್',
  'table tennis': 'ಟೇಬಲ್ ಟೆನ್ನಿಸ್',
  'train': 'ರೈಲು',
  'squid': 'ಸ್ಕ್ವಿಡ್',
  'butterfly': 'ಚಿಟ್ಟೆ',
  'bee': 'ಜೇನುಹುಳು',
  'squirrel': 'ಅಣ್ಣಾ',
  'nurse': 'ನರ್ಸ್',
  'slide': 'ಸ್ಲೈಡ್',
  'picnic': 'ಪಿಕ್ನಿಕ್',
  'jacket': 'ಜಾಕೆಟ್',
  'shoes': 'ಷೂಸ್',
  'tennis': 'ಟೆನ್ನಿಸ್'
};