final Map<String, String> malayalamItemList = {

  'accordian': 'അക്കോര്‍ഡിയന്‍',
  'airplane': 'വിമാനം',
  'anaconda': 'അനാകോണ്ട',
  'ant': 'ആന്‍റ്',
  'anteater': 'ആന്‍റ് ഈറ്റര്‍',
  'apple': 'ആപ്പിള്‍',
  'apricot': 'അപ്രിക്കോട്ട്',
  'archery': 'അമ്പുതിരി',
  'astronaut': 'അന്താരാഷ്ട്രയാത്രികന്‍',
  'avocado': 'അവോകാഡോ',
  'badminton': 'ബാഡ്‌മിന്റണ്‍',
  'banana': 'വാഴപ്പഴം',
  'baseball': 'ബേസ്ബോള്‍',
  'basketball': 'ബാസ്കറ്റ്ബോള്‍',
  'bassoon': 'ബാസൂണ്‍',
  'bat': 'ബാറ്റ്',
  'beach': 'കടല്‍ത്തീര്‍',
  'bear': 'കരടി',
  'bicycle': 'സൈക്കിൾ',
  'blackboard': 'കറുപ്പ് ബോര്‍ഡ്',
  'blowfish': 'ബ്ലോഫിഷ്',
  'blueberries': 'ബ്ലൂബെറിയുകള്‍',
  'boar': 'കാട്ടുപന്നി',
  'book': 'പുസ്തകം',
  'boots': 'ബൂട്ടുകള്‍',
  'bowling': 'ബോള്‍ിങ്',
  'boxing': 'ബോക്സിംഗ്',
  'broccoli': 'ബ്രോകോളി',
  'bumper car': 'ബമ്പര്‍ കാര്‍',
  'bus': 'ബസ്',
  'cabbage': 'കാബേജ്',
  'camel': 'ഉട്ട',
  'carp': 'കാര്‍പ്പ്',
  'carpenter': 'കാര്‍പന്റര്‍',
  'carrot': 'ക്യാരറ്റ്',
  'castanets': 'കാസ്റ്റാനെറ്റ്സ്',
  'cat': 'പൂച്ച',
  'cello': 'സെല്ലോ',
  'chameleon': 'ചാമലിയന്‍',
  'cheetah': 'ചീറ്റ',
  'cherry': 'ചെറി',
  'chick': 'ചിക്ക്',
  'chicken': 'കോഴി',
  'clarinet': 'ക്ലാരിനറ്റ്',
  'classroom': 'വിദ്യാലയ മുറി',
  'cloud': 'മേഘം',
  'cobra': 'കോബ്ര',
  'coconut': 'തേങ്ങ',
  'computer': 'കമ്പ്യൂട്ടര്‍',
  'conductor': 'കണ്ടക്ടര്‍',
  'contrabass': 'കൊണ്ട്രാബാസ്',
  'cook': 'അടുക്കന്‍',
  'corn': 'മക്ക',
  'cow': 'പശു',
  'crab': 'ക്രാബ്',
  'crane': 'ക്രെയിൻ',
  'crocodile': 'തിമിംഗലം',
  'crow': 'കാക്ക',
  'cucumber': 'വെള്ളരി',
  'curling': 'കര്‍ളിംഗ്',
  'cymbals': 'സിംബല്‍സ്',
  'deer': 'ജിങ്ക്',
  'dentist': 'ദന്തചികിത്സകന്‍',
  'desert': 'മരുഭൂമി',
  'doctor': 'ഡോക്ടര്‍',
  'dog': 'നായ',
  'dolphin': 'ഡോള്‍ഫിന്‍',
  'drum': 'തടം',
  'duck': 'താറാവ്',
  'eagle': 'ഇഗിള്‍',
  'earthquake': 'ഭൂകമ്പം',
  'elephant': 'ആന',
  'exam': 'പരീക്ഷ',
  'farmer': 'കർഷകൻ',
  'fencing': 'ഫെൻസിംഗ്',
  'ferris wheel': 'ഫെറിസ് വീൽ',
  'fig': 'അത്തിപ്പഴം',
  'firefighter': 'അഗ്നിശമനക്കാരൻ',
  'fisherman': 'മത്സ്യബന്ധൻ',
  'flower': 'പൂവ്',
  'flute': 'മുരളി',
  'fog': 'മൂടൽ',
  'forest': 'കാട്',
  'fox': 'ഫോക്സ്',
  'friend': 'സുഹൃത്ത്',
  'frog': 'തവിട്ട്',
  'garlic': 'വെളുത്തുള്ളി',
  'ginger': 'ഇഞ്ചി',
  'ginseng': 'ജിൻസെങ്',
  'giraffe': 'ജിറാഫ്',
  'gloves': 'ഗ്ലൗവ്സ്',
  'goat': 'ആട്',
  'golf': 'ഗോൾഫ്',
  'goose': 'ഹംസ്',
  'gorilla': 'ഗൊരില്ല',
  'grape': 'ദ്രാക്ഷി',
  'grapefruit': 'ഗ്രേപ്‌ഫ്രൂട്ട്',
  'guitar': 'ഗിറ്റാർ',
  'hairdressor': 'ഹെയർഡ്രസർ',
  'hallway': 'ഹാൾവേ',
  'harmonica': 'ഹാർമോണിക',
  'harp': 'ഹാർപ്',
  'hat': 'ടോപ്പി',
  'hawk': 'ഹോക്ക്',
  'helicopter': 'ഹെലികോപ്റ്റർ',
  'hippo': 'ഹിപ്പൊപോട്ടമസ്',
  'hippocampus': 'ഹിപ്പോകാമ്പസ്',
  'hockey': 'ഹോക്കി',
  'horse': 'കുതിര',
  'hyena': 'ഹൈയിന',
  'iceberg': 'ഐസ്‌ബര്‍ഗ್',
  'iguana': 'ഇഗ്വാന',
  'jellyfish': 'ജെല്ലിഫിഷ്',
  'judge': 'ന്യായാധിപൻ',
  'judo': 'ജൂഡോ',
  'jujube': 'ജൂജ്യൂബ്',
  'jungle': 'ജംഗിൾ',
  'kangaroo': 'കാംഗാറു',
  'kiwi': 'കിവി',
  'koala': 'കൊവാല',
  'lake': 'തേര്‍',
  'lemon': 'ലെമൺ',
  'leopard': 'ചീറ്റ',
  'lettuce': 'ലറ്റ്യൂസ്',
  'lightning': 'ഇലക്ട്രിക് മിന്നല്‍',
  'lion': 'സിംഹം',
  'lizard': 'ലിസാര്‍ഡ്',
  'lobster': 'ലോബ്സ്റ്റർ',
  'magpie': 'മാഗ്‌പൈ',
  'mango': 'മാംഗ',
  'marathon': 'മാരത്തോൺ',
  'meerkat': 'മീര്കാറ്റ്',
  'melon': 'മെലൻ',
  'Merry go round': 'മേരി ഗോ റൗണ്ട്',
  'mole': 'മോൾ',
  'monkey': 'കുരങ്ങ്',
  'moon': 'ചന്ദ്രൻ',
  'mountain': 'പർവതം',
  'mouse': 'എലി',
  'mushroom': 'കൂൺ',
  'notebook': 'നോട്ട്ബുക്ക്',
  'ocarina': 'ഓകരീന',
  'ocean': 'സമുദ്രം',
  'octopus': 'ഓക്ടോപസ്',
  'onion': 'വെങ്ങുപ്പായ്',
  'orange': 'ഓറഞ്ച്',
  'orangutan': 'ഓറങ്ങുട്ടാൻ',
  'orchestra': 'ഓർക്കസ്ട്ര',
  'ostrich': 'ഒസ്ട്രിച്ച്',
  'owl': 'ഓവല്‍',
  'painter': 'ചിത്രകാരൻ',
  'pants': 'പാന്റ്സ്',
  'parrot': 'പാരറ്റ്',
  'parsley': 'പാര്‍സ്ലി',
  'peach': 'പീച്ച്',
  'peacock': 'മയൂര്‍',
  'pelican': 'പെലിക്കൻ',
  'pencil': 'പെൻസിൽ',
  'penguin': 'പെംഗ്വിൻ',
  'pepper': 'മിരി',
  'pharmacist': 'ഫാർമസിസ്റ്റ്',
  'piano': 'പിയാനോ',
  'pickle': 'അച്ചാര്‍',
  'pig': 'പന്നി',
  'pigeon': 'കബുതർ',
  'pilot': 'പൈലറ്റ്',
  'pineapple': 'അന്നാസി',
  'platypus': 'പ്ലാറ്റിപസ്',
  'playground': 'കളിസ്ഥലം',
  'policeman': 'പോലീസ്',
  'pomegranate': 'മത്തളി',
  'potato': 'ഉരുളകിഴങ്ങ്',
  'principal': 'പ്രിൻസിപ്പാൾ',
  'professor': 'പ്രൊഫസർ',
  'pumpkin': 'കുമ്പളം',
  'rabbit': 'രാബിറ്റ്',
  'raccoon': 'റാക്കൂണ്‍',
  'rain': 'മഴ',
  'restroom': 'ശൌചാലയം',
  'rhino': 'ഗേതെ',
  'river': 'നദി',
  'rock': 'റോക്ക്',
  'saxophone': 'സാക്സോഫോൺ',
  'scientist': 'ശാസ്ത്രജ്ഞൻ',
  'seagull': 'കടൽ പක්ෂി',
  'seal': 'സീൽ',
  'sesame': 'എള്ളി',
  'shark': 'ശാർക്ക്',
  'sheep': 'മേട',
  'shirt': 'ഷർട്ട്',
  'singer': 'ഗായകൻ',
  'ski': 'സ്കീ',
  'skunk': 'സ്കങ്ക്',
  'sky': 'ആകാശം',
  'snail': 'സ്നെയിൽ',
  'snake': 'പാമ്പ്',
  'snow': 'മഞ്ഞ്',
  'snowboard': 'സ്നോബോർഡ്',
  'soccer': 'ഫുട്ബോൾ',
  'socks': 'സോക്സ്',
  'soil': 'മണ്ണ്',
  'soldier': 'സൈനികൻ',
  'space': 'അന്താരാഷ്ട്രം',
  'sparrow': 'സ്പാരോ',
  'spinach': 'കറിവേപ്പില',
  'starfish': 'നക്ഷത്ര മത്സ്യം',
  'stewardess': 'സ്റ്റുവാർഡസ്',
  'stingray': 'സ്റ്റിങ്ഗ്‌റേ',
  'strawberry': 'സ്ട്രോബെറി',
  'sun': 'സൂര്യൻ',
  'subway': 'സബ്‌വേ',
  'swallow': 'സ്വാലോ',
  'sweater': 'സ്വെറ്റർ',
  'swimming': 'ഈതം',
  'swing': 'സ്വിംഗ്',
  'table': 'മേശ',
  'tambourine': 'ടാംബോറിൻ',
  'teacher': 'അധ്യാപകൻ',
  'tiger': 'പുലി',
  'timpani': 'ടിംപാനി',
  'toad': 'തവള',
  'trampoline': 'ട്രാമ്പോളിൻ',
  'tree': 'മരം',
  'triangle': 'ത്രികോണം',
  'truck': 'ട്രക്ക്',
  'trumpet': 'ട്രമ്പറ്റ്',
  'turtle': 'കപ്പ',
  'typhoon': 'തുഫാൻ',
  'unicorn': 'യൂണികോൺ',
  'violin': 'വയോളിൻ',
  'viking ship': 'വൈകിങ്ങ് കപ്പൽ',
  'volcano': 'ജ്വാലാമുഖി',
  'volleyball': 'വോളിബോൾ',
  'vuvuzela': 'വുവുസെല',
  'waterfall': 'ജലപ്രപാതം',
  'watermelon': 'തണ്ണിമത്തിപ്പഴം',
  'wave': 'തരംഗം',
  'whale': 'തിമിംഗലൻ',
  'wind': 'കാറ്റ്',
  'window': 'ജന്നൽ',
  'wolf': 'വോള്ഫ്',
  'woodpecker': 'വുഡ്‌പേക്കർ',
  'xylophone': 'സൈലോഫോൺ',
  'yacht': 'യാച്ച്',
  'zebra': 'സെബ്ര',
  'library': 'ഗ്രന്ഥശാല',
  'post office': 'തപാൽ കാര്യാലയം',
  'traffic light': 'ട്രാഫിക് ലൈറ്റ്',
  'clock tower': 'ഘടികാര ഗോപുരം',
  'pebble': 'ചെറിയ കല്ല്',
  'moss': 'പായൽ',
  'cactus': 'കാക്റ്റസ്',
  'rainbow': 'മഴവില്ല്',
  'toast': 'വറുത്ത റൊട്ടി',
  'cookie': 'കുക്കി',
  'ice cream': 'ഐസ് ക്രീം',
  'jelly': 'ജെല്ലി',
  'writer': 'എഴുത്തുകാരൻ',
  'actor': 'നടൻ',
  'crown': 'കിരീടം',
  'compass': 'ദിശാസൂചി',
  'flowerpot': 'പൂവിന്റെ കുട്ട',
  'roller skates': 'റോളർ സ്കേറ്റ്',
  'airport': 'വിമാനത്താവളം',
  'goldfish': 'സ്വർണ്ണ മത്സ്യം',
  'spider': 'ചിലന്തി',
  'light bulb': 'ബൾബ്',
  'mirror': 'കണ്ണാടി',
  'magnet': 'കാന്തം',
  'toothbrush': 'പല്ലുത്തല',
  'soap': 'സോപ്പ്',
  'plate': 'പ്ലേറ്റ്',
  'spoon': 'കരണ്ടി',
  'mobile phone': 'മൊബൈൽ ഫോൺ',
  'key': 'ചാവി',
  'newspaper': 'വാർത്താപത്രം',
  'calendar': 'കലണ്ടർ',
  'chair': 'കസേര',
  'sofa': 'സോഫ',
  'refrigerator': 'റഫ്രിജറേറ്റർ',
  'stairs': 'പടികൾ',
  'pillow': 'തലയിണ',
  'candle': 'മെഴുകുതിരി',
  'bank': 'ബാങ്ക്',
  'beetle': 'വീട്ടിൽ',
  'cicada': 'സികാഡ',
  'dragonfly': 'ഡ്രാഗൺ ഫ്ലൈ',
  'earthworm': 'ഭൂമി പുരുഗ്',
  'komodo dragon': 'കോമോഡോ ഡ്രാഗൺ',
  'mantis': 'മാന്റിസ്',
  'mosquito': 'കൊതുക്',
  'silkworm': 'പട്ട് പുരുഗ്',
  'stag beetle': 'സ്റ്റാഗ് ബീറ്റിൽ',
  'table tennis': 'ടേബിൾ ടെന്നിസ്',
  'train': 'ട്രെയിൻ',
  'squid': 'സ്ക്വിഡ്',
  'butterfly': 'ചിത്രശലഭം',
  'bee': 'തേനീച്ച',
  'squirrel': 'അണ്ണാൻ',
  'nurse': 'നഴ്സ്',
  'slide': 'സ്ലൈഡ്',
  'picnic': 'പിക്നിക്',
  'jacket': 'ജാക്കറ്റ്',
  'shoes': 'ഷൂസ്',
  'tennis': 'ടെന്നിസ്'
};