final Map<String, String> malayItemList = {

  'accordian': 'akordion',
  'airplane': 'kapal terbang',
  'anaconda': 'anaconda',
  'ant': 'semut',
  'anteater': 'pemakan semut',
  'apple': 'epal',
  'apricot': 'aprikot',
  'archery': 'memanah',
  'astronaut': 'angkasawan',
  'avocado': 'avokado',
  'badminton': 'badminton',
  'banana': 'pisang',
  'baseball': 'basbol',
  'basketball': 'bola keranjang',
  'bassoon': 'bassun',
  'bat': 'kelawar',
  'beach': 'pantai',
  'bear': 'beruang',
  'bicycle': 'basikal',
  'blackboard': 'papan hitam',
  'blowfish': 'ikan buntal',
  'blueberries': 'beri biru',
  'boar': 'babi hutan',
  'book': 'buku',
  'boots': 'but',
  'bowling': 'bowling',
  'boxing': 'tinju',
  'broccoli': 'brokoli',
  'bumper car': 'kereta tumbuk',
  'bus': 'bas',
  'cabbage': 'kubis',
  'camel': 'unta',
  'carp': 'ikan karper',
  'carpenter': 'tukang kayu',
  'carrot': 'lobak merah',
  'castanets': 'kastanet',
  'cat': 'kucing',
  'cello': 'cello',
  'chameleon': 'bunglon',
  'cheetah': 'cheetah',
  'cherry': 'ceri',
  'chick': 'anak ayam',
  'chicken': 'ayam',
  'clarinet': 'klarinet',
  'classroom': 'bilik darjah',
  'cloud': 'awan',
  'cobra': 'kobra',
  'coconut': 'kelapa',
  'computer': 'komputer',
  'conductor': 'konduktor',
  'contrabass': 'kontrabass',
  'cook': 'tukang masak',
  'corn': 'jagung',
  'cow': 'lembu',
  'crab': 'ketam',
  'crane': 'bangau',
  'crocodile': 'buaya',
  'crow': 'gagak',
  'cucumber': 'timun',
  'curling': 'curling',
  'cymbals': 'simbal',
  'deer': 'rusa',
  'dentist': 'doktor gigi',
  'desert': 'padang pasir',
  'doctor': 'doktor',
  'dog': 'anjing',
  'dolphin': 'lumba-lumba',
  'drum': 'gendang',
  'duck': 'itik',
  'eagle': 'helang',
  'earthquake': 'gempa bumi',
  'elephant': 'gajah',
  'exam': 'peperiksaan',
  'farmer': 'petani',
  'fencing': 'fencing',
  'ferris wheel': 'roda ferris',
  'fig': 'buah ara',
  'firefighter': 'pemadam kebakaran',
  'fisherman': 'nelayan',
  'flower': 'bunga',
  'flute': 'seruling',
  'fog': 'kabut',
  'forest': 'hutan',
  'fox': 'rubah',
  'friend': 'kawan',
  'frog': 'katak',
  'garlic': 'bawang putih',
  'ginger': 'halia',
  'ginseng': 'ginseng',
  'giraffe': 'zirafah',
  'gloves': 'sarung tangan',
  'goat': 'kambing',
  'golf': 'golf',
  'goose': 'angsa',
  'gorilla': 'gorila',
  'grape': 'anggur',
  'grapefruit': 'limau bali',
  'guitar': 'gitar',
  'hairdressor': 'penata rambut',
  'hallway': 'lorong',
  'harmonica': 'harmonika',
  'harp': 'harpa',
  'hat': 'topi',
  'hawk': 'elang',
  'helicopter': 'helikopter',
  'hippo': 'kuda nil',
  'hippocampus': 'hippocampus',
  'hockey': 'hoki',
  'horse': 'kuda',
  'hyena': 'hyena',
  'iceberg': 'aisberg',
  'iguana': 'iguana',
  'jellyfish': 'ubur-ubur',
  'judge': 'hakim',
  'judo': 'judo',
  'jujube': 'jujube',
  'jungle': 'hutan belantara',
  'kangaroo': 'kanguru',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'tasik',
  'lemon': 'lemon',
  'leopard': 'harimau bintang',
  'lettuce': 'selada',
  'lightning': 'kilat',
  'lion': 'singa',
  'lizard': 'biawak',
  'lobster': 'lobster',
  'magpie': 'burung magpie',
  'mango': 'mangga',
  'marathon': 'maraton',
  'meerkat': 'meerkat',
  'melon': 'tembikai',
  'Merry go round': 'kereta putar',
  'mole': 'mole',
  'monkey': 'monyet',
  'moon': 'bulan',
  'mountain': 'gunung',
  'mouse': 'tikus',
  'mushroom': 'cendawan',
  'notebook': 'buku nota',
  'ocarina': 'okarina',
  'ocean': 'lautan',
  'octopus': 'gurita',
  'onion': 'bawang',
  'orange': 'oren',
  'orangutan': 'orang utan',
  'orchestra': 'orkestra',
  'ostrich': 'burung unta',
  'owl': 'burung hantu',
  'painter': 'pelukis',
  'pants': 'seluar',
  'parrot': 'burung kakak tua',
  'parsley': 'parsli',
  'peach': 'persik',
  'peacock': 'merak',
  'pelican': 'pelikan',
  'pencil': 'pensel',
  'penguin': 'pinguin',
  'pepper': 'lada',
  'pharmacist': 'ahli farmasi',
  'piano': 'piano',
  'pickle': 'acar',
  'pig': 'babi',
  'pigeon': 'merpati',
  'pilot': 'juruterbang',
  'pineapple': 'nanas',
  'platypus': 'platipus',
  'playground': 'taman permainan',
  'policeman': 'polis',
  'pomegranate': 'delima',
  'potato': 'kentang',
  'principal': 'pengetua',
  'professor': 'profesor',
  'pumpkin': 'labu',
  'rabbit': 'arnab',
  'raccoon': 'rakun',
  'rain': 'hujan',
  'restroom': 'tandas',
  'rhino': 'badak',
  'river': 'sungai',
  'rock': 'batu',
  'saxophone': 'saksophon',
  'scientist': 'ahli sains',
  'seagull': 'burung camar',
  'seal': 'anjing laut',
  'sesame': 'bijan',
  'shark': 'jerung',
  'sheep': 'domba',
  'shirt': 'baju',
  'singer': 'penyanyi',
  'ski': 'ski',
  'skunk': 'skunk',
  'sky': 'langit',
  'snail': 'siput',
  'snake': 'ular',
  'snow': 'salji',
  'snowboard': 'snowboard',
  'soccer': 'bola sepak',
  'socks': 'stokin',
  'soil': 'tanah',
  'soldier': 'askar',
  'space': 'angkasa',
  'sparrow': 'burung pipit',
  'spinach': 'bayam',
  'starfish': 'bintang laut',
  'stewardess': 'pramugari',
  'stingray': 'pari',
  'strawberry': 'stroberi',
  'sun': 'matahari',
  'subway': 'kereta api bawah tanah',
  'swallow': 'burung layang-layang',
  'sweater': 'sweater',
  'swimming': 'berenang',
  'swing': 'ayunan',
  'table': 'meja',
  'tambourine': 'tamborin',
  'teacher': 'guru',
  'tiger': 'harimau',
  'timpani': 'timpani',
  'toad': 'katak darat',
  'trampoline': 'trampolin',
  'tree': 'pokok',
  'triangle': 'segitiga',
  'truck': 'truk',
  'trumpet': 'terompet',
  'turtle': 'penyu',
  'typhoon': 'taufan',
  'unicorn': 'unicorn',
  'violin': 'biola',
  'viking ship': 'kapal Viking',
  'volcano': 'gunung berapi',
  'volleyball': 'bola tampar',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'air terjun',
  'watermelon': 'tembikai',
  'wave': 'ombak',
  'whale': 'paus',
  'wind': 'angin',
  'window': 'tingkap',
  'wolf': 'serigala',
  'woodpecker': 'burung pelatuk',
  'xylophone': 'xilofon',
  'yacht': 'yacht',
  'zebra': 'zebra',
  'library': 'perpustakaan',
  'post office': 'pejabat pos',
  'traffic light': 'lampu isyarat',
  'clock tower': 'menara jam',
  'pebble': 'batu kecil',
  'moss': 'lumut',
  'cactus': 'kaktus',
  'rainbow': 'pelangi',
  'toast': 'roti bakar',
  'cookie': 'biskut',
  'ice cream': 'ais krim',
  'jelly': 'jeli',
  'writer': 'penulis',
  'actor': 'pelakon',
  'crown': 'mahkota',
  'compass': 'kompas',
  'flowerpot': 'pasu bunga',
  'roller skates': 'kasut roda',
  'airport': 'lapangan terbang',
  'goldfish': 'ikan emas',
  'spider': 'labah-labah',
  'light bulb': 'mentol lampu',
  'mirror': 'cermin',
  'magnet': 'magnet',
  'toothbrush': 'sikat gigi',
  'soap': 'sabun',
  'plate': 'pinggan',
  'spoon': 'sudu',
  'mobile phone': 'telefon bimbit',
  'key': 'kunci',
  'newspaper': 'surat khabar',
  'calendar': 'kalendar',
  'chair': 'kerusi',
  'sofa': 'sofa',
  'refrigerator': 'peti sejuk',
  'stairs': 'tangga',
  'pillow': 'bantal',
  'candle': 'lilin',
  'bank': 'bank',
  'beetle': 'kumbang',
  'cicada': 'riang-riang',
  'dragonfly': 'capung',
  'earthworm': 'cacing tanah',
  'komodo dragon': 'komodo',
  'mantis': 'belalang sembah',
  'mosquito': 'nyamuk',
  'silkworm': 'ulat sutera',
  'stag beetle': 'kumbang tanduk',
  'table tennis': 'ping pong',
  'train': 'kereta api',
  'squid': 'cumi-cumi',
  'butterfly': 'kupu-kupu',
  'bee': 'lebah',
  'squirrel': 'tupai',
  'nurse': 'perawat',
  'slide': 'perosotan',
  'picnic': 'piknik',
  'jacket': 'jaket',
  'shoes': 'sepatu',
  'tennis': 'tenis'
};