final Map<String, String> marathiItemList = {

  'accordian': 'अकॉर्डियन',
  'airplane': 'विमान',
  'anaconda': 'अनाकोन्डा',
  'ant': 'अँट',
  'anteater': 'अँट खाणारा',
  'apple': 'सफरचंद',
  'apricot': 'अप्रिकॉट',
  'archery': 'तीरंदाजी',
  'astronaut': 'अंतराळवीर',
  'avocado': 'अवोकाडो',
  'badminton': 'बॅडमिंटन',
  'banana': 'केळी',
  'baseball': 'बेसबॉल',
  'basketball': 'बास्केटबॉल',
  'bassoon': 'बासून',
  'bat': 'चमगादळ',
  'beach': 'किनारा',
  'bear': 'करडा',
  'bicycle': 'सायकल',
  'blackboard': 'काळा फळक',
  'blowfish': 'ब्लोफिश',
  'blueberries': 'ब्लूबेरी',
  'boar': 'जंगली डुक्कर',
  'book': 'पुस्तक',
  'boots': 'बूट',
  'bowling': 'बोलिंग',
  'boxing': 'बॉक्सिंग',
  'broccoli': 'ब्रोकली',
  'bumper car': 'बम्पर कार',
  'bus': 'बस',
  'cabbage': 'कोबी',
  'camel': 'उंट',
  'carp': 'कार्प',
  'carpenter': 'सुतार',
  'carrot': 'गाजर',
  'castanets': 'कॅस्टॅनेट्स',
  'cat': 'मांजर',
  'cello': 'सेलो',
  'chameleon': 'चेमेलियन',
  'cheetah': 'चीत',
  'cherry': 'चेरी',
  'chick': 'पिल्ला',
  'chicken': 'कोळी',
  'clarinet': 'क्लैरिनेट',
  'classroom': 'वर्गखोली',
  'cloud': 'मेघ',
  'cobra': 'कोब्रा',
  'coconut': 'नारळ',
  'computer': 'संगणक',
  'conductor': 'कंडक्टेर',
  'contrabass': 'कोंट्राबास',
  'cook': 'स्वयंपाकी',
  'corn': 'भुट्टा',
  'cow': 'गाय',
  'crab': 'खिंबीर',
  'crane': 'क्रेन',
  'crocodile': 'मगर',
  'crow': 'कावळा',
  'cucumber': 'दोसर',
  'curling': 'करळिंग',
  'cymbals': 'झांझ',
  'deer': 'हरण',
  'dentist': 'दंतवैद्य',
  'desert': 'मरुभूमी',
  'doctor': 'डॉक्टर',
  'dog': 'कुत्रा',
  'dolphin': 'डॉल्फिन',
  'drum': 'ढोल',
  'duck': 'बत्तख',
  'eagle': 'गरुड',
  'earthquake': 'भूकंप',
  'elephant': 'हत्ती',
  'exam': 'परीक्षा',
  'farmer': 'शेतकरी',
  'fencing': 'फेन्सिंग',
  'ferris wheel': 'फेरिस व्हील',
  'fig': 'अंजीर',
  'firefighter': 'अग्निशामक',
  'fisherman': 'मच्छिमार',
  'flower': 'फुल',
  'flute': 'बांसरी',
  'fog': 'कुहासा',
  'forest': 'वन',
  'fox': 'कोल्हा',
  'friend': 'मित्र',
  'frog': 'बेडक',
  'garlic': 'लसूण',
  'ginger': 'आदू',
  'ginseng': 'जिनसेंग',
  'giraffe': 'जिराफ',
  'gloves': 'हातमोजे',
  'goat': 'बकरी',
  'golf': 'गोल्फ',
  'goose': 'हंस',
  'gorilla': 'गोरिल्ला',
  'grape': 'द्राक्ष',
  'grapefruit': 'ग्रेपफ्रूट',
  'guitar': 'गिटार',
  'hairdressor': 'केस कापणारा',
  'hallway': 'गल्ली',
  'harmonica': 'हार्मोनिका',
  'harp': 'हार्प',
  'hat': 'टोपी',
  'hawk': 'बाज',
  'helicopter': 'हेलिकॉप्टर',
  'hippo': 'हिप्पोपोटॅमस',
  'hippocampus': 'हिप्पोकॅम्पस',
  'hockey': 'हॉकी',
  'horse': 'घोडा',
  'hyena': 'हायना',
  'iceberg': 'आइसबर्ग',
  'iguana': 'इगुआना',
  'jellyfish': 'जेलीफिश',
  'judge': 'न्यायाधीश',
  'judo': 'जूडो',
  'jujube': 'जुझूब',
  'jungle': 'अरण्य',
  'kangaroo': 'कँगारू',
  'kiwi': 'कीवी',
  'koala': 'कोआला',
  'lake': 'सरोवर',
  'lemon': 'लिंबू',
  'leopard': 'तेंदुआ',
  'lettuce': 'सलाड पाने',
  'lightning': 'विद्युत झपाट',
  'lion': 'सिंह',
  'lizard': 'डागर',
  'lobster': 'लॉब्स्टर',
  'magpie': 'मॅगपाई',
  'mango': 'आंबा',
  'marathon': 'मॅरेथॉन',
  'meerkat': 'मीरकॅट',
  'melon': 'तरबूज',
  'Merry go round': 'फेरीची गाडी',
  'mole': 'मोल',
  'monkey': 'माकड',
  'moon': 'चंद्र',
  'mountain': 'डोंगर',
  'mouse': 'मासु',
  'mushroom': 'मशरूम',
  'notebook': 'नोटबुक',
  'ocarina': 'ओकारिना',
  'ocean': 'महासागर',
  'octopus': 'ऑक्टोपस',
  'onion': 'कांदा',
  'orange': 'संत्रं',
  'orangutan': 'ओरंगुटान',
  'orchestra': 'वाद्यवृंद',
  'ostrich': 'शुतुरमुर्ग',
  'owl': 'घुबड',
  'painter': 'चित्रकार',
  'pants': 'पॅंट्स',
  'parrot': 'तोता',
  'parsley': 'पार्सली',
  'peach': 'पीच',
  'peacock': 'मयूर',
  'pelican': 'पेलिकन',
  'pencil': 'पेन्सिल',
  'penguin': 'पेंग्विन',
  'pepper': 'मिरी',
  'pharmacist': 'औषध विक्रेता',
  'piano': 'पियानो',
  'pickle': 'आचार',
  'pig': 'डुक्कर',
  'pigeon': 'कबूतर',
  'pilot': 'पायलट',
  'pineapple': 'अननस',
  'platypus': 'प्लॅटिपस',
  'playground': 'खेळमैदानी',
  'policeman': 'पोलिस',
  'pomegranate': 'अनार',
  'potato': 'बटाटा',
  'principal': 'मुख्याध्यापक',
  'professor': 'प्राध्यापक',
  'pumpkin': 'भोपळा',
  'rabbit': 'ससा',
  'raccoon': 'रॅकून',
  'rain': 'पाऊस',
  'restroom': 'शौचालय',
  'rhino': 'गेंडा',
  'river': 'नदी',
  'rock': 'दगड',
  'saxophone': 'सॅक्सोफोन',
  'scientist': 'शास्त्रज्ञ',
  'seagull': 'समुद्री पक्षी',
  'seal': 'सील',
  'sesame': 'तिळ',
  'shark': 'शार्क',
  'sheep': 'मेंढी',
  'shirt': 'कमीज',
  'singer': 'गायक',
  'ski': 'स्की',
  'skunk': 'स्कंक',
  'sky': 'आकाश',
  'snail': 'घोंगडी',
  'snake': 'साप',
  'snow': 'हिम',
  'snowboard': 'स्नोबोर्ड',
  'soccer': 'फुटबॉल',
  'socks': 'मोजे',
  'soil': 'माती',
  'soldier': 'सैनिक',
  'space': 'अंतराळ',
  'sparrow': 'चिमणी',
  'spinach': 'पालक',
  'starfish': 'स्टारफिश',
  'stewardess': 'स्टूअर्डेस',
  'stingray': 'स्टिंगरे',
  'strawberry': 'स्ट्रॉबेरी',
  'sun': 'सूर्य',
  'subway': 'सबवे',
  'swallow': 'निगळणारा',
  'sweater': 'स्वेटर',
  'swimming': 'स्विमिंग',
  'swing': 'झुलणे',
  'table': 'टेबल',
  'tambourine': 'टॅम्बोरिन',
  'teacher': 'शिक्षक',
  'tiger': 'वाघ',
  'timpani': 'टिम्पानी',
  'toad': 'मेंढक',
  'trampoline': 'ट्रॅम्पोलिन',
  'tree': 'झाड',
  'triangle': 'त्रिकोण',
  'truck': 'ट्रक',
  'trumpet': 'ट्रंपेट',
  'turtle': 'कासव',
  'typhoon': 'तूफान',
  'unicorn': 'युनिकॉर्न',
  'violin': 'वायलिन',
  'viking ship': 'वाइकिंग जहाज',
  'volcano': 'ज्वालामुखी',
  'volleyball': 'व्हॉलीबॉल',
  'vuvuzela': 'वुवुझेला',
  'waterfall': 'धबधबा',
  'watermelon': 'तरबूज',
  'wave': 'तरंग',
  'whale': 'तोतळ',
  'wind': 'हवा',
  'window': 'खिडकी',
  'wolf': 'वुल्फ',
  'woodpecker': 'वुडपेकर',
  'xylophone': 'जायलोफोन',
  'yacht': 'यॉट',
  'zebra': 'झेब्रा',
  'library': 'ग्रंथालय',
  'post office': 'पोस्ट ऑफिस',
  'traffic light': 'ट्रॅफिक लाइट',
  'clock tower': 'घड्याळ टॉवर',
  'pebble': 'छोटा दगड',
  'moss': 'शेवाळ',
  'cactus': 'कॅक्टस',
  'rainbow': 'इंद्रधनुष्य',
  'toast': 'टोस्ट',
  'cookie': 'कुकी',
  'ice cream': 'आईस्क्रीम',
  'jelly': 'जेली',
  'writer': 'लेखक',
  'actor': 'अभिनेता',
  'crown': 'मुकुट',
  'compass': 'हवालदार',
  'flowerpot': 'फुलांचा घडा',
  'roller skates': 'रोलर स्केट',
  'airport': 'विमानतळ',
  'goldfish': 'सोन्याची मासे',
  'spider': 'कोळी',
  'light bulb': 'लाइट बल्ब',
  'mirror': 'आरसा',
  'magnet': 'चुंबक',
  'toothbrush': 'दातांचा ब्रश',
  'soap': 'साबण',
  'plate': 'प्लेट',
  'spoon': 'चमचा',
  'mobile phone': 'मोबाइल फोन',
  'key': 'चावी',
  'newspaper': 'वृत्तपत्र',
  'calendar': 'कॅलेंडर',
  'chair': 'खुर्ची',
  'sofa': 'सोफा',
  'refrigerator': 'रेफ्रिजरेटर',
  'stairs': 'पायऱ्या',
  'pillow': 'उशी',
  'candle': 'मेणबत्ती',
  'bank': 'बँक',
  'beetle': 'वील्ड',
  'cicada': 'सिकाडा',
  'dragonfly': 'ड्रॅगन फ्लाय',
  'earthworm': 'भूमि पुतळा',
  'komodo dragon': 'कोमोडो ड्रॅगन',
  'mantis': 'मेंटिस',
  'mosquito': 'डास',
  'silkworm': 'रेशम पुतळा',
  'stag beetle': 'स्टॅग बीटल',
  'table tennis': 'टेबल टेनिस',
  'train': 'रेलगाडी',
  'squid': 'स्क्विड',
  'butterfly': 'फुलपाखरू',
  'bee': 'मधमाशी',
  'squirrel': 'खिशकी',
  'nurse': 'नर्स',
  'slide': 'स्लाइड',
  'picnic': 'पिकनिक',
  'jacket': 'जॅकेट',
  'shoes': 'शूज',
  'tennis': 'टेनिस'
};