final Map<String, String> mongolianItemList = {

  'accordian': 'аккордеон',
  'airplane': 'онгоц',
  'anaconda': 'анаконда',
  'ant': 'хорхой',
  'anteater': 'хорхой идэгч',
  'apple': 'алим',
  'apricot': 'өрхөн',
  'archery': 'сум таг',
  'astronaut': 'сансар нисгэгч',
  'avocado': 'авокадо',
  'badminton': 'бадминтон',
  'banana': 'банан',
  'baseball': 'бейсбол',
  'basketball': 'баскетбол',
  'bassoon': 'басун',
  'bat': 'бат',
  'beach': 'далайн эрэг',
  'bear': 'баавгай',
  'bicycle': 'дугуй',
  'blackboard': 'хар самбар',
  'blowfish': 'блоуфиш',
  'blueberries': 'цэнхэр жимс',
  'boar': 'эрч гахай',
  'book': 'ном',
  'boots': 'цоб',
  'bowling': 'болинг',
  'boxing': 'бокс',
  'broccoli': 'брокколи',
  'bumper car': 'бумпер машин',
  'bus': 'автобус',
  'cabbage': 'капуста',
  'camel': 'үмт',
  'carp': 'карп',
  'carpenter': 'чинхүүрчин',
  'carrot': 'морковь',
  'castanets': 'кастанетс',
  'cat': 'муур',
  'cello': 'чело',
  'chameleon': 'хамелеон',
  'cheetah': 'чита',
  'cherry': 'черешня',
  'chick': 'пилт',
  'chicken': 'тахиа',
  'clarinet': 'кларинет',
  'classroom': 'анги',
  'cloud': 'үлэг',
  'cobra': 'кобра',
  'coconut': 'кокос',
  'computer': 'компьютер',
  'conductor': 'диригент',
  'contrabass': 'контрабас',
  'cook': 'хоолчин',
  'corn': 'маис',
  'cow': 'үхэр',
  'crab': 'краб',
  'crane': 'крана',
  'crocodile': 'крокодил',
  'crow': 'хархаг',
  'cucumber': 'огурец',
  'curling': 'керлинг',
  'cymbals': 'симбал',
  'deer': 'олень',
  'dentist': 'шүд эмч',
  'desert': 'цөл',
  'doctor': 'эмч',
  'dog': 'нохой',
  'dolphin': 'делфин',
  'drum': 'дарим',
  'duck': 'дак',
  'eagle': 'бургэд',
  'earthquake': 'газрын сэглээ',
  'elephant': 'хонь',
  'exam': 'шалгалт',
  'farmer': 'фермер',
  'fencing': 'фенсинг',
  'ferris wheel': 'феррис дугуй',
  'fig': 'инжир',
  'firefighter': 'гал унтраагч',
  'fisherman': 'загасчин',
  'flower': 'эцэг',
  'flute': 'флейта',
  'fog': 'үүл',
  'forest': 'ой',
  'fox': 'өлгий',
  'friend': 'найз',
  'frog': 'тохой',
  'garlic': 'сонгино',
  'ginger': 'имбир',
  'ginseng': 'женшен',
  'giraffe': 'жираф',
  'gloves': 'гарийн бүүмс',
  'goat': 'маз',
  'golf': 'гольф',
  'goose': 'ангас',
  'gorilla': 'горилла',
  'grape': 'үзэм',
  'grapefruit': 'грейпфрут',
  'guitar': 'гитара',
  'hairdressor': 'үс засагч',
  'hallway': 'галерея',
  'harmonica': 'хармоник',
  'harp': 'харп',
  'hat': 'малгай',
  'hawk': 'хангар',
  'helicopter': 'хеликоптер',
  'hippo': 'хиппопотам',
  'hippocampus': 'хиппокампус',
  'hockey': 'хоккей',
  'horse': 'морь',
  'hyena': 'хайена',
  'iceberg': 'айсберг',
  'iguana': 'игуана',
  'jellyfish': 'желе загас',
  'judge': 'шүүгч',
  'judo': 'дзюдо',
  'jujube': 'джуджуб',
  'jungle': 'джунгл',
  'kangaroo': 'кэнгару',
  'kiwi': 'киви',
  'koala': 'коала',
  'lake': 'нуур',
  'lemon': 'лимон',
  'leopard': 'леопард',
  'lettuce': 'салат',
  'lightning': 'цохилт',
  'lion': 'арыслан',
  'lizard': 'лизард',
  'lobster': 'лобстер',
  'magpie': 'магпай',
  'mango': 'манго',
  'marathon': 'марафон',
  'meerkat': 'миркэт',
  'melon': 'дыня',
  'Merry go round': 'карусель',
  'mole': 'мол',
  'monkey': 'саван',
  'moon': 'сар',
  'mountain': 'уул',
  'mouse': 'хулгана',
  'mushroom': 'мәшрум',
  'notebook': 'зошит',
  'ocarina': 'окарина',
  'ocean': 'тэнгис',
  'octopus': 'октопус',
  'onion': 'сонгино',
  'orange': 'апельсин',
  'orangutan': 'орангутан',
  'orchestra': 'оркестр',
  'ostrich': 'ност',
  'owl': 'филин',
  'painter': 'зурагч',
  'pants': 'пантс',
  'parrot': 'парарт',
  'parsley': 'петрушка',
  'peach': 'пич',
  'peacock': 'павиан',
  'pelican': 'пеликан',
  'pencil': 'пэнсил',
  'penguin': 'пингвин',
  'pepper': 'перец',
  'pharmacist': 'фармацевт',
  'piano': 'пиано',
  'pickle': 'ассар',
  'pig': 'порка',
  'pigeon': 'кбүүтар',
  'pilot': 'пилот',
  'pineapple': 'ананас',
  'platypus': 'платипус',
  'playground': 'тохлоом талбай',
  'policeman': 'цагдаа',
  'pomegranate': 'нар',
  'potato': 'картошка',
  'principal': 'багшийн дарга',
  'professor': 'профессор',
  'pumpkin': 'хүрш',
  'rabbit': 'занган',
  'raccoon': 'ракун',
  'rain': 'бороо',
  'restroom': 'угаалгын өрөө',
  'rhino': 'носорог',
  'river': 'мэл',
  'rock': 'чулуу',
  'saxophone': 'саксафон',
  'scientist': 'эрдэмтэн',
  'seagull': 'далайн шувуу',
  'seal': 'силинг',
  'sesame': 'тал',
  'shark': 'акула',
  'sheep': 'овог',
  'shirt': 'цамц',
  'singer': 'дуучин',
  'ski': 'ски',
  'skunk': 'сканк',
  'sky': 'тэнгэр',
  'snail': 'пууж',
  'snake': 'змей',
  'snow': 'цас',
  'snowboard': 'сноуборд',
  'soccer': 'футбол',
  'socks': 'носки',
  'soil': 'гүнд',
  'soldier': 'цэрэг',
  'space': 'сансар',
  'sparrow': 'воробей',
  'spinach': 'шпинат',
  'starfish': 'морска звезда',
  'stewardess': 'стюардесса',
  'stingray': 'скат',
  'strawberry': 'клубника',
  'sun': 'нар',
  'subway': 'метро',
  'swallow': 'ласточка',
  'sweater': 'свитер',
  'swimming': 'плавалт',
  'swing': 'дуулгал',
  'table': 'ширээ',
  'tambourine': 'тамбурин',
  'teacher': 'багш',
  'tiger': 'пули',
  'timpani': 'тимпани',
  'toad': 'тоад',
  'trampoline': 'трамполин',
  'tree': 'мод',
  'triangle': 'хориг',
  'truck': 'трактор',
  'trumpet': 'трампет',
  'turtle': 'хлоп',
  'typhoon': 'тофун',
  'unicorn': 'юникорн',
  'violin': 'виолин',
  'viking ship': 'вайкингийн хөлөг онгоц',
  'volcano': 'галын уул',
  'volleyball': 'волейбол',
  'vuvuzela': 'вувузела',
  'waterfall': 'водопад',
  'watermelon': 'арбуз',
  'wave': 'далайн долги',
  'whale': 'кит',
  'wind': 'салхи',
  'window': 'цонх',
  'wolf': 'чоно',
  'woodpecker': 'мод сүйэгч',
  'xylophone': 'ксилофон',
  'yacht': 'яхта',
  'zebra': 'зебра',
  'library': 'номын сан',
  'post office': 'шуудан',
  'traffic light': 'гэрэл дохио',
  'clock tower': 'цагийн цамхаг',
  'pebble': 'чулуу',
  'moss': 'хөвд',
  'cactus': 'кактус',
  'rainbow': 'солонго',
  'toast': 'тост',
  'cookie': 'жигнэмэг',
  'ice cream': 'цэцгийн мэс',
  'jelly': 'желе',
  'writer': 'зохиолч',
  'actor': 'жүжигчин',
  'crown': 'титэм',
  'compass': 'компас',
  'flowerpot': 'цэцгийн сав',
  'roller skates': 'гулгадаг тэшүүр',
  'airport': 'нисэх буудал',
  'goldfish': 'алтан загас',
  'spider': 'аалз',
  'light bulb': 'гэрэл',
  'mirror': 'толь',
  'magnet': 'соронз',
  'toothbrush': 'шүдний сойз',
  'soap': 'саван',
  'plate': 'таваг',
  'spoon': 'халбага',
  'mobile phone': 'гар утас',
  'key': 'түлхүүр',
  'newspaper': 'сонин',
  'calendar': 'хуанли',
  'chair': 'сандал',
  'sofa': 'буйдан',
  'refrigerator': 'хөргөгч',
  'stairs': 'шат',
  'pillow': 'дэр',
  'candle': 'лаа',
  'bank': 'банк',
  'beetle': 'хорхой',
  'cicada': 'шувуу',
  'dragonfly': 'хуурай',
  'earthworm': 'хөрсний хорхой',
  'komodo dragon': 'комодо луу',
  'mantis': 'самар',
  'mosquito': 'шумуул',
  'silkworm': 'торгоны хорхой',
  'stag beetle': 'буга хорхой',
  'table tennis': 'ширээний теннис',
  'train': 'галт тэрэг',
  'squid': 'кальмар',
  'butterfly': 'эрвээхэй',
  'bee': 'зөгий',
  'squirrel': 'хэрэм',
  'nurse': 'сувилагч',
  'slide': 'гулгадаг',
  'picnic': 'пикник',
  'jacket': 'хүрэм',
  'shoes': 'гутал',
  'tennis': 'тенис'
};