final Map<String, String> persianItemList = {

  'accordian': 'آکاردئون',
  'airplane': 'هواپیما',
  'anaconda': 'آناکوندا',
  'ant': 'مورچه',
  'anteater': 'مورچه‌خوار',
  'apple': 'سیب',
  'apricot': 'زردآلو',
  'archery': 'تیراندازی با کمان',
  'astronaut': 'فضانورد',
  'avocado': 'آووکادو',
  'badminton': 'بدمینتون',
  'banana': 'موز',
  'baseball': 'بیسبال',
  'basketball': 'بسکتبال',
  'bassoon': 'باسون',
  'bat': 'خفاش',
  'beach': 'ساحل',
  'bear': 'خرس',
  'bicycle': 'دوچرخه',
  'blackboard': 'تخته سیاه',
  'blowfish': 'ماهی بادکنکی',
  'blueberries': 'بلوبری',
  'boar': 'گراز',
  'book': 'کتاب',
  'boots': 'چکمه',
  'bowling': 'بولینگ',
  'boxing': 'بوکس',
  'broccoli': 'کلم بروکلی',
  'bumper car': 'ماشین برخوردی',
  'bus': 'اتوبوس',
  'cabbage': 'کلم',
  'camel': 'شتر',
  'carp': 'کارپ',
  'carpenter': 'نجار',
  'carrot': 'هویج',
  'castanets': 'کستانتس',
  'cat': 'گربه',
  'cello': 'چلو',
  'chameleon': 'کاملیون',
  'cheetah': 'یوزپلنگ',
  'cherry': 'گیلاس',
  'chick': 'جوجه',
  'chicken': 'مرغ',
  'clarinet': 'کلارینت',
  'classroom': 'اتاق کلاس',
  'cloud': 'ابر',
  'cobra': 'کوبرا',
  'coconut': 'نارگیل',
  'computer': 'کامپیوتر',
  'conductor': 'رهبر ارکستر',
  'contrabass': 'کنترا باس',
  'cook': 'آشپز',
  'corn': 'ذرت',
  'cow': 'گاو',
  'crab': 'خرچنگ',
  'crane': 'مَنُوف',
  'crocodile': 'مگرمَچھ',
  'crow': 'کلاغ',
  'cucumber': 'خیار',
  'curling': 'کرلینگ',
  'cymbals': 'سیمبال',
  'deer': 'گوزن',
  'dentist': 'دندانپزشک',
  'desert': 'بیابان',
  'doctor': 'دکتر',
  'dog': 'سگ',
  'dolphin': 'دلفین',
  'drum': 'طبل',
  'duck': 'اردک',
  'eagle': 'عقاب',
  'earthquake': 'زلزله',
  'elephant': 'فیل',
  'exam': 'امتحان',
  'farmer': 'کشاورز',
  'fencing': 'شمشیربازی',
  'ferris wheel': 'چرخ و فلک',
  'fig': 'انجیر',
  'firefighter': 'آتش‌نشان',
  'fisherman': 'ماهیگیر',
  'flower': 'گل',
  'flute': 'فلوت',
  'fog': 'مه',
  'forest': 'جنگل',
  'fox': 'روباه',
  'friend': 'دوست',
  'frog': 'قورباغه',
  'garlic': 'سیر',
  'ginger': 'زنجفیل',
  'ginseng': 'جینسینگ',
  'giraffe': 'زرافه',
  'gloves': 'دستکش',
  'goat': 'بز',
  'golf': 'گالف',
  'goose': 'غاز',
  'gorilla': 'گوریل',
  'grape': 'انگور',
  'grapefruit': 'گریپ‌فروت',
  'guitar': 'گیتار',
  'hairdressor': 'آرایشگر',
  'hallway': 'راهرو',
  'harmonica': 'هارمونیکا',
  'harp': 'هارپ',
  'hat': 'کلاه',
  'hawk': 'شاهین',
  'helicopter': 'هلیکوپتر',
  'hippo': 'اسب آبی',
  'hippocampus': 'هیپوکامپس',
  'hockey': 'هاکی',
  'horse': 'اسب',
  'hyena': 'هایانا',
  'iceberg': 'آیسبرگ',
  'iguana': 'ایگوانا',
  'jellyfish': 'عروس دریایی',
  'judge': 'قاضی',
  'judo': 'جودو',
  'jujube': 'جوجوب',
  'jungle': 'جنگل',
  'kangaroo': 'کنگورو',
  'kiwi': 'کیوی',
  'koala': 'کوآلا',
  'lake': 'دریاچه',
  'lemon': 'لیمو',
  'leopard': 'پلنگ',
  'lettuce': 'کاهو',
  'lightning': 'صاعقه',
  'lion': 'شیر',
  'lizard': 'مارمولک',
  'lobster': 'لابستر',
  'magpie': 'مگپای',
  'mango': 'انبه',
  'marathon': 'ماراتن',
  'meerkat': 'میریکت',
  'melon': 'خربزه',
  'Merry go round': 'مری گو راند',
  'mole': 'مول',
  'monkey': 'میمون',
  'moon': 'ماه',
  'mountain': 'کوه',
  'mouse': 'موش',
  'mushroom': 'قارچ',
  'notebook': 'دفترچه',
  'ocarina': 'اوکارینا',
  'ocean': 'مهاساغر',
  'octopus': 'اختاپوس',
  'onion': 'پیاز',
  'orange': 'پرتقال',
  'orangutan': 'اورانگوتان',
  'orchestra': 'ارکستر',
  'ostrich': 'شترمرغ',
  'owl': 'ינשוף',
  'painter': 'نقاش',
  'pants': 'شلوار',
  'parrot': 'طوطی',
  'parsley': 'جعفری',
  'peach': 'هلو',
  'peacock': 'طاووس',
  'pelican': 'پلیکان',
  'pencil': 'مداد',
  'penguin': 'پنگوئن',
  'pepper': 'فلفل',
  'pharmacist': 'داروساز',
  'piano': 'پیانو',
  'pickle': 'آچار',
  'pig': 'خوک',
  'pigeon': 'کبوتر',
  'pilot': 'خلبان',
  'pineapple': 'آناناس',
  'platypus': 'پلاتیپوس',
  'playground': 'زمین بازی',
  'policeman': 'پلیس',
  'pomegranate': 'انار',
  'potato': 'سیب زمینی',
  'principal': 'مدیر مدرسه',
  'professor': 'استاد',
  'pumpkin': 'کدو تنبل',
  'rabbit': 'خرگوش',
  'raccoon': 'راکون',
  'rain': 'باران',
  'restroom': 'دستشویی',
  'rhino': 'کرگدن',
  'river': 'رودخانه',
  'rock': 'سنگ',
  'saxophone': 'سکسفون',
  'scientist': 'دانشمند',
  'seagull': 'مرغ دریایی',
  'seal': 'فقار',
  'sesame': 'کنجد',
  'shark': 'کوسه',
  'sheep': 'گوسفند',
  'shirt': 'پیراهن',
  'singer': 'خواننده',
  'ski': 'اسکی',
  'skunk': 'اسکنک',
  'sky': 'آسمان',
  'snail': 'حلزون',
  'snake': 'مار',
  'snow': 'برف',
  'snowboard': 'اسنوبرد',
  'soccer': 'فوتبال',
  'socks': 'جوراب',
  'soil': 'خاک',
  'soldier': 'سرتیپ',
  'space': 'فضا',
  'sparrow': 'گنجشک',
  'spinach': 'اسفناج',
  'starfish': 'کوسه دریایی',
  'stewardess': 'دلیلته',
  'stingray': 'استینگ‌ری',
  'strawberry': 'توت فرنگی',
  'sun': 'خورشید',
  'subway': 'مترو',
  'swallow': 'سوالو',
  'sweater': 'سوئتر',
  'swimming': 'شنا',
  'swing': 'تأرجح',
  'table': 'میز',
  'tambourine': 'تمبورین',
  'teacher': 'معلم',
  'tiger': 'ببر',
  'timpani': 'تیمپانی',
  'toad': 'قورباغه',
  'trampoline': 'ترامپولین',
  'tree': 'درخت',
  'triangle': 'مثلث',
  'truck': 'کامیون',
  'trumpet': 'ترومپت',
  'turtle': 'لاکپشت',
  'typhoon': 'طوفان',
  'unicorn': 'یونیکورن',
  'violin': 'ویولین',
  'viking ship': 'کشتی وایکینگ',
  'volcano': 'ج्वالاموخی',
  'volleyball': 'والیبال',
  'vuvuzela': 'ووووزه‌لا',
  'waterfall': 'آبشار',
  'watermelon': 'هندوانه',
  'wave': 'موج',
  'whale': 'نهنگ',
  'wind': 'باد',
  'window': 'پنجره',
  'wolf': 'ولف',
  'woodpecker': 'وودپکر',
  'xylophone': 'زیلوفون',
  'yacht': 'یاخت',
  'zebra': 'زبرا',
  'library': 'کتابخانه',
  'post office': 'پستخانه',
  'traffic light': 'چراغ راهنمایی',
  'clock tower': 'برج ساعت',
  'pebble': 'ریگ',
  'moss': 'خزه',
  'cactus': 'کاکتوس',
  'rainbow': 'رنگین کمان',
  'toast': 'نان تست',
  'cookie': 'کلوچه',
  'ice cream': 'بستنی',
  'jelly': 'ژله',
  'writer': 'نویسنده',
  'actor': 'بازیگر',
  'crown': 'تاج',
  'compass': 'قطب نما',
  'flowerpot': 'گلدان',
  'roller skates': 'اسکیت',
  'airport': 'فرودگاه',
  'goldfish': 'ماهی طلایی',
  'spider': 'عنکبوت',
  'light bulb': 'لامپ',
  'mirror': 'آینه',
  'magnet': 'آهنربا',
  'toothbrush': 'مسواک',
  'soap': 'صابون',
  'plate': 'بشقاب',
  'spoon': 'قاشق',
  'mobile phone': 'تلفن همراه',
  'key': 'کلید',
  'newspaper': 'روزنامه',
  'calendar': 'تقویم',
  'chair': 'صندلی',
  'sofa': 'مبل',
  'refrigerator': 'یخچال',
  'stairs': 'پله',
  'pillow': 'بالش',
  'candle': 'شمع',
  'bank': 'بانک',
  'beetle': 'سوسک',
  'cicada': 'جیرجیرک',
  'dragonfly': 'سنجاقک',
  'earthworm': 'کرم خاکی',
  'komodo dragon': 'اژدهای کومودو',
  'mantis': 'آخوندک',
  'mosquito': 'پشه',
  'silkworm': 'کرم ابریشم',
  'stag beetle': 'سوسک شاخدار',
  'table tennis': 'تنیس روی میز',
  'train': 'قطار',
  'squid': 'ماهی مرکب',
  'butterfly': 'پروانه',
  'bee': 'زنبور',
  'squirrel': 'سنجاب',
  'nurse': 'پرستار',
  'slide': 'سرسره',
  'picnic': 'پیکنیک',
  'jacket': 'کت',
  'shoes': 'کفش',
  'tennis': 'تنیس'
};