final Map<String, String> punjabiItemList = {

  'accordian': 'ਅਕੌਰਡੀਅਨ',
  'airplane': 'ਵਿਮਾਨ',
  'anaconda': 'ਐਨਾਕੋਂਡਾ',
  'ant': 'ਚੀੰਟੀ',
  'anteater': 'ਚੀੰਟੀ ਖਾਣ ਵਾਲਾ',
  'apple': 'ਸੇਬ',
  'apricot': 'ਖੁਬਾਨੀ',
  'archery': 'ਤੀਰੰਦਾਜ਼ੀ',
  'astronaut': 'ਅੰਤਰਿਕਸ਼ ਯਾਤਰੀ',
  'avocado': 'ਐਵੋਕਾਡੋ',
  'badminton': 'ਬੈਡਮਿੰਟਨ',
  'banana': 'ਕੇਲਾ',
  'baseball': 'ਬੇਸਬਾਲ',
  'basketball': 'ਬਾਸਕੇਟਬਾਲ',
  'bassoon': 'ਬੈਸੂਨ',
  'bat': 'ਚਮਗਾਦੜ',
  'beach': 'ਸਮੁੰਦਰ ਕਿਨਾਰਾ',
  'bear': 'ਭਾਲੂ',
  'bicycle': 'ਸਾਈਕਲ',
  'blackboard': 'ਕਾਲਾ ਫਲਕ',
  'blowfish': 'ਬਲੋਫਿਸ਼',
  'blueberries': 'ਬਲੂਬੇਰੀ',
  'boar': 'ਜੰਗਲੀ ਸੂਰ',
  'book': 'ਕਿਤਾਬ',
  'boots': 'ਬੂਟ',
  'bowling': 'ਬੋਲਿੰਗ',
  'boxing': 'ਬਾਕਸਿੰਗ',
  'broccoli': 'ਬ੍ਰੋਕਲੀ',
  'bumper car': 'ਬੰਪਰ ਕਾਰ',
  'bus': 'ਬੱਸ',
  'cabbage': 'ਗੋਭੀ',
  'camel': 'ਉਂਟ',
  'carp': 'ਕਾਰਪ',
  'carpenter': 'ਸੁਤਾਰ',
  'carrot': 'ਗਾਜਰ',
  'castanets': 'ਕਾਸਟਾਨੇਟਸ',
  'cat': 'ਬਿੱਲੀ',
  'cello': 'ਸੈੱਲੋ',
  'chameleon': 'ਚਾਮੇਲੀਅਨ',
  'cheetah': 'ਚੀਤਾ',
  'cherry': 'ਚੈਰੀ',
  'chick': 'ਚਿੱਕ',
  'chicken': 'ਕੁੱਕੜ',
  'clarinet': 'ਕਲੈਰੀਨੈਟ',
  'classroom': 'ਕਲਾਸਰੂਮ',
  'cloud': 'ਬਾਦਲ',
  'cobra': 'ਕੋਬਰਾ',
  'coconut': 'ਨਾਰੀਅਲ',
  'computer': 'ਕੰਪਿਊਟਰ',
  'conductor': 'ਕੰਡਕਟਰ',
  'contrabass': 'ਕੌਂਟਰਾਬਾਸ',
  'cook': 'ਰਸੋਈਆ',
  'corn': 'ਮੱਕੀ',
  'cow': 'ਗਊ',
  'crab': 'ਕੇਕੜਾ',
  'crane': 'ਕਰੇਨ',
  'crocodile': 'ਮਗਰਮੱਛ',
  'crow': 'ਕਾਂ',
  'cucumber': 'ਖੀਰਾ',
  'curling': 'ਕਰਲਿੰਗ',
  'cymbals': 'ਝਾਂਝ',
  'deer': 'ਹਰਨ',
  'dentist': 'ਦੰਦਾਂ ਦਾ ਡਾਕਟਰ',
  'desert': 'ਮਰੂਭੂਮੀ',
  'doctor': 'ਡਾਕਟਰ',
  'dog': 'ਕੁੱਤਾ',
  'dolphin': 'ਡੌਲਫਿਨ',
  'drum': 'ਡਰੰਮ',
  'duck': 'ਬਤਖ',
  'eagle': 'ਗਰੁੜ',
  'earthquake': 'ਭੂਕੰਪ',
  'elephant': 'ਹਾਥੀ',
  'exam': 'ਪਰੀਖਿਆ',
  'farmer': 'ਕਿਸਾਨ',
  'fencing': 'ਫੇਨਸਿੰਗ',
  'ferris wheel': 'ਫੇਰਿਸ ਚੱਕਰ',
  'fig': 'ਅੰਜੀਰ',
  'firefighter': 'ਅੱਗ ਬੁਝਾਉਣ ਵਾਲਾ',
  'fisherman': 'ਮਛੀ ਮਾਰਣ ਵਾਲਾ',
  'flower': 'ਫੁੱਲ',
  'flute': 'ਬਾਂਸਰੀ',
  'fog': 'ਧੁੰਦ',
  'forest': 'ਜੰਗਲ',
  'fox': 'ਲੂੰਬੜ',
  'friend': 'ਦੋਸਤ',
  'frog': 'ਮੀਂਡਕ',
  'garlic': 'ਲਹਿਣ',
  'ginger': 'ਅਦਰਕ',
  'ginseng': 'ਜਿਨਸੇਂਗ',
  'giraffe': 'ਜਿਰਾਫ',
  'gloves': 'ਦਸਤਾਨੇ',
  'goat': 'ਬੱਕਰੀ',
  'golf': 'ਗੋਲਫ',
  'goose': 'ਹੰਸ',
  'gorilla': 'ਗੋਰਿਲਾ',
  'grape': 'ਅੰਗੂਰ',
  'grapefruit': 'ਗ੍ਰੇਪਫਰੂਟ',
  'guitar': 'ਗੀਤਾਰ',
  'hairdressor': 'ਬਾਲ ਸੰਵਾਰਨ ਵਾਲਾ',
  'hallway': 'ਰਾਹ',
  'harmonica': 'ਹਾਰਮੋਨਿਕਾ',
  'harp': 'ਹਾਰਪ',
  'hat': 'ਟੋਪੀ',
  'hawk': 'ਬਾਜ਼',
  'helicopter': 'ਹੈਲੀਕਾਪਟਰ',
  'hippo': 'ਹਿਪੋਪੋਟੈਮਸ',
  'hippocampus': 'ਹਿਪੋਕੈਂਪਸ',
  'hockey': 'ਹਾਕੀ',
  'horse': 'ਘੋੜਾ',
  'hyena': 'ਹਾਈਨਾ',
  'iceberg': 'ਆਈਸਬੇਰਗ',
  'iguana': 'ਇਗੁਆਨਾ',
  'jellyfish': 'ਜੈਲੀਫਿਸ਼',
  'judge': 'ਨਿਆਯਧੀਸ਼',
  'judo': 'ਜੂਡੋ',
  'jujube': 'ਜੂਜੂਬ',
  'jungle': 'ਜੰਗਲ',
  'kangaroo': 'ਕੰਗਾਰੂ',
  'kiwi': 'ਕੀਵੀ',
  'koala': 'ਕੋਆਲਾ',
  'lake': 'ਝੀਲ',
  'lemon': 'ਨਿੰਬੂ',
  'leopard': 'ਤेंदੂਆ',
  'lettuce': 'ਸਲੇਡ',
  'lightning': 'ਬਿਜਲੀ',
  'lion': 'ਸ਼ੇਰ',
  'lizard': 'ਛਿਪਕਲੀ',
  'lobster': 'ਲਾਬਸਟਾਰ',
  'magpie': 'ਮੈਗਪਾਈ',
  'mango': 'ਅੰਬ',
  'marathon': 'ਮੈਰਥਾਨ',
  'meerkat': 'ਮੀਰਕੈਟ',
  'melon': 'ਤਰਬੂਜ',
  'Merry go round': 'ਗੋਲ ਚੱਕਰ',
  'mole': 'ਮੋਲ',
  'monkey': 'ਬੰਦਰ',
  'moon': 'ਚੰਦਰਮਾ',
  'mountain': 'ਪਹਾੜ',
  'mouse': 'ਚੂਹਾ',
  'mushroom': 'ਮਸ਼ਰੂਮ',
  'notebook': 'ਨੋਟਬੁੱਕ',
  'ocarina': 'ਓਕਾਰਿਨਾ',
  'ocean': 'ਮਹਾਸਾਗਰ',
  'octopus': 'ਆਕਟੋਪਸ',
  'onion': 'ਪਿਆਜ਼',
  'orange': 'ਸੰਤਰਾ',
  'orangutan': 'ਓਰੰਗੁਟਾਨ',
  'orchestra': 'ਵਾਦਯ ਸਮੂਹ',
  'ostrich': 'ਸ਼ੁਤੁਰਮੁਰਗਾ',
  'owl': 'ਉੱਲੂ',
  'painter': 'ਚਿੱਤਰਕਾਰ',
  'pants': 'ਪੈਂਟ',
  'parrot': 'ਤੋਤਾ',
  'parsley': 'ਪਾਰਸਲੀ',
  'peach': 'ਪੀਚ',
  'peacock': 'ਮੋਰ',
  'pelican': 'ਪੇਲਿਕਨ',
  'pencil': 'ਪੈਨਸਿਲ',
  'penguin': 'ਪੇਂਗਵਿਨ',
  'pepper': 'ਮਿਰਚ',
  'pharmacist': 'ਦਵਾਈ ਵਾਲਾ',
  'piano': 'ਪਿਆਨੋ',
  'pickle': 'ਅਚਾਰ',
  'pig': 'ਸੂਰ',
  'pigeon': 'ਕਬੂਤਰ',
  'pilot': 'ਪਾਇਲਟ',
  'pineapple': 'ਅਨਾਨਸ',
  'platypus': 'ਪਲੈਟਿਪਸ',
  'playground': 'ਖੇਡ ਦਾ ਮੈਦਾਨ',
  'policeman': 'ਪੁਲਿਸ',
  'pomegranate': 'ਅਨਾਰ',
  'potato': 'ਆਲੂ',
  'principal': 'ਪ੍ਰਧਾਨ ਅਧਿਆਪਕ',
  'professor': 'ਪ੍ਰੋਫੈਸਰ',
  'pumpkin': 'ਕੱਦੂ',
  'rabbit': 'ਖਰਗੋਸ਼',
  'raccoon': 'ਰੈਕੂਨ',
  'rain': 'ਮੀਹ',
  'restroom': 'ਸ਼ੌਚਾਲਯ',
  'rhino': 'ਗੇਂਡਾ',
  'river': 'ਦਰਿਆ',
  'rock': 'ਚਟਾਨ',
  'saxophone': 'ਸੈਕਸੋਫੋਨ',
  'scientist': 'ਵਿਗਿਆਨੀ',
  'seagull': 'ਸਮੁੰਦਰੀ ਪੰਛੀ',
  'seal': 'ਸੀਲ',
  'sesame': 'ਤਿਲ',
  'shark': 'ਸ਼ਾਰਕ',
  'sheep': 'ਭੇਡ',
  'shirt': 'ਕਮੀਜ਼',
  'singer': 'ਗਾਇਕ',
  'ski': 'ਸਕੀ',
  'skunk': 'ਸਕੰਕ',
  'sky': 'ਆਕਾਸ਼',
  'snail': 'ਘੋਗਰ',
  'snake': 'ਸਾੱਪ',
  'snow': 'ਬਰਫ',
  'snowboard': 'ਸਨੋਬੋਰਡ',
  'soccer': 'ਫੁੱਟਬਾਲ',
  'socks': 'ਮੋਜੇ',
  'soil': 'ਮਿੱਟੀ',
  'soldier': 'ਸੈਨੀਕ',
  'space': 'ਅੰਤਰਿਕਸ਼',
  'sparrow': 'ਚਿੜੀ',
  'spinach': 'ਪਾਲਕ',
  'starfish': 'ਤਾਰਾਮੱਛੀ',
  'stewardess': 'ਸਟੂਵਰਡੈਸ',
  'stingray': 'ਸਟਿੰਗਰੇ',
  'strawberry': 'ਸਟ੍ਰਾਬੇਰੀ',
  'sun': 'ਸੂਰਜ',
  'subway': 'ਸਬਵੇ',
  'swallow': 'ਨਿਗਲਣਾ',
  'sweater': 'ਸਵੈਟਰ',
  'swimming': 'ਤੈਰਨ',
  'swing': 'ਝੂਲਣਾ',
  'table': 'ਮੇਜ਼',
  'tambourine': 'ਟੈਂਬੋਰਿਨ',
  'teacher': 'ਅਧਿਆਪਕ',
  'tiger': 'ਬਾਘ',
  'timpani': 'ਟਿੰਪਾਨੀ',
  'toad': 'ਟੋਡ',
  'trampoline': 'ਟ੍ਰੈਂਪੋਲਿਨ',
  'tree': 'ਗଛ',
  'triangle': 'ਤਿਕੋਣ',
  'truck': 'ਟਰੱਕ',
  'trumpet': 'ਟਰੰਪੇਟ',
  'turtle': 'ਕੱਛੂ',
  'typhoon': 'ਤੂਫਾਨ',
  'unicorn': 'ਯੂਨਿਕਾਰਨ',
  'violin': 'ਵਾਇਲਿਨ',
  'viking ship': 'ਵਾਈਕਿੰਗ ਜਹਾਜ਼',
  'volcano': 'ਜ੍ਵਾਲਾਮੁਖੀ',
  'volleyball': 'ਵਾਲੀਬਾਲ',
  'vuvuzela': 'ਵੁਵੁਜ਼ੇਲਾ',
  'waterfall': 'ਜਲ ਪ੍ਰਪਾਤ',
  'watermelon': 'ਤਰਬੂਜ',
  'wave': 'ਲਹਿਰ',
  'whale': 'ਤਿਮਿੰਗਲ',
  'wind': 'ਹਵਾ',
  'window': 'ਖਿੜਕੀ',
  'wolf': 'ਭੇੜਿਆ',
  'woodpecker': 'ਵੁਡਪੇਕਰ',
  'xylophone': 'ਜ਼ਾਇਲੋਫੋਨ',
  'yacht': 'ਯਾਚਟ',
  'zebra': 'ਜ਼ੀਬਰਾ',
  'library': 'ਲਾਇਬ੍ਰੇਰੀ',
  'post office': 'ਡਾਕਖਾਨਾ',
  'traffic light': 'ਟ੍ਰੈਫਿਕ ਲਾਈਟ',
  'clock tower': 'ਘੜੀ ਟਾਵਰ',
  'pebble': 'ਛੋਟਾ ਪੱਥਰ',
  'moss': 'ਕਾਈ',
  'cactus': 'ਕੈਕਟਸ',
  'rainbow': 'ਇੰਦਰਧਨੁਸ਼',
  'toast': 'ਟੋਸਟ',
  'cookie': 'ਕੁਕੀ',
  'ice cream': 'ਆਈਸ ਕਰੀਮ',
  'jelly': 'ਜੈਲੀ',
  'writer': 'ਲੇਖਕ',
  'actor': 'ਅਦਾਕਾਰ',
  'crown': 'ਤਾਜ',
  'compass': 'ਕੰਪਾਸ',
  'flowerpot': 'ਫੁੱਲਾਂ ਦਾ ਘੜਾ',
  'roller skates': 'ਰੋਲਰ ਸਕੇਟ',
  'airport': 'ਹਵਾਈ ਅੱਡਾ',
  'goldfish': 'ਸੋਨੇ ਦੀ ਮੱਛੀ',
  'spider': 'ਮੱਕੜੀ',
  'light bulb': 'ਲਾਈਟ ਬਲਬ',
  'mirror': 'ਸ਼ੀਸ਼ਾ',
  'magnet': 'ਚੁੰਬਕ',
  'toothbrush': 'ਦੰਦ ਸਾਫ਼ ਕਰਨ ਵਾਲਾ',
  'soap': 'ਸਾਬਣ',
  'plate': 'ਪਲੇਟ',
  'spoon': 'ਚਮਚ',
  'mobile phone': 'ਮੋਬਾਈਲ ਫੋਨ',
  'key': 'ਚਾਬੀ',
  'newspaper': 'ਅਖਬਾਰ',
  'calendar': 'ਕੈਲੰਡਰ',
  'chair': 'ਕੁਰਸੀ',
  'sofa': 'ਸੋਫਾ',
  'refrigerator': 'ਫਰਿੱਜ',
  'stairs': 'ਸੀੜੀਆਂ',
  'pillow': 'ਤਕੀਆ',
  'candle': 'ਮੋਮਬੱਤੀ',
  'bank': 'ਬੈਂਕ',
  'beetle': 'ਵੀਲਡ',
  'cicada': 'ਸਿਕਾਡਾ',
  'dragonfly': 'ਡ੍ਰੈਗਨ ਫਲਾਈ',
  'earthworm': 'ਭੂਮੀ ਪੁਰੁਗ',
  'komodo dragon': 'ਕੋਮੋਡੋ ਡ੍ਰੈਗਨ',
  'mantis': 'ਮੇਂਟਿਸ',
  'mosquito': 'ਮੱਛਰ',
  'silkworm': 'ਰੇਸ਼ਮ ਪੁਰੁਗ',
  'stag beetle': 'ਸਟੈਗ ਬੀਟਲ',
  'table tennis': 'ਟੇਬਲ ਟੈਨਿਸ',
  'train': 'ਰੇਲਗਾਡੀ',
  'squid': 'ਸਕੁਇਡ',
  'butterfly': 'ਤਿਤਲੀ',
  'bee': 'ਮਧੂਮੱਖੀ',
  'squirrel': 'ਗਿਲਹਰੀ',
  'nurse': 'ਨਰਸ',
  'slide': 'ਸਲਾਈਡ',
  'picnic': 'ਪਿਕਨਿਕ',
  'jacket': 'ਜੈਕਟ',
  'shoes': 'ਜੁੱਤੇ',
  'tennis': 'ਟੈਨਿਸ'
};