final Map<String, String> romanianItemList = {

  'accordian': 'acordion',
  'airplane': 'avion',
  'anaconda': 'anaconda',
  'ant': 'furnică',
  'anteater': 'mâncător de furnici',
  'apple': 'măr',
  'apricot': 'cais',
  'archery': 'tir cu arcul',
  'astronaut': 'astronaut',
  'avocado': 'avocadă',
  'badminton': 'badminton',
  'banana': 'banană',
  'baseball': 'baseball',
  'basketball': 'baschet',
  'bassoon': 'fagot',
  'bat': 'liliac',
  'beach': 'plajă',
  'bear': 'urs',
  'bicycle': 'bicicletă',
  'blackboard': 'tablă neagră',
  'blowfish': 'pește balon',
  'blueberries': 'afine',
  'boar': 'mistret',
  'book': 'carte',
  'boots': 'cizme',
  'bowling': 'bowling',
  'boxing': 'box',
  'broccoli': 'broccoli',
  'bumper car': 'mașină de coliziune',
  'bus': 'autobuz',
  'cabbage': 'varză',
  'camel': 'cămilă',
  'carp': 'caras',
  'carpenter': 'tâmplar',
  'carrot': 'morcov',
  'castanets': 'castaniete',
  'cat': 'pisică',
  'cello': 'violoncel',
  'chameleon': 'cameleon',
  'cheetah': 'ghepard',
  'cherry': 'cireașă',
  'chick': 'pui',
  'chicken': 'pui',
  'clarinet': 'clarinetă',
  'classroom': 'sală de clasă',
  'cloud': 'nor',
  'cobra': 'cobra',
  'coconut': 'nucă de cocos',
  'computer': 'calculator',
  'conductor': 'dirijor',
  'contrabass': 'contrabas',
  'cook': 'bucătar',
  'corn': 'porumb',
  'cow': 'vacă',
  'crab': 'rac',
  'crane': 'macara',
  'crocodile': 'crocodil',
  'crow': 'cioară',
  'cucumber': 'castravete',
  'curling': 'curling',
  'cymbals': 'cimbaluri',
  'deer': 'cerb',
  'dentist': 'dentist',
  'desert': 'deșert',
  'doctor': 'doctor',
  'dog': 'câine',
  'dolphin': 'delfin',
  'drum': 'tobă',
  'duck': 'rață',
  'eagle': 'vultur',
  'earthquake': 'cutremur',
  'elephant': 'elefant',
  'exam': 'examen',
  'farmer': 'țăran',
  'fencing': 'scrimă',
  'ferris wheel': 'roata norocului',
  'fig': 'smochin',
  'firefighter': 'pompier',
  'fisherman': 'pescar',
  'flower': 'floare',
  'flute': 'flaut',
  'fog': 'ceață',
  'forest': 'pădure',
  'fox': 'vulpe',
  'friend': 'prieten',
  'frog': 'broască',
  'garlic': 'usturoi',
  'ginger': 'ghimbir',
  'ginseng': 'ginseng',
  'giraffe': 'girafă',
  'gloves': 'mănuși',
  'goat': 'capră',
  'golf': 'golf',
  'goose': 'gască',
  'gorilla': 'gorilă',
  'grape': 'strugure',
  'grapefruit': 'grepfrut',
  'guitar': 'chitară',
  'hairdressor': 'coafor',
  'hallway': 'hol',
  'harmonica': 'armonica',
  'harp': 'arpa',
  'hat': 'pălărie',
  'hawk': 'șoim',
  'helicopter': 'elicopter',
  'hippo': 'hipopotam',
  'hippocampus': 'hipocampus',
  'hockey': 'hochei',
  'horse': 'cal',
  'hyena': 'hienă',
  'iceberg': 'aisberg',
  'iguana': 'iguana',
  'jellyfish': 'meduză',
  'judge': 'judecător',
  'judo': 'judo',
  'jujube': 'jujube',
  'jungle': 'junglă',
  'kangaroo': 'cangur',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'lac',
  'lemon': 'lămâie',
  'leopard': 'leopard',
  'lettuce': 'salată verde',
  'lightning': 'fulger',
  'lion': 'leu',
  'lizard': 'șopârlă',
  'lobster': 'homar',
  'magpie': 'magpie',
  'mango': 'mango',
  'marathon': 'maraton',
  'meerkat': 'meerkat',
  'melon': 'pepene',
  'Merry go round': 'carusel',
  'mole': 'mol',
  'monkey': 'maimuță',
  'moon': 'lună',
  'mountain': 'munte',
  'mouse': 'șoarece',
  'mushroom': 'ciupercă',
  'notebook': 'caiet',
  'ocarina': 'ocarină',
  'ocean': 'ocean',
  'octopus': 'caracatiță',
  'onion': 'ceapă',
  'orange': 'portocală',
  'orangutan': 'orangutan',
  'orchestra': 'orchestră',
  'ostrich': 'struț',
  'owl': 'bufniță',
  'painter': 'pictor',
  'pants': 'pantaloni',
  'parrot': 'papagal',
  'parsley': 'pătrunjel',
  'peach': 'piersică',
  'peacock': 'paun',
  'pelican': 'pelican',
  'pencil': 'creion',
  'penguin': 'pinguin',
  'pepper': 'piper',
  'pharmacist': 'farmacist',
  'piano': 'pian',
  'pickle': 'murătură',
  'pig': 'purcel',
  'pigeon': 'porumbel',
  'pilot': 'pilot',
  'pineapple': 'ananas',
  'platypus': 'ornitorinc',
  'playground': 'loc de joacă',
  'policeman': 'polițist',
  'pomegranate': 'rodie',
  'potato': 'cartof',
  'principal': 'director de școală',
  'professor': 'profesor',
  'pumpkin': 'dovleac',
  'rabbit': 'iepure',
  'raccoon': 'rakun',
  'rain': 'ploaie',
  'restroom': 'toaletă',
  'rhino': 'rinocer',
  'river': 'râu',
  'rock': 'piatră',
  'saxophone': 'saksofon',
  'scientist': 'om de știință',
  'seagull': 'gâscă de mare',
  'seal': 'foca',
  'sesame': 'susam',
  'shark': 'rechin',
  'sheep': 'oaie',
  'shirt': 'cămașă',
  'singer': 'cântăreț',
  'ski': 'schi',
  'skunk': 'skunk',
  'sky': 'cer',
  'snail': 'melc',
  'snake': 'șarpe',
  'snow': 'zăpadă',
  'snowboard': 'snowboard',
  'soccer': 'fotbal',
  'socks': 'șosete',
  'soil': 'sol',
  'soldier': 'soldat',
  'space': 'spațiu',
  'sparrow': 'vrabie',
  'spinach': 'spanac',
  'starfish': 'stea de mare',
  'stewardess': 'stewardesă',
  'stingray': 'stingrei',
  'strawberry': 'căpșună',
  'sun': 'soare',
  'subway': 'metrou',
  'swallow': 'rândunică',
  'sweater': 'pulover',
  'swimming': 'înot',
  'swing': 'leagăn',
  'table': 'masă',
  'tambourine': 'tamburină',
  'teacher': 'învățător',
  'tiger': 'tigrul',
  'timpani': 'timpani',
  'toad': 'broască de baltă',
  'trampoline': 'trambulină',
  'tree': 'copac',
  'triangle': 'triunghi',
  'truck': 'camion',
  'trumpet': 'trompetă',
  'turtle': 'broască țestoasă',
  'typhoon': 'taifun',
  'unicorn': 'unicorni',
  'violin': 'vioară',
  'viking ship': 'navă viking',
  'volcano': 'vulcan',
  'volleyball': 'volei',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'cascadă',
  'watermelon': 'pepene verde',
  'wave': 'val',
  'whale': 'balenă',
  'wind': 'vânt',
  'window': 'fereastră',
  'wolf': 'lup',
  'woodpecker': 'ciocănitoare',
  'xylophone': 'xilofon',
  'yacht': 'iaht',
  'zebra': 'zebră',
  'library': 'bibliotecă',
  'post office': 'oficiu poștal',
  'traffic light': 'semafoare',
  'clock tower': 'turn cu ceas',
  'pebble': 'pietricică',
  'moss': 'mușchi',
  'cactus': 'cactus',
  'rainbow': 'curcubeu',
  'toast': 'pâine prăjită',
  'cookie': 'biscuit',
  'ice cream': 'înghețată',
  'jelly': 'jeleu',
  'writer': 'scriitor',
  'actor': 'actor',
  'crown': 'coroană',
  'compass': 'busolă',
  'flowerpot': 'ghiveci',
  'roller skates': 'patine cu rotile',
  'airport': 'aeroport',
  'goldfish': 'pește roșu',
  'spider': 'păianjen',
  'light bulb': 'bec',
  'mirror': 'oglindă',
  'magnet': 'magnet',
  'toothbrush': 'periuță de dinți',
  'soap': 'săpun',
  'plate': 'farfurie',
  'spoon': 'lingură',
  'mobile phone': 'telefon mobil',
  'key': 'cheie',
  'newspaper': 'ziar',
  'calendar': 'calendar',
  'chair': 'scaun',
  'sofa': 'canapea',
  'refrigerator': 'frigider',
  'stairs': 'scări',
  'pillow': 'pernă',
  'candle': 'lumânare',
  'bank': 'bancă',
  'beetle': 'gândac',
  'cicada': 'cicoare',
  'dragonfly': 'libelulă',
  'earthworm': 'râmă',
  'komodo dragon': 'dragon komodo',
  'mantis': 'călugăriță',
  'mosquito': 'țânțar',
  'silkworm': 'vierme de mătase',
  'stag beetle': 'cerb zburător',
  'table tennis': 'tenis de masă',
  'train': 'tren',
  'squid': 'calmar',
  'butterfly': 'fluture',
  'bee': 'albină',
  'squirrel': 'veveriță',
  'nurse': 'infirmieră',
  'slide': 'tobogan',
  'picnic': 'picnic',
  'jacket': 'sacou',
  'shoes': 'pantofi',
  'tennis': 'tenis'
};