final Map<String, String> serbianItemList = {

  'accordian': 'akordeon',
  'airplane': 'avion',
  'anaconda': 'anakonda',
  'ant': 'mrav',
  'anteater': 'mravojedač',
  'apple': 'jabuka',
  'apricot': 'kajsija',
  'archery': 'lukostreljaštvo',
  'astronaut': 'astronaut',
  'avocado': 'avokado',
  'badminton': 'badminton',
  'banana': 'banana',
  'baseball': 'bejzbol',
  'basketball': 'košarka',
  'bassoon': 'basun',
  'bat': 'šišmiš',
  'beach': 'plaža',
  'bear': 'medved',
  'bicycle': 'bicikl',
  'blackboard': 'crna tabla',
  'blowfish': 'napuhana riba',
  'blueberries': 'borovnice',
  'boar': 'divlja svinja',
  'book': 'knjiga',
  'boots': 'čizme',
  'bowling': 'kuglanje',
  'boxing': 'boks',
  'broccoli': 'brokoli',
  'bumper car': 'automobil za sudaranje',
  'bus': 'autobus',
  'cabbage': 'kupus',
  'camel': 'verblud', // Termin prilagođen srpskom jeziku
  'carp': 'krap',
  'carpenter': 'tesar',
  'carrot': 'šargarepa',
  'castanets': 'kastanete',
  'cat': 'mačka',
  'cello': 'čelo',
  'chameleon': 'kameleon',
  'cheetah': 'gepard',
  'cherry': 'trešnja',
  'chick': 'pile',
  'chicken': 'kokoš',
  'clarinet': 'klarinet',
  'classroom': 'učionica',
  'cloud': 'oblak',
  'cobra': 'kobra',
  'coconut': 'kokos',
  'computer': 'računar',
  'conductor': 'dirigent',
  'contrabass': 'kontrabas',
  'cook': 'kuvar',
  'corn': 'kukuruz',
  'cow': 'krava',
  'crab': 'rak',
  'crane': 'žerjav',
  'crocodile': 'krokodil',
  'crow': 'vrana',
  'cucumber': 'krastavac',
  'curling': 'curling',
  'cymbals': 'činely',
  'deer': 'jelen',
  'dentist': 'zubozdrav',
  'desert': 'pustinja',
  'doctor': 'lekar',
  'dog': 'pas',
  'dolphin': 'delfin',
  'drum': 'bubanj',
  'duck': 'patka',
  'eagle': 'orao',
  'earthquake': 'potres',
  'elephant': 'slon',
  'exam': 'ispit',
  'farmer': 'poljoprivrednik',
  'fencing': 'mačevanje',
  'ferris wheel': 'vrtiljak',
  'fig': 'smokva',
  'firefighter': 'vatrogasac',
  'fisherman': 'ribolovac',
  'flower': 'cvet',
  'flute': 'flut',
  'fog': 'magla',
  'forest': 'šuma',
  'fox': 'lisica',
  'friend': 'prijatelj',
  'frog': 'žaba',
  'garlic': 'beli luk',
  'ginger': 'đumbir',
  'ginseng': 'ženšen',
  'giraffe': 'žirafa',
  'gloves': 'rukavice',
  'goat': 'koza',
  'golf': 'golf',
  'goose': 'guska',
  'gorilla': 'gorila',
  'grape': 'grožđe',
  'grapefruit': 'grejpfrut',
  'guitar': 'gitara',
  'hairdressor': 'frizer',
  'hallway': 'hodnik',
  'harmonica': 'harmonika',
  'harp': 'harfa',
  'hat': 'šešir',
  'hawk': 'jastreb',
  'helicopter': 'helikopter',
  'hippo': 'hipopotam',
  'hippocampus': 'hipokampus',
  'hockey': 'hokej',
  'horse': 'konj',
  'hyena': 'hijena',
  'iceberg': 'ledeni breg',
  'iguana': 'iguana',
  'jellyfish': 'meduza',
  'judge': 'sudija',
  'judo': 'judo',
  'jujube': 'jujube',
  'jungle': 'džungla',
  'kangaroo': 'kengur',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'jezero',
  'lemon': 'limun',
  'leopard': 'leopard',
  'lettuce': 'zelena salata',
  'lightning': 'munja',
  'lion': 'lav',
  'lizard': 'gušterica',
  'lobster': 'jastog',
  'magpie': 'magpai',
  'mango': 'mango',
  'marathon': 'maraton',
  'meerkat': 'meerkat',
  'melon': 'dinja',
  'Merry go round': 'kolotoč',
  'mole': 'krtek',
  'monkey': 'majmun',
  'moon': 'mesec',
  'mountain': 'planina',
  'mouse': 'miš',
  'mushroom': 'gljiva',
  'notebook': 'sveska',
  'ocarina': 'okarina',
  'ocean': 'okean',
  'octopus': 'hobotnica',
  'onion': 'luk',
  'orange': 'narandža',
  'orangutan': 'orangutan',
  'orchestra': 'orkestar',
  'ostrich': 'noj',
  'owl': 'sova',
  'painter': 'slikar',
  'pants': 'hlače',
  'parrot': 'papagaj',
  'parsley': 'peršun',
  'peach': 'breskva',
  'peacock': 'paun',
  'pelican': 'pelikan',
  'pencil': 'olovka',
  'penguin': 'pingvin',
  'pepper': 'biber',
  'pharmacist': 'apoteker',
  'piano': 'pijano',
  'pickle': 'kiseli krastavac',
  'pig': 'svinja',
  'pigeon': 'golub',
  'pilot': 'pilot',
  'pineapple': 'ananas',
  'platypus': 'platipus',
  'playground': 'igralište',
  'policeman': 'policajac',
  'pomegranate': 'nar',
  'potato': 'krompir',
  'principal': 'direktor škole',
  'professor': 'profesor',
  'pumpkin': 'tikva',
  'rabbit': 'zec',
  'raccoon': 'rakun',
  'rain': 'kiša',
  'restroom': 'toalet',
  'rhino': 'nosorog',
  'river': 'reka',
  'rock': 'kamen',
  'saxophone': 'saksofon',
  'scientist': 'naučnik',
  'seagull': 'galeb',
  'seal': 'tuljan',
  'sesame': 'sezam',
  'shark': 'ajkula',
  'sheep': 'ovca',
  'shirt': 'košulja',
  'singer': 'pevač',
  'ski': 'ski',
  'skunk': 'skank',
  'sky': 'nebo',
  'snail': 'puž',
  'snake': 'zmija',
  'snow': 'sneg',
  'snowboard': 'snežna daska',
  'soccer': 'fudbal',
  'socks': 'čarape',
  'soil': 'tlo',
  'soldier': 'vojnik',
  'space': 'svemir',
  'sparrow': 'vrabac',
  'spinach': 'špinat',
  'starfish': 'morska zvezda',
  'stewardess': 'stjuardesa',
  'stingray': 'morski raž',
  'strawberry': 'jagoda',
  'sun': 'sunce',
  'subway': 'metro',
  'swallow': 'lastavica',
  'sweater': 'džemper',
  'swimming': 'plivanje',
  'swing': 'ljuljaška',
  'table': 'sto',
  'tambourine': 'tamburin',
  'teacher': 'učitelj',
  'tiger': 'tigar',
  'timpani': 'timpani',
  'toad': 'žaba',
  'trampoline': 'trampolin',
  'tree': 'drvo',
  'triangle': 'trokut',
  'truck': 'kamion',
  'trumpet': 'trumpeta',
  'turtle': 'kornjača',
  'typhoon': 'tajfun',
  'unicorn': 'jednorog',
  'violin': 'violina',
  'viking ship': 'vikingski brod',
  'volcano': 'vulkan',
  'volleyball': 'odbojka',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'vodopad',
  'watermelon': 'lubenica',
  'wave': 'talas',
  'whale': 'kit',
  'wind': 'vetar',
  'window': 'prozor',
  'wolf': 'vuk',
  'woodpecker': 'stukalica',
  'xylophone': 'ksilofon',
  'yacht': 'jahta',
  'zebra': 'zebra',
  'library': 'biblioteka',
  'post office': 'pošta',
  'traffic light': 'semafor',
  'clock tower': 'sat toranj',
  'pebble': 'kamenčić',
  'moss': 'mahovina',
  'cactus': 'kaktus',
  'rainbow': 'duga',
  'toast': 'tost',
  'cookie': 'kolačić',
  'ice cream': 'sladoled',
  'jelly': 'žele',
  'writer': 'pisac',
  'actor': 'glumac',
  'crown': 'kruna',
  'compass': 'kompas',
  'flowerpot': 'cvjetni lonac',
  'roller skates': 'rolerice',
  'airport': 'aerodrom',
  'goldfish': 'zlatna ribica',
  'spider': 'pauk',
  'light bulb': 'žarulja',
  'mirror': 'ogledalo',
  'magnet': 'magnet',
  'toothbrush': 'četkica za zube',
  'soap': 'sapun',
  'plate': 'tanjur',
  'spoon': 'kašika',
  'mobile phone': 'mobilni telefon',
  'key': 'ključ',
  'newspaper': 'novine',
  'calendar': 'kalendar',
  'chair': 'stolica',
  'sofa': 'sofa',
  'refrigerator': 'hladnjak',
  'stairs': 'stepenice',
  'pillow': 'jastuk',
  'candle': 'sveća',
  'bank': 'banka',
  'beetle': 'buba',
  'cicada': 'cvrčak',
  'dragonfly': 'vila',
  'earthworm': 'kišna glista',
  'komodo dragon': 'komodo zmaj',
  'mantis': 'bogomoljka',
  'mosquito': 'komarac',
  'silkworm': 'svila gusjenica',
  'stag beetle': 'jelenak',
  'table tennis': 'stolni tenis',
  'train': 'voz',
  'squid': 'lignja',
  'butterfly': 'leptir',
  'bee': 'pčela',
  'squirrel': 'veverica',
  'nurse': 'sestra',
  'slide': 'klizalište',
  'picnic': 'piknik',
  'jacket': 'jakna',
  'shoes': 'cipele',
  'tennis': 'tenis'
};