final Map<String, String> sinhalaItemList = {

  'accordian': 'ඇකෝඩියන්',
  'airplane': 'ගුවන් යානය',
  'anaconda': 'අනකොන්ඩා',
  'ant': 'ඇන්ට්',
  'anteater': 'ඇන්ට්-ඉටර්',
  'apple': 'සෙබු',
  'apricot': 'ඇප්‍රිකොට්',
  'archery': 'ධනුවැදි ක්‍රීඩා',
  'astronaut': 'අන්තර්කාශ සෙවණැල්ල',
  'avocado': 'ඇවොකාඩෝ',
  'badminton': 'බෑඩ්මින්ටන්',
  'banana': 'කෙසෙල්',
  'baseball': 'බේස්බෝල්',
  'basketball': 'බාස්කට්බෝල්',
  'bassoon': 'බැසූන්',
  'bat': 'බෑට්',
  'beach': 'වෙරළ',
  'bear': 'භාලූ',
  'bicycle': 'සයිකලය',
  'blackboard': 'කළු පුවරුව',
  'blowfish': 'බ්ලෝෆිශ්',
  'blueberries': 'නිල්බෙරි',
  'boar': 'වන සුර',
  'book': 'පොත',
  'boots': 'බූට්ස්',
  'bowling': 'බෝවිංග්',
  'boxing': 'බොක්සිං',
  'broccoli': 'බ්‍රොකලී',
  'bumper car': 'බම්පර් කාර්',
  'bus': 'බස් රථය',
  'cabbage': 'කැබ්බේජ්',
  'camel': 'ඇට',
  'carp': 'කාර්ප්',
  'carpenter': 'හඩි කැපිය',
  'carrot': 'කැරට්',
  'castanets': 'කැස්ටනෙට්ස්',
  'cat': 'පූසා',
  'cello': 'සෙලෝ',
  'chameleon': 'චේමලියන්',
  'cheetah': 'චිතා',
  'cherry': 'චෙරි',
  'chick': 'කුකුළ ළමයා',
  'chicken': 'කුකුළා',
  'clarinet': 'ක්ලැරිනට්',
  'classroom': 'පන්තිකාමරය',
  'cloud': 'මেঘය',
  'cobra': 'කොබ්‍රා',
  'coconut': 'නාරිල්',
  'computer': 'පරිගණකය',
  'conductor': 'කන්ඩක්ටර්',
  'contrabass': 'කොන්ට්‍රාබෑස්',
  'cook': 'පකවන්නා',
  'corn': 'බඩල',
  'cow': 'ගවය',
  'crab': 'කැකුළු',
  'crane': 'ක්‍රේන්',
  'crocodile': 'මැංගෙලා',
  'crow': 'කොව්ව',
  'cucumber': 'වෙස්ස',
  'curling': 'ක්‍රලින්',
  'cymbals': 'සින්බල්ස්',
  'deer': 'මෙදුරා',
  'dentist': 'දන්ත වෛද්‍ය',
  'desert': 'වැලිවෑරුම',
  'doctor': 'වෛද්‍යවරයා',
  'dog': 'බල්ලා',
  'dolphin': 'ඩොල්ෆින්',
  'drum': 'ඩ්‍රම්',
  'duck': 'බත්තා',
  'eagle': 'ගුරුලු',
  'earthquake': 'භූකම්පනය',
  'elephant': 'අලි',
  'exam': 'පරීක්ෂණය',
  'farmer': 'ගොවියා',
  'fencing': 'ෆෙන්සිං',
  'ferris wheel': 'ෆෙරීස් වීල්',
  'fig': 'ෆිග්',
  'firefighter': 'ගිනි නිවාරකයා',
  'fisherman': 'මාසුන් හොයන කෙනා',
  'flower': 'පූෂ්පය',
  'flute': 'බාසුරිය',
  'fog': 'ෆොග්',
  'forest': 'අරණ',
  'fox': 'නරිය',
  'friend': 'මිතුරා',
  'frog': 'බැටියා',
  'garlic': 'ලූණු',
  'ginger': 'ඉඟුරු',
  'ginseng': 'ජින්සෙං',
  'giraffe': 'ජිරාෆ්',
  'gloves': 'අත් ඇඳුම්',
  'goat': 'දෙමම',
  'golf': 'ගොල්ෆ්',
  'goose': 'හංසයා',
  'gorilla': 'ගොරීලා',
  'grape': 'දොඩම්',
  'grapefruit': 'ග්‍රේප්ෆෘට්',
  'guitar': 'ගිටාර්',
  'hairdressor': 'කෙස් හැඩකරන්නා',
  'hallway': 'මංසල',
  'harmonica': 'හාර්මොනිකා',
  'harp': 'හාර්ප්',
  'hat': 'හැට්',
  'hawk': 'හැක්',
  'helicopter': 'හෙලික්පටර්',
  'hippo': 'හිපොපොටමස්',
  'hippocampus': 'හිපොකැම්පස්',
  'hockey': 'හොක්කී',
  'horse': 'අශ්වයා',
  'hyena': 'හයින',
  'iceberg': 'අයිස්බර්ග්',
  'iguana': 'ඉගුවාන',
  'jellyfish': 'ජෙල්ලීෆිශ්',
  'judge': 'නිවැසියා',
  'judo': 'ජුඩෝ',
  'jujube': 'ජුජුබ්',
  'jungle': 'අරණ',
  'kangaroo': 'කැන්ගරු',
  'kiwi': 'කිවි',
  'koala': 'කෝඅලා',
  'lake': 'උයන',
  'lemon': 'ලෙමන්',
  'leopard': 'චීතා',
  'lettuce': 'ලෙටස්',
  'lightning': 'විදුලිය',
  'lion': 'සිංහයා',
  'lizard': 'छिपकली', // Sinhala for “lizard” is often transliterated as well.
  'lobster': 'ලොබස්ටර්',
  'magpie': 'මැග්පයි',
  'mango': 'මැන්ගෝ',
  'marathon': 'මැරතන්',
  'meerkat': 'මීර්කැට්',
  'melon': 'තර්බුජ',
  'Merry go round': 'වටේ රැඳෙන රථය',
  'mole': 'මෝල්',
  'monkey': 'වඳුරා',
  'moon': 'චන්ද්‍රයා',
  'mountain': 'පර්වතය',
  'mouse': 'මුසයා',
  'mushroom': 'කුකුඳු',
  'notebook': 'නොට්බුක්',
  'ocarina': 'ඔකාරිනා',
  'ocean': 'සාගරය',
  'octopus': 'ඔක්ටොපස්',
  'onion': 'ලූණු',
  'orange': 'ඔරේන්ජ්',
  'orangutan': 'ඔරැන්ගුටන්',
  'orchestra': 'ඔර්කෙස්ට්රාව',
  'ostrich': 'ශුටුරං',
  'owl': 'ඔව්ල්',
  'painter': 'චිත්‍ර ශිල්පියා',
  'pants': 'පෑන්ට්ස්',
  'parrot': 'කොකුර',
  'parsley': 'පාර්ස්ලි',
  'peach': 'පීච්',
  'peacock': 'මොරයා',
  'pelican': 'පෙලිකන්',
  'pencil': 'පෑන්සල්',
  'penguin': 'පෙන්ග්වින්',
  'pepper': 'මිරිස්',
  'pharmacist': 'ෆාමසීස්ට්',
  'piano': 'පියනෝ',
  'pickle': 'පික්ල්',
  'pig': 'පන්දුව',
  'pigeon': 'දෝව',
  'pilot': 'පයිලට්',
  'pineapple': 'අනනස්',
  'platypus': 'ප්ලැටිපස්',
  'playground': 'ක්‍රීඩාංගනය',
  'policeman': 'පොලිස්',
  'pomegranate': 'දාලම්',
  'potato': 'අල',
  'principal': 'ප්‍රධාන ගුරුවරයා',
  'professor': 'පැරොෆෙසරය',
  'pumpkin': 'කූදු',
  'rabbit': 'හුල්ල',
  'raccoon': 'රැකූන්',
  'rain': 'වැසි',
  'restroom': 'වැසි කිළිය',
  'rhino': 'රයිනො',
  'river': 'නදිය',
  'rock': 'කුඹුර',
  'saxophone': 'සැක්සොෆෝන්',
  'scientist': 'විද්‍යාඥයා',
  'seagull': 'හාවා',
  'seal': 'සීල්',
  'sesame': 'තල්මහු',
  'shark': 'ශාක්',
  'sheep': 'ගොනා',
  'shirt': 'ශර්ට්',
  'singer': 'ගායකයා',
  'ski': 'ස්කි',
  'skunk': 'ස්කන්ක්',
  'sky': 'අහස',
  'snail': 'කුඩු',
  'snake': 'පවිල',
  'snow': 'හිම',
  'snowboard': 'ස්නොබෝඩ්',
  'soccer': 'ෆුට්බෝල්',
  'socks': 'සොක්ස්',
  'soil': 'මාටි',
  'soldier': 'සෙනා',
  'space': 'අකාශය',
  'sparrow': 'චුගුරුවා',
  'spinach': 'පාළු',
  'starfish': 'තරු මසුන්',
  'stewardess': 'ස්ටුවඩ්වෙස්',
  'stingray': 'ස්ටින්ග් රේ',
  'strawberry': 'ස්ට්‍රෝබෙරි',
  'sun': 'හිරු',
  'subway': 'උපමාර්ග රථ',
  'swallow': 'ස්වලෝ',
  'sweater': 'ස්වෙටර්',
  'swimming': 'හෙලීම',
  'swing': 'ඉරියව්',
  'table': 'මේසය',
  'tambourine': 'ටැම්බුරින්',
  'teacher': 'ගුරුවරයා',
  'tiger': 'පැටියා',
  'timpani': 'ටිම්පැනි',
  'toad': 'ටෝඩ්',
  'trampoline': 'ට්‍රැම්පොලීන්',
  'tree': 'ගස',
  'triangle': 'ත්‍රිකෝණය',
  'truck': 'ට්‍රක්',
  'trumpet': 'ට්‍රම්පෙට්',
  'turtle': 'කුලුබඩු',
  'typhoon': 'සුළං',
  'unicorn': 'යුනිකෝන්',
  'violin': 'වයලින්',
  'viking ship': 'වයිකින් නැව්',
  'volcano': 'වොල්කේනෝ',
  'volleyball': 'වොලිබෝල්',
  'vuvuzela': 'වුවුසෙලා',
  'waterfall': 'ජලාධාරය',
  'watermelon': 'දඹ',
  'wave': 'තරංගය',
  'whale': 'වේල්',
  'wind': 'සුළඟ',
  'window': 'කවුළ',
  'wolf': 'බළලා',
  'woodpecker': 'වුඩ්පෙක්කර්',
  'xylophone': 'සිලොෆෝන්',
  'yacht': 'යාච්ට්',
  'zebra': 'සෙබ්ර',
  'library': 'පුස්තකාලය',
  'post office': 'තැපැල් කාර්යාලය',
  'traffic light': 'ගමනාගමන ආලෝක',
  'clock tower': 'ගැලරි ටවර්',
  'pebble': 'කුඩා ගල්',
  'moss': 'මොස්',
  'cactus': 'කැක්ටස්',
  'rainbow': 'දුම්රිය පාලම',
  'toast': 'ටෝස්ට්',
  'cookie': 'කුකී',
  'ice cream': 'අයිස් ක්රීම්',
  'jelly': 'ජෙලි',
  'writer': 'ලේඛකයා',
  'actor': 'නළුවා',
  'crown': 'රාජ මුකුටය',
  'compass': 'දිශානුරූපය',
  'flowerpot': 'මල් බඳුන',
  'roller skates': 'රෝලර් ස්කේට්',
  'airport': 'ගුවන් තොටුපළ',
  'goldfish': 'රන් මස්',
  'spider': 'මකුළුවා',
  'light bulb': 'බල්බය',
  'mirror': 'කැඩපත',
  'magnet': 'චුම්බකය',
  'toothbrush': 'දත් බුරුසුව',
  'soap': 'සබන්',
  'plate': 'පිත්තල',
  'spoon': 'හැඳි',
  'mobile phone': 'ජංගම දුරකථනය',
  'key': 'යතුර',
  'newspaper': 'පුවත්පත',
  'calendar': 'දින දර්ශනය',
  'chair': 'කඩඉම',
  'sofa': 'සෝෆා',
  'refrigerator': 'ශීතකරණය',
  'stairs': 'පියගැට',
  'pillow': 'බාලිෂ්',
  'candle': 'මොම්බති',
  'bank': 'බැංකුව',
  'train': 'දුම්රිය',
  'squid': 'කුම්බා',
  'butterfly': 'සමනලයා',
  'bee': 'මී මැස්සා',
  'squirrel': 'ලේනා',
  'nurse': 'හෙදිය',
  'slide': 'ස්ලයිඩ්',
  'picnic': 'පික්නික්',
  'jacket': 'ජැකට්',
  'shoes': 'රෙදිපිළි',
  'tennis': 'ටෙනිස්'
};