final Map<String, String> slovakItemList = {

  'accordian': 'akordeón',
  'airplane': 'lietadlo',
  'anaconda': 'anakonda',
  'ant': 'mravec',
  'anteater': 'mravcovjedec',
  'apple': 'jablko',
  'apricot': 'marhuľa',
  'archery': 'lukostreľba',
  'astronaut': 'astronaut',
  'avocado': 'avokádo',
  'badminton': 'badminton',
  'banana': 'banán',
  'baseball': 'baseball',
  'basketball': 'basketbal',
  'bassoon': 'basoon',
  'bat': 'netopier',
  'beach': 'pláž',
  'bear': 'medveď',
  'bicycle': 'bicykel',
  'blackboard': 'čierna tabuľa',
  'blowfish': 'nafukovacia ryba',
  'blueberries': 'čučoriedky',
  'boar': 'kačací diviak',
  'book': 'kniha',
  'boots': 'čižmy',
  'bowling': 'bowling',
  'boxing': 'box',
  'broccoli': 'brokolica',
  'bumper car': 'bumpérové autíčko',
  'bus': 'autobus',
  'cabbage': 'kapusta',
  'camel': 'veľblúd',
  'carp': 'kapor',
  'carpenter': 'tesár',
  'carrot': 'mrkva',
  'castanets': 'kastaniety',
  'cat': 'mačka',
  'cello': 'cello',
  'chameleon': 'chameleón',
  'cheetah': 'gepard',
  'cherry': 'čerešňa',
  'chick': 'kuriatko',
  'chicken': 'kurča',
  'clarinet': 'klarinet',
  'classroom': 'trieda',
  'cloud': 'oblak',
  'cobra': 'kobra',
  'coconut': 'kokos',
  'computer': 'počítač',
  'conductor': 'dirigent',
  'contrabass': 'kontrabas',
  'cook': 'kuchár',
  'corn': 'kukurica',
  'cow': 'krava',
  'crab': 'krab',
  'crane': 'žeriav',
  'crocodile': 'krokodíl',
  'crow': 'havran',
  'cucumber': 'uhorka',
  'curling': 'curling',
  'cymbals': 'činely',
  'deer': 'jeleň',
  'dentist': 'zubár',
  'desert': 'púšť',
  'doctor': 'lekár',
  'dog': 'pes',
  'dolphin': 'delfín',
  'drum': 'bubon',
  'duck': 'kačica',
  'eagle': 'orel',
  'earthquake': 'zemetrasenie',
  'elephant': 'slon',
  'exam': 'skúška',
  'farmer': 'farmár',
  'fencing': 'šerm',
  'ferris wheel': 'ferris koleso',
  'fig': 'smokva',
  'firefighter': 'hasič',
  'fisherman': 'rybár',
  'flower': 'kvet',
  'flute': 'flétna',
  'fog': 'hmla',
  'forest': 'les',
  'fox': 'lišák',
  'friend': 'priateľ',
  'frog': 'žaba',
  'garlic': 'cesnak',
  'ginger': 'zázvor',
  'ginseng': 'ženšen',
  'giraffe': 'žirafa',
  'gloves': 'rukavice',
  'goat': 'koza',
  'golf': 'golf',
  'goose': 'husa',
  'gorilla': 'gorila',
  'grape': 'hrozno',
  'grapefruit': 'grepfrút',
  'guitar': 'gitara',
  'hairdressor': 'kaderník',
  'hallway': 'chodba',
  'harmonica': 'harmonika',
  'harp': 'harfa',
  'hat': 'klobúk',
  'hawk': 'jestreb',
  'helicopter': 'vrtuľník',
  'hippo': 'hroch',
  'hippocampus': 'hipokampus',
  'hockey': 'hokej',
  'horse': 'kôň',
  'hyena': 'hyena',
  'iceberg': 'ľadovec',
  'iguana': 'iguana',
  'jellyfish': 'medúza',
  'judge': 'súdca',
  'judo': 'judo',
  'jujube': 'jujube',
  'jungle': 'džungľa',
  'kangaroo': 'kangaroo',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'jazero',
  'lemon': 'citrón',
  'leopard': 'leopard',
  'lettuce': 'hlávkový šalát',
  'lightning': 'blesk',
  'lion': 'lev',
  'lizard': 'jašterica',
  'lobster': 'homár',
  'magpie': 'straka',
  'mango': 'mango',
  'marathon': 'maratón',
  'meerkat': 'meerkat',
  'melon': 'melón',
  'Merry go round': 'kolotoč',
  'mole': 'krtek',
  'monkey': 'opica',
  'moon': 'mesiac',
  'mountain': 'hora',
  'mouse': 'myš',
  'mushroom': 'huba',
  'notebook': 'zošit',
  'ocarina': 'ocarina',
  'ocean': 'oceán',
  'octopus': 'chobotnica',
  'onion': 'cibuľa',
  'orange': 'pomaranč',
  'orangutan': 'orangutan',
  'orchestra': 'orkester',
  'ostrich': 'pštros',
  'owl': 'sova',
  'painter': 'maľar',
  'pants': 'nohavice',
  'parrot': 'papagáj',
  'parsley': 'petržlen',
  'peach': 'broskyňa',
  'peacock': 'páv',
  'pelican': 'pelikán',
  'pencil': 'ceruzka',
  'penguin': 'tučniak',
  'pepper': 'piper',
  'pharmacist': 'farmaceut',
  'piano': 'piáno',
  'pickle': 'nakladaný uhorka',
  'pig': 'prasa',
  'pigeon': 'holub',
  'pilot': 'pilot',
  'pineapple': 'ananas',
  'platypus': 'platypus',
  'playground': 'detské ihrisko',
  'policeman': 'policajt',
  'pomegranate': 'granátové jablko',
  'potato': 'zemiak',
  'principal': 'riaditeľ školy',
  'professor': 'profesor',
  'pumpkin': 'tekvica',
  'rabbit': 'zajac',
  'raccoon': 'mýval',
  'rain': 'dážď',
  'restroom': 'toaleta',
  'rhino': 'nosorožec',
  'river': 'rieka',
  'rock': 'dmeň',
  'saxophone': 'saksofon',
  'scientist': 'vedec',
  'seagull': 'morská volavka',
  'seal': 'tulen',
  'sesame': 'sezam',
  'shark': 'žralok',
  'sheep': 'ovca',
  'shirt': 'košeľa',
  'singer': 'spevák',
  'ski': 'lyže',
  'skunk': 'skunk',
  'sky': 'obloha',
  'snail': 'puž',
  'snake': 'had',
  'snow': 'sneh',
  'snowboard': 'snowboard',
  'soccer': 'futbal',
  'socks': 'ponožky',
  'soil': 'pôda',
  'soldier': 'vojak',
  'space': 'vesmír',
  'sparrow': 'vrabec',
  'spinach': 'špenát',
  'starfish': 'morská hviezda',
  'stewardess': 'stjuardesa',
  'stingray': 'rejnok',
  'strawberry': 'jahoda',
  'sun': 'slnko',
  'subway': 'metro',
  'swallow': 'lastovička',
  'sweater': 'sveter',
  'swimming': 'plávanie',
  'swing': 'hojdačka',
  'table': 'stôl',
  'tambourine': 'tamburína',
  'teacher': 'učiteľ',
  'tiger': 'tiger',
  'timpani': 'timpani',
  'toad': 'roptavec',
  'trampoline': 'trampolína',
  'tree': 'strom',
  'triangle': 'trojuholník',
  'truck': 'nákladné auto',
  'trumpet': 'trubka',
  'turtle': 'korytnačka',
  'typhoon': 'tajfun',
  'unicorn': 'jednoroh',
  'violin': 'housle',
  'viking ship': 'vikingská loď',
  'volcano': 'sopka',
  'volleyball': 'volejbal',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'vodopád',
  'watermelon': 'vodný melón',
  'wave': 'vlna',
  'whale': 'veľryba',
  'wind': 'vietor',
  'window': 'okno',
  'wolf': 'vlk',
  'woodpecker': 'dúpavka',
  'xylophone': 'ksilofón',
  'yacht': 'jahta',
  'zebra': 'zebra',
  'library': 'knižnica',
  'post office': 'pošta',
  'traffic light': 'semafór',
  'clock tower': 'hodinová veža',
  'pebble': 'kamienok',
  'moss': 'mach',
  'cactus': 'kaktus',
  'rainbow': 'dúha',
  'toast': 'toast',
  'cookie': 'sušienka',
  'ice cream': 'zmrzlina',
  'jelly': 'želé',
  'writer': 'spisovateľ',
  'actor': 'herec',
  'crown': 'koruna',
  'compass': 'kompas',
  'flowerpot': 'kvetináč',
  'roller skates': 'kolieskové korčule',
  'airport': 'letisko',
  'goldfish': 'zlatá rybka',
  'spider': 'pavúk',
  'light bulb': 'žiarovka',
  'mirror': 'zrkadlo',
  'magnet': 'magnet',
  'toothbrush': 'zubná kefka',
  'soap': 'mydlo',
  'plate': 'tanier',
  'spoon': 'lyžička',
  'mobile phone': 'mobilný telefón',
  'key': 'kľúč',
  'newspaper': 'noviny',
  'calendar': 'kalendár',
  'chair': 'stolička',
  'sofa': 'gauč',
  'refrigerator': 'chladnička',
  'stairs': 'schody',
  'pillow': 'vankúš',
  'candle': 'sviečka',
  'bank': 'banka',
  'beetle': 'chrobák',
  'cicada': 'cikáda',
  'dragonfly': 'vážka',
  'earthworm': 'dážďovka',
  'komodo dragon': 'komodo drak',
  'mantis': 'modlivka',
  'mosquito': 'komár',
  'silkworm': 'hodvábnik',
  'stag beetle': 'roháč',
  'table tennis': 'stolný tenis',
  'train': 'vlak',
  'squid': 'kalamár',
  'butterfly': 'motýľ',
  'bee': 'včela',
  'squirrel': 'veverica',
  'nurse': 'sestra',
  'slide': 'šmykľavka',
  'picnic': 'piknik',
  'jacket': 'bunda',
  'shoes': 'topánky',
  'tennis': 'tenis'
};