final Map<String, String> slovenianItemList = {

  'accordian': 'harmonika',
  'airplane': 'letalo',
  'anaconda': 'anakonda',
  'ant': 'mravlja',
  'anteater': 'jedec mravelj',
  'apple': 'jabolko',
  'apricot': 'marelica',
  'archery': 'lukostrelstvo',
  'astronaut': 'astronavt',
  'avocado': 'avokado',
  'badminton': 'badminton',
  'banana': 'banana',
  'baseball': 'bejzbol',
  'basketball': 'košarka',
  'bassoon': 'basoon',
  'bat': 'netopir',
  'beach': 'plaža',
  'bear': 'medved',
  'bicycle': 'kolo',
  'blackboard': 'tabla',
  'blowfish': 'napuhana riba',
  'blueberries': 'borovnice',
  'boar': 'divja svinja',
  'book': 'knjiga',
  'boots': 'škornji',
  'bowling': 'kuglanje',
  'boxing': 'boks',
  'broccoli': 'brokoli',
  'bumper car': 'avto za trkanje',
  'bus': 'avtobus',
  'cabbage': 'zelje',
  'camel': 'deva',
  'carp': 'karp',
  'carpenter': 'tesar',
  'carrot': 'korenček',
  'castanets': 'kastanjeti',
  'cat': 'mačka',
  'cello': 'čelo',
  'chameleon': 'kamaleon',
  'cheetah': 'gepard',
  'cherry': 'češnja',
  'chick': 'piščanček',
  'chicken': 'piščanec',
  'clarinet': 'klarinet',
  'classroom': 'učilnica',
  'cloud': 'oblak',
  'cobra': 'kobra',
  'coconut': 'kokos',
  'computer': 'računalnik',
  'conductor': 'dirigent',
  'contrabass': 'kontrabas',
  'cook': 'kuhar',
  'corn': 'koruza',
  'cow': 'krava',
  'crab': 'rak',
  'crane': 'žerjav',
  'crocodile': 'krokodil',
  'crow': 'vrana',
  'cucumber': 'kumara',
  'curling': 'curling',
  'cymbals': 'cimbali',
  'deer': 'jelen',
  'dentist': 'zobozdravnik',
  'desert': 'puščava',
  'doctor': 'zdravnik',
  'dog': 'pes',
  'dolphin': 'dupini',
  'drum': 'boben',
  'duck': 'raca',
  'eagle': 'orel',
  'earthquake': 'potres',
  'elephant': 'slon',
  'exam': 'izpit',
  'farmer': 'kmet',
  'fencing': 'šerm',
  'ferris wheel': 'vrtiljak',
  'fig': 'smokva',
  'firefighter': 'gasilec',
  'fisherman': 'ribič',
  'flower': 'cvet',
  'flute': 'flavta',
  'fog': 'megla',
  'forest': 'gozd',
  'fox': 'lisica',
  'friend': 'prijatelj',
  'frog': 'žaba',
  'garlic': 'česen',
  'ginger': 'ingver',
  'ginseng': 'ženšen',
  'giraffe': 'žirafa',
  'gloves': 'rokavice',
  'goat': 'koza',
  'golf': 'golf',
  'goose': 'guska',
  'gorilla': 'gorila',
  'grape': 'grozdje',
  'grapefruit': 'grejpfrut',
  'guitar': 'kitara',
  'hairdressor': 'frizer',
  'hallway': 'hodnik',
  'harmonica': 'harmonika',
  'harp': 'harfa',
  'hat': 'klobuk',
  'hawk': 'jastreb',
  'helicopter': 'helikopter',
  'hippo': 'hipopotam',
  'hippocampus': 'hipokampus',
  'hockey': 'hokej',
  'horse': 'konj',
  'hyena': 'hijena',
  'iceberg': 'ledeni brijeg',
  'iguana': 'iguana',
  'jellyfish': 'meduza',
  'judge': 'sodnik',
  'judo': 'judo',
  'jujube': 'jujube',
  'jungle': 'džungla',
  'kangaroo': 'kangaroo',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'jezero',
  'lemon': 'limona',
  'leopard': 'leopard',
  'lettuce': 'zelena solata',
  'lightning': 'strela',
  'lion': 'lev',
  'lizard': 'gušter',
  'lobster': 'jastog',
  'magpie': 'magpie',
  'mango': 'mango',
  'marathon': 'maraton',
  'meerkat': 'meerkat',
  'melon': 'dinja',
  'Merry go round': 'karusel',
  'mole': 'krtek',
  'monkey': 'opica',
  'moon': 'luna',
  'mountain': 'gora',
  'mouse': 'miš',
  'mushroom': 'goba',
  'notebook': 'zvezek',
  'ocarina': 'okarina',
  'ocean': 'oceán',
  'octopus': 'hobotnica',
  'onion': 'čebula',
  'orange': 'oranžna',
  'orangutan': 'orangutan',
  'orchestra': 'orkester',
  'ostrich': 'noj',
  'owl': 'sova',
  'painter': 'slikar',
  'pants': 'hlače',
  'parrot': 'papagaj',
  'parsley': 'peršin',
  'peach': 'breskev',
  'peacock': 'paun',
  'pelican': 'pelikan',
  'pencil': 'svinčnik',
  'penguin': 'pingvin',
  'pepper': 'paprika',
  'pharmacist': 'farmacevt',
  'piano': 'klavir',
  'pickle': 'kiseli kumar',
  'pig': 'svinja',
  'pigeon': 'golob',
  'pilot': 'pilot',
  'pineapple': 'ananas',
  'platypus': 'platipus',
  'playground': 'igrišče',
  'policeman': 'policist',
  'pomegranate': 'nar',
  'potato': 'krumpir',
  'principal': 'ravnatelj',
  'professor': 'profesor',
  'pumpkin': 'buča',
  'rabbit': 'zec',
  'raccoon': 'rakun',
  'rain': 'dež',
  'restroom': 'toalet',
  'rhino': 'nosorog',
  'river': 'reka',
  'rock': 'kamen',
  'saxophone': 'saksofon',
  'scientist': 'znanstvenik',
  'seagull': 'morski galeb',
  'seal': 'tuljan',
  'sesame': 'sezam',
  'shark': 'morski pes',
  'sheep': 'ovca',
  'shirt': 'srajca',
  'singer': 'pevka',
  'ski': 'smučanje',
  'skunk': 'skunk',
  'sky': 'nebo',
  'snail': 'polž',
  'snake': 'kača',
  'snow': 'sneg',
  'snowboard': 'snežna deska',
  'soccer': 'nogomet',
  'socks': 'nogavice',
  'soil': 'tlo',
  'soldier': 'vojak',
  'space': 'vesolje',
  'sparrow': 'vrabec',
  'spinach': 'špinača',
  'starfish': 'morska zvezda',
  'stewardess': 'stjuardesa',
  'stingray': 'morska raža',
  'strawberry': 'jagoda',
  'sun': 'sonce',
  'subway': 'metro',
  'swallow': 'lastovka',
  'sweater': 'pulover',
  'swimming': 'plavanje',
  'swing': 'gugalnica',
  'table': 'miza',
  'tambourine': 'tamburin',
  'teacher': 'učitelj',
  'tiger': 'tigar',
  'timpani': 'timpani',
  'toad': 'krastača',
  'trampoline': 'trampolin',
  'tree': 'drevo',
  'triangle': 'trikotnik',
  'truck': 'kamion',
  'trumpet': 'trumpeta',
  'turtle': 'kornjača',
  'typhoon': 'tajfun',
  'unicorn': 'ednorog',
  'violin': 'violina',
  'viking ship': 'vikingska ladja',
  'volcano': 'vulkan',
  'volleyball': 'odbojka',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'slap',
  'watermelon': 'lubenica',
  'wave': 'val',
  'whale': 'kit',
  'wind': 'veter',
  'window': 'okno',
  'wolf': 'volk',
  'woodpecker': 'stukalica',
  'xylophone': 'ksilofon',
  'yacht': 'jahta',
  'zebra': 'zebra',
  'library': 'knjižnica',
  'post office': 'pošta',
  'traffic light': 'semafor',
  'clock tower': 'ura stolp',
  'pebble': 'kamenček',
  'moss': 'mah',
  'cactus': 'kaktus',
  'rainbow': 'mavrica',
  'toast': 'toast',
  'cookie': 'piškot',
  'ice cream': 'sladoled',
  'jelly': 'žele',
  'writer': 'pisatelj',
  'actor': 'igralec',
  'crown': 'krona',
  'compass': 'kompas',
  'flowerpot': 'cvetlični lonček',
  'roller skates': 'drsalke',
  'airport': 'letališče',
  'goldfish': 'zlata ribica',
  'spider': 'pajek',
  'light bulb': 'žarnica',
  'mirror': 'ogledalo',
  'magnet': 'magnet',
  'toothbrush': 'zobna ščetka',
  'soap': 'milo',
  'plate': 'krožnik',
  'spoon': 'žlica',
  'mobile phone': 'mobilni telefon',
  'key': 'ključ',
  'newspaper': 'časopis',
  'calendar': 'koledar',
  'chair': 'stol',
  'sofa': 'kavč',
  'refrigerator': 'hladilnik',
  'stairs': 'stopnice',
  'pillow': 'blazina',
  'candle': 'sveča',
  'bank': 'banka',
  'beetle': 'hrošč',
  'cicada': 'cvrčak',
  'dragonfly': 'kačja pastirica',
  'earthworm': 'deževnik',
  'komodo dragon': 'komodo zmaj',
  'mantis': 'bogomoljka',
  'mosquito': 'komar',
  'silkworm': 'svilen črv',
  'stag beetle': 'jelenjak',
  'table tennis': 'namizni tenis',
  'train': 'vlak',
  'squid': 'lignja',
  'butterfly': 'metulj',
  'bee': 'čebela',
  'squirrel': 'veverica',
  'nurse': 'medicinska sestra',
  'slide': 'drsalnica',
  'picnic': 'piknik',
  'jacket': 'jakna',
  'shoes': 'čevlji',
  'tennis': 'tenis'
};