final Map<String, String> swahiliItemList = {

  'accordian': 'akordioni',
  'airplane': 'ndege',
  'anaconda': 'anaconda',
  'ant': 'mchwa',
  'anteater': 'mteremchi',
  'apple': 'tufaa',
  'apricot': 'aprikoti',
  'archery': 'upigaji mshale',
  'astronaut': 'msafiri wa anga',
  'avocado': 'avokado',
  'badminton': 'badminton',
  'banana': 'ndizi',
  'baseball': 'baseball',
  'basketball': 'mpira wa kikapu',
  'bassoon': 'bassoon',
  'bat': 'popo',
  'beach': 'ufukwe',
  'bear': 'dubu',
  'bicycle': 'baiskeli',
  'blackboard': 'ubao mweusi',
  'blowfish': 'blowfish',
  'blueberries': 'blueberries',
  'boar': 'nguruwe pori',
  'book': 'kitabu',
  'boots': 'booti',
  'bowling': 'bowling',
  'boxing': 'boxing',
  'broccoli': 'brokoli',
  'bumper car': 'gari la bumper',
  'bus': 'basi',
  'cabbage': 'kabiji',
  'camel': 'kameli',
  'carp': 'karpi',
  'carpenter': 'karpentia',
  'carrot': 'karoti',
  'castanets': 'kastaneti',
  'cat': 'paka',
  'cello': 'cello',
  'chameleon': 'kameleon',
  'cheetah': 'duma',
  'cherry': 'cheri',
  'chick': 'kuku mchanga',
  'chicken': 'kuku',
  'clarinet': 'klarineti',
  'classroom': 'chumba cha masomo',
  'cloud': 'wingu',
  'cobra': 'kobra',
  'coconut': 'nazi',
  'computer': 'kompyuta',
  'conductor': 'kondakta',
  'contrabass': 'contrabass',
  'cook': 'mpishi',
  'corn': 'mahindi',
  'cow': 'ng\'ombe',
  'crab': 'kamba',
  'crane': 'krani',
  'crocodile': 'mamba',
  'crow': 'kunguru',
  'cucumber': 'mtango',
  'curling': 'curling',
  'cymbals': 'cymbals',
  'deer': 'paa',
  'dentist': 'daktari wa meno',
  'desert': 'jangwa',
  'doctor': 'daktari',
  'dog': 'mbwa',
  'dolphin': 'dofini',
  'drum': 'ngoma',
  'duck': 'bata',
  'eagle': 'tai',
  'earthquake': 'tetemeko la ardhi',
  'elephant': 'tembo',
  'exam': 'mtihani',
  'farmer': 'mkulima',
  'fencing': 'fencing',
  'ferris wheel': 'ferris wheel',
  'fig': 'figi',
  'firefighter': 'mwalinzi wa moto',
  'fisherman': 'mvuvi',
  'flower': 'ua',
  'flute': 'filuti',
  'fog': 'ukungu',
  'forest': 'msitu',
  'fox': 'mbweha',
  'friend': 'rafiki',
  'frog': 'chura',
  'garlic': 'kitunguu saumu',
  'ginger': 'tangawizi',
  'ginseng': 'ginseng',
  'giraffe': 'twiga',
  'gloves': 'glovu',
  'goat': 'mbuzi',
  'golf': 'golf',
  'goose': 'gusi',
  'gorilla': 'gorila',
  'grape': 'zabibu',
  'grapefruit': 'grapefruit',
  'guitar': 'gitaa',
  'hairdressor': 'mtaalamu wa nywele',
  'hallway': 'korido',
  'harmonica': 'harmonika',
  'harp': 'harpa',
  'hat': 'kofia',
  'hawk': 'mwewe',
  'helicopter': 'helikopta',
  'hippo': 'kiboko',
  'hippocampus': 'hippocampus',
  'hockey': 'hockey',
  'horse': 'farasi',
  'hyena': 'fisi',
  'iceberg': 'barafu',
  'iguana': 'iguana',
  'jellyfish': 'jellyfish',
  'judge': 'hakimu',
  'judo': 'judo',
  'jujube': 'jujube',
  'jungle': 'msitu mnene',
  'kangaroo': 'kangaroo',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'ziwa',
  'lemon': 'limau',
  'leopard': 'chui',
  'lettuce': 'letusi',
  'lightning': 'radi',
  'lion': 'simba',
  'lizard': 'dima',
  'lobster': 'lobasta',
  'magpie': 'magpie',
  'mango': 'embe',
  'marathon': 'marathon',
  'meerkat': 'meerkat',
  'melon': 'melon',
  'Merry go round': 'merry go round',
  'mole': 'mole',
  'monkey': 'nyani',
  'moon': 'mwezi',
  'mountain': 'mlima',
  'mouse': 'panya',
  'mushroom': 'uyoga',
  'notebook': 'daftari',
  'ocarina': 'ocarina',
  'ocean': 'bahari',
  'octopus': 'pweza',
  'onion': 'kitunguu',
  'orange': 'chungwa',
  'orangutan': 'orangutani',
  'orchestra': 'orkestra',
  'ostrich': 'mbuni',
  'owl': 'bundi',
  'painter': 'mpiga rangi',
  'pants': 'suruali',
  'parrot': 'kasuku',
  'parsley': 'parsley',
  'peach': 'pichi',
  'peacock': 'tausi',
  'pelican': 'pelikana',
  'pencil': 'penseli',
  'penguin': 'pengwini',
  'pepper': 'pilipili',
  'pharmacist': 'mfamasia',
  'piano': 'piano',
  'pickle': 'pickle',
  'pig': 'nguruwe',
  'pigeon': 'njiwa',
  'pilot': 'mpilipoti',
  'pineapple': 'nanasi',
  'platypus': 'platypus',
  'playground': 'uwanja wa michezo',
  'policeman': 'polisi',
  'pomegranate': 'pomegranate',
  'potato': 'viazi',
  'principal': 'mkuu wa shule',
  'professor': 'profesa',
  'pumpkin': 'kabochi',
  'rabbit': 'sungura',
  'raccoon': 'raccoon',
  'rain': 'mvua',
  'restroom': 'choo',
  'rhino': 'kifaru',
  'river': 'mto',
  'rock': 'jiwe',
  'saxophone': 'saksafoni',
  'scientist': 'mwanasayansi',
  'seagull': 'mwewe wa bahari',
  'seal': 'seal',
  'sesame': 'ufuta',
  'shark': 'papai',
  'sheep': 'kondoo',
  'shirt': 'shati',
  'singer': 'mwimbaji',
  'ski': 'ski',
  'skunk': 'skunk',
  'sky': 'anga',
  'snail': 'kinyara',
  'snake': 'nyoka',
  'snow': 'theluji',
  'snowboard': 'snowboard',
  'soccer': 'soka',
  'socks': 'soksi',
  'soil': 'udongo',
  'soldier': 'askari',
  'space': 'anga',
  'sparrow': 'sparrow',
  'spinach': 'mchicha',
  'starfish': 'nyota ya bahari',
  'stewardess': 'msaidizi wa ndege',
  'stingray': 'stingray',
  'strawberry': 'strawberry',
  'sun': 'jua',
  'subway': 'subway',
  'swallow': 'swallow',
  'sweater': 'sweater',
  'swimming': 'kuogelea',
  'swing': 'swingi',
  'table': 'meza',
  'tambourine': 'tamburini',
  'teacher': 'mwalimu',
  'tiger': 'tiger',
  'timpani': 'timpani',
  'toad': 'toad',
  'trampoline': 'trampoline',
  'tree': 'mti',
  'triangle': 'pembetatu',
  'truck': 'lori',
  'trumpet': 'trumpeti',
  'turtle': 'chewe',
  'typhoon': 'typhoon',
  'unicorn': 'unicorn',
  'violin': 'violini',
  'viking ship': 'meli ya Viking',
  'volcano': 'volkano',
  'volleyball': 'volleyball',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'maporomoko ya maji',
  'watermelon': 'tikiti maji',
  'wave': 'wimbi',
  'whale': 'nyangumi',
  'wind': 'upepo',
  'window': 'dirisha',
  'wolf': 'mbwa mwitu',
  'woodpecker': 'woodpecker',
  'xylophone': 'xilofoni',
  'yacht': 'yahti',
  'zebra': 'punda milia',
  'library': 'maktaba',
  'post office': 'posta',
  'traffic light': 'trafiki ya mwanga',
  'clock tower': 'mnara wa saa',
  'pebble': 'jiwe dogo',
  'moss': 'moss',
  'cactus': 'kaktasi',
  'rainbow': 'upinde wa mvua',
  'toast': 'mkate wa kukaanga',
  'cookie': 'biskuti',
  'ice cream': 'aiskrimu',
  'jelly': 'jeli',
  'writer': 'mwandishi',
  'actor': 'mwigizaji',
  'crown': 'taji',
  'compass': 'kibao cha kuelekeza',
  'flowerpot': 'chungu cha maua',
  'roller skates': 'viatu vya kuteleza',
  'airport': 'kiwanja cha ndege',
  'goldfish': 'samaki wa dhahabu',
  'spider': 'buibui',
  'light bulb': 'globu ya taa',
  'mirror': 'kioo',
  'magnet': 'sumaku',
  'toothbrush': 'mswaki wa meno',
  'soap': 'sabuni',
  'plate': 'sahani',
  'spoon': 'kijiko',
  'mobile phone': 'simu ya mkononi',
  'key': 'ufunguo',
  'newspaper': 'gazeti',
  'calendar': 'kalenda',
  'chair': 'kiti',
  'sofa': 'sofa',
  'refrigerator': 'jokofu',
  'stairs': 'ngazi',
  'pillow': 'mto',
  'candle': 'mshumaa',
  'bank': 'benki',
  'beetle': 'mende',
  'cicada': 'sikada',
  'dragonfly': 'kereng\'ende',
  'earthworm': 'mnyoo',
  'komodo dragon': 'komodo dragon',
  'mantis': 'dua',
  'mosquito': 'mbu',
  'silkworm': 'mnyoo wa hariri',
  'stag beetle': 'mende wa pembe',
  'table tennis': 'tenisi ya meza',
  'train': 'gari la moshi',
  'squid': 'pweza',
  'butterfly': 'kipepeo',
  'bee': 'nyuki',
  'squirrel': 'chindi',
  'nurse': 'muuguzi',
  'slide': 'telemko',
  'picnic': 'chakula cha nje',
  'jacket': 'koti',
  'shoes': 'viatu',
  'tennis': 'tenisi'
};