final Map<String, String> tamilItemList = {

  'accordian': 'அக்கார்டியன்',
  'airplane': 'விமானம்',
  'anaconda': 'அனகாண்டா',
  'ant': 'எறும்பு',
  'anteater': 'எறும்பு உண்ணுபவர்',
  'apple': 'ஆப்பிள்',
  'apricot': 'அப்ரிகாட்',
  'archery': 'ஆர்ச்சரி',
  'astronaut': 'விண்ணுலக பயணி',
  'avocado': 'அவகாடோ',
  'badminton': 'பேட்மிண்டன்',
  'banana': 'வாழைப்பழம்',
  'baseball': 'பேஸ்பால்',
  'basketball': 'பாஸ்கெட்ட்பால்',
  'bassoon': 'பேசூன்',
  'bat': 'வாத்து',
  'beach': 'கடலோரம்',
  'bear': 'கரடி',
  'bicycle': 'சைக்கிள்',
  'blackboard': 'கருப்பு பலகை',
  'blowfish': 'ப்ளோஃபிஷ்',
  'blueberries': 'நீலப்பழம்',
  'boar': 'காட்டு பன்றி',
  'book': 'புத்தகம்',
  'boots': 'காலணிகள்',
  'bowling': 'போவுலிங்',
  'boxing': 'பாக்சிங்',
  'broccoli': 'பிராகோலி',
  'bumper car': 'பம்பர் கார்',
  'bus': 'பஸ்',
  'cabbage': 'முட்டைக் கொசு',
  'camel': 'ஊட்டகம்',
  'carp': 'கார்ப்',
  'carpenter': 'கார்பென்டர்',
  'carrot': 'கேரட்',
  'castanets': 'காஸ்டனெட்ஸ்',
  'cat': 'பூனை',
  'cello': 'செல்லோ',
  'chameleon': 'சாமெலியன்',
  'cheetah': 'சீட்டா',
  'cherry': 'செரி',
  'chick': 'குழந்தை கோழி',
  'chicken': 'கோழி',
  'clarinet': 'கிளாரினெட்',
  'classroom': 'வகுப்பு அறை',
  'cloud': 'மெகம்',
  'cobra': 'கொப்ரா',
  'coconut': 'தேங்காய்',
  'computer': 'கணினி',
  'conductor': 'ஓட்டுநர்',
  'contrabass': 'கொன்ட்ராபாஸ்',
  'cook': 'சமையல்காரர்',
  'corn': 'மக்காச்சோள',
  'cow': 'மாடு',
  'crab': 'நண்டு',
  'crane': 'கிரேன்',
  'crocodile': 'முதலை',
  'crow': 'காகம்',
  'cucumber': 'வெள்ளரிக்காய்',
  'curling': 'கர்ளிங்',
  'cymbals': 'சிம்பல்ஸ்',
  'deer': 'மான்',
  'dentist': 'பல் மருத்துவர்',
  'desert': 'மருதாணி',
  'doctor': 'மருத்துவர்',
  'dog': 'நாய்',
  'dolphin': 'டால்பின்',
  'drum': 'தடம்',
  'duck': 'வாத்து',
  'eagle': 'கழுகு',
  'earthquake': 'நிலநடுக்கம்',
  'elephant': 'யானை',
  'exam': 'பரீட்சை',
  'farmer': 'உழவர்',
  'fencing': 'ஃபென்சிங்',
  'ferris wheel': 'ஃபெரிஸ் சக்கரம்',
  'fig': 'அத்திப்பழம்',
  'firefighter': 'தீ அணைப்பவர்',
  'fisherman': 'மீனவர்',
  'flower': 'பூ',
  'flute': 'புலூட்',
  'fog': 'மூடு',
  'forest': 'காடு',
  'fox': 'நரி',
  'friend': 'தோழர்',
  'frog': 'தவள',
  'garlic': 'பூண்டு',
  'ginger': 'இஞ்சி',
  'ginseng': 'ஜின்செங்',
  'giraffe': 'ஜிராஃப்',
  'gloves': 'கையுறை',
  'goat': 'ஆடு',
  'golf': 'கால்ஃப்',
  'goose': 'ஆந்தை',
  'gorilla': 'கொரில்லா',
  'grape': 'திராட்சை',
  'grapefruit': 'கிரேப் ஃப்ரூட்',
  'guitar': 'கிட்டார்',
  'hairdressor': 'முடி அலங்கரிப்பவர்',
  'hallway': 'தெரு',
  'harmonica': 'ஹார்மொனிகா',
  'harp': 'ஹார்ப்',
  'hat': 'தோப்பி',
  'hawk': 'ஹாக்',
  'helicopter': 'ஹெலிகாப்டர்',
  'hippo': 'ஹிப்போ',
  'hippocampus': 'ஹிப்போகாம்பஸ்',
  'hockey': 'ஹாக்கி',
  'horse': 'குதிரை',
  'hyena': 'ஹைனா',
  'iceberg': 'ஐஸ்பெர்க்',
  'iguana': 'இகுவானா',
  'jellyfish': 'ஜெல்லிபிஷ்',
  'judge': 'நியாயாதிபதி',
  'judo': 'ஜூடோ',
  'jujube': 'ஜூஜூப்',
  'jungle': 'அரண்யம்',
  'kangaroo': 'காங்கரூ',
  'kiwi': 'கிவி',
  'koala': 'கோலா',
  'lake': 'ஆறை',
  'lemon': 'எலுமிச்சை',
  'leopard': 'லெபார்டு',
  'lettuce': 'லெட்டூஸ்',
  'lightning': 'மின்னல்',
  'lion': 'சிங்கம்',
  'lizard': 'இளங்கோளி',
  'lobster': 'லாப்ஸ்டர்',
  'magpie': 'மெக்பை',
  'mango': 'மாம்பழம்',
  'marathon': 'மாரத்தான்',
  'meerkat': 'மீர்காட்',
  'melon': 'தர்பூசு',
  'Merry go round': 'சக்கரம்',
  'mole': 'மோல்',
  'monkey': 'குரங்கு',
  'moon': 'சந்திரன்',
  'mountain': 'மலை',
  'mouse': 'எலி',
  'mushroom': 'கூண்',
  'notebook': 'குறிப்புத்தாள்',
  'ocarina': 'ஒகரினா',
  'ocean': 'கடல்',
  'octopus': 'ஆக்டோபஸ்',
  'onion': 'வெங்காயம்',
  'orange': 'ஆரஞ்சு',
  'orangutan': 'ஆரங்குடான்',
  'orchestra': 'இசைக்குழு',
  'ostrich': 'நாக்கு',
  'owl': 'பூச்சை',
  'painter': 'சித்தர்',
  'pants': 'காலணிகள்',
  'parrot': 'தோதை',
  'parsley': 'பார்ஸ்லி',
  'peach': 'பீச்',
  'peacock': 'மயில்',
  'pelican': 'பெலிகன்',
  'pencil': 'பென்சில்',
  'penguin': 'பெங்குவின்',
  'pepper': 'மிளகு',
  'pharmacist': 'ஃபார்மசிஸ்ட்',
  'piano': 'பியாணோ',
  'pickle': 'அச்சார்',
  'pig': 'பன்றி',
  'pigeon': 'துறுவன்',
  'pilot': 'பைலட்',
  'pineapple': 'அன்னாசி',
  'platypus': 'பிளாட்டிபஸ்',
  'playground': 'விளையாட்டு மைதானம்',
  'policeman': 'போலீசார்',
  'pomegranate': 'மாதுளை',
  'potato': 'உருளைக்கிழங்கு',
  'principal': 'தலைமையாளர்',
  'professor': 'ப்ரொபசர்',
  'pumpkin': 'பூசணி',
  'rabbit': 'முயல்',
  'raccoon': 'ரேகூன்',
  'rain': 'மழை',
  'restroom': 'கழிப்பறை',
  'rhino': 'கொண்டை',
  'river': 'ஆறு',
  'rock': 'கல்',
  'saxophone': 'சாக்ஸோபோன்',
  'scientist': 'அறிஞர்',
  'seagull': 'கடல் புறா',
  'seal': 'சீல்',
  'sesame': 'எள்',
  'shark': 'சுறா',
  'sheep': 'ஷீப்',
  'shirt': 'சேர்ட்',
  'singer': 'பாடகர்',
  'ski': 'ஸ்கீ',
  'skunk': 'ஸ்கங்க்',
  'sky': 'வானம்',
  'snail': 'ஸ்நெயில்',
  'snake': 'பாம்பு',
  'snow': 'பனி',
  'snowboard': 'ஸ்நோபோர்டு',
  'soccer': 'கால்பந்து',
  'socks': 'சாக்ஸ்',
  'soil': 'மண்',
  'soldier': 'படை வீரர்',
  'space': 'விண்ணகம்',
  'sparrow': 'குறுவி',
  'spinach': 'முருங்கைக்கீரை',
  'starfish': 'தாராமீன்',
  'stewardess': 'ஸ்டூவர்டெஸ்',
  'stingray': 'ஸ்டிங்ரே',
  'strawberry': 'ஸ்ட்ராபெரி',
  'sun': 'சூரியன்',
  'subway': 'தளம் ரயில்',
  'swallow': 'ஸ்வாலோ',
  'sweater': 'ஸ்வெட்டர்',
  'swimming': 'நீச்சல்',
  'swing': 'ஸ்விங்',
  'table': 'மேசை',
  'tambourine': 'டாம்போரின்',
  'teacher': 'ஆசிரியர்',
  'tiger': 'புலி',
  'timpani': 'டிம்பானி',
  'toad': 'தவளை',
  'trampoline': 'ட்ராம்போலின்',
  'tree': 'மரம்',
  'triangle': 'முக்கோணம்',
  'truck': 'டிரக்',
  'trumpet': 'ட்ரம்பெட்',
  'turtle': 'ஆமை',
  'typhoon': 'புயல்',
  'unicorn': 'யுனிகார்ன்',
  'violin': 'வயலின்',
  'viking ship': 'வைகிங்கின் கப்பல்',
  'volcano': 'அக்னிவெளி',
  'volleyball': 'வாலிபால்',
  'vuvuzela': 'வுவூசெலா',
  'waterfall': 'நீர்வீழ்ச்சி',
  'watermelon': 'தர்பூசணி',
  'wave': 'அலை',
  'whale': 'வாலா',
  'wind': 'காற்று',
  'window': 'ஜன்னல்',
  'wolf': 'வுல்ப்',
  'woodpecker': 'வுட்பெக்கர்',
  'xylophone': 'ஜைலோபோன்',
  'yacht': 'யாட்',
  'zebra': 'செப்ரா',
  'library': 'நூலகம்',
  'post office': 'அஞ்சலகம்',
  'traffic light': 'போக்குவரத்து விளக்கு',
  'clock tower': 'கடிகார கோபுரம்',
  'pebble': 'சிறு கல்',
  'moss': 'பாசி',
  'cactus': 'கற்றாழை',
  'rainbow': 'வானவில்',
  'toast': 'வறுத்த ரொட்டி',
  'cookie': 'குக்கி',
  'ice cream': 'பனிக்கூழ்',
  'jelly': 'ஜெல்லி',
  'writer': 'எழுத்தாளர்',
  'actor': 'நடிகர்',
  'crown': 'முடி',
  'compass': 'திசைகாட்டி',
  'flowerpot': 'மலர் தொட்டி',
  'roller skates': 'ரோலர் ஸ்கேட்',
  'airport': 'விமான நிலையம்',
  'goldfish': 'தங்க மீன்',
  'spider': 'சிலந்தி',
  'light bulb': 'மின்விளக்கு',
  'mirror': 'கண்ணாடி',
  'magnet': 'காந்தம்',
  'toothbrush': 'பல் துலக்கி',
  'soap': 'சோப்பு',
  'plate': 'தட்டு',
  'spoon': 'கரண்டி',
  'mobile phone': 'மொபைல் போன்',
  'key': 'திறவுகோல்',
  'newspaper': 'செய்தித்தாள்',
  'calendar': 'நாட்காட்டி',
  'chair': 'நாற்காலி',
  'sofa': 'சோபா',
  'refrigerator': 'குளிர்சாதன பெட்டி',
  'stairs': 'படிக்கட்டு',
  'pillow': 'தலையணை',
  'candle': 'மெழுகுவர்த்தி',
  'bank': 'வங்கி',
  'beetle': 'வண்டு',
  'cicada': 'சிக்காடா',
  'dragonfly': 'டிராகன்ஃபிளை',
  'earthworm': 'மண்புழு',
  'komodo dragon': 'கோமோடோ டிராகன்',
  'mantis': 'மாண்டிஸ்',
  'mosquito': 'கொசு',
  'silkworm': 'பட்டுப்புழு',
  'stag beetle': 'ஸ்டாக் பீடில்',
  'table tennis': 'டேபிள் டென்னிஸ்',
  'train': 'ரயில்',
  'squid': 'சிட்',
  'butterfly': 'வண்ணத்துப்பூச்சி',
  'bee': 'தேனீ',
  'squirrel': 'அணில்',
  'nurse': 'நர்ஸ்',
  'slide': 'ஸ்லைட்',
  'picnic': 'பிக்னிக்',
  'jacket': 'ஜாக்கெட்',
  'shoes': 'காலணிகள்',
  'tennis': 'டென்னிஸ்'
};