final Map<String, String> teluguItemList = {

  'accordian': 'అకార్డియన్',
  'airplane': 'విమానం',
  'anaconda': 'అనకాండ',
  'ant': 'ఎరుంగుళ్ళు',
  'anteater': 'ఎరుంగుళ్లు తినేవాడు',
  'apple': 'ఆపిల్',
  'apricot': 'అప్రికాట్',
  'archery': 'ధనుస్సు గోలింపులు',
  'astronaut': 'అంతరిక్షయాత్రికుడు',
  'avocado': 'అవకాడో',
  'badminton': 'బ్యాడ్మింటన్',
  'banana': 'అరటి పండు',
  'baseball': 'బేస్బాల్',
  'basketball': 'బాస్కెట్‌బాల్',
  'bassoon': 'బాసూన్',
  'bat': 'చమగాడు',
  'beach': 'సముద్ర తీరము',
  'bear': 'ఎలుగుబంటి',
  'bicycle': 'సైకిల్',
  'blackboard': 'కరుపు బోర్డు',
  'blowfish': 'బ్లోఫిష్',
  'blueberries': 'నీలి బెర్రీలు',
  'boar': 'అడవి పంది',
  'book': 'పుస్తకం',
  'boots': 'బూట్లు',
  'bowling': 'బోలింగ్',
  'boxing': 'బాక్సింగ్',
  'broccoli': 'బ్రొకలీ',
  'bumper car': 'బంపర్ కారు',
  'bus': 'బస్',
  'cabbage': 'క్యాబేజి',
  'camel': 'ఊటు',
  'carp': 'కార్ప్',
  'carpenter': 'కార్పెంటర్',
  'carrot': 'గాజర్',
  'castanets': 'క్యాస్టానెట్స్',
  'cat': 'పిల్లి',
  'cello': 'సెల్లో',
  'chameleon': 'చమెలియాన్',
  'cheetah': 'చీత',
  'cherry': 'చెర్రీ',
  'chick': 'కొడుక్కూర్చు',
  'chicken': 'కోడి',
  'clarinet': 'క్లారినెట్',
  'classroom': 'తరగతి గది',
  'cloud': 'మేఘం',
  'cobra': 'కోబ్రా',
  'coconut': 'తెంగాకు',
  'computer': 'కంప్యూటర్',
  'conductor': 'కండక్టర్',
  'contrabass': 'కాంట్రాబాస్',
  'cook': 'వంటగాడు',
  'corn': 'మక్క',
  'cow': 'పశు',
  'crab': 'క్రాబ్',
  'crane': 'క్రేన్',
  'crocodile': 'తిమింగలం',
  'crow': 'కాకి',
  'cucumber': 'దోసకాయ',
  'curling': 'కర్లింగ్',
  'cymbals': 'సింబల్స్',
  'deer': 'జింక',
  'dentist': 'దంత వైద్యుడు',
  'desert': 'మరూదేస్ట్',
  'doctor': 'డాక్టర్',
  'dog': 'కుక్క',
  'dolphin': 'డాల్ఫిన్',
  'drum': 'డ్రమ్',
  'duck': 'డక్క',
  'eagle': 'గరుడ',
  'earthquake': 'భూకంపం',
  'elephant': 'ఏనుగు',
  'exam': 'పరీక్ష',
  'farmer': 'రైతు',
  'fencing': 'ఫెన్సింగ్',
  'ferris wheel': 'ఫెరిస్ వీల్',
  'fig': 'అత్తిపండు',
  'firefighter': 'మంట నివారకుడు',
  'fisherman': 'మీనివాడు',
  'flower': 'పూలు',
  'flute': 'మురళి',
  'fog': 'మబ్బు',
  'forest': 'అరణ్యం',
  'fox': 'నక్క',
  'friend': 'స్నేహితుడు',
  'frog': 'తవ్వ',
  'garlic': 'వెళ్లులి',
  'ginger': 'ఇంగువ',
  'ginseng': 'జిన్సెంగ్',
  'giraffe': 'జిరాఫ్',
  'gloves': 'గ్లౌవ్స్',
  'goat': 'మేక',
  'golf': 'గోల్ఫ్',
  'goose': 'గూస్',
  'gorilla': 'గొరిల్లా',
  'grape': 'ద్రాక్ష',
  'grapefruit': 'గ్రేప్‌ఫ్రూట్',
  'guitar': 'గిటార్',
  'hairdressor': 'హేర్‌డ్రెసర్',
  'hallway': 'హాల్వే',
  'harmonica': 'హార్మోనికా',
  'harp': 'హార్ప్',
  'hat': 'టోపీ',
  'hawk': 'హాక్',
  'helicopter': 'హెలికాప్టర్',
  'hippo': 'హిప్పోపోటామస్',
  'hippocampus': 'హిపోకాంపస్',
  'hockey': 'హాకీ',
  'horse': 'అశ్వము',
  'hyena': 'హైయినా',
  'iceberg': 'ఐస్‌బర్గ్',
  'iguana': 'ఇగువానా',
  'jellyfish': 'జెల్లీఫిష్',
  'judge': 'న్యాయమూర్తి',
  'judo': 'జూడో',
  'jujube': 'జూజుబ్',
  'jungle': 'అరణ్యం',
  'kangaroo': 'కంగారూ',
  'kiwi': 'కివీ',
  'koala': 'కోఅలా',
  'lake': 'సరస్సు',
  'lemon': 'నిమ్మ',
  'leopard': 'తేందువ',
  'lettuce': 'లెట్ట్యూస్',
  'lightning': 'విద్యుత్ కిరణం',
  'lion': 'సింహం',
  'lizard': 'లిజర్డ్',
  'lobster': 'లోబ్స్టర్',
  'magpie': 'మ్యాగ్పై',
  'mango': 'మామిడి',
  'marathon': 'మారథాన్',
  'meerkat': 'మీరక్యాట్',
  'melon': 'మెలన్',
  'Merry go round': 'మేరీ గో రౌండ్',
  'mole': 'మోల్',
  'monkey': 'కోతి',
  'moon': 'చంద్రుడు',
  'mountain': 'పర్వతం',
  'mouse': 'ఎలుక',
  'mushroom': 'మష్రూమ్',
  'notebook': 'నోట్బుక్',
  'ocarina': 'ఓకారినా',
  'ocean': 'సముద్రం',
  'octopus': 'ఆక్టోపస్',
  'onion': 'ఉల్లిపాయ',
  'orange': 'నారింజ',
  'orangutan': 'ఒరంగుటాన్',
  'orchestra': 'ఒర్కెస్ట్రా',
  'ostrich': 'శుతురము',
  'owl': 'ఓవల్',
  'painter': 'చిత్రకారుడు',
  'pants': 'ప్యాంట్లు',
  'parrot': 'ప్యారట్',
  'parsley': 'పార్స్లీ',
  'peach': 'పీచ్',
  'peacock': 'మయూరం',
  'pelican': 'పెలికన్',
  'pencil': 'పెన్సిల్',
  'penguin': 'పెంగ్విన్',
  'pepper': 'మిరియాలు',
  'pharmacist': 'ఫార్మసిస్ట్',
  'piano': 'పియానో',
  'pickle': 'పిక్కుల్',
  'pig': 'పంది',
  'pigeon': 'పావురం',
  'pilot': 'పైలట్',
  'pineapple': 'అన్నాస',
  'platypus': 'ప్లాటిపస్',
  'playground': 'ఆడుకునే ప్రాంగణం',
  'policeman': 'పోలీసు',
  'pomegranate': 'దానిమ్మ',
  'potato': 'బంగాళాదుంప',
  'principal': 'ప్రధాన అధ్యాపకుడు',
  'professor': 'ప్రొఫెసర్',
  'pumpkin': 'గుమ్మడికాయ',
  'rabbit': 'రాబిట్',
  'raccoon': 'రక్కూన్',
  'rain': 'వర్షం',
  'restroom': 'శౌచాలయం',
  'rhino': 'గేదె',
  'river': 'నది',
  'rock': 'గడ్డ',
  'saxophone': 'సాక్సోఫోన్',
  'scientist': 'శాస్త్రవేత్త',
  'seagull': 'సముద్ర పక్షి',
  'seal': 'సీల్',
  'sesame': 'నువ్వు',
  'shark': 'షార్క్',
  'sheep': 'షీప్',
  'shirt': 'షర్ట్',
  'singer': 'గాయకుడు',
  'ski': 'స్కీ',
  'skunk': 'స్కంక్',
  'sky': 'ఆకాశం',
  'snail': 'స్నయిల్',
  'snake': 'పాము',
  'snow': 'మంచు',
  'snowboard': 'స్నోబోర్డు',
  'soccer': 'ఫుట్‌బాల్',
  'socks': 'సాక్స్',
  'soil': 'మట్టి',
  'soldier': 'సైనికుడు',
  'space': 'అంతరిక్షం',
  'sparrow': 'స్పారో',
  'spinach': 'పాలకూర',
  'starfish': 'నక్షత్ర చేప',
  'stewardess': 'స్ట్యువర్డ్‌టెస్',
  'stingray': 'స్టింగ్‌రే',
  'strawberry': 'స్ట్రాబెర్రీ',
  'sun': 'సూర్యుడు',
  'subway': 'సబ్‌వే',
  'swallow': 'స్వాలో',
  'sweater': 'స్వెటర్',
  'swimming': 'తెరచడం',
  'swing': 'స్వింగ్',
  'table': 'మెజ్',
  'tambourine': 'టాంబోరిన్',
  'teacher': 'గురువు',
  'tiger': 'పులి',
  'timpani': 'టింపాని',
  'toad': 'టోడ్',
  'trampoline': 'ట్రాంపోలిన్',
  'tree': 'మరము',
  'triangle': 'త్రికోణం',
  'truck': 'ట్రక్',
  'trumpet': 'ట్రంపెట్',
  'turtle': 'కప్ప',
  'typhoon': 'తుఫాను',
  'unicorn': 'యూనీకార్న్',
  'violin': 'వయోలిన్',
  'viking ship': 'వైకింగ్ పడవ',
  'volcano': 'అగ్ని పర్వతం',
  'volleyball': 'వాలీబాల్',
  'vuvuzela': 'వువుజెలా',
  'waterfall': 'జలపాతం',
  'watermelon': 'వాటర్మెలన్',
  'wave': 'తరంగం',
  'whale': 'వేల్',
  'wind': 'గాలి',
  'window': 'జానల్',
  'wolf': 'వోల్ఫ్',
  'woodpecker': 'వుడ్‌పెకర్',
  'xylophone': 'జైలోఫోన్',
  'yacht': 'యాచ్',
  'zebra': 'జెబ్రా',
  'library': 'గ్రంథాలయం',
  'post office': 'తపాలా కార్యాలయం',
  'traffic light': 'ట్రాఫిక్ లైట్',
  'clock tower': 'గడియార గోపురం',
  'pebble': 'చిన్న రాయి',
  'moss': 'పాచి',
  'cactus': 'కాక్టస్',
  'rainbow': 'ఇంద్రధనుస్సు',
  'toast': 'వేయించిన రొట్టె',
  'cookie': 'కుకీ',
  'ice cream': 'ఐస్ క్రీమ్',
  'jelly': 'జెల్లీ',
  'writer': 'రచయిత',
  'actor': 'నటుడు',
  'crown': 'కిరీటం',
  'compass': 'దిక్సూచి',
  'flowerpot': 'పువ్వుల కుండ',
  'roller skates': 'రోలర్ స్కేట్స్',
  'airport': 'విమానాశ్రయం',
  'goldfish': 'బంగారు చేప',
  'spider': 'సాలెపురుగు',
  'light bulb': 'లైట్ బల్బ్',
  'mirror': 'అద్దం',
  'magnet': 'అయస్కాంతం',
  'toothbrush': 'దంత శుభ్రత',
  'soap': 'సబ్బు',
  'plate': 'ప్లేట్',
  'spoon': 'చెంచా',
  'mobile phone': 'మొబైల్ ఫోన్',
  'key': 'కీ',
  'newspaper': 'వార్తాపత్రిక',
  'calendar': 'క్యాలెండర్',
  'chair': 'కుర్చీ',
  'sofa': 'సోఫా',
  'refrigerator': 'రిఫ్రిజిరేటర్',
  'stairs': 'మెట్లు',
  'pillow': 'తలగడ',
  'candle': 'మొమ్బత్తి',
  'bank': 'బ్యాంక్',
  'beetle': 'వీటిల్',
  'cicada': 'సికాడా',
  'dragonfly': 'డ్రాగన్ ఫ్లై',
  'earthworm': 'భూమి పురుగు',
  'komodo dragon': 'కోమోడో డ్రాగన్',
  'mantis': 'మాంటిస్',
  'mosquito': 'దోమ',
  'silkworm': 'పట్టు పురుగు',
  'stag beetle': 'స్టాగ్ బీటిల్',
  'table tennis': 'టేబుల్ టెన్నిస్',
  'train': 'రైలు',
  'squid': 'స్క్విడ్',
  'butterfly': 'సీతాకోకచిలుక',
  'bee': 'తేనెటీగ',
  'squirrel': 'అణిల',
  'nurse': 'నర్స్',
  'slide': 'స్లైడ్',
  'picnic': 'పిక్నిక్',
  'jacket': 'జాకెట్',
  'shoes': 'బూట్లు',
  'tennis': 'టెన్నిస్'
};