final Map<String, String> turItemList = {

  'accordian': 'akordeon',
  'airplane': 'uçak',
  'anaconda': 'anakonda',
  'ant': 'karınca',
  'anteater': 'karıncayiyen',
  'apple': 'elma',
  'apricot': 'kayısı',
  'archery': 'okçuluk',
  'astronaut': 'astronot',
  'avocado': 'avokado',
  'badminton': 'badminton',
  'banana': 'muz',
  'baseball': 'beyzbol',
  'basketball': 'basketbol',
  'bassoon': 'fagot',
  'bat': 'yarasa',
  'beach': 'plaj',
  'bear': 'ayı',
  'bicycle': 'bisiklet',
  'blackboard': 'kara tahta',
  'blowfish': 'balon balığı',
  'blueberries': 'yaban mersini',
  'boar': 'yaban domuzu',
  'book': 'kitap',
  'boots': 'botlar',
  'bowling': 'bovling',
  'boxing': 'boks',
  'broccoli': 'brokoli',
  'bumper car': 'çarpışan araba',
  'bus': 'otobüs',
  'cabbage': 'lahana',
  'camel': 'deve',
  'carp': 'sazan',
  'carpenter': 'marangoz',
  'carrot': 'havuç',
  'castanets': 'kastanyet',
  'cat': 'kedi',
  'cello': 'çello',
  'chameleon': 'bukalemun',
  'cheetah': 'çita',
  'cherry': 'kiraz',
  'chick': 'civciv',
  'chicken': 'tavuk',
  'clarinet': 'klarnet',
  'classroom': 'sınıf',
  'cloud': 'bulut',
  'cobra': 'kobra',
  'coconut': 'hindistancevizi',
  'computer': 'bilgisayar',
  'conductor': 'orkestra şefi',
  'contrabass': 'kontrbas',
  'cook': 'aşçı',
  'corn': 'mısır',
  'cow': 'inek',
  'crab': 'yengeç',
  'crane': 'vinç',
  'crocodile': 'timsah',
  'crow': 'karga',
  'cucumber': 'salatalık',
  'curling': 'körling',
  'cymbals': 'zil',
  'deer': 'geyik',
  'dentist': 'diş hekimi',
  'desert': 'çöl',
  'doctor': 'doktor',
  'dog': 'köpek',
  'dolphin': 'yunus',
  'drum': 'davul',
  'duck': 'ördek',
  'eagle': 'kartal',
  'earthquake': 'deprem',
  'elephant': 'fil',
  'exam': 'sınav',
  'farmer': 'çiftçi',
  'fencing': 'eskrim',
  'ferris wheel': 'dönme dolap',
  'fig': 'incir',
  'firefighter': 'itfaiyeci',
  'fisherman': 'balıkçı',
  'flower': 'çiçek',
  'flute': 'flüt',
  'fog': 'sis',
  'forest': 'orman',
  'fox': 'tilki',
  'friend': 'arkadaş',
  'frog': 'kurbağa',
  'garlic': 'sarımsak',
  'ginger': 'zencefil',
  'ginseng': 'ginseng',
  'giraffe': 'zürafa',
  'gloves': 'eldiven',
  'goat': 'keçi',
  'golf': 'golf',
  'goose': 'kaz',
  'gorilla': 'goril',
  'grape': 'üzüm',
  'grapefruit': 'greyfurt',
  'guitar': 'gitar',
  'hairdressor': 'kuaför',
  'hallway': 'koridor',
  'harmonica': 'armonika',
  'harp': 'arpa',
  'hat': 'şapka',
  'hawk': 'şahin',
  'helicopter': 'helikopter',
  'hippo': 'su aygırı',
  'hippocampus': 'denizatı',
  'hockey': 'hokey',
  'horse': 'at',
  'hyena': 'sırtlan',
  'iceberg': 'buzdağı',
  'iguana': 'iguana',
  'jellyfish': 'denizanası',
  'judge': 'hakim',
  'judo': 'judo',
  'jujube': 'hünnap',
  'jungle': 'orman',
  'kangaroo': 'kanguru',
  'kiwi': 'kivi',
  'koala': 'koala',
  'lake': 'göl',
  'lemon': 'limon',
  'leopard': 'leopar',
  'lettuce': 'marul',
  'lightning': 'şimşek',
  'lion': 'aslan',
  'lizard': 'kertenkele',
  'lobster': 'ıstakoz',
  'magpie': 'saksağan',
  'mango': 'mango',
  'marathon': 'maraton',
  'meerkat': 'mirket',
  'melon': 'kavun',
  'Merry go round': 'atlıkarınca',
  'mole': 'köstebek',
  'monkey': 'maymun',
  'moon': 'ay',
  'mountain': 'dağ',
  'mouse': 'fare',
  'mushroom': 'mantar',
  'notebook': 'defter',
  'ocarina': 'okarina',
  'ocean': 'okyanus',
  'octopus': 'ahtapot',
  'onion': 'soğan',
  'orange': 'portakal',
  'orangutan': 'orangutan',
  'orchestra': 'orchestre',
  'ostrich': 'devekuşu',
  'owl': 'baykuş',
  'painter': 'ressam',
  'pants': 'pantolon',
  'parrot': 'papağan',
  'parsley': 'maydanoz',
  'peach': 'şeftali',
  'peacock': 'tavus kuşu',
  'pelican': 'pelikan',
  'pencil': 'kurşun kalem',
  'penguin': 'penguen',
  'pepper': 'biber',
  'pharmacist': 'eczacı',
  'piano': 'piyano',
  'pickle': 'turşu',
  'pig': 'domuz',
  'pigeon': 'güvercin',
  'pilot': 'pilot',
  'pineapple': 'ananas',
  'platypus': 'ornitorenk',
  'playground': 'oyun alanı',
  'policeman': 'polis',
  'pomegranate': 'nar',
  'potato': 'patates',
  'principal': 'müdür',
  'professor': 'profesör',
  'pumpkin': 'balkabağı',
  'rabbit': 'tavşan',
  'raccoon': 'rakun',
  'rain': 'yağmur',
  'restroom': 'tuvalet',
  'rhino': 'gergedan',
  'river': 'nehir',
  'rock': 'kaya',
  'saxophone': 'saksafon',
  'scientist': 'bilim insanı',
  'seagull': 'martı',
  'seal': 'fok',
  'sesame': 'susam',
  'shark': 'köpekbalığı',
  'sheep': 'koyun',
  'shirt': 'gömlek',
  'singer': 'şarkıcı',
  'ski': 'kayak',
  'skunk': 'kokarca',
  'sky': 'gökyüzü',
  'snail': 'salyangoz',
  'snake': 'yılan',
  'snow': 'kar',
  'snowboard': 'kar kayağı',
  'soccer': 'futbol',
  'socks': 'çorap',
  'soil': 'toprak',
  'soldier': 'asker',
  'space': 'uzay',
  'sparrow': 'serçe',
  'spinach': 'ıspanak',
  'starfish': 'denizyıldızı',
  'stewardess': 'hostes',
  'stingray': 'vatoz',
  'strawberry': 'çilek',
  'sun': 'güneş',
  'subway': 'metro',
  'swallow': 'kırlangıç',
  'sweater': 'kazak',
  'swimming': 'yüzme',
  'swing': 'salıncak',
  'table': 'masa',
  'tambourine': 'tef',
  'teacher': 'öğretmen',
  'tiger': 'kaplan',
  'timpani': 'timpani',
  'toad': 'karakurbağası',
  'trampoline': 'trambolin',
  'tree': 'ağaç',
  'triangle': 'üçgen',
  'truck': 'kamyon',
  'trumpet': 'trompet',
  'turtle': 'kaplumbağa',
  'typhoon': 'tayfun',
  'unicorn': 'tek boynuzlu at',
  'violin': 'keman',
  'viking ship': 'viking gemisi',
  'volcano': 'volkan',
  'volleyball': 'voleybol',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'şelale',
  'watermelon': 'karpuz',
  'wave': 'dalga',
  'whale': 'balina',
  'wind': 'rüzgar',
  'window': 'pencere',
  'wolf': 'loup',
  'woodpecker': 'ağaçkakan',
  'xylophone': 'ksilofon',
  'yacht': 'yat',
  'zebra': 'zebra',
  'library': 'kütüphane',
  'post office': 'postane',
  'traffic light': 'trafik ışığı',
  'clock tower': 'saat kulesi',
  'pebble': 'çakıl taşı',
  'moss': 'yosun',
  'cactus': 'kaktüs',
  'rainbow': 'gökkuşağı',
  'toast': 'tost',
  'cookie': 'kurabiye',
  'ice cream': 'dondurma',
  'jelly': 'jöle',
  'writer': 'yazar',
  'actor': 'oyuncu',
  'crown': 'taç',
  'compass': 'pusula',
  'flowerpot': 'saksı',
  'roller skates': 'paten',
  'airport': 'havaalanı',
  'goldfish': 'altın balık',
  'spider': 'örümcek',
  'light bulb': 'ampul',
  'mirror': 'ayna',
  'magnet': 'mıknatıs',
  'toothbrush': 'diş fırçası',
  'soap': 'sabun',
  'plate': 'tabak',
  'spoon': 'kaşık',
  'mobile phone': 'cep telefonu',
  'key': 'anahtar',
  'newspaper': 'gazete',
  'calendar': 'takvim',
  'chair': 'sandalye',
  'sofa': 'kanepe',
  'refrigerator': 'buzdolabı',
  'stairs': 'merdiven',
  'pillow': 'yastık',
  'candle': 'mum',
  'bank': 'banka',
  'beetle': 'böcek',
  'cicada': 'ağustos böceği',
  'dragonfly': 'yusufçuk',
  'earthworm': 'toprak solucanı',
  'komodo dragon': 'komodo ejderi',
  'mantis': 'peygamber devesi',
  'mosquito': 'sivrisinek',
  'silkworm': 'ipek böceği',
  'stag beetle': 'geyik böceği',
  'table tennis': 'masa tenisi',
  'train': 'tren',
  'squid': 'kalamar',
  'butterfly': 'kelebek',
  'bee': 'arı',
  'squirrel': 'sincap',
  'nurse': 'hemşire',
  'slide': 'kaydırak',
  'picnic': 'piknik',
  'jacket': 'ceket',
  'shoes': 'ayakkabı',
  'tennis': 'tenis'
};