final Map<String, String> urduItemList = {
  'accordian': 'اکارڈین',
  'airplane': 'ہوائی جہاز',
  'anaconda': 'اناکونڈا',
  'ant': 'چیونٹی',
  'anteater': 'چیونٹی خور',
  'apple': 'سیب',
  'apricot': 'خوبانی',
  'archery': 'تیر اندازی',
  'astronaut': 'خلا باز',
  'avocado': 'ایوکاڈو',
  'badminton': 'بیڈمنٹن',
  'banana': 'کیلا',
  'baseball': 'بیس بال',
  'basketball': 'باسکٹ بال',
  'bassoon': 'باسون',
  'bat': 'چمگادڑ',
  'beach': 'ساحل',
  'bear': 'ریچھ',
  'bicycle': 'سائیکل',
  'blackboard': 'تختہ سیاہ',
  'blowfish': 'پھولنے والی مچھلی',
  'blueberries': 'نیلی بیریاں',
  'boar': 'جنگلی سور',
  'book': 'کتاب',
  'boots': 'بوٹ',
  'bowling': 'باؤلنگ',
  'boxing': 'باکسنگ',
  'broccoli': 'بروکلی',
  'bumper car': 'بمپر کار',
  'bus': 'بس',
  'cabbage': 'بند گوبھی',
  'camel': 'اونٹ',
  'carp': 'کارپ مچھلی',
  'carpenter': 'بڑھئی',
  'carrot': 'گاجر',
  'castanets': 'کاسٹینیٹس',
  'cat': 'بلی',
  'cello': 'چیلو',
  'chameleon': 'گرگٹ',
  'cheetah': 'چیتا',
  'cherry': 'چیری',
  'chick': 'چوزہ',
  'chicken': 'مرغی',
  'clarinet': 'کلیرینیٹ',
  'classroom': 'کلاس روم',
  'cloud': 'بادل',
  'cobra': 'کوبرا',
  'coconut': 'ناریل',
  'computer': 'کمپیوٹر',
  'conductor': 'کنڈکٹر',
  'contrabass': 'کونٹراباس',
  'cook': 'باورچی',
  'corn': 'مکئی',
  'cow': 'گائے',
  'crab': 'کیکڑا',
  'crane': 'سارس',
  'crocodile': 'مگرمچھ',
  'crow': 'کوا',
  'cucumber': 'کھیرا',
  'curling': 'کرلنگ',
  'cymbals': 'سیمبالز',
  'deer': 'ہرن',
  'dentist': 'دانتوں کا ڈاکٹر',
  'desert': 'صحرا',
  'doctor': 'ڈاکٹر',
  'dog': 'کتا',
  'dolphin': 'ڈولفن',
  'drum': 'ڈرم',
  'duck': 'بطخ',
  'eagle': 'عقاب',
  'earthquake': 'زلزلہ',
  'elephant': 'ہاتھی',
  'exam': 'امتحان',
  'farmer': 'کسان',
  'fencing': 'فینسنگ',
  'ferris wheel': 'فیرس وہیل',
  'fig': 'انجیر',
  'firefighter': 'فائر فائٹر',
  'fisherman': 'ماہی گیر',
  'flower': 'پھول',
  'flute': 'بانسری',
  'fog': 'دھند',
  'forest': 'جنگل',
  'fox': 'لومڑی',
  'friend': 'دوست',
  'frog': 'مینڈک',
  'garlic': 'لہسن',
  'ginger': 'ادرک',
  'ginseng': 'جنسنگ',
  'giraffe': 'زرافہ',
  'gloves': 'دستانے',
  'goat': 'بکری',
  'golf': 'گولف',
  'goose': 'ہنس',
  'gorilla': 'گوریلا',
  'grape': 'انگور',
  'grapefruit': 'چکوترا',
  'guitar': 'گٹار',
  'hairdressor': 'بال کاٹنے والا',
  'hallway': 'ہال وے',
  'harmonica': 'ہارمونیکا',
  'harp': 'ہارپ',
  'hat': 'ٹوپی',
  'hawk': 'شاہین',
  'helicopter': 'ہیلی کاپٹر',
  'hippo': 'دریائی گھوڑا',
  'hippocampus': 'ہپپوکیمپس',
  'hockey': 'ہاکی',
  'horse': 'گھوڑا',
  'hyena': 'لگڑبگڑ',
  'iceberg': 'برفانی تودہ',
  'iguana': 'اگوانا',
  'jellyfish': 'جیلی فش',
  'judge': 'جج',
  'judo': 'جوڈو',
  'jujube': 'جوجوبے',
  'jungle': 'جنگل',
  'kangaroo': 'کنگارو',
  'kiwi': 'کیوی',
  'koala': 'کوآلا',
  'lake': 'جھیل',
  'lemon': 'لیموں',
  'leopard': 'چیتا',
  'lettuce': 'لیٹش',
  'lightning': 'بجلی',
  'lion': 'شیر',
  'lizard': 'چھپکلی',
  'lobster': 'کیکڑا',
  'magpie': 'مگپائی',
  'mango': 'آم',
  'marathon': 'میراتھن',
  'meerkat': 'میرکٹ',
  'melon': 'خربوزہ',
  'Merry go round': 'میری گو راؤنڈ',
  'mole': 'چھچھوندر',
  'monkey': 'بندر',
  'moon': 'چاند',
  'mountain': 'پہاڑ',
  'mouse': 'چوہا',
  'mushroom': 'مشروم',
  'notebook': 'نوٹ بک',
  'ocarina': 'اوکارینا',
  'ocean': 'سمندر',
  'octopus': 'آکٹوپس',
  'onion': 'پیاز',
  'orange': 'سنترہ',
  'orangutan': 'اورانگوتان',
  'orchestra': 'آرکسٹرا',
  'ostrich': 'شتر مرغ',
  'owl': 'الو',
  'painter': 'پینٹر',
  'pants': 'پتلون',
  'parrot': 'طوطا',
  'parsley': 'اجوائن',
  'peach': 'آڑو',
  'peacock': 'مور',
  'pelican': 'پیلکن',
  'pencil': 'پنسل',
  'penguin': 'پینگوئن',
  'pepper': 'کالی مرچ',
  'pharmacist': 'فارماسسٹ',
  'piano': 'پیانو',
  'pickle': 'اچار',
  'pig': 'سور',
  'pigeon': 'کبوتر',
  'pilot': 'پائلٹ',
  'pineapple': 'انناس',
  'platypus': 'پلیٹیپس',
  'playground': 'کھیل کا میدان',
  'policeman': 'پولیس والا',
  'pomegranate': 'انار',
  'potato': 'آلو',
  'principal': 'پرنسپل',
  'professor': 'پروفیسر',
  'pumpkin': 'کدو',
  'rabbit': 'خرگوش',
  'raccoon': 'ریکون',
  'rain': 'بارش',
  'restroom': 'باتھ روم',
  'rhino': 'گینڈا',
  'river': 'دریا',
  'rock': 'پتھر',
  'saxophone': 'سیکسوفون',
  'scientist': 'سائنسدان',
  'seagull': 'سی گل',
  'seal': 'سیل',
  'sesame': 'تل',
  'shark': 'شارک',
  'sheep': 'بھیڑ',
  'shirt': 'قمیض',
  'singer': 'گلوکار',
  'ski': 'اسکی',
  'skunk': 'اسکنک',
  'sky': 'آسمان',
  'snail': 'گھونگا',
  'snake': 'سانپ',
  'snow': 'برف',
  'snowboard': 'سنو بورڈ',
  'soccer': 'فٹ بال',
  'socks': 'جرابیں',
  'soil': 'مٹی',
  'soldier': 'فوجی',
  'space': 'خلا',
  'sparrow': 'چڑیا',
  'spinach': 'پالک',
  'starfish': 'ستارہ مچھلی',
  'stewardess': 'اسٹیورڈیس',
  'stingray': 'سٹنگ رے',
  'strawberry': 'اسٹرابیری',
  'sun': 'سورج',
  'subway': 'سب وے',
  'swallow': 'ابابیل',
  'sweater': 'سویٹر',
  'swimming': 'تیراکی',
  'swing': 'جھولا',
  'table': 'میز',
  'tambourine': 'ٹیمبورین',
  'teacher': 'استاد',
  'tiger': 'شیر',
  'timpani': 'ٹمپانی',
  'toad': 'مینڈک',
  'trampoline': 'ٹرامپولین',
  'tree': 'درخت',
  'triangle': 'مثلث',
  'truck': 'ٹرک',
  'trumpet': 'ترمپٹ',
  'turtle': 'کچھوا',
  'typhoon': 'طوفان',
  'unicorn': 'یونیکورن',
  'violin': 'وائلن',
  'viking ship': 'وائیکنگ جہاز',
  'volcano': 'آتش فشاں',
  'volleyball': 'والی بال',
  'vuvuzela': 'وووزیلا',
  'waterfall': 'آبشار',
  'watermelon': 'تربوز',
  'wave': 'لہر',
  'whale': 'وہیل',
  'wind': 'ہوا',
  'window': 'کھڑکی',
  'wolf': 'بھیڑیا',
  'woodpecker': 'لکڑہارا',
  'xylophone': 'زائیلوفون',
  'yacht': 'یاخٹ',
  'zebra': 'زیبرا',
  'library': 'کتب خانہ',
  'post office': 'ڈاک خانہ',
  'traffic light': 'ٹریفک لائٹ',
  'clock tower': 'گھڑیال ٹاور',
  'pebble': 'کنکر',
  'moss': 'کائی',
  'cactus': 'کیکٹس',
  'rainbow': 'قوس قزح',
  'toast': 'ٹوسٹ',
  'cookie': 'کوکی',
  'ice cream': 'آئس کریم',
  'jelly': 'جیلی',
  'writer': 'مصنف',
  'actor': 'ایکٹر',
  'crown': 'تاج',
  'compass': 'قطب نما',
  'flowerpot': 'گملہ',
  'roller skates': 'رولر اسکیٹس',
  'airport': 'ہوائی اڈا',
  'goldfish': 'گولڈ فش',
  'spider': 'مکڑی',
  'light bulb': 'بلب',
  'mirror': 'آئینہ',
  'magnet': 'مقناطیس',
  'toothbrush': 'ٹوتھ برش',
  'soap': 'صابن',
  'plate': 'پلیٹ',
  'spoon': 'چمچ',
  'mobile phone': 'موبائل فون',
  'key': 'چابی',
  'newspaper': 'اخبار',
  'calendar': 'کیلنڈر',
  'chair': 'کرسی',
  'sofa': 'صوفہ',
  'refrigerator': 'ریفریجریٹر',
  'stairs': 'سیڑھیاں',
  'pillow': 'تکیہ',
  'candle': 'موم بتی',
  'bank': 'بینک',
  'beetle': 'بھنورا',
  'cicada': 'سکاڈا',
  'dragonfly': 'ڈریگن فلائی',
  'earthworm': 'کینچوا',
  'komodo dragon': 'کوموڈو ڈریگن',
  'mantis': 'مینٹس',
  'mosquito': 'مچھر',
  'silkworm': 'ریشم کا کیڑا',
  'stag beetle': 'سٹیگ بیٹل',
  'table tennis': 'ٹیبل ٹینس',
  'train': 'ٹرین',
  'squid': 'سکویڈ',
  'butterfly': 'تتلی',
  'bee': 'شہد کی مکھی',
  'squirrel': 'گلہری',
  'nurse': 'نرس',
  'slide': 'سلائیڈ',
  'picnic': 'پکنک',
  'jacket': 'جیکٹ',
  'shoes': 'جوتے',
  'tennis': 'ٹینس'
};
