final Map<String, String> uzbekItemList = {

  'accordian': 'akkordion',
  'airplane': 'samolyot',
  'anaconda': 'anakonda',
  'ant': 'chumolcha',
  'anteater': 'chumolchani yeyuvchi',
  'apple': 'olma',
  'apricot': 'o\'rik',
  'archery': 'kamon otish',
  'astronaut': 'kosmonavt',
  'avocado': 'avokado',
  'badminton': 'badminton',
  'banana': 'banan',
  'baseball': 'beysbol',
  'basketball': 'basketbol',
  'bassoon': 'bassun',
  'bat': 'yopiq qanotli hayvon',
  'beach': 'sohil',
  'bear': 'ayiq',
  'bicycle': 'velosiped',
  'blackboard': 'qora doska',
  'blowfish': 'shishqoq baliq',
  'blueberries': 'ko\'k mevalar',
  'boar': 'yovvoyi cho\'chqa',
  'book': 'kitob',
  'boots': 'irbas',
  'bowling': 'bowling',
  'boxing': 'boks',
  'broccoli': 'brokoli',
  'bumper car': 'to\'qnashuv avtomobili',
  'bus': 'avtobus',
  'cabbage': 'karam',
  'camel': 'tuya',
  'carp': 'karp',
  'carpenter': 'karpenter',
  'carrot': 'sabzi',
  'castanets': 'kastanet',
  'cat': 'mushuk',
  'cello': 'chello',
  'chameleon': 'kamaleon',
  'cheetah': 'cheetah',
  'cherry': 'gilos',
  'chick': 'tovuq bolasi',
  'chicken': 'tovuq',
  'clarinet': 'klarinet',
  'classroom': 'sinf xonasi',
  'cloud': 'bulut',
  'cobra': 'kobra',
  'coconut': 'kokos',
  'computer': 'kompyuter',
  'conductor': 'dirigent',
  'contrabass': 'kontrabas',
  'cook': 'oshpaz',
  'corn': 'makkajo\'xori',
  'cow': 'sigir',
  'crab': 'krab',
  'crane': 'kran',
  'crocodile': 'timsah',
  'crow': 'qarg\'a',
  'cucumber': 'bodring',
  'curling': 'curling',
  'cymbals': 'tsimbal',
  'deer': 'olen',
  'dentist': 'stomatolog',
  'desert': 'cho\'l',
  'doctor': 'doktor',
  'dog': 'it',
  'dolphin': 'delfin',
  'drum': 'baraban',
  'duck': 'o\'rdak',
  'eagle': 'qartal',
  'earthquake': 'zilzil',
  'elephant': 'fil',
  'exam': 'imtihon',
  'farmer': 'dehqon',
  'fencing': 'fencing',
  'ferris wheel': 'feris g\'ildirak',
  'fig': 'injir',
  'firefighter': 'yong\'inchi',
  'fisherman': 'baliqchi',
  'flower': 'gul',
  'flute': 'nay',
  'fog': 'tuman',
  'forest': 'o\'rmon',
  'fox': 'tulki',
  'friend': 'do\'st',
  'frog': 'baqiraq',
  'garlic': 'sarimsoq',
  'ginger': 'zanjabil',
  'ginseng': 'jin-sen',
  'giraffe': 'zirafa',
  'gloves': 'qo\'lqop',
  'goat': 'echki',
  'golf': 'golf',
  'goose': 'g\'oz',
  'gorilla': 'gorilla',
  'grape': 'uzum',
  'grapefruit': 'grejpfrut',
  'guitar': 'gitara',
  'hairdressor': 'frizer',
  'hallway': 'koridor',
  'harmonica': 'harmonika',
  'harp': 'harpa',
  'hat': 'shlyapa',
  'hawk': 'hawk',
  'helicopter': 'gelikopter',
  'hippo': 'hipopotam',
  'hippocampus': 'hippokampus',
  'hockey': 'hokkey',
  'horse': 'ot',
  'hyena': 'hayena',
  'iceberg': 'aysberg',
  'iguana': 'iguana',
  'jellyfish': 'meduza',
  'judge': 'hakim',
  'judo': 'judo',
  'jujube': 'jujube',
  'jungle': 'jungl',
  'kangaroo': 'kanguru',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'ko\'l',
  'lemon': 'limon',
  'leopard': 'leopard',
  'lettuce': 'salat',
  'lightning': 'chaqmoq',
  'lion': 'sher',
  'lizard': 'lizard',
  'lobster': 'lobster',
  'magpie': 'magpai',
  'mango': 'mango',
  'marathon': 'marafon',
  'meerkat': 'meerkat',
  'melon': 'kavun',
  'Merry go round': 'karusel',
  'mole': 'mol',
  'monkey': 'maymun',
  'moon': 'oy',
  'mountain': 'tog\'',
  'mouse': 'sichqon',
  'mushroom': 'qo\'ziqorin',
  'notebook': 'daftar',
  'ocarina': 'okarina',
  'ocean': 'okean',
  'octopus': 'oyoqbaliq',
  'onion': 'piyoz',
  'orange': 'apelsin',
  'orangutan': 'orangutan',
  'orchestra': 'orkestr',
  'ostrich': 'noj',
  'owl': 'boyqush',
  'painter': 'rasmchi',
  'pants': 'shim',
  'parrot': 'papagaj',
  'parsley': 'maydanoz',
  'peach': 'shaftoli',
  'peacock': 'tavus',
  'pelican': 'pelikan',
  'pencil': 'qalam',
  'penguin': 'pingvin',
  'pepper': 'qalampir',
  'pharmacist': 'dorixonachi',
  'piano': 'piano',
  'pickle': 'achchar',
  'pig': 'cho\'chqa',
  'pigeon': 'kabutar',
  'pilot': 'pilot',
  'pineapple': 'ananas',
  'platypus': 'platipus',
  'playground': 'o\'yin maydoni',
  'policeman': 'politsiyachi',
  'pomegranate': 'anor',
  'potato': 'kartoshka',
  'principal': 'maktab direktori',
  'professor': 'professor',
  'pumpkin': 'qovoq',
  'rabbit': 'quyon',
  'raccoon': 'rakun',
  'rain': 'yomg\'ir',
  'restroom': 'hojatxona',
  'rhino': 'nosorog',
  'river': 'daryo',
  'rock': 'tos',
  'saxophone': 'saksofon',
  'scientist': 'olim',
  'seagull': 'baliqqush',
  'seal': 'seal',
  'sesame': 'kunjut',
  'shark': 'akula',
  'sheep': 'qo\'y',
  'shirt': 'ko\'ylak',
  'singer': 'qo\'shiqchi',
  'ski': 'ski',
  'skunk': 'skunk',
  'sky': 'osmon',
  'snail': 'salyangoz',
  'snake': 'ilon',
  'snow': 'qor',
  'snowboard': 'snoubord',
  'soccer': 'futbol',
  'socks': 'paypoq',
  'soil': 'tuproq',
  'soldier': 'harbiy',
  'space': 'kosmos',
  'sparrow': 'chirpon',
  'spinach': 'ispanak',
  'starfish': 'ulduz baliq',
  'stewardess': 'styuardessa',
  'stingray': 'skat',
  'strawberry': 'qulupnay',
  'sun': 'quyosh',
  'subway': 'metro',
  'swallow': 'lastovka',
  'sweater': 'sveter',
  'swimming': 'suzish',
  'swing': 'tebranish',
  'table': 'stol',
  'tambourine': 'tamburin',
  'teacher': 'o\'qituvchi',
  'tiger': 'yo\'lbars',
  'timpani': 'timpani',
  'toad': 'qurbaqa',
  'trampoline': 'trampolin',
  'tree': 'daraxt',
  'triangle': 'uchburchak',
  'truck': 'yuk mashinasi',
  'trumpet': 'trumpeta',
  'turtle': 'tosbaqa',
  'typhoon': 'tayfun',
  'unicorn': 'yunikorn',
  'violin': 'skripka',
  'viking ship': 'viking kemasi',
  'volcano': 'vulkan',
  'volleyball': 'voleybol',
  'vuvuzela': 'vuvuzela',
  'waterfall': 'sharshara',
  'watermelon': 'tarvuz',
  'wave': 'to‘lqin',
  'whale': 'kit',
  'wind': 'shamol',
  'window': 'deraza',
  'wolf': 'bo‘ri',
  'woodpecker': 'yog‘ochqush',
  'xylophone': 'ksilofon',
  'yacht': 'yaxta',
  'zebra': 'zebra',
  'library': 'kutubxona',
  'post office': 'pochta',
  'traffic light': 'svetofor',
  'clock tower': 'soat minorasi',
  'pebble': 'toş',
  'moss': 'yosun',
  'cactus': 'kaktus',
  'rainbow': 'kamalak',
  'toast': 'tost',
  'cookie': 'pechenye',
  'ice cream': 'muzqaymoq',
  'jelly': 'jelly',
  'writer': 'yozuvchi',
  'actor': 'aktyor',
  'crown': 'toj',
  'compass': 'kompas',
  'flowerpot': 'guldon',
  'roller skates': 'konki',
  'airport': 'aeroport',
  'goldfish': 'oltin baliq',
  'spider': 'o\'rgimchak',
  'light bulb': 'lampochka',
  'mirror': 'oyna',
  'magnet': 'magnit',
  'toothbrush': 'tish cho\'tkasi',
  'soap': 'sovun',
  'plate': 'tarelka',
  'spoon': 'qoshiq',
  'mobile phone': 'mobil telefon',
  'key': 'kalit',
  'newspaper': 'gazeta',
  'calendar': 'kalendar',
  'chair': 'o\'rindiq',
  'sofa': 'divan',
  'refrigerator': 'muzlatgich',
  'stairs': 'narvon',
  'pillow': 'yostiq',
  'candle': 'sham',
  'bank': 'bank',
  'beetle': 'qo\'ng\'iz',
  'cicada': 'chigirtka',
  'dragonfly': 'yusufchik',
  'earthworm': 'yer qurti',
  'komodo dragon': 'komodo ajdari',
  'mantis': 'bogomol',
  'mosquito': 'chivin',
  'silkworm': 'ipak qurti',
  'stag beetle': 'bug\'u qo\'ng\'izi',
  'table tennis': 'stol tennisi',
  'train': 'poezd',
  'squid': 'kalamar',
  'butterfly': 'kapalak',
  'bee': 'ari',
  'squirrel': 'sichqon',
  'nurse': 'hamshira',
  'slide': 'siljish',
  'picnic': 'piknik',
  'jacket': 'kofta',
  'shoes': 'oyoq kiyim',
  'tennis': 'tennis'
};