final Map<String, String> vieItemList = {

  'accordian': 'đàn accordion',
  'airplane': 'máy bay',
  'anaconda': 'trăn anaconda',
  'ant': 'kiến',
  'anteater': 'thú ăn kiến',
  'apple': 'táo',
  'apricot': 'mơ',
  'archery': 'bắn cung',
  'astronaut': 'phi hành gia',
  'avocado': 'bơ',
  'badminton': 'cầu lông',
  'banana': 'chuối',
  'baseball': 'bóng chày',
  'basketball': 'bóng rổ',
  'bassoon': 'kèn bassoon',
  'bat': 'dơi',
  'beach': 'bãi biển',
  'bear': 'gấu',
  'bicycle': 'xe đạp',
  'blackboard': 'bảng đen',
  'blowfish': 'cá nóc',
  'blueberries': 'việt quất',
  'boar': 'lợn rừng',
  'book': 'sách',
  'boots': 'giày ủng',
  'bowling': 'bowling',
  'boxing': 'quyền anh',
  'broccoli': 'bông cải xanh',
  'bumper car': 'xe điện đụng',
  'bus': 'xe buýt',
  'cabbage': 'bắp cải',
  'camel': 'lạc đà',
  'carp': 'cá chép',
  'carpenter': 'thợ mộc',
  'carrot': 'cà rốt',
  'castanets': 'catanh',
  'cat': 'mèo',
  'cello': 'đàn cello',
  'chameleon': 'tắc kè hoa',
  'cheetah': 'báo gêpa',
  'cherry': 'anh đào',
  'chick': 'gà con',
  'chicken': 'gà',
  'clarinet': 'kèn clarinet',
  'classroom': 'lớp học',
  'cloud': 'mây',
  'cobra': 'rắn hổ mang',
  'coconut': 'dừa',
  'computer': 'máy tính',
  'conductor': 'nhạc trưởng',
  'contrabass': 'đàn contrabass',
  'cook': 'đầu bếp',
  'corn': 'ngô',
  'cow': 'bò',
  'crab': 'cua',
  'crane': 'cần cẩu',
  'crocodile': 'cá sấu',
  'crow': 'quạ',
  'cucumber': 'dưa chuột',
  'curling': 'môn curling',
  'cymbals': 'chũm chọe',
  'deer': 'hươu',
  'dentist': 'nha sĩ',
  'desert': 'sa mạc',
  'doctor': 'bác sĩ',
  'dog': 'chó',
  'dolphin': 'cá heo',
  'drum': 'trống',
  'duck': 'vịt',
  'eagle': 'đại bàng',
  'earthquake': 'động đất',
  'elephant': 'voi',
  'exam': 'kỳ thi',
  'farmer': 'nông dân',
  'fencing': 'đấu kiếm',
  'ferris wheel': 'vòng đu quay',
  'fig': 'sung',
  'firefighter': 'lính cứu hỏa',
  'fisherman': 'ngư dân',
  'flower': 'hoa',
  'flute': 'sáo',
  'fog': 'sương mù',
  'forest': 'rừng',
  'fox': 'cáo',
  'friend': 'bạn',
  'frog': 'ếch',
  'garlic': 'tỏi',
  'ginger': 'gừng',
  'ginseng': 'nhân sâm',
  'giraffe': 'hươu cao cổ',
  'gloves': 'găng tay',
  'goat': 'dê',
  'golf': 'gôn',
  'goose': 'ngỗng',
  'gorilla': 'khỉ đột',
  'grape': 'nho',
  'grapefruit': 'bưởi',
  'guitar': 'đàn guitar',
  'hairdressor': 'thợ làm tóc',
  'hallway': 'hành lang',
  'harmonica': 'kèn harmonica',
  'harp': 'đàn hạc',
  'hat': 'mũ',
  'hawk': 'diều hâu',
  'helicopter': 'trực thăng',
  'hippo': 'hà mã',
  'hippocampus': 'cá ngựa',
  'hockey': 'khúc côn cầu',
  'horse': 'ngựa',
  'hyena': 'linh cẩu',
  'iceberg': 'tảng băng trôi',
  'iguana': 'kỳ nhông',
  'jellyfish': 'sứa',
  'judge': 'thẩm phán',
  'judo': 'judo',
  'jujube': 'táo tàu',
  'jungle': 'rừng nhiệt đới',
  'kangaroo': 'chuột túi',
  'kiwi': 'kiwi',
  'koala': 'gấu túi',
  'lake': 'hồ',
  'lemon': 'chanh',
  'leopard': 'báo',
  'lettuce': 'xà lách',
  'lightning': 'sét',
  'lion': 'sư tử',
  'lizard': 'thằn lằn',
  'lobster': 'tôm hùm',
  'magpie': 'chim ác là',
  'mango': 'xoài',
  'marathon': 'marathon',
  'meerkat': 'cầy vằn',
  'melon': 'dưa',
  'Merry go round': 'vòng quay ngựa gỗ',
  'mole': 'chuột chũi',
  'monkey': 'khỉ',
  'moon': 'mặt trăng',
  'mountain': 'núi',
  'mouse': 'chuột',
  'mushroom': 'nấm',
  'notebook': 'vở',
  'ocarina': 'đàn ocarina',
  'ocean': 'đại dương',
  'octopus': 'bạch tuộc',
  'onion': 'hành',
  'orange': 'cam',
  'orangutan': 'đười ươi',
  'orchestra': 'dàn nhạc',
  'ostrich': 'đà điểu',
  'owl': 'cú',
  'painter': 'họa sĩ',
  'pants': 'quần',
  'parrot': 'vẹt',
  'parsley': 'ngò tây',
  'peach': 'đào',
  'peacock': 'công',
  'pelican': 'bồ nông',
  'pencil': 'bút chì',
  'penguin': 'chim cánh cụt',
  'pepper': 'hạt tiêu',
  'pharmacist': 'dược sĩ',
  'piano': 'đàn piano',
  'pickle': 'dưa muối',
  'pig': 'lợn',
  'pigeon': 'bồ câu',
  'pilot': 'phi công',
  'pineapple': 'dứa',
  'platypus': 'thú mỏ vịt',
  'playground': 'sân chơi',
  'policeman': 'cảnh sát',
  'pomegranate': 'lựu',
  'potato': 'khoai tây',
  'principal': 'hiệu trưởng',
  'professor': 'giáo sư',
  'pumpkin': 'bí ngô',
  'rabbit': 'thỏ',
  'raccoon': 'gấu mèo',
  'rain': 'mưa',
  'restroom': 'nhà vệ sinh',
  'rhino': 'tê giác',
  'river': 'sông',
  'rock': 'đá',
  'saxophone': 'kèn saxophone',
  'scientist': 'nhà khoa học',
  'seagull': 'mòng biển',
  'seal': 'hải cẩu',
  'sesame': 'vừng',
  'shark': 'cá mập',
  'sheep': 'cừu',
  'shirt': 'áo sơ mi',
  'singer': 'ca sĩ',
  'ski': 'trượt tuyết',
  'skunk': 'chồn hôi',
  'sky': 'bầu trời',
  'snail': 'ốc sên',
  'snake': 'rắn',
  'snow': 'tuyết',
  'snowboard': 'ván trượt tuyết',
  'soccer': 'bóng đá',
  'socks': 'tất',
  'soil': 'đất',
  'soldier': 'lính',
  'space': 'không gian',
  'sparrow': 'chim sẻ',
  'spinach': 'rau chân vịt',
  'starfish': 'sao biển',
  'stewardess': 'tiếp viên hàng không',
  'stingray': 'cá đuối',
  'strawberry': 'dâu tây',
  'sun': 'mặt trời',
  'subway': 'tàu điện ngầm',
  'swallow': 'chim én',
  'sweater': 'áo len',
  'swimming': 'bơi lội',
  'swing': 'xích đu',
  'table': 'bàn',
  'tambourine': 'trống lục lạc',
  'teacher': 'giáo viên',
  'tiger': 'hổ',
  'timpani': 'trống định âm',
  'toad': 'cóc',
  'trampoline': 'bạt nhún',
  'tree': 'cây',
  'triangle': 'tam giác',
  'truck': 'xe tải',
  'trumpet': 'kèn trumpet',
  'turtle': 'rùa',
  'typhoon': 'bão',
  'unicorn': 'kỳ lân',
  'violin': 'đàn violin',
  'viking ship': 'tàu viking',
  'volcano': 'núi lửa',
  'volleyball': 'bóng chuyền',
  'vuvuzela': 'kèn vuvuzela',
  'waterfall': 'thác nước',
  'watermelon': 'dưa hấu',
  'wave': 'sóng',
  'whale': 'cá voi',
  'wind': 'gió',
  'window': 'cửa sổ',
  'wolf': 'sói',
  'woodpecker': 'chim gõ kiến',
  'xylophone': 'đàn xylophone',
  'yacht': 'du thuyền',
  'zebra': 'ngựa vằn',
  'library': 'thư viện',
  'post office': 'bưu điện',
  'traffic light': 'đèn giao thông',
  'clock tower': 'tháp đồng hồ',
  'pebble': 'sỏi',
  'moss': 'rêu',
  'cactus': 'xương rồng',
  'rainbow': 'cầu vồng',
  'toast': 'bánh mì nướng',
  'cookie': 'bánh quy',
  'ice cream': 'kem',
  'jelly': 'thạch',
  'writer': 'nhà văn',
  'actor': 'diễn viên',
  'crown': 'vương miện',
  'compass': 'la bàn',
  'flowerpot': 'chậu hoa',
  'roller skates': 'giày trượt patin',
  'airport': 'sân bay',
  'goldfish': 'cá vàng',
  'spider': 'nhện',
  'light bulb': 'bóng đèn',
  'mirror': 'gương',
  'magnet': 'nam châm',
  'toothbrush': 'bàn chải đánh răng',
  'soap': 'xà phòng',
  'plate': 'đĩa',
  'spoon': 'thìa',
  'mobile phone': 'điện thoại di động',
  'key': 'chìa khóa',
  'newspaper': 'báo',
  'calendar': 'lịch',
  'chair': 'ghế',
  'sofa': 'ghế sofa',
  'refrigerator': 'tủ lạnh',
  'stairs': 'cầu thang',
  'pillow': 'gối',
  'candle': 'nến',
  'bank': 'ngân hàng',
  'beetle': 'bọ cánh cứng',
  'cicada': 've sầu',
  'dragonfly': 'chuồn chuồn',
  'earthworm': 'giun đất',
  'komodo dragon': 'rồng komodo',
  'mantis': 'bọ ngựa',
  'mosquito': 'muỗi',
  'silkworm': 'tằm',
  'stag beetle': 'bọ cánh cứng sừng',
  'table tennis': 'bóng bàn',
  'train': 'tàu hỏa',
  'squid': 'mực',
  'butterfly': 'bướm',
  'bee': 'ong',
  'squirrel': 'sóc',
  'nurse': 'y tá',
  'slide': 'cầu trượt',
  'picnic': 'dã ngoại',
  'jacket': 'áo khoác',
  'shoes': 'giày',
  'tennis': 'quần vợt'
};