final Map<String, String> zuluItemList = {

  'accordian': 'i-accordion',
  'airplane': 'indiza',
  'anaconda': 'i-anaconda',
  'ant': 'i-ant',
  'anteater': 'i-anteater',
  'apple': 'i-apula',
  'apricot': 'i-apricot',
  'archery': 'ukudubula ngomcibisholo',
  'astronaut': 'i-astronaut',
  'avocado': 'i-avocado',
  'badminton': 'i-badminton',
  'banana': 'ubhanana',
  'baseball': 'i-baseball',
  'basketball': 'i-basketball',
  'bassoon': 'i-bassoon',
  'bat': 'i-bat',
  'beach': 'ibhishi',
  'bear': 'i-bear',
  'bicycle': 'ibhayisikili',
  'blackboard': 'ibhodi elimnyama',
  'blowfish': 'i-blowfish',
  'blueberries': 'ama-blueberries',
  'boar': 'i-boar',
  'book': 'incwadi',
  'boots': 'amabhutsu',
  'bowling': 'i-bowling',
  'boxing': 'i-boxing',
  'broccoli': 'i-broccoli',
  'bumper car': 'imoto yomhlanganyeli',
  'bus': 'ibhasi',
  'cabbage': 'iklabhishi',
  'camel': 'ikamel',
  'carp': 'i-carp',
  'carpenter': 'umsekeli wezinkuni',
  'carrot': 'ikaroti',
  'castanets': 'i-castanets',
  'cat': 'ikati',
  'cello': 'i-cello',
  'chameleon': 'i-chameleon',
  'cheetah': 'i-cheetah',
  'cherry': 'i-cherry',
  'chick': 'i-chick',
  'chicken': 'inkukhu',
  'clarinet': 'i-clarinet',
  'classroom': 'igumbi lokufundela',
  'cloud': 'ifindo',
  'cobra': 'ikobra',
  'coconut': 'ikhokonati',
  'computer': 'ikhompyutha',
  'conductor': 'umqondisi',
  'contrabass': 'i-contrabass',
  'cook': 'upheki',
  'corn': 'umbila',
  'cow': 'inkomo',
  'crab': 'ikrakethi',
  'crane': 'i-crane',
  'crocodile': 'ingwenya',
  'crow': 'i-crow',
  'cucumber': 'ukhukhamba',
  'curling': 'i-curling',
  'cymbals': 'izinsimbi zomculo',
  'deer': 'i-deer',
  'dentist': 'udokotela wamazinyo',
  'desert': 'isihlabathi',
  'doctor': 'udokotela',
  'dog': 'inja',
  'dolphin': 'i-dolphin',
  'drum': 'idrimu',
  'duck': 'idaka',
  'eagle': 'i-eagle',
  'earthquake': 'umsindo womhlaba',
  'elephant': 'indlovu',
  'exam': 'uhlolo',
  'farmer': 'umlima',
  'fencing': 'i-fencing',
  'ferris wheel': 'i-ferris wheel',
  'fig': 'ifigi',
  'firefighter': 'umlwi womlilo',
  'fisherman': 'umfishi',
  'flower': 'imbali',
  'flute': 'ifluti',
  'fog': 'ifog',
  'forest': 'ihlathi',
  'fox': 'ifoksi',
  'friend': 'umngane',
  'frog': 'ixoxo',
  'garlic': 'iogarliki',
  'ginger': 'i-ginger',
  'ginseng': 'i-ginseng',
  'giraffe': 'i-giraffe',
  'gloves': 'iziglavu',
  'goat': 'imbuzi',
  'golf': 'i-golf',
  'goose': 'i-goose',
  'gorilla': 'i-gorilla',
  'grape': 'i-grape',
  'grapefruit': 'i-grapefruit',
  'guitar': 'igitha',
  'hairdressor': 'umqaphi wezinwele',
  'hallway': 'ikhilimu',
  'harmonica': 'i-harmonica',
  'harp': 'i-harp',
  'hat': 'isigqoko',
  'hawk': 'i-hawk',
  'helicopter': 'i-helicopter',
  'hippo': 'i-hippo',
  'hippocampus': 'i-hippocampus',
  'hockey': 'i-hockey',
  'horse': 'ihhashi',
  'hyena': 'i-hyena',
  'iceberg': 'i-iceberg',
  'iguana': 'i-iguana',
  'jellyfish': 'i-jellyfish',
  'judge': 'umahluleli',
  'judo': 'i-judo',
  'jujube': 'i-jujube',
  'jungle': 'ijungle',
  'kangaroo': 'ikangaroo',
  'kiwi': 'kiwi',
  'koala': 'koala',
  'lake': 'ichibi',
  'lemon': 'ilamoni',
  'leopard': 'ingwe',
  'lettuce': 'i-lettuce',
  'lightning': 'inkungu',
  'lion': 'ingonyama',
  'lizard': 'i-lizard',
  'lobster': 'ilobasta',
  'magpie': 'i-magpie',
  'mango': 'umango',
  'marathon': 'imarathon',
  'meerkat': 'i-meerkat',
  'melon': 'imelon',
  'Merry go round': 'ijikelezo elimnandi',
  'mole': 'imole',
  'monkey': 'inkawu',
  'moon': 'inyanga',
  'mountain': 'intaba',
  'mouse': 'igundane',
  'mushroom': 'imushroom',
  'notebook': 'inothibhuku',
  'ocarina': 'i-ocarina',
  'ocean': 'ulwandle',
  'octopus': 'i-octopus',
  'onion': 'u-anyanisi',
  'orange': 'i-orange',
  'orangutan': 'orangutan',
  'orchestra': 'i-orchestra',
  'ostrich': 'i-ostrich',
  'owl': 'i-owl',
  'painter': 'umdwebi',
  'pants': 'amabhulukwe',
  'parrot': 'ipharati',
  'parsley': 'iparsley',
  'peach': 'ipeach',
  'peacock': 'ipeacock',
  'pelican': 'ipelicane',
  'pencil': 'ipensela',
  'penguin': 'ipengwini',
  'pepper': 'uphepha',
  'pharmacist': 'ipharmacist',
  'piano': 'ipiyano',
  'pickle': 'ipickle',
  'pig': 'ingulube',
  'pigeon': 'ipijoni',
  'pilot': 'ipayili',
  'pineapple': 'ananas',
  'platypus': 'platypus',
  'playground': 'indawo yokudlala',
  'policeman': 'ipolisi',
  'pomegranate': 'ipomegranate',
  'potato': 'ipotato',
  'principal': 'umphathi wesikole',
  'professor': 'uProfesa',
  'pumpkin': 'ipumpkin',
  'rabbit': 'irabithi',
  'raccoon': 'raccoon',
  'rain': 'imvula',
  'restroom': 'indlu yokugezela',
  'rhino': 'irhino',
  'river': 'umfula',
  'rock': 'itshe',
  'saxophone': 'isaksofoni',
  'scientist': 'ososayensi',
  'seagull': 'iseagull',
  'seal': 'iseal',
  'sesame': 'isesame',
  'shark': 'ushaka',
  'sheep': 'izimvu',
  'shirt': 'ishati',
  'singer': 'umculi',
  'ski': 'iski',
  'skunk': 'iskhunk',
  'sky': 'izulu',
  'snail': 'isnail',
  'snake': 'inyoka',
  'snow': 'iqhwa',
  'snowboard': 'isnowboard',
  'soccer': 'ibhola lezinyawo',
  'socks': 'amasokisi',
  'soil': 'hlabathi',
  'soldier': 'isosha',
  'space': 'isikhala',
  'sparrow': 'isparrow',
  'spinach': 'isipinashi',
  'starfish': 'istarfish',
  'stewardess': 'stewardess',
  'stingray': 'stingray',
  'strawberry': 'isitrawberry',
  'sun': 'ilanga',
  'subway': 'isubway',
  'swallow': 'iswallow',
  'sweater': 'iswetha',
  'swimming': 'ukubhukuda',
  'swing': 'iswing',
  'table': 'itafula',
  'tambourine': 'itamburini',
  'teacher': 'uthisha',
  'tiger': 'itiger',
  'timpani': 'itimpani',
  'toad': 'itoad',
  'trampoline': 'itrampoline',
  'tree': 'isihlahla',
  'triangle': 'itrangle',
  'truck': 'iloli',
  'trumpet': 'itrumpet',
  'turtle': 'iturtle',
  'typhoon': 'ityphoon',
  'unicorn': 'unicorn',
  'violin': 'ivayoleni',
  'viking ship': 'iviking ship',
  'volcano': 'ivolcayo',
  'volleyball': 'ivolleyball',
  'vuvuzela': 'ivuvuzela',
  'waterfall': 'umetshezi',
  'watermelon': 'iwatermelon',
  'wave': 'ugagasi',
  'whale': 'iwhale',
  'wind': 'umoya',
  'window': 'iwindi',
  'wolf': 'impisi',
  'woodpecker': 'iwoodpecker',
  'xylophone': 'ixilofoni',
  'yacht': 'iyakhtha',
  'zebra': 'izebra',
  'library': 'umtapo wolutshwelo',
  'post office': 'iposi',
  'traffic light': 'isibani sezimoto',
  'clock tower': 'umbhoshongo wewashi',
  'pebble': 'itshe elincane',
  'moss': 'umoss',
  'cactus': 'i-cactus',
  'rainbow': 'umnyama',
  'toast': 'isinkwa esiphekwe',
  'cookie': 'i-cookie',
  'ice cream': 'i-ice cream',
  'jelly': 'i-jelly',
  'writer': 'umbhali',
  'actor': 'umlingisi',
  'crown': 'isithsaba',
  'compass': 'i-compass',
  'flowerpot': 'imbiza yezimbali',
  'roller skates': 'i-roller skates',
  'airport': 'isikhumulo sezindiza',
  'goldfish': 'inhlanzi yegolide',
  'spider': 'isicabucabu',
  'light bulb': 'i-bulb',
  'mirror': 'isibuko',
  'magnet': 'i-magnet',
  'toothbrush': 'i-toothbrush',
  'soap': 'i-soap',
  'plate': 'i-plate',
  'spoon': 'i-spoon',
  'mobile phone': 'i-mobile phone',
  'key': 'i-key',
  'newspaper': 'i-newspaper',
  'calendar': 'i-calendar',
  'chair': 'i-chair',
  'sofa': 'i-sofa',
  'refrigerator': 'i-refrigerator',
  'stairs': 'i-stairs',
  'pillow': 'i-pillow',
  'candle': 'i-candle',
  'bank': 'i-bank',
  'beetle': 'i-beetle',
  'cicada': 'i-cicada',
  'dragonfly': 'i-dragonfly',
  'earthworm': 'i-earthworm',
  'komodo dragon': 'i-komodo dragon',
  'mantis': 'i-mantis',
  'mosquito': 'i-mosquito',
  'silkworm': 'i-silkworm',
  'stag beetle': 'i-stag beetle',
  'table tennis': 'i-table tennis',
  'train': 'isitimela',
  'squid': 'i-squid',
  'butterfly': 'i-butterfly',
  'bee': 'inyosi',
  'squirrel': 'i-squirrel',
  'nurse': 'i-nurse',
  'slide': 'i-slide',
  'picnic': 'i-picnic',
  'jacket': 'i-jacket',
  'shoes': 'izicathulo',
  'tennis': 'i-tennis'
};